### ISSUE TITLE
Label Oneplus 3/3T instead of Oneplus 3

### ISSUE THREAD

**Issue by libermax** [ubports/ubports-installer#1000]
IMO, It would make more evident that the same image of the installer support both oneplus3 and oneplus3T. Don't you think so ?

**Comment by NeoTheThird** [comment]
Should already be in there with brackets (https://github.com/ubports/installer-configs/pull/6/files), if you would prefer a different notation, feel free to send a pr.

**Comment by NeoTheThird** [comment]
Also, holy shit, issue number 1000! Not sure how I feel about this :D
