### ISSUE TITLE
Feature Request: Reference to Green Robots

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/ubports-installer#1006]
When installer is running, for android users (99% of installs I think?)  it would be useful to be more clear what they *should* see on the page when it reboots to the bootloader.

Currently it shows this on that stage:
![ut_installer_Should_see_green_robot](https://user-images.githubusercontent.com/16578346/68306950-4f447100-005f-11ea-8400-785d607abe06.png)

You could either show an image of the android robot being opened up and operated on, or, even just a block of text that says something like this:

> Android Devices: When device successfully reboots to the bootloader, you should see the green android robot with some menu options.  When you see this on the device you are ready to continue.

Thanks!

**Comment by NeoTheThird** [comment]
> When installer is running, for android users (99% of installs I think?) it would be useful to be more clear what they should see on the page when it reboots to the bootloader.

It would be so nice, if this was how it actually worked. In reality, there's a billion possibilities how it can look. So a picture is not an option. Text, i'm also not a big fan of, because it just becomes too much. People don't properly read the short text as-is, adding more text is almost always counterproductive.

**Comment by wayneoutthere** [comment]
if you select 'nexus 4' as an example for your install, there is not a billion ways that can look.  So it would seem that based on your device you could stream very specific information to these pages.  I don't disagree this would be a lot of **work** and may never happen as a result but I think there could be a  way to put specific images.  Because I believe (and I could be wrong) that once a device is shipped that the bootloader screen and the way it looks will remain static forever so that image, for that device, should always remain static.

**Comment by NeoTheThird** [comment]
Nope. You can reflash the bootloader.

**Comment by wayneoutthere** [comment]
well then. haha  
a billion may therefore be possible.
I bow my head in shame...
