### ISSUE TITLE
Feature Request: Orange Dot Reference

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/ubports-installer#1007]
On the last stage of the installer it shows this:

![UT_Installer_Last_stage_](https://user-images.githubusercontent.com/16578346/68307573-5750e080-0060-11ea-8dc9-a4c0e50cf099.png)

Right now it says that it has to do a few things and how long it takes but I think an image of the big orange dots, or reference to those dots would be helpful to reduce the stress of person who is installing and to make sure what they are seeing is 'normal and expected' since it likely will be their first time

I suggest either an image with the big orange dots and a sentence such as:

 "You should see this screen during the last stages ________ (screenshot)" followed by the normal Ubuntu Touch screen after that."

or, simply describe it like this:

"During these last few minutes of your install you should see some large orange dots moving intermittently across your screen.  This will happen for a few minutes until  the screen changes to the normal Ubuntu Touch start up screen."

**Comment by NeoTheThird** [comment]
We can think about that. I think it's fairly self-explainatory as well here, both the spinning circle of friends animation on the canonical devices and the blinking yumi on our ports are pretty intuitive. If something goes wrong, it'll also be clear most of the time...

**Comment by NeoTheThird** [comment]
I think we can close this for the time being.
