### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by parag-thoughti** [ubports/ubports-installer#1009]
*Automatically generated error report* 
UBports Installer Version: 0.4.7-beta 
Device: oneplus3
Channel: 16.04/arm64/edge
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.418] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/JVzd4GWHy9/

**Comment by NeoTheThird** [comment]
Duplicate of #963. Fixed in next release.
