### ISSUE TITLE
Error occurred when flashig out Firmware of Nokia 8.1

### ISSUE THREAD

**Issue by mainul35** [ubports/ubports-installer#1011]
Error: fastboot:flash: flashing failed: error: {killed:false,code:1,signal:null,cmd:C:\\Users\\mainu\\AppData\\Local\\Temp\\1TAc0nlYFbY3WH4y4Dx0GsuCwaC\\resources\\app.asar.unpacked\\platform-tools\\win\\fastboot

**Comment by NeoTheThird** [comment]
That's not an officially supported device, what config did you use?

**Comment by mainul35** [comment]
6 GB ram, 64 GB Rom

**Comment by NeoTheThird** [comment]
No, what installer config. Did you write your own config file? Or did you just choose one of the other devices? That would **not** work!
