### ISSUE TITLE
user-requested bug-report meizu pro 5

### ISSUE THREAD

**Issue by Vonderman** [ubports/ubports-installer#1014]
*Automatically generated error report* 
UBports Installer Version: 0.4.6-beta 
Device: turbo
Channel: ubports-touch/16.04/rc
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.449] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/VBTC9jrPzT/

**Comment by Vonderman** [comment]
Error: systemimage: Push failed: Failed push: Failed to push file 2: Push failed: error: {killed:false,code:1,signal:null,cmd:C:\Users\PV\AppData\Local\Temp\1TAc0nlYFbY3WH4y4Dx0GsuCwaC\resources\app.asar.unpacked\platform-tools\win\adb

Ubuntu cannot be installed to the Meizu Pro 5 phone via the UBportd Windows client. Either such an error, or the download occurs, and after rebooting for a second, a fix bar appears and then a white background with an inscription in different languages that you need to ask for help. Win 10 x64 system.

**Comment by NeoTheThird** [comment]
What OS is the phone running? If it's android, it needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices) before the installer works.

**Comment by Vonderman** [comment]
Firmware 6.3.0.0G. The bootloader is unlocked. Once the firmware is supposedly installed, but the log shows that there are errors. After the program stops uploading the firmware and says that everything is ok, enjoy, the phone reboots and displays a white background with an exclamation mark and the message “update error”, contact support.

**Comment by Vonderman** [comment]
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/3829008/ubports-installer.log)

**Comment by Vonderman** [comment]
I don’t understand what’s the matter. I do everything according to the instructions.

**Comment by NeoTheThird** [comment]
No, i mean what operating system. Android or Ubuntu Touch?

**Comment by Vonderman** [comment]
Android Firmware 6.3.0.0G

**Comment by NeoTheThird** [comment]
Okay, then you have to [unlock it first](https://nc.ubports.com/s/9yd88Xo4CWzRbMq).

**Comment by Vonderman** [comment]
How do I install this? Via TWRP?

**Comment by NeoTheThird** [comment]
Here's some instructions: https://forums.ubports.com/topic/2755/meizu-pro-5-flyme-os-to-ubuntu-touch-modem-update-fingerprint-function

**Comment by Vonderman** [comment]
Yes, but this is an instruction for Linux! I have 10 wines. I understand that it is impossible to install without Ubuntu or is there a way?

**Comment by NeoTheThird** [comment]
You can use adb and fastboot on windows as well. Like it says in the further posts in the forum thread, you can use the ubports installer instead of ubuntu device flash in step 5. So all of the steps should be available on windows. If you have further questions, please ask in that thread.

Here's adb and fastboot: https://wiki.lineageos.org/adb_fastboot_guide.html#on-windows
