### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: error.includes is not a function

### ISSUE THREAD

**Issue by dmaglio** [ubports/ubports-installer#1015]
*Automatically generated error report* 
UBports Installer Version: 0.4.8-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Versione 10.0.18362.418] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/dTVHr6xH6F/

**Comment by dmaglio** [comment]
same issue with UBports Installer Version: 0.4.6-beta

**Comment by NeoTheThird** [comment]
Bug in our error handling. Underlying problem Seems to be a network issue on your end, fyi.

**Comment by NeoTheThird** [comment]
Fixed in #1050.
