### ISSUE TITLE
Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: out of space

### ISSUE THREAD

**Issue by PYT29** [ubports/ubports-installer#1016]
*Automatically generated error report* 
UBports Installer Version: 0.4.8-beta 
Device: arale
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/bfBjjC5CN3/

**Comment by NeoTheThird** [comment]
What OS is the device running? If it's android, you'll have to [manually unlock it by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices) first. Then the installer should work.
