### ISSUE TITLE
Uncaught TypeError: Cannot read property 'send' of undefined (MainRenderer:81)

### ISSUE THREAD

**Issue by b4thed4wn** [ubports/ubports-installer#1017]
*Automatically generated error report* 
UBports Installer Version: 0.4.8-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/rc","wipe":true,"bootstrap":true}
Package: dmg
Operating System: macOS 10.15.119B88 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/v2MMBjJFX4/

**Comment by NeoTheThird** [comment]
I'm assuming you got an oem lock warning and clicked unlock?
