### ISSUE TITLE
Snap does not run with strict confinement

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#102]
Currently the snap only works when running w/o confinement, so it can not be published on the stable and candidate channels in the store. There are two blockers for this:

- [x] [Obtain an exception](https://askubuntu.com/questions/980155/how-to-connect-non-auto-connect-snap-interfaces-at-daemon-service-start) that will allow us to auto-connect to the [raw-usb](https://docs.snapcraft.io/reference/interfaces) interface socket
- [x] Find out how to run sub-programs with sudo in a snap

If these problems are solved, the installer will be able to run confined.

**Comment by mariogrip** [comment]
I wonder, if we have raw-usb if we can run fastboot without sudo

**Comment by NeoTheThird** [comment]
Only one way to find out...

**Comment by NeoTheThird** [comment]
No, we can not because of #56. #103 contains a temporary workaround for this, which is echoing the vendor id into the snaps usb_ini.

**Comment by NeoTheThird** [comment]
Okay, here goes: https://forum.snapcraft.io/t/requesting-auto-connection-of-raw-usb-for-ubports-installer/4278
