### ISSUE TITLE
oneplus 3 recovery connection issue on windows

### ISSUE THREAD

**Issue by kissstudio** [ubports/ubports-installer#1021]
*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {channel:16.04/arm64/edge,wipe:false,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.17763.864] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/4qkzHZ3bD6/ 

failed to do "sending file to the device". when sending file, the device "FASTBOOT MODE" screen display few sec then android recovery screen shows on.

**Comment by kissstudio** [comment]
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/3844324/ubports-installer.log)

**Comment by NeoTheThird** [comment]
Okay, so the installer is unable to detect the device over adb when its in recovery mode.

> failed to do "sending file to the device". when sending file, the device "FASTBOOT MODE" screen display few sec then android recovery screen shows on.

To be clear, the fastboot screen was shown *before* the installer began sending files to the device, correct? As soon as it was trying to send, it should be the recovery screen already, which is also what i see in the log. If the device was back into fastboot mode by the time the installer had downloaded and verified the files, that'd be a problem :) But i'm assuming that's not the case, maybe try again and pay close attention to what happens.

You might also want to try a different USB cable and a different USB port on your computer. Cheap and old cables tend to lose connection during the installation. You might also want to check if [adb](https://wiki.lineageos.org/adb_fastboot_guide.html), the tool the installer is using to communicate with the device, can see the device when in recovery mode. If not, you need to check your adb driver.

**Comment by kissstudio** [comment]
> the fastboot screen was shown before the installer began sending files to the device, correct?
yes.

will the fastboot mode timeout if nothing sent? if the fastboot mode has a timeout, the file verfication step may cause this problem, it takes few sec.

**Comment by NeoTheThird** [comment]
Okay, i don't think i have made myself clear. When the installer says it's sending files, the device needs to be in *recovery mode*, not in fastboot. Was that the case or not?

No, fastboot mode should not time out.

**Comment by kissstudio** [comment]
About the case you asked I will check again. But a question, it cannot enter recovery mode by phone keys after the raw recovery environment replaced by the installer, but the installer can do. Why?
Another question, does the secure boot enabled state shows on bootloader screen make sence?

**Comment by NeoTheThird** [comment]
>  Another question, does the secure boot enabled state shows on bootloader screen make sence?

Yes, that doesn't matter.

> About the case you asked I will check again. But a question, it cannot enter recovery mode by phone keys after the raw recovery environment replaced by the installer, but the installer can do. Why?

That's a decision that oneplus made. We have no influence on that. Every device is different.

**Comment by kissstudio** [comment]
Well, about the 1st question, now can enter recovery modeby keys, its a misunderstand about warning screen. I have thought phone must enter android os after 5 seconds.

And about adb devices command output, the phone will not list out unless i active #android actions - #apply update - #apply from adb at recover mode, that means recovery mode was not really actived yet when phone screen shows the ui.

**Comment by kissstudio** [comment]
The operation ( #android actions - #apply update - #apply from adb)
on recovery mode will cause the adbd restart. And trigger installer reconnect. the problem still.

And about the case, when sending file text shows  on installer, the phone still a #fast boot mode# screen , and after few seconds , recovery mode screen shows. But file send will failed and a retry popup tips, retry action make nothing but a next loop

**Comment by kissstudio** [comment]
After a factory reset, i made it. 😃 , sending os file success
