### ISSUE TITLE
Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: out of space

### ISSUE THREAD

**Issue by manishhsinam89** [ubports/ubports-installer#1027]
*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/edge","wipe":false,"bootstrap":true,"format":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/Z7CBCzNC3f/

**Comment by NeoTheThird** [comment]
Should be fixed in the latest config.
