### ISSUE TITLE
krillin does not boot after installation

### ISSUE THREAD

**Issue by cm-t** [ubports/ubports-installer#1028]
*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/edge","wipe":true,"bootstrap":true}
Package: AppImage
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/wyFNQBKkjX/ 

```bash
cm-t@Desktop-t:~/Téléchargements$ ./ubports-installer.0.4.9-beta.AppImage
info: Welcome to the UBports Installer version 0.4.9-beta!
Pug interceptor registered successfully
info: Downloaded file 1 of 1
checked: keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz true
checked: version-189.tar.xz true
checked: device-77cc8901c5003c09436622d881297c5b4a7d60050d1cd176197da844986fee3d.tar.xz true
checked: ubports-0892840187a03edc690eecccfc620e84cd50d0eb47207374dd8b9f338c448fb3.tar.xz true
info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
```

* After installer said it is installed with success, the phone will reboot as expected
* Can see a white BQ boot screen for few second
* Can then see a Ubuntu colored backgroud + a loading bar 
* reboot after bar goes to 100%
* Can see a white BQ boot screen
* _stuck here_

**Comment by NeoTheThird** [comment]
I'm assuming the phone's still broken? *Might* be a hardware-specific issue.
