### ISSUE TITLE
Installer stuck on "Flashing firmware"

### ISSUE THREAD

**Issue by Flaburgan** [ubports/ubports-installer#1029]
My phone is already running UT devel with anbox img and I want to get ride of Anbox so I try to reflash the phone without wiping the data, but the installer is stuck on "Flashing firmware". I tried it twice, in the terminal where I launched the installer, last printed line is `info: Downloaded file 2 of 2`.

*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: FP2
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/devel","wipe":false,"bootstrap":true}
Package: deb
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/MsWSMjrwVF/

**Comment by Flaburgan** [comment]
I'm currently doing the install steps manually and it looks like `fastboot` needs to be prefixed by `sudo`, or it gets stuck on `<waiting for device>`. I guess that's why nothing's happening with the gui.

**Comment by NeoTheThird** [comment]
If you set up [udev rules](https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules) like the installer tells you in the beginning, you don't need sudo for fastboot.

**Comment by Flaburgan** [comment]
Well, that's true that I do not have those rules in a `51-android.rules` file, however my device is shown when I enter `adb devices`. I thought this meant I didn't need the rules, I didn't know rules also deal with superuser rights.

**Comment by NeoTheThird** [comment]
Udev rules handle permissions for usb devices, adb and fastboot work a little different in how they access it.

> never asked me to add rules.

It does it when you start it for the very first time, where you can also dismiss the notice so it never shows up again.

**Comment by Flaburgan** [comment]
>It does it when you start it for the very first time, where you can also dismiss the notice so it never shows up again.

Indeed.

I'll try with rules this week-end and confirm if it solves the problem.

**Comment by NeoTheThird** [comment]
Any news? You might also want to try with the [latest prerelease](https://github.com/ubports/ubports-installer/releases).

**Comment by Flaburgan** [comment]
I won't be able to test it before next Wednesday sorry.

**Comment by Flaburgan** [comment]
So I just tried to launch the installer with `sudo` without adding any udev rules and... it worked. So you were right, it was a permission problem. Now, I honestly don't know what we should recommend. In one hand, running an app with `sudo` is obviously easier than to add udev rules which requires some command lines, exactly what this installer is trying to avoid. In the other hand, running apps downloaded from the web with `sudo` is a bad practice and should not be encouraged. So... what do you think? Maybe we should simply mention it in the popup where users are asked to add the rules? Something like "You can also run this program with administrator rights if your device is detected and you don't want to add these rules".

I think we should at least detect when flashing firmware is not working and tell something to the user, as seeing the installer looping, the device being in fastboot mode, without knowing how to leave that is very frightening.

**Comment by NeoTheThird** [comment]
Yes, running the installer as sudo works, but as you said yourself, it's very bad practice. **Do not do it**. It can also lead to other issues, such as file permission problems on the next run as non-root, or mess up parts of your x11. We previously had a prompt for the password to only execute the adb and fastboot commands in the installer as root, but that lead to its own world of pain with many security concerns.

*Setting the correct udev rules is the clean and correct way to go. Everything else is bad practice.*

Now, i agree with your concerns that it goes against the philosophy of the installer to require the user to do this manually, and there's things we can do about it. The snap package for example plugs in to an interface in snapcraft that automatically sets the required udev rules. For the more basic packages, we have #901 to look forward to.

Everyone who recommends running the installer with sudo over our support channels **needs to stop that immediately**. I have had it up to \*gestures\* here with helping people to fix the issues that come from sudo, but it's a fight against windmills. Once wrong information is out there, it's out there.

End of rant, sorry you were of the recieving end of this. I appreciate your input of course, and i'm happy you got your phone working again. :)
