### ISSUE TITLE
Error: fastboot:flash: flashing failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery /home/bini/.cache/ubports/krillin/recovery/recovery-krillin.img"}stderr: < waiting for any device >Sending 'recovery' (9578 KB)                       OKAY [  0.350s]Writing 'recovery'                                 FAILED (remote: 'partition 'recovery' not support flash')fastboot: error: Command failed

### ISSUE THREAD

**Issue by ebni** [ubports/ubports-installer#1031]
*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/Ccy3swfT7w/

**Comment by NeoTheThird** [comment]
What OS is the device running? If it's Android, it needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices) for the installer to work.
