### ISSUE TITLE
oem unlock failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/249/app/resources/app.asar.unpacked/platform-tools/linux/fastboot oem unlock"}stderr: FAILED (remote: 'oem unlock is not allowed')fastboot: error: Command failed

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-installer#1033]
*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/dN4NZ75Mmb/

**Comment by ernesst** [comment]
The issue is not related to the software but the fact that oem unlock was not set in developper mode.
I would suggest to add the following steps in the installer : 
"

Hi all!

Following advice from @banderson5586:

    flashed TWRP to recovery partition using fastboot
    'fastboot flash recovery <twrp.img>
    where twrp.img was downloaded from https://twrp.me/oneplus/oneplusthree.html
    rebooted phone if 'recovery' mode and then using UI of TWRP I did the following

    fixed 'cache' partition
    fixed 'data' partition
    formatted and fixed 'system' partition

    after that installation with ubports-installer v.0.4.6 could be finished successfully.

Now all seem to work finally!

Important step was to format and fix the 'system' partition, before I did that, only fixing 'cache' and 'data' partition did not help - installation always stalled somewhere in the middle of 'sending' phase, when Ubuntu OS is supposed to be flashed on the device. After doing manipulations with 'system' partition, finally all finished successfully.

Thank you everybody for your comments and shared experience! And special thanks to UBPorts developers who make it all possible in the first place!
"
as per https://forums.ubports.com/topic/3253/oneplus-3-3t/33

**Comment by NeoTheThird** [comment]
This error should be handled in [devices.js](https://github.com/ubports/ubports-installer/blob/master/src/devices.js#L321) by showing a new modal that references the unlock steps (#937) with a button to restart the install.

**Comment by ernesst** [comment]
On the otherside, my oneplus 3T has been given to my wife for emergency, I've tried with a oneplus3, it was a pain to install lineage os due to partition issue too, so not really a bug on our side. 

Having these steps automatized would help the migration for newbie.
