### ISSUE TITLE
Error: fastboot:flash: flashing failed: error: {killed:false,code:1,signal:null,cmd:C:\\Users\\bkipp\\AppData\\Local\\Temp\\1TZ7gePbAuzykO3LuZHxOGDw15V\\resources\\app.asar.unpacked\\platform-tools\\win\\fastboot

### ISSUE THREAD

**Issue by benjaminlk21** [ubports/ubports-installer#1036]

**Comment by benjaminlk21** [comment]
This is on an Asus Nexus 7

**Comment by NeoTheThird** [comment]
The log seems to be cut off. Could you upload the [log file](https://github.com/ubports/ubports-installer#logs) here? Also, what webbrowser did you use? I need to reproduce the cut-off log issue.
