### ISSUE TITLE
Xperia X detected but can't fetch installation instructions

### ISSUE THREAD

**Issue by retro486** [ubports/ubports-installer#1037]
*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: F5121
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/xqRrkXcbgF/ 

Xperia X is detected as F5121 but installer gets stuck at "Fetching installation instructions..."

Phone is fresh flashed to latest stock 8.0 with USB debugging enabled.

**Comment by NeoTheThird** [comment]
Looks like those are [alternative codenames](https://en.wikipedia.org/wiki/Sony_Xperia_X) for the xperia x. @fredldotme can you confirm that both `F5121` and `F5122` should work? Then we can add [overrides](https://github.com/ubports/installer-configs/blob/master/aliases.json) for these.

**Comment by fredldotme** [comment]
Currently only the F5121 is supported. In the PR I'll propose soon(tm) the F5121 is explicitly mentioned. It's currently in the `master-suzu` branch.
