### ISSUE TITLE
Error: systemimage: Download failed: Download failed: undefined

### ISSUE THREAD

**Issue by 438816417** [ubports/ubports-installer#1038]
*Automatically generated error report* 
UBports Installer Version: 0.4.9-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: deb
Operating System: Red Hat Linux 5 undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/zDsK42cpVN/

**Comment by NeoTheThird** [comment]
Weird, no idea what's going on. Try again, if it fails again run `rm -rf /home/romantic/.cache/ubports/oneplus3/` and try again.
