### ISSUE TITLE
Fastboot: Unknown error:  ERROR: could not clear input pipe

### ISSUE THREAD

**Issue by popesz** [ubports/ubports-installer#104]
Automatically generated error report %0AVersion: 0.1.11-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v8.2.1 %0A%0AError log: http://paste.ubuntu.com/p/TDxDs9xmZf/ %0A

**Comment by NeoTheThird** [comment]
Duplicate of #92.
