### ISSUE TITLE
android-tools "workbench" for debugging

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#1041]
We are bundling `adb` and `fastboot` (and in the future also `heimdall`) binaries with the installer to communicate with the device. To allow debugging without actual hardware, it would be amazing to have sort of a "workbench" in a separate window that catches all adb and fastboot calls and allows replying to them to test the installers behavior. Similar to #697, but interactive.

This requires quite a bit of work, but if someone wants to take a swing at it, it would be immensely helpful down the road.

**Comment by orzelek77** [comment]
ok thx :)

**Comment by NeoTheThird** [comment]
Not a priority at the moment.
