### ISSUE TITLE
Really want go to next level with Ub Touch

### ISSUE THREAD

**Issue by fjmpchato** [ubports/ubports-installer#1043]
I propose need same way how you do Ubuntu for Pc and Server for Phones

any Pc, laptop, server can install and run Ubuntu in minutes

what you need for can flash any empty board or any other Android, windows or IOS and install new one Ubuntu Touch erase and write new OS

for example the customer can buy CPU, Memory, MotherBoard in Pc

why manufacture component phones offer the same for create personalization phones
 

Buy - Select - CPU - Qualcomm -Snapdragon- MTK - Etc
             Memory - 1 GB - 2 GB - 4 GB - 6 GB - 8 GB - 16 GB
             GPU 2 GB- 4 GB
             Board - Asus - Samsung - MSI - same as PC
             LCD

my idea is a interface detect list all Hardware for phones
create config file bash for install new OS Phone
pre select app to install or features same way how run for create server run thru network 

i see any mobile device as server can connect run work any futures thanks kernel linux  

OS - Ubuntu Touch 
i think if any hardware is compatible now with Linux Kernel can be posible with any hardware phone too today

phones have several areas
partitions - SYSTEM, USER, ETC.

Opensource and community is big for work together only need view clear where need to target

We need easy way to developt APPs

HTML5
JAVASCRIPT
PYTHON 
PHP
etc.
any language or Database

Best Regard

FJMPCHATO

**Comment by NeoTheThird** [comment]
Hey there, i love your enthusiasm, even though the bug tracker for the installer is not the best place to discuss this ;) Maybe you'd be interested to join some discussions [on the forum](https://forums.ubports.com)?
