### ISSUE TITLE
Data partition does not exist on hammerhead

### ISSUE THREAD

**Issue by sincaster** [ubports/ubports-installer#1045]
*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.19033.1] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/GqzSzFwVYW/ 

Stuck at "Ubuntu Touch successfully installed!" and at Google logo.

**Comment by NeoTheThird** [comment]
Looks like the data partition doesn't exist as we expect it. I'm assuming the deivce was running android with an encrypted partition of some sort before.

Could you try again and pass [this file](https://github.com/ubports/installer-configs/blob/882c68415289167a91405570699054d7329685af/v1/hammerhead.json) as a [config file argument](https://github.com/ubports/ubports-installer#config-files)?
