### ISSUE TITLE
Add option to quit with cmd+q to electron menu for our macOS users

### ISSUE THREAD

**Issue by vlladdrakk** [ubports/ubports-installer#1047]
The only way to quit the ubports installer is to right click on the dock icon and select quit. The typical way is to hit command-q (which does nothing) or to select quit from the menu bar (there is no quit option there). I think it would make the experience better if those methods of closing the application were available.
The close button (red X) on the window will only close the window, the application will remain open.

*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: dmg
Operating System: macOS 10.14.618G1012 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/HMM2zwg6nk/

**Comment by NeoTheThird** [comment]
Keeping the application open after the x is closed is conventional on macos, that's why we do it like that. It might be okay to break the convention though, as we are not a normal app that you will want to return to after closing. Not sure what I think about this.

**Comment by vlladdrakk** [comment]
I agree with that, clicking the x doesn't need to quit the application. However, I still think that hitting command-q should quit and that there should be a quit option in the menubar. Those, I think, are the convention on macos.

**Comment by NeoTheThird** [comment]
Included in [0.5.6-beta](https://github.com/ubports/ubports-installer/releases/tag/0.5.6-beta).
