### ISSUE TITLE
Udev rules

### ISSUE THREAD

**Issue by LEMOUELLIC** [ubports/ubports-installer#1048]
Bonjour,

J'ai essayé de passer d'ubuntutouch version ubuntu 15.04(OTA-15) à UBPorts par ubports-installer_0.4.11-beta_amd64.deb et cela ne fonctionne pas.

Ci-joint message d'erreur en capture d'écran.
2ème problème le reboot to bootloader "press and hold the volume down and power buttons until the phones reboots" il ne se passe rien au niveau du téléphone écran noir.
La 2ème fois en bas à gauche en le déconnectant du PC apparait bootloader et pour lire le reste il faudrait une loupe.

Merci d'avance pour votre aide

Joël Le Mouëllic
![Capture d’écran_2019-12-01_14-30-02](https://user-images.githubusercontent.com/58391461/69984396-5749e080-1539-11ea-904d-9f191d4a93d4.png)

**Comment by NeoTheThird** [comment]
Bonjour, je suis desolé de mon francais terrible. Je responde en anglais maintenant. Si tu ne me comprends pas, j'appellerai plus de personnes qui parlent francais.

It would have been a little easier if you had clicked the "Report a bug" button, then i would already have all the information i need. I'm assuming you are using the installer as a deb or appimage. There is a problem with the udev rules, which is a subsystem in linux responsible for regulating access to usb devices. [Here](https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules)'s how to fix it.

**Comment by LEMOUELLIC** [comment]
Hello,

Thank you to reply

I have clicked the "Report a bug" button and sended with the joined file in copy for you.

I have used the installer as a deb and not appimage.

I have tried with WIN 7 but it's the same error (joined file).

With the error "insufficient permissions for device" i have deleted the password and it's the same error message.

Thank you for your help

Best regards

Joël Le Mouëllic

----- Mail original -----
De: "Jan Sprinz" <notifications@github.com>
À: "ubports/ubports-installer" <ubports-installer@noreply.github.com>
Cc: "LEMOUELLIC" <mouellj@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 3 Décembre 2019 14:18:00
Objet: Re: [ubports/ubports-installer] Pb ubuntu touch with Github  (#1048)



Bonjour, je suis desolé de mon francais terrible. Je responde en anglais maintenant. Si tu ne me comprends pas, j'appellerai plus de personnes qui parlent francais. 

It would have been a little easier if you had clicked the "Report a bug" button, then i would already have all the information i need. I'm assuming you are using the installer as a deb or appimage. There is a problem with the udev rules, which is a subsystem in linux responsible for regulating access to usb devices. Here 's how to fix it.

**Comment by NeoTheThird** [comment]
As i asked you in my previous comment, and also in #1053, you need to set the udev rules: https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules

It is not possible to have the same error in Windows 7, since it does not have the udev system.

**Comment by LEMOUELLIC** [comment]
Hy,

Hourra the upgrade is OK. Now My MX4 is in UBUNTU 16.04 (OTA-11).

Thank you for your help best regards

Joel LE MOUELLIC


----- Mail original -----
De: "Jan Sprinz" <notifications@github.com>
À: "ubports/ubports-installer" <ubports-installer@noreply.github.com>
Cc: "LEMOUELLIC" <mouellj@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mercredi 4 Décembre 2019 13:45:26
Objet: Re: [ubports/ubports-installer] Udev rules (#1048)



Closed #1048 .

**Comment by NeoTheThird** [comment]
Awesome, glad it worked for you. Hope you enjoy Ubuntu Touch :)
