### ISSUE TITLE
device not detected

### ISSUE THREAD

**Issue by kpphyoe** [ubports/ubports-installer#1049]
*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: frieza
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/SCjvPxwWZq/

**Comment by NeoTheThird** [comment]
So, your PC does not see your device. Try running `snap connect ubports-installer:raw-usb`. If that doesn't work, maybe try a different cable.
