### ISSUE TITLE
[hammerhead] Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: out of space

### ISSUE THREAD

**Issue by byronbgs** [ubports/ubports-installer#1052]
*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/edge,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.418] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/cBM3trQtJ6/

**Comment by NeoTheThird** [comment]
What OS was the phone running before? Exact version?

**Comment by byronbgs** [comment]
Jan, 

 

What OS was the phone running before?  Exact version? …… AOKP Android 7.1  http://xfer.aokp.co/?developer=AOKP <http://xfer.aokp.co/?developer=AOKP&folder=hammerhead> &folder=hammerhead 

 

 

FURTHER INFO (you may need):

 

I did try Android 9.0 but the requirements were to repartition the phone to accept the bigger ROM. 

https://forum.xda-developers.com/google-nexus-5/orig-development/repartition-nexus-5-repartition-t3844395

 

After the flash of 9.0 the phone was buggy and slow. I went back to AOKP 7.1 and I ended up with 1 GB root partition. The ROM ran fine with the bigger partition and it allowed for me to flash a larger GAPPS file. 

 

Thanks

Byron Briggs

**Comment by KylePiira** [comment]
I'm also having this issue on my OnePlus 3. I noticed that the `/cache` partition is only 231 MB.

**Comment by chhager** [comment]
possibel solution: repartition to stock partition configuration
explanation: switched from ubtouch to Lineage 17.1, for that I had to repartition; didn't like Android 10, so wanted to go back to ubtouch;

here's a link to a repartition-to-stock-script, that's part of a twrp image ( twrp-3.3.1-HH-hammerhead.img ) :
https://forum.xda-developers.com/showpost.php?p=79928889&postcount=190

just follow the instructions for reverting the partitioning.

**Comment by baruchiro** [comment]
> possibel solution: repartition to stock partition configuration
> explanation: switched from ubtouch to Lineage 17.1, for that I had to repartition; didn't like Android 10, so wanted to go back to ubtouch;
> 
> here's a link to a repartition-to-stock-script, that's part of a twrp image ( twrp-3.3.1-HH-hammerhead.img ) :
> https://forum.xda-developers.com/showpost.php?p=79928889&postcount=190
> 
> just follow the instructions for reverting the partitioning.

It didn't work for me.

I even reinstalled *LineageOS*, but when I run `hh_repart` it tells me `Unknown partitions`

**Comment by pedja1** [comment]
This worked for me to go back to stock partition layout
https://forum.xda-developers.com/google-nexus-5/orig-development/repartition-nexus-5-repartition-t3844395

1. flash `twrp-3.3.1-1_UA-hh.img` via fastboot
2. Reboot to twrp
3. Install `hh_clamor_repartition.zip`
4. When complete go to Advanced->Terminal and type `stock`, it will automatically reboot

That is it, not it should be back to stock partition table and installer should work

**Comment by byronbgs** [comment]
Thanks I'll give it a try.

⁣Get BlueMail for Android ​
