### ISSUE TITLE
Error: adb:format: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."}stderr: error: insufficient permissions for device: user in plugdev group

### ISSUE THREAD

**Issue by LEMOUELLIC** [ubports/ubports-installer#1053]
![Capture d’écran_2019-12-01_14-30-02](https://user-images.githubusercontent.com/58391461/70135641-bc611b80-168a-11ea-9dff-dfcd29dd6bdc.png)
*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: arale
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/P3nMFrgsKf/

**Comment by NeoTheThird** [comment]
Looks like your udev rules have a problem. [Here](https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules)'s how to fix it.

**Comment by LEMOUELLIC** [comment]
hello,

The bootloader is OK.
During the installation process i have to disconnect the MX4 to pass in bootloader mode. When i push in the same time the power button and the down volume button i see in little characters in the bottown left corner of the MX4 "bootloader".

The connection between PC and smartphone is OK.

thank you

best regards

joel le mouellic




----- Mail original -----
De: "Jan Sprinz" <notifications@github.com>
À: "ubports/ubports-installer" <ubports-installer@noreply.github.com>
Cc: "LEMOUELLIC" <mouellj@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mercredi 4 Décembre 2019 11:52:42
Objet: Re: [ubports/ubports-installer] Error: adb:format: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."}stderr: error: insufficient permissions for device: user in plugdev group (#1053)



Closed #1053 .

**Comment by NeoTheThird** [comment]
Yeah, i got that. But if you don't have udev rules set, your device can't be detected. That's why i asked you to look at the udev instructions: https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules
