### ISSUE TITLE
Error: fastboot:flash: flashing failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery /home/mk/.cache/ubports/FP2/firmware/recovery-FP2.img"}stderr: < waiting for any device >Sending 'recovery' (11442 KB)                      OKAY [  0.669s]Writing 'recovery'                                 FAILED (remote: 'can't flash unsigned image')fastboot: error: Command failed

### ISSUE THREAD

**Issue by manlamkonyak** [ubports/ubports-installer#1058]
*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: FP2
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/Nt3tP6BVP8/

**Comment by NeoTheThird** [comment]
You're trying to install the FP2 image on an ASUS_Z010_CD? That's not a great idea :)

**Comment by manlamkonyak** [comment]
it's an android phone. Can I not force install? ubport installer doesn't
have my device listed.
is there any way I get to  install Ubuntu touch to any android device on my
own risk.

>

**Comment by NeoTheThird** [comment]
No, android devices work a little different than most computers. If you want to look into porting, see [docs.halium.org](https://docs.halium.org).
