### ISSUE TITLE
oem unlock failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot oem unlock"}stderr: FAILED (remote: 'oem unlock is not allowed')fastboot: error: Command failed

### ISSUE THREAD

**Issue by jakeant2** [ubports/ubports-installer#1059]
*Automatically generated error report* 
UBports Installer Version: 0.4.11-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/SVNcwNCBMJ/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
