### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash splash \"/home/radiant/.cache/ubports/FP2/firmware/splash-FP2.img\""}stderr: Sending 'splash' (6075 KB)                         OKAY [  0.205s]Writing 'splash'                                   FAILED (remote: 'This partition doesn't exist')fastboot: error: Command failed

### ISSUE THREAD

**Issue by Ngugisenior** [ubports/ubports-installer#1067]
*Automatically generated error report* 
UBports Installer Version: 0.4.12-beta 
Device: FP2
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/N7nqFzWyWs/

**Comment by NeoTheThird** [comment]
Sorry about that, what OS and version is the device running?
