### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Panos-4** [ubports/ubports-installer#1068]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux  19.10  eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/68g2PzTnch/

**Comment by NeoTheThird** [comment]
try running `snap connect ubports-installer:raw-usb` and start the installer again
