### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery \"/home/toujirou71/.cache/ubports/frieza/recovery/recovery-frieza.img\""},"stdout":"","stderr":"Sending 'recovery' (11450 KB)                      OKAY [  0.425s]\nWriting 'recovery'                                 FAILED (remote: 'failed to get download permission for partition 'recovery'\n')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by toujirou** [ubports/ubports-installer#1069]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: frieza
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/9p4FdBvV3S/

**Comment by NeoTheThird** [comment]
What OS is the tablet running?
