### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by lool-lauris** [ubports/ubports-installer#1070]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/devel","wipe":true,"bootstrap":true,"format":true}
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/G2hc49yZGZ/

**Comment by NeoTheThird** [comment]
Sorry about that, what OS is the device running?

**Comment by lool-lauris** [comment]
OK, it's fixed.
The problem was that the partition was exotic ( https://forum.xda-developers.com/showpost.php?p=79928889&postcount=190 ).
I revert back to its original partition and everything goes well.

**Comment by bbored** [comment]
How do you revert the partitioning?
