### ISSUE TITLE
[suzu] Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/home/daveacc/.cache/ubports/pool/ubports-910e1b8d940df68e751cd1e047a21b438b85bc24471aade397242765009a6c4d.tar.xz' to '/cache/recovery/ubports-910e1b8d940df68e751cd1e047a21b438b85bc24471aade397242765009a6c4d.tar.xz': remote write failed: Read-only file system/home/daveacc/.cache/ubports/pool/ubports-910e1b8d940df68e751cd1e047a21b438b85bc24471aade397242765009a6c4d.tar.xz: 0 files pushed. 13.2 MB/s (209820656 bytes in 15.148s)

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubports-installer#1072]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/P5Q9rX7KJ2/

**Comment by Dave1152000** [comment]
Updated to latest version of installer but still seems to fail sending files to device

**Comment by NeoTheThird** [comment]
Weird. Is it possible that the device was in system mode rather than recovery when this happened?

**Comment by S3sm9** [comment]
Ya eh resuelto el problema, aqui la solucion:

#1089 (comment)

Es la respuesta al mismo problema que tienes.

**Comment by bblaha** [comment]
I had the same problem on my OnePlus 3. This is how I fixed it in a much easier and less intrusive way than @S3sm9 suggested:
Have your basic OS installed
Run the installer according to UBinstaller guidelines
In my case it always had an error where it did not find the device and I was in the Android/Ubuntu Recovery menu (black and yellow)
Go to Android functions and perform a FULL WIPE (Factory reset!)
Go to fastboot mode and let the installer run again
Now it should give you the Read only error.
NOW go to fastboot and install TWRP again
Go to WIPE and do the following:
Select Advanced, select cache.
Not sure what it is called exactly, but change the File system to ext4, then go back, repair the partition and finally resize the partition.
Then reboot to fast mode
Let the installer run again

Then it worked for me

I am sure this can be broken down further and I am not sure what the initial cause is. I'm just happy it works after hours of failure.

**Comment by NeoTheThird** [comment]
We made a lot of changes to the config for suzu, so i'm going to close this for now. If it comes back, we'll look into it some more.
