### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by Gryent** [ubports/ubports-installer#1073]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Versi�n 10.0.19041.1] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/WynsfGYXTC/

**Comment by NeoTheThird** [comment]
Sorry about that. There's two things here. For one, it seems like we still have an issue with usernames with spaces on windows (#847), which i have to look into again, for the other, we're not handling the adb error here properly. The latter is easily fixed. For now, just dismiss the error, you should be okay to continue.
