### ISSUE TITLE
no device detected on snap

### ISSUE THREAD

**Issue by stew42069** [ubports/ubports-installer#1074]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/83Dg3fVv5s/

**Comment by NeoTheThird** [comment]
Sorry about that. Try running `snap connect ubports-installer:raw-usb` and starting the installer again.
