### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/262/app/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/posao/snap/ubports-installer/262/.cache/ubports/flo/firmware/boot.img\""},"stdout":"","stderr":"Sending 'boot' (11320 KB)                          FAILED (Write to device failed (Protocol error))\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by pasanov** [ubports/ubports-installer#1077]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":true}
Package: snap
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/kNSjHFJk5J/

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed in the next release.
