### ISSUE TITLE
[flo] Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/fastboot flash boot '/Users/nabakishore/Library/Caches/ubports/flo/firmware/boot.img'"},"stdout":"","stderr":"Sending 'boot' (11320 KB)                          OKAY [  1.352s]\nWriting 'boot'                                     FAILED (remote: '(InvalidSize)')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by nabakishore** [ubports/ubports-installer#1078]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/devel","wipe":true,"bootstrap":true,"format":true}
Package: dmg
Operating System: macOS 10.11.615G19009 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/Dwg4z7N483/

**Comment by NeoTheThird** [comment]
This should not be an issue any more with the new version of fastboot shipped in 0.5.0-beta and above.
