### ISSUE TITLE
Switch to the ubuntu font

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#108]
The installer deserves to look beautiful.

**Comment by ismaelbonato** [comment]
Hello, I think Gustavo Silva can help us with this Task.

**Comment by gsilvapt** [comment]
Hello! Yes, I want to resolve this issue if that's okay :smile:

**Comment by NeoTheThird** [comment]
Sounds good! I don't think we use anything from fontawesome, so yes, i think that folder and their css files and imports can be removed. @mariogrip can you confirm this?

We might want to add fallback-options to the css, who knows what kind of weird shit will happen. `"Ubuntu", "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif` should be plenty ;)

Could you send a PR for this, @gsilvapt?

**Comment by gsilvapt** [comment]
As this has been merged, I propose closing this issue. Thanks @NeoTheThird and @ismaelbonato for helping me getting started :+1:
