### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/usr/share/ubports-installer/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: No such process"}

### ISSUE THREAD

**Issue by miketth** [ubports/ubports-installer#1080]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: dir
Operating System: Arch Linux undefined undefined x64 
NodeJS version: v10.11.0 

Error log: https://paste.ubuntu.com//p/tWgT8dX4hb/

**Comment by NeoTheThird** [comment]
duplicate of #1304
