### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by fengjutian** [ubports/ubports-installer#1082]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: dmg
Operating System: macOS 10.1519A583 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/VfJ8xhCSgk/

**Comment by NeoTheThird** [comment]
Will be fixed in latest version.
