### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/fastboot flash recovery '/Users/himavarshan/Library/Caches/ubports/krillin/recovery/recovery-krillin.img'"},"stdout":"","stderr":"Sending 'recovery' (9578 KB)                       OKAY [  0.241s]\nWriting 'recovery'                                 FAILED (remote: 'unknown command')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by himavarshan** [ubports/ubports-installer#1083]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: dmg
Operating System: macOS 10.15.219C57 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/TvMC4T9s47/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
