### ISSUE TITLE
Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: insufficient permissions for device: user in plugdev group

### ISSUE THREAD

**Issue by kurianCoding** [ubports/ubports-installer#1085]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":false}
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/5G5SXv9zs7/

**Comment by NeoTheThird** [comment]
sorry about that, try [adding the udev rules](https://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules)
