### ISSUE TITLE
[flo] Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by buglinjo** [ubports/ubports-installer#1087]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: dmg
Operating System: macOS 10.15.219C57 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/BjF8Prrdzf/

**Comment by S3sm9** [comment]
Ya eh resuelto el problema, aqui la solucion:

https://github.com/ubports/ubports-installer/issues/1089#issuecomment-570749212

Es la respuesta al mismo problema que tienes.
