### ISSUE TITLE
[mako] Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by ddaumiller** [ubports/ubports-installer#1089]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/devel","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/QBg8365RF9/

**Comment by ddaumiller** [comment]
looks like the installer is trying to push its files to /cache.
But that's only 90MB... can the storage be adapted?

**Comment by kolyan4g** [comment]
I resized the partition. This guide has helped me: "How To: Re-partition Your Android Tablet Or Smartphone? (All Options Included: Change Size, FS Type, Etc…)" https://iwf1.com/how-to-re-partition-your-android-tablet-or-smartphone-all-options-included-change-size-fs-type-etc/2

**Comment by S3sm9** [comment]
Hola, eh escrito un pequeño tutorial en txt que les puede ayudar con este problema, el tutorial esta en español pero no creo que tengan problemas si lo traducen con google translate.
Adjunto un archivo .zip con el Archivo txt, el archivo parted.rar y herramientas adb para la edicion de las particiones desde el cmd. 

[Instructivo y ADB Tools.zip](https://github.com/ubports/ubports-installer/files/4021458/Instructivo.y.ADB.Tools.zip)
