### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery \"/home/allwin/.cache/ubports/krillin/recovery/recovery-krillin.img\""},"stdout":"","stderr":"Sending 'recovery' (9578 KB)                       OKAY [ 11.985s]\nWriting 'recovery'                                 FAILED (remote: '\npartition 'recovery' not support flash')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by it-azatka** [ubports/ubports-installer#1091]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/vdBytCJTQq/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
