### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by JacinteLYU** [ubports/ubports-installer#1092]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [�汾 10.0.18362.535] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/9hhV6T4BWG/

**Comment by NeoTheThird** [comment]
Will be fixed in next version.
