### ISSUE TITLE
Correct Nexus 4 Bootloader button instructions 

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/ubports-installer#1093]
# Quick comments
I was doing a wipe of my N4 and remembered this issue.  The accompanying image also should reflect the extra button required below.  Thanks!

### What the installer says

"Hold power button and Volume down button"

### What the installer should say

"Hold Power, and Volume Down, **and Volume Up** button"

**Comment by NeoTheThird** [comment]
thanks
