### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by vitalinvent** [ubports/ubports-installer#1097]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:false,bootstrap:true,format:false}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.535] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/GhMtGZJJhY/

**Comment by NeoTheThird** [comment]
Please try a different cable or usb slot.
