### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by puuska** [ubports/ubports-installer#1098]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 6.3.9600] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/F55WVkkH9n/

**Comment by NeoTheThird** [comment]
Will be fixed in next version.
