### ISSUE TITLE
Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: more than one device/emulator"}

### ISSUE THREAD

**Issue by xxm3234** [ubports/ubports-installer#1099]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":false}
Package: dmg
Operating System: macOS 10.15.219C57 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/pYzT9NdYk7/

**Comment by NeoTheThird** [comment]
#653
