### ISSUE TITLE
Windows path contains a forward slash

### ISSUE THREAD

**Issue by ijgarcia** [ubports/ubports-installer#110]
Autom

It stops there. Using a nexus 5 and windows 10

Adb push error: cannot stat ''C:\Users\Ignacio\AppData\Roaming\ubports\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

**Comment by ijgarcia** [comment]
Worked with 0.9 version of the installer

**Comment by NeoTheThird** [comment]
Good to hear, i'll leave this issue open though, this obviously needs to be fixed.

**Comment by vadrian89** [comment]
Got the same error, seems version 0.1.9 works.

**Comment by NeoTheThird** [comment]
Why was this closed @mariogrip?

**Comment by rdrowe** [comment]
Still happening. Reference my #300 above. Submitted today. With Windows 0.1.13(beta) installer.
