### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery \"/home/serpentcs/.cache/ubports/krillin/recovery/recovery-krillin.img\""},"stdout":"","stderr":"Sending 'recovery' (9578 KB)                       OKAY [  0.353s]\nWriting 'recovery'                                 FAILED (remote: 'download for partition 'recovery' is not allowed\n')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by chandnaniSk** [ubports/ubports-installer#1101]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/3Xdm5n3Zh6/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
