### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Sparrow1984** [ubports/ubports-installer#1104]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/hHWQVZG293/

**Comment by NeoTheThird** [comment]
What seems to be the problem?
