### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by globalbestvl** [ubports/ubports-installer#1108]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux  19.10  eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/xgFCGXf72f/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
