### ISSUE TITLE
Nexus 7 2013 (flo) never detected

### ISSUE THREAD

**Issue by PSBaffins** [ubports/ubports-installer#1109]
consistently comes up as disconnected despite using different usb cables and different ports. Android Studio and adb tools & drivers are both installed.
EDIT: tried on Windows 10, Ubuntu 19.10 and Ubuntu 18.04, none of which worked.

**Comment by NeoTheThird** [comment]
Does the connection work initially? Could you try again and send me a [log](https://github.com/ubports/ubports-installer#logs)? How does the micro-usb port look? If it's damaged, the cable might loosen, so you could try holding it in a position to ensure it keeps contact.
