### ISSUE TITLE
Oneplus One does not boot

### ISSUE THREAD

**Issue by DealerJohn** [ubports/ubports-installer#1112]
Latest Oneplus One bug report.....

*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":false}
Package: dmg
Operating System: macOS 10.14.618G2022 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/JJj7SpS7s4/

**Comment by NeoTheThird** [comment]
Sorry about that. What OS was the device running before?

**Comment by kilchenmann** [comment]
I have the same issue with the BQ Aquarius E4.5 which had already Ubuntu touch installed, but version 15.04 and I wanted to upgrade to 16.04. A direct update (from system settings) was not offered, so I thought to reinstall with UBports installer (0.4.14-beta) on Mac OS Catalina 10.15.3
