### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by a937983423** [ubports/ubports-installer#1113]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [�汾 10.0.17763.973] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/FQ8j6dD7W2/

**Comment by NeoTheThird** [comment]
sorry about that, will be fixed in the next release.
