### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by stephiemtz12** [ubports/ubports-installer#1115]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: cooler
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/edge","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/pw2jNd8dNM/

**Comment by NeoTheThird** [comment]
What seems to be the problem? There's nothing in the log, unfortunately :)
