### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/luckxa/.cache/ubports/flo/firmware/boot.img\""},"stdout":"","stderr":"Sending 'boot' (11320 KB)                          OKAY [  1.333s]\nWriting 'boot'                                     FAILED (remote: '(InvalidSize)')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by Luckxa** [ubports/ubports-installer#1116]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/rc","wipe":true,"bootstrap":true,"format":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/bfcSyj627n/

**Comment by NeoTheThird** [comment]
You selected the device manually. Are you sure you have a **flo**?
