### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {error:{killed:false,code:1,signal:null,cmd:C:\\Users\\Elmer\\AppData\\Local\\Temp\\1Uo4H80AYPnCivmpnC8M9LLWxLb\\resources\\app.asar.unpacked\\platform-tools\\win\\fastboot

### ISSUE THREAD

**Issue by elmerrivera** [ubports/ubports-installer#1117]
Need help

**Comment by NeoTheThird** [comment]
Thank you for reporting this. For future bug reports,  please sum up the most important information in the title of the issue and provide further information (Logs, steps to reproduce, etc.) on the  bug in the description if necessary. (No offense.) It's ok for a clear issue like this one, but debug information is vital for most bug  reports. If you're interested, you [can read our guide on writing a good bug report](https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report). Thank you :)
