### ISSUE TITLE
Node.js developers w/ experience on macOS and Windows needed

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#112]
Most UBports developers work with Linux, so re-producing and fixing edge-cases on macOS and Windows can be difficult. If there are macOS and Windows users with a soft spot for Ubuntu Touch out there, all help would be appreciated!

**Comment by Arc676** [comment]
What do you mean by “Node.js developers”? I don’t work on Node itself but I’ve written Discord bots in JS that I run with Node and have basic JS knowledge. 

I run Mac and Linux though. If there’s anything I can do to help, I’d be happy to. I run UBPorts Ubuntu Touch on a Nexus 7 (flo).

For Windows, I have XP, if that’s still relevant in any way.

**Comment by NeoTheThird** [comment]
Hey @Arc676, maybe take a look at the code to see if you're comfortable working with it. There's a couple issues that [need help](https://github.com/ubports/ubports-installer/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) and some (at the moment only one) [that is reserved for first-time contributors](https://github.com/ubports/ubports-installer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). If you want to start looking at weird macOS issues, #92 is definitely up there. Thanks for your help!

**Comment by NeoTheThird** [comment]
Closing now, as the main issues are resolved. But of course we can still use all the help we can get! If you're still interested @Arc676 (or anyone else), here are some [good first issues](https://github.com/ubports/ubports-installer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). Thanks :)
