### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {error:{killed:false,code:1,signal:null,cmd:C:\\Users\\Elmer\\AppData\\Local\\Temp\\1Uo4H80AYPnCivmpnC8M9LLWxLb\\resources\\app.asar.unpacked\\platform-tools\\win\\fastboot

### ISSUE THREAD

**Issue by elmerrivera** [ubports/ubports-installer#1120]
Im trying to install Ubuntu touch on my Nexus 7 (2013 Wifi) but I get the message shown. Please help!

**Comment by NeoTheThird** [comment]
That's odd. Could you try again and send me the [log](https://github.com/ubports/ubports-installer#logs)?
