### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by offbeat-stuff** [ubports/ubports-installer#1121]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: generic_x86_64
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/ktBXNKwRWZ/

**Comment by NeoTheThird** [comment]
sorry about that, will be fixed in the next release.
