### ISSUE TITLE
user-requested bug-report (trying to istall Ubuntu Touch)

### ISSUE THREAD

**Issue by nankimora** [ubports/ubports-installer#1123]
Hello, I just got a Nexus 5 Hammerhead phone specially to install Ubuntu Touch on it, but the Ubports installer simply won't find my phone, and I've tried downloading the installer directly from the phone, but the phone won't open the installer file. 

What could be wrong/ missing here? 

Thank you. 

*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: dmg
Operating System: macOS 10.1418A391 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/YQpJvp7VZz/

**Comment by C0n57an71n** [comment]
Hi. Have you activated your Developer option on your Android?

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
