### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by afanhermawan** [ubports/ubports-installer#1131]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: ginkgo
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Ubuntu Linux    18.04    bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/JVVbSF7tmJ/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
