### ISSUE TITLE
Adb failed to reboot!, reboot failed: -1 : 

### ISSUE THREAD

**Issue by geminiano65** [ubports/ubports-installer#114]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: ia32 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/FRb4g9QrtR/

**Comment by geminiano65** [comment]
I installed ubuntu xenial 16.04 in nexus 5 and when I went to vivid it gave me this error in ubuntu installer

**Comment by NeoTheThird** [comment]
Possible duplicate of #43.
