### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by daniel1988** [ubports/ubports-installer#1144]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/cSy47HTt48/

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed in the next release.
