### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/michele/.cache/ubports/hammerhead/firmware/boot-hammerhead.img\""},"stdout":"","stderr":"Sending 'boot' (12302 KB)                          OKAY [  0.539s]\nWriting 'boot'                                     FAILED (remote: 'size too large')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by Michelebuffa** [ubports/ubports-installer#1145]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/6FXtQQgfBy/

**Comment by NeoTheThird** [comment]
unable to reproduce
