### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by raffaindo** [ubports/ubports-installer#1152]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: lavender
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.418] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/R93bXvgK8q/

**Comment by NeoTheThird** [comment]
Sorry, that device is not supported by the UBports Installer yet.

**Comment by NeoTheThird** [comment]
I see where your confusion came from, i added a section on missing installer support to the [devices detail page](https://devices.ubuntu-touch.io/device/lavender/).
