### ISSUE TITLE
Fallback user action results in split-brain

### ISSUE THREAD

**Issue by millerfortie** [ubports/ubports-installer#1154]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/4HjYjfH9JN/

**Comment by millerfortie** [comment]
Same on 16 version. For what you are doing reboot in command... Don't do that! Because after reboot it does not go to that mode in auto regime... no common sense.

**Comment by millerfortie** [comment]
Dont check ADB in auto too no common sense because sometime it's goes without number of the device or empty line. But fastboot devices command see that as well as adb commands work.

**Comment by millerfortie** [comment]
Ask user to do it manually.

**Comment by millerfortie** [comment]
or check adb working in fastboot regime

**Comment by NeoTheThird** [comment]
Thanks for reporting
