### ISSUE TITLE
UBports Installer 0.4.16-beta from Ubuntu snapstore does not open

### ISSUE THREAD

**Issue by stanwood77** [ubports/ubports-installer#1155]
Since last Ubports Installer update 0.4.16-beta. I'm unable to open it. The used version is the one from Ubuntu official snapstore.
By clicking on the program nothing's happening.
I tried many times to reinstall the application but nothing changes.
However AppImage does work properly. Bug only affects snapstore version.
Please find the attached logs error that I've got. (Ubuntu 19.10)

BR, Stanwood77

![UBports installer error 2020-04-01 12-58-20](https://user-images.githubusercontent.com/62994815/78131666-b9e5b700-741b-11ea-892f-40a0708bf705.png)

**Comment by NeoTheThird** [comment]
Freaky. It works when running from cli, which is how i tested. Thanks for reporting.

**Comment by stanwood77** [comment]
Ok, Thank you. Strange… Still not working from my side (and other users neither). I did uninstall + sudo apt update + reboot + re-install from Ubuntu snap store, but still not working ;-( Programm do not opening when click on it.

 

Regards,

 

Steve

 

 

De : Jan Sprinz [mailto:notifications@github.com] 
Envoyé : mercredi, 1 avril 2020 21:09
À : ubports/ubports-installer
Cc : stanwood77; Author
Objet : Re: [ubports/ubports-installer] UBports Installer 0.4.16-beta from Ubuntu snapstore does not open (#1155)

 

Freaky. It works when running from cli, which is how i tested. Thanks for reporting.

**Comment by NeoTheThird** [comment]
Sorry, i made a mistake, that's why i deleted my comment on github. Yes, i was able to reproduce the behavior and am working on a fix. GitHub's email-replies aren't very nice to use, btw, check out what it did with your reply :D https://github.com/ubports/ubports-installer/issues/1155

If you need the installer right now, consider using the appimage : https://devices.ubuntu-touch.io/installer/?package=appimage

**Comment by stanwood77** [comment]
Thank you very much Jan,

 

If it can help, here’re error message logs:

 

21:34:49 dbus-daemon: /snap/ubports-installer/269/app/ubports-installer: 

error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

21:34:49 dbus-daemon: /snap/ubports-installer/269/app/ubports-installer: 

error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

21:34:41 dbus-daemon: /snap/ubports-installer/269/app/ubports-installer: 

error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

21:34:36 dbus-daemon: /snap/ubports-installer/269/app/ubports-installer: 

error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

21:34:36 systemd: tmp-snap.rootfs_TRd7Fa.mount: Succeeded.

21:34:28 gnome-shell: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).

 

AppImage runs fine ,-)

 

Cheers, Steve

 

De : Jan Sprinz [mailto:notifications@github.com] 
Envoyé : mercredi, 1 avril 2020 21:45
À : ubports/ubports-installer
Cc : stanwood77; Author
Objet : Re: [ubports/ubports-installer] UBports Installer 0.4.16-beta from Ubuntu snapstore does not open (#1155)

 

Sorry, i made a mistake, that's why i deleted my comment on github. Yes, i was able to reproduce the behavior and am working on a fix. GitHub's email-replies aren't very nice to use, btw, check out what it did with your reply :D #1155 <https://github.com/ubports/ubports-installer/issues/1155> 

If you need the installer right now, consider using the appimage : https://devices.ubuntu-touch.io/installer/?package=appimage

**Comment by NeoTheThird** [comment]
Should be fixed in [this release](https://github.com/ubports/ubports-installer/releases/tag/0.4.17-beta). Could you try and let me know? You can run `snap refresh ubports-installer --edge` to try it. Thanks!

**Comment by stanwood77** [comment]
Great it works! Thank you!

**Comment by NeoTheThird** [comment]
thanks
