### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by baruchiro** [ubports/ubports-installer#1164]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/DpXgDRnT9r/

**Comment by beltet** [comment]
If you have been on Linage recently(as me) check out this bug report:
https://github.com/ubports/ubports-installer/issues/1052

The solution is that you need to resize you partitions on the phone again. As you needed to do it so you could install Linage. How to revert the resize:
https://forum.xda-developers.com/showpost.php?p=79928889&postcount=190

Credits to:
https://github.com/chhager

**Comment by baruchiro** [comment]
Thanks, duplicate of https://github.com/ubports/ubports-installer/issues/1052, closing.
