### ISSUE TITLE
Uncaught ReferenceError: modals is not defined (MainRenderer:535)

### ISSUE THREAD

**Issue by TiNredmc** [ubports/ubports-installer#1165]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 10.0.19592.1001] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/49px6wXqmC/

**Comment by NeoTheThird** [comment]
I think this has been solved by the move to pre-compiled html
