### ISSUE TITLE
user-requested bug-report Es läuft nicht und lässt sich selbst nicht auf meinem onplus3 T installieren 

### ISSUE THREAD

**Issue by carrabelloy** [ubports/ubports-installer#1170]
*Automatically generated error report* 
UBports Installer Version: 0.4.16-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {channel:16.04/arm64/edge,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.720] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/FJdVdxNZMh/

**Comment by NeoTheThird** [comment]
Looks like it's just loosing connection. Make sure the cable fits snugly and don't touch the device while the installer is working it's magic, then it should be fine.
