### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery \"/home/outman/.cache/ubports/krillin/recovery/recovery-krillin.img\""},"stdout":"","stderr":"Sending 'recovery' (9578 KB)                       OKAY [  0.383s]\nWriting 'recovery'                                 FAILED (remote: '\npartition 'recovery' not support flash')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by a7210232** [ubports/ubports-installer#1175]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/vScHbNX3BX/

**Comment by Nobby888** [comment]
Hi there,
after a couple of years I wanted to give UbuntuTouch another try and got the same error.
Any solutions?

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
