### ISSUE TITLE
Error: systemimage: Error: Error: wiping cache failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell rm -rf /cache/*"},"stdout":"","stderr":"rm: can't remove '/cache/recovery/SWAP.img': Operation not permitted\nrm: can't remove '/cache/recovery': Directory not empty"}

### ISSUE THREAD

**Issue by userj** [ubports/ubports-installer#1178]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/HbCvfDQty4/

**Comment by NeoTheThird** [comment]
This should not be an issue any more due to some recent changes in the adb module.
