### ISSUE TITLE
Uncaught TypeError: Cannot read property 'device' of undefined (MainRenderer:406)

### ISSUE THREAD

**Issue by simonhasan** [ubports/ubports-installer#118]
Automatically generated error report %0AVersion: 0.1.11-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v8.2.1 %0A%0AError log: http://paste.ubuntu.com/p/5bJdtpb6Ns/ %0A

**Comment by NeoTheThird** [comment]
Should be fixed in the next release by #161.
