### ISSUE TITLE
Error: configure: Error: fetching system image channels failed: Error: connect ETIMEDOUT 104.26.6.138:443

### ISSUE THREAD

**Issue by hottabychozr** [ubports/ubports-installer#1181]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true,format:true}
Package: exe
Operating System: Microsoft Windows [Version 6.3.9600] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/SSHkWv5Ygv/

**Comment by NeoTheThird** [comment]
please check your network connection and try again
