### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by DaveMellor** [ubports/ubports-installer#1183]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/RZDvnN8m6J/ 

Hi, I'm running Ubuntu 18.04.4 LTS on an HP 1100- 30 GByte (with a cracked touch screen!).

I've attached my phone (VodaFone VFD 200) but nothing is happening! The system does nothing.

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
