### ISSUE TITLE
Error: oem unlock failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot oem unlock"},"stdout":"","stderr":"(bootloader) Start unlock flow\n\nFAILED (remote: '\nUnlock operation is not allowed\n')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by sergei2102** [ubports/ubports-installer#1184]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/Ck7hjdTxwv/

**Comment by NeoTheThird** [comment]
This error should be handled in [devices.js](https://github.com/ubports/ubports-installer/blob/master/src/devices.js#L321) by showing a new modal that references the unlock steps (#937) with a button to restart the install.
