### ISSUE TITLE
wrong instructions for bacon

### ISSUE THREAD

**Issue by ghost** [ubports/ubports-installer#1189]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18363.778] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/BmhfZXdhKW/ 

Instructions say you should hold Power + Volume Up.  You need to hold Power + Volume Down.

**Comment by NeoTheThird** [comment]
Just tried it. The current instructions work on my Oneplus One.
