### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\userName\AppData\Roaming\ubports\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by bianxbx** [ubports/ubports-installer#119]
ubports\pool/ubports-e5cf0885f061c961
wrong path in windows-10 home

**Comment by advocatux** [comment]
Yesterday helping a user to install from Windows 10 to FP2 we hit the same problem.
I don't have more info or logs to share.

**Comment by NeoTheThird** [comment]
Duplicate of #110. Thanks for reporting!
