### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by didin17** [ubports/ubports-installer#1194]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {channel:16.04/community/fredldotme/devel,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.10240] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/dPP63M54kn/

**Comment by NeoTheThird** [comment]
what seems to be the problem?
