### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Hernest-Glitch** [ubports/ubports-installer#1196]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/edge","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux   18.04   bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/rYss3R5BxD/

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed in the next release.
