### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by jjconstrgh** [ubports/ubports-installer#1199]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/wzC9mJkzsP/

**Comment by jjconstrgh** [comment]
Touch installation proceeds until after Nexus 5 has been unlocked. Clicking 'restart bootloader' reverts to 'start' repeatedly until the installer freezes at the 'yikes' screen. Selecting 'recovery on Nexus 5 leads to 'no command' and smaller icon. 

This phone was in boot loop when I received it. After replacing power switch, was able to be shut off, charged fully, but was unable to complete boot up. Holding power switch until starting with vibrate, results in Boot loop, with boot loader able to be brought up and stay up. Before power switch replacement, boot loader would disappear imediately.

**Comment by NeoTheThird** [comment]
The phone might have suffered some hardware damage or be hardbricked. The installer can fix most softbricks, but a hardbrick is a different story. You might be able to find instructions to fix it somewhere, but i'm afraid we can't help you with that here, sorry...
