### ISSUE TITLE
Install adb drivers on Windows automatically

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubports-installer#12]
If there are no adb drivers installed, the installer can not locate connected devices. Therefore, the program should handle driver installation.

**Comment by gsilvapt** [comment]
@NeoTheThird As this feature was added before, do you think we should close this issue?

**Comment by gsilvapt** [comment]
Ah, apologies, understood the commit wrong. You're correct.

**Comment by NeoTheThird** [comment]
No problem :) There's no official generic adb driver (like you have on linux) for windows, which is super annoying. Every device comes with it's own driver. There is, however, [the universal adb driver by clockworkmod](https://adb.clockworkmod.com/), which is what we currently recommend in the readme and the popup window in the beginning of the installation on windows.

**Comment by NeoTheThird** [comment]
Actually, [it looks like](https://github.com/koush/UniversalAdbDriver/blob/master/usb_driver/android_winusb.inf) the universal driver doesn't support all our devices. Back when I added the recommendation, I only tried with the Oneplus One, Nexus 5, and Nexus 4 and went on with my life, but ofc we also need to support the likes of Fairphone, BQ and Meizu...

Our options:

- Add support for our missing devices to the driver ( [doesn't look too difficult](https://github.com/koush/UniversalAdbDriver/commit/d4b8e56dbbe16746ef05fb1cc1f049e4bf0a648c) )
- Recommend (or install automagically) the correct adb driver for every device
- Say fuck it Windows sucks anyways (imho a truthful statement, but probably not a good idea)

**Comment by gsilvapt** [comment]
Hum, the Universal driver sound like an option to me. Not the prettiest but we do have been receiving many reports from Windows machines so I don't think we can ignore them at this stage. It's strange we do not have more alternatives though, considering Android has many guides built for Windows. 

    * Recommend (or install automagically) the correct adb driver for every device

How hard can this be? Can't we re-use some API from the Android Studio? They have some neat stuff working for Windows so my expectation is we can maybe find something.

My only concern with adding supporting for missing devices is complexity (meaning each port need to be added to the list which by itself is daunting - I have no clue what those numbers are and what do they mean, test, submit PR) and availability throughout time - After submitting the PR we have to wait for it to be approved.

**Comment by NeoTheThird** [comment]
I think we can close this. Most users seem to be able to handle the driver installation with the current popup.
