### ISSUE TITLE
Installer hangs and keeps asking to "connect device with an usb cable" on macOS Sierra

### ISSUE THREAD

**Issue by WolfpackN64** [ubports/ubports-installer#120]
I tried flashing my OnePlus One multiple times with the ubports installer on macOS Sierra.
It always asks me to "connect device with an usb cable" even when devmode on android was enabled.
The installer still detects my device as a OnePlus One, but the message remains.
When continuing with the install, the installer screen appears, but there is no progress bar and nothing further happens.

Also tried installing without android (since the installer wiped LineageOS) from TWRP and I have the same problem. 

The device is recognized by adb in the recovery and android, but as soon as it enters fastboot, it loses connection to adb (but the device is still recognized on my mac with the fastboot command).

**Comment by Dave-Melia** [comment]
Having the same issue with MacOS High Sierra.  UBTouch Installer v0.1.13 and I'm using the phone BQ Aquarius E4.5.  I get further using Ubuntu on VirtualBox, but still doesn't complete the flash.

It'll detect the phone, you click install, it asks for your system password, the phone reboots into fastboot mode, then the installer just hangs at 'Connect Device With An USB Cable'

**Comment by NeoTheThird** [comment]
Please try again with [the latest release](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by Xylobol** [comment]
I hit the same issue, I fixed it by running the app as admin. (use `sudo open /path/to/the.app` in the terminal)

**Comment by NeoTheThird** [comment]
@Xylobol thanks for reporting, we'll check that.
