### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by JeanVert** [ubports/ubports-installer#1205]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: dora
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/anpok/devel","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/qyH93scBss/

**Comment by NeoTheThird** [comment]
duplicate of #1071
