### ISSUE TITLE
ADB completely explodes on windows

### ISSUE THREAD

**Issue by tangtang-garden** [ubports/ubports-installer#1208]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [�汾 6.1.7601] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/dHJbj9Tx4C/

**Comment by NeoTheThird** [comment]
Should be fixed in [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta).
