### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Chakosai** [ubports/ubports-installer#1210]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/edge","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/sJtG3ymG96/

**Comment by NeoTheThird** [comment]
What seems to be the problem here?
