### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by tiboa83** [ubports/ubports-installer#1212]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux   18.04   bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/MF7JW4pG45/

**Comment by NeoTheThird** [comment]
what seems to be the problem here?
