### ISSUE TITLE
[deb] Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by ioanpintican** [ubports/ubports-installer#1217]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: deb
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/xCk6KkS7Tx/

**Comment by NeoTheThird** [comment]
There have been some changes to the systemimage step since this was opened, since we did not see this again, i'm going to close this for now. If it comes back, we need to investigate more.
