### ISSUE TITLE
Error: systemimage: Error: Download failed: Error: EACCES: permission denied, open '/home/br3n/.cache/ubports/commandfile/ubuntu_commandbacon7689'

### ISSUE THREAD

**Issue by doughertybmdos** [ubports/ubports-installer#1218]
*Automatically generated error report* 
UBports Installer Version: 0.4.16-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: AppImage
Operating System: Linux Mint 19.3 tricia x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/WgSY93QJmx/

**Comment by NeoTheThird** [comment]
Looks like you might have been running the installer with sudo, please don't do that. To fix your permissions, run `sudo rm -rf /home/br3n/.cache/ubports` and start the installer in user mode.
