### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by yejingyan2** [ubports/ubports-installer#1219]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [�汾 6.1.7601] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/XQKRJQdyV4/

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed in the next release.
