### ISSUE TITLE
there is a bug in ubuntu installer  thats is my device is redmi note 7 and my device is not showing user-requested bug-report

### ISSUE THREAD

**Issue by yogeshkumar980** [ubports/ubports-installer#1223]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 10.0.15063] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/ZsVkdw8wB5/

**Comment by NeoTheThird** [comment]
Sorry, there's no config for that device yet.
