### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by bastardogg0105** [ubports/ubports-installer#1225]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: generic_x86_64
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/DzbJPGNTBm/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
