### ISSUE TITLE
Con't connect server

### ISSUE THREAD

**Issue by sweeneycai** [ubports/ubports-installer#1229]
![image](https://user-images.githubusercontent.com/16558006/82513186-d4e3c600-9b44-11ea-96a5-558095b0e7d8.png)

Mac OS, cannot connect to the server, the internet connection is fine.

**Comment by jasonber** [comment]
I have the  same problem......

**Comment by outyang** [comment]
me too,but low version of UBports well to connect.but low version have a short device list can choose,oneplus 3&3t,not in the list,you can try version 0.3.2.here,version 0.4.0 or later have this problem too

**Comment by NeoTheThird** [comment]
If you're using a proxy (#1322), try disabling it.
