### ISSUE TITLE
Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: insufficient permissions for device: user in plugdev group

### ISSUE THREAD

**Issue by Thom-karum** [ubports/ubports-installer#1231]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: arale
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/Yc3KBbDr2N/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
