### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by SytzedeR** [ubports/ubports-installer#1233]
Hi Installation seems to hang on flashing firmware. Removing Nexus from USB port doesnot give an error. It seems contact between pc and nexus is lost when entering bootloader.

*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: deb
Operating System: Linux Mint 19.3 tricia x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/m4hvNmMVjz/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
