### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by bastardogg0105** [ubports/ubports-installer#1235]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/GF5mMFYPfd/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
