### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by txaumevw** [ubports/ubports-installer#124]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/mjPQ25KR4Z/

**Comment by NeoTheThird** [comment]
Thanks for reporting. What device are you trying to install?

**Comment by txaumevw** [comment]
It was with an E5, but with the previous version of the installer.

I downloaded the latest version and everything ok.

Thanks !


El dimecres, 14 de març de 2018, Jan Sprinz <notifications@github.com> va
escriure:
> Thanks for reporting. What device are you trying to install?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/8yPjdt6VnOrq52GM70mrqPHaqO35iYLeBaBaIhk6ZHIyjM3L0wLjx648xW-1ZwvSQt1JheaNUAqaBEYoQGzjGiO8iaoeofu3n628gHgjfHsKViTtoEMzXqfMvPk24ITaeIj3WLada5F7BxE60sDMLGbZEGv9Xw=s0-d-e1-ft#https://github.com/notifications/beacon/AYW1fOHBnJle2y7cWPsTS1bQP006RJz6ks5teO0jgaJpZM4SltOl.gif>

**Comment by NeoTheThird** [comment]
Ok, thanks for letting me know. I'll close this, it looks different than #122
