### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by jumatth** [ubports/ubports-installer#1241]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: FP2
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/qWnFkNM6dW/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
