### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by bwwe** [ubports/ubports-installer#1242]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: cooler
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux   20.04   focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/6WTqSs8sXx/

**Comment by NeoTheThird** [comment]
What seems to be the problem?
