### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by msab** [ubports/ubports-installer#1243]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: dmg
Operating System: macOS 10.15.519F96 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/XHfJC98mry/ 

I'm stuck, it's not find the device after reboot.

**Comment by msab** [comment]
I got it to work, just had to reboot the device into bootloader. I believe it is installed, but now it says installing update and i have yet to actually see it load.

**Comment by msab** [comment]
It's working.

**Comment by NeoTheThird** [comment]
good to hear :) sorry for the inconvenience
