### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by cliffcoggin** [ubports/ubports-installer#1244]
![Screenshot from 2020-06-04 15-02-01](https://user-images.githubusercontent.com/48879579/83776069-a6ef9d00-a67f-11ea-8895-fba2c051775d.png)
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Linux Mint 19.2 tina x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/6rGVxhCP84/

**Comment by NeoTheThird** [comment]
Can you try again? Not sure why it stopped.

**Comment by cliffcoggin** [comment]
Sorry Jan, I gave after many failed attempts and got rid of the phone two months ago.
Cliff.

**Comment by NeoTheThird** [comment]
Ok :/ sorry about the late reply
