### ISSUE TITLE
for rpi version of Debian 'Buster' if it is installed on the RPI the package has to be ARM 7?

### ISSUE THREAD

**Issue by OsirianOne** [ubports/ubports-installer#1250]

**Comment by OsirianOne** [comment]
I was putting my installer onto my rpi and the image onto a RokChip 'D2-927G'
Its quite old but I will be you tester for this model currently runs 4.1.1 KitKat of Android.

Let me know, thanks.  In the meantime I will try to create a Ubuntu boot-able thumb drive in 32bit to use on an old pc to run it just enough to complete this task.

**Comment by OsirianOne** [comment]
@NeoTheThird Thanks for the concise non existent answer.  It is MUCH appreciated....

**Comment by NeoTheThird** [comment]
I don't think you're on the right repository? What does this have to do with the UBports Installer?
