### ISSUE TITLE
Ubports trouble on Meizu pro 5

### ISSUE THREAD

**Issue by hugolzw** [ubports/ubports-installer#1254]
Hello: 
     I   want to install Ubuntu on Meizu pro 5 unlock. (ubports-installer.0.4.18-beta.exe &windows 10)
    but when connect the PRO5 with Fastboot mode  to PC,  ubports-installer display "connection to device lost", I have changed the other USB cable and port  but still failed.  please help, thank you!

![1](https://user-images.githubusercontent.com/66789390/84406179-c2d4df00-ac3b-11ea-8daf-a0055bc71ead.jpg)

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
