### ISSUE TITLE
Error: unhandled rejection at [object Promise]: TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by gamedebug** [ubports/ubports-installer#1257]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: dmg
Operating System: macOS 10.15.519F101 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/PCRSm6m5nZ/

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed in the next release.
