### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by gamedebug** [ubports/ubports-installer#1259]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: dmg
Operating System: macOS 10.15.519F101 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/SMcgGxJVGR/

**Comment by NeoTheThird** [comment]
What seems to be the problem?
