### ISSUE TITLE
user-requested bug-report - file 51-android.rules not created during installation

### ISSUE THREAD

**Issue by Barry-T** [ubports/ubports-installer#1260]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: deb
Operating System: Linux Mint  19.3  tricia x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/K33by9djs3/ 

Installation of the UBPorts Installer software fails to create the file
/etc/udev/rules.d/51-android.rules
causing the attempted installation of the Ubuntu Touch software onto a phone to stall at the 'Flashing firmware....' stage.

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
