### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery \"/home/lifeander/.cache/ubports/krillin/recovery/recovery-krillin.img\""},"stdout":"","stderr":"Sending 'recovery' (9578 KB)                       OKAY [  0.380s]\nWriting 'recovery'                                 FAILED (remote: '\npartition 'recovery' not support flash')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by ander2712** [ubports/ubports-installer#1263]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/NzDkxNbYWV/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
