### ISSUE TITLE
[dora] Your device has been unlocked and can't be trusted

### ISSUE THREAD

**Issue by kophamerla** [ubports/ubports-installer#1266]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: dora
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/anpok/devel","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux   20.04   focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/BfZ5SYpHwh/ 

As UBports begins to flash my Sony Xperia X Performance the phone boots up with the message "Your device has been unlocked and can't be trusted" it then boots up and the installer sits on "preparing..." until it loses connection

**Comment by FlorianPaintner** [comment]
I can confirm this behaviour.

**Comment by NeoTheThird** [comment]
Aparently this screen is shows up for all unlocked sony devices (https://forum.xda-developers.com/xperia-x/help/help-how-fix-device-unlocked-trusted-t3631881). The fact that the installer is sitting there and can't get a connection is a separate issue, probably a loose connection.
