### ISSUE TITLE
flashing xperia aosp

### ISSUE THREAD

**Issue by stef7773** [ubports/ubports-installer#1267]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Linux Mint 19.3 tricia x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/gb55Pj5442/ 

fastboot flash oem '/home/stefano/Desktop/SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_loire.img' 
target reported max download size of 536870912 bytes
sending 'oem' (220783 KB)...
OKAY [  6.948s]
writing 'oem'...
FAILED (remote: Command not allowed)
finished. total time: 6.950s

**Comment by NeoTheThird** [comment]
Not an installer issue. Where did you get that file you're flashing?
