### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubports-installer#1271]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/community/fredldotme/devel","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/7T8Hyr9Qyg/

**Comment by NeoTheThird** [comment]
what seems to be the problem?
