### ISSUE TITLE
[bacon] Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by arkhub** [ubports/ubports-installer#1272]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.19041.329] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/WkBQ8SXfwd/

**Comment by NeoTheThird** [comment]
duplicate of #1032
