### ISSUE TITLE
Error: configure: Error: fetching system image channels failed: Error: getaddrinfo ENOTFOUND system-image.ubports.com

### ISSUE THREAD

**Issue by stef7773** [ubports/ubports-installer#1273]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {}
Package: deb
Operating System: Linux Mint  20  ulyana x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/PFjjzTCDry/

**Comment by NeoTheThird** [comment]
Check your internet connection and try again. If you're using a proxy, try without it.
