### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Edugomes95** [ubports/ubports-installer#1276]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/bpfpzYy5w3/

**Comment by NeoTheThird** [comment]
What seems to be the problem here?
