### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery \"/home/carlos/.cache/ubports/krillin/recovery/recovery-krillin.img\""},"stdout":"","stderr":"Sending 'recovery' (9578 KB)                       OKAY [  1.526s]\nWriting 'recovery'                                 (bootloader) secure device\n(bootloader) unsigned image\nFAILED (remote: 'not allowed to update unsigned image on secure device')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by carloshasantos** [ubports/ubports-installer#1280]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: krillin
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/3TVrXH4qjw/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
