### ISSUE TITLE
Error: configure: Error: fetching system image channels failed: Error: getaddrinfo ENOTFOUND system-image.ubports.com

### ISSUE THREAD

**Issue by gamedebug** [ubports/ubports-installer#1283]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: arale
OS to install: Ubuntu Touch
Settings: {}
Package: dmg
Operating System: macOS 10.15.519F101 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/gn7qC9MQX5/

**Comment by NeoTheThird** [comment]
possibly #1322
