### ISSUE TITLE
Error: systemimage: Error: Can't find latest version: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Ethan492** [ubports/ubports-installer#1286]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":false}
Package: dmg
Operating System: macOS 10.15.519F101 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/fMHzmjQ2vC/

**Comment by NeoTheThird** [comment]
Most likely #1322
