### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by magicsystem** [ubports/ubports-installer#1289]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: mako
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 19.10 eoan x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/xPjyH96k4M/

**Comment by NeoTheThird** [comment]
what seems to be the problem here?
