### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:423)

### ISSUE THREAD

**Issue by BlueKenny** [ubports/ubports-installer#129]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Fedora 27
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/tsnXzsCRv7/ 

Same as #128

**Comment by BlueKenny** [comment]
On version 0.1.7 it works

**Comment by NeoTheThird** [comment]
Thanks for reporting, duplicate of #87
