### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by aska-GitHub** [ubports/ubports-installer#1294]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: FP2
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux  20.04  focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/VHp6T3zQWT/

**Comment by NeoTheThird** [comment]
What seems to be the problem here?

**Comment by aska-GitHub** [comment]
I installed another operating system. I will reproduce the error on my test device an report back next week.
