### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by floop2** [ubports/ubports-installer#1299]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: snap
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/pcJbVwKrPQ/

**Comment by floop2** [comment]
Background info: the phone was previously running [[ROM][UNOFFICIAL] LineageOS 17.1 for Nexus 5 (hammerhead)](https://forum.xda-developers.com/google-nexus-5/orig-development/rom-lineageos-17-1-nexus-5-hammerhead-t4039273). Restored latest factory image, enabled developer mode and usb debugging, started ubports-installer followed instructions taking the defaults.

**Comment by vdagguma** [comment]
try with "hh_clamor_repartition.zip" https://androidfilehost.com/?fid=4349826312261760768 by manually flashing this file and in the terminal hit "stock". the same issue has been fixed for me

**Comment by floop2** [comment]
Thanks for the tip.  I was attempting to install the Nexus 5 port on Halium 7.1 [https://forums.ubports.com/topic/3614/lge-nexus-5-hammerhead](url).  I repeated the process a few times and eventually succeeded. Once testing haliium install I will retry the installer.  I'll close this for now.
