### ISSUE TITLE
Package as a deb

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#13]
Appimages are not very well-known, so a deb package would be helpful.

**Comment by probonopd** [comment]
@NeoTheThird what is the problem with "not very well-known"?

**Comment by NeoTheThird** [comment]
@probonopd People need to google on how to even start and install it, that's not really userfriendly. At a time where debs are the go-to packaging format, it does make sense to provide them. I see your point, but i'm not saying we shouldn't provide appimages at all, but an additional deb and snap ( #14 ) package would make sense.

**Comment by probonopd** [comment]
Or provide clear instructions such as http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80 - educating users...

**Comment by NeoTheThird** [comment]
Sure, that's also a good idea. Could you send a PR to work that into the readme? The cli instructions are already there, but the gui way probably clicks more with non-technical users.

I would leave this issue open nonetheless, maybe at some point someone comes along who just gets off to packaging debs... ;)
