### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.515s]booting...FAILED (remote: dtb not found)finished. total time: 0.552s

### ISSUE THREAD

**Issue by uaqben** [ubports/ubports-installer#130]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/XHPSmD8dXp/

**Comment by NeoTheThird** [comment]
Could you try again with the latest version?
