### ISSUE TITLE
Bootloader unlocking for suzu: Back up TA partition, accept unlock code, flash OEM binaries for AOSP

### ISSUE THREAD

**Issue by vasyugan** [ubports/ubports-installer#1305]
At the moment, the installer is dysfunctional for suzu:

- It cannot back up the TA partition, which **must** be done before unlocking the boatloader, or you can never revert to factory state (happened to me)
- I doesn't hint at the need to obtain an unlock code from sony and provides no opportunity for entering it.
- It doesn't flash or hint at the need to  flash the OEM binaries for AOSP **BEFORE** proceeding with the installation, so that the Ubuntu recovery installed ends up in a boot loop, and thus, installation doesn't get completed

I think that therefore when the installer detects a locked bootloader it should stop and provide a link to the instructions, I have written them down [here](https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io/-/merge_requests/12/diffs#note_344967377) and I would think they should be on the device page, because that's obviously the place where you look first.

**Comment by Flohack74** [comment]
@fredldotme what do you think, what would be a good UX for that?

**Comment by NeoTheThird** [comment]
Here's how this looks in the wild #1071

**Comment by fredldotme** [comment]
Aargghh, if I just didn't miss the notifications. Alright, so the device unlock UX I'm not sure we can do easily without implementing a lot of things in the installer, so I would recommend hinting on the requirement in the device config, let that surface to the user in the installer UI and link them to a new forum thread I could set up specifically to guide the user.

**Comment by NeoTheThird** [comment]
I'm always a fan of automating as much as possible, if it's just a matter of passing the key for the oem-unlock, i'm happy to implement a UI for that. If you have ideas on how a note could look, could you send a PR to the config?

**Comment by fredldotme** [comment]
I noticed we already have a guide for TA backup, unlocking etc. on suzu's devices.ubuntu-touch.io page, we could show that one after showing the hint about the Android 8 requirement.

**Comment by NeoTheThird** [comment]
Manual downloads for flashing the oem partition are included in [0.5.6-beta](https://github.com/ubports/ubports-installer/releases/tag/0.5.6-beta). If someone wants to add it to the [config files](https://github.com/ubports/installer-configs/tree/master/v1) where it's needed, i'd be very appreciative. See the notes for developers on the release for usage documentation.

**Comment by NeoTheThird** [comment]
Opened #1479 to track those new-fangled unlock requirements. For the rest, i'll update the config accordingly.

**Comment by robiwan1** [comment]
the easiest way to add unlock code to the "fastboot oem unlock..." command is to ask in the UI and/or add an option in the config file, because there is already an option in the ubports-installer to view/edit the selected config file...

**Comment by NeoTheThird** [comment]
@robiwan1 we're going to have an ui, that's being tracked in #1479
