### ISSUE TITLE
Error: systemimage: Error: Error: stopped waiting

### ISSUE THREAD

**Issue by ravikumar0012** [ubports/ubports-installer#1307]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 10.0.20175.1000] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/f56TJvYYzJ/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
