### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:423)

### ISSUE THREAD

**Issue by uaqben** [ubports/ubports-installer#131]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/RpBgmvvs83/

**Comment by NeoTheThird** [comment]
Thanks for reporting, duplicate of #87
