### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by EODGuy107** [ubports/ubports-installer#1310]
I'm trying to delete the program and It's not coming up in the app window.  How do I remove the program because I don't like all of the permissions it has.  
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: AppImage
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/r6PC3hrF5V/

**Comment by NeoTheThird** [comment]
You're using it as an appimage (at least in this case), which is not actually installed but just a file on your computer. By the way, it does not have any special permissions, it's a normal userspace application. If you set udev rules, you might want to remove them (http://docs.ubports.com/en/latest/userguide/install.html#missing-udev-rules). You can delete that file and remove the menu entry like [this](https://stackoverflow.com/questions/43680226/how-can-i-uninstall-an-appimage). If you also installed a deb package, run `sudo apt purge ubports-installer`, if you also installed a snap run `snap remove ubports-installer`.
