### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mardy** [ubports/ubports-installer#1322]
Shortly after starting up 0.14.8beta version of the installer, I get this message:

![installer-error](https://user-images.githubusercontent.com/59287/91631383-d47b8680-e9e1-11ea-9e0e-4fa5e5088aa1.png)

The logs say:

```
$ ./ubports-installer.0.4.18-beta.AppImage -D -V
info: Welcome to the UBports Installer version 0.4.18-beta!
debug: killing all running adb servers
command: adb: {"args":["-P",5037,"kill-server"],"error":null,"stdout":"","stderr":""}
debug: starting adb server on port 5037
command: adb: {"args":["-P",5037,"start-server"],"error":null,"stdout":"","stderr":"* daemon not running; starting now at tcp:5037\n* daemon started successfully\n"}
command: adb: {"args":["-P",5037,"shell","echo","."],"error":null,"stdout":".\r\n","stderr":""}
command: adb: {"args":["-P",5037,"shell","getprop","ro.product.device"],"error":null,"stdout":"turbo\r\n","stderr":""}
error: getDeviceSelects error: Error: timeout of 7500ms exceeded
error: getDeviceName error: Error: timeout of 7500ms exceeded
```

Version 0.14.4beta works fine (and of course, my internet works fine too).

**Comment by 0312birdzhang** [comment]
Do you have set `http_proxy` or `https_proxy` environment?

**Comment by mardy** [comment]
> Do you have set `http_proxy` or `https_proxy` environment?

Yes indeed, I run privoxy on the localhost, and I have the proxy variables set to `http://localhost:8119/`. Thanks for the hint, I'll try without the proxy!

**Comment by NeoTheThird** [comment]
cf https://github.com/axios/axios/issues/2072
