### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by Georgeorgeorge2020** [ubports/ubports-installer#1323]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: frieza
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:false,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18363.1016] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/SZ3RQNsJsN/

**Comment by Georgeorgeorge2020** [comment]
Hello,
I have an Aquaris M10 FSD with original Ubuntu Touch 15.04 that I was trying to upgrade using UBPorts Install 0.4.18-Beta.
The Installer lost connection during the install and my Aquaris no longer boots...  frozen with Ubuntu image...
The error message was about Unable to Push data.   Unfortunately, I don't have the "Installing Ubuntu update" at bottom.
I can Reboot to Bootloader, Wipe Cache partition and Power down only...
Can anyone please help me recover?
Thank you in advance.
George

**Comment by Georgeorgeorge2020** [comment]
Hello,
I have an Aquaris M10 FSD with original Ubuntu Touch 15.04 that I was trying to upgrade using UBPorts Install 0.4.18-Beta.
The Installer lost connection during the install and my Aquaris no longer boots... frozen with Ubuntu image...
The error message was about Unable to Push data. Unfortunately, I don't have screen shot.
Message is"Installing Ubuntu update" at bottom.
I can Reboot to Bootloader, Wipe Cache partition and Power down only...
Can anyone please help me recover?
Thank you in advance.
George

**Comment by NeoTheThird** [comment]
Hey, could you just try running the installer again? It should just work, as long as the connection isn't lost again.

**Comment by Georgeorgeorge2020** [comment]
Thank you!

It did finally work!

I had to choose erase drive option.

Thank you!

George

PS When will Snapd be ported?

Sent from my iPhone

On Sep 23, 2020, at 5:48 AM, Jan Sprinz <notifications@github.com> wrote:

﻿

Hey, could you just try running the installer again? It should just work, as long as the connection isn't lost again.

**Comment by NeoTheThird** [comment]
Good to hear, hope you'll enjoy it!

> PS When will Snapd be ported?

Can't give you a definitive ETA on that yet, but hopefully in one of the next releases. We cleared out some blockers with the new mir we got in OTA-12, and further sanitized our stack in the just released OTA-13. Now we'll tackle some systemd issues, then snaps will be within reach.
