### ISSUE TITLE
Error: oem unlock failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/275/app/resources/app.asar.unpacked/platform-tools/linux/fastboot oem unlock"},"stdout":"","stderr":"(bootloader) Check 'Allow OEM Unlock' in Developer Options.\nFAILED (remote: '')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by bertico32** [ubports/ubports-installer#1324]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: yggdrasil
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/android9/edge","wipe":true,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/92PgVtVkwg/

**Comment by NeoTheThird** [comment]
This error should be handled in [devices.js](https://github.com/ubports/ubports-installer/blob/master/src/devices.js#L321) by showing a new modal that references the unlock steps (#937) with a button to restart the install.
