### ISSUE TITLE
connection on windows

### ISSUE THREAD

**Issue by DekstopMRL678** [ubports/ubports-installer#1326]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {channel:16.04/arm64/hybris/stable,wipe:false,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.17763.1397] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/NcDzjFgFwz/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
