### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: stdout: adb: error: failed to copy '/root/.cache/ubports/pool/ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz' to '/cache/recovery/ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz': remote Bad file number/root/.cache/ubports/pool/ubports-aa9dad30db962019f4dfcc58162fbb86660bc3680767af7fc20506bbefc6675f.tar.xz: 0 files pushed, 0 skipped. 6.9 MB/s (176073736 bytes in 24.481s)

### ISSUE THREAD

**Issue by t3kg33k** [ubports/ubports-installer#1331]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: flo
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: AppImage
Operating System: Fedora 32 Thirty Two x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/r8JMY6PTM5/

**Comment by NeoTheThird** [comment]
After some googling, i think this is a connectivity issue, not an issue with the push itself. If we handle this as a connection to device lost error, we might be okay.
