### ISSUE TITLE
[Feature request] Add proxy support

### ISSUE THREAD

**Issue by 0312birdzhang** [ubports/ubports-installer#1332]
ubports.com or some ubuntu domains are “blocked” in some countries, and it's very slow for them to download images.

Another problem is ubports-installer not support `http_proxy` and `https_proxy`, https://github.com/ubports/ubports-installer/issues/1322

It would be great helpful and useful with this feature, thank you.

**Comment by NeoTheThird** [comment]
Thanks for the hint, closing this in favor of #1322
