### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by hiurequeiroz** [ubports/ubports-installer#1336]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/fcmpGDwVYh/

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed in the next release.
