### ISSUE TITLE
README does not inform users of distro requirement for setup-dev.sh

### ISSUE THREAD

**Issue by Bujiraso** [ubports/ubports-installer#1345]
Hello,

I'm on Arch and I tried the "setup-dev.sh" which I can see only runs `apt` and doesn't handle other package managers.
The README should be updated to help newer users understand that it is not currently handling distributions other than Ubuntu, openSUSE, and other `apt` based distributions.

I don't see any notes about plans to support other distros. Is that desirable?
I am more than happy to open another issue to tackle it and add some glue for Arch as I enjoy BASH and can help out.

**Comment by NeoTheThird** [comment]
> I don't see any notes about plans to support other distros. Is that desirable?
> I am more than happy to open another issue to tackle it and add some glue for Arch as I enjoy BASH and can help out.

That'd be great, thanks! As long as it a) doesn't break the existing functionality and b) doesn't completely butcher readability of the script, i'll gladly approve a PR for that :)
