### ISSUE TITLE
timeouts in channel-detection not handled: Error: configure: Error: fetching system image channels failed: Error: Request failed with status code 522

### ISSUE THREAD

**Issue by rantpalas** [ubports/ubports-installer#1346]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: oneplus3
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/rc","wipe":true,"bootstrap":true}
Package: snap
Operating System: Raspbian 4.1 undefined x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/JhXS8Pr4m8/

**Comment by NeoTheThird** [comment]
Should display the connection lost screen...

**Comment by NeoTheThird** [comment]
Fixed in 0.8.1-beta
