### ISSUE TITLE
Switch snap publisher from mariogrip to UBports

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-installer#1349]
GizmoChicken has brought my attention to the [UBports Installer snap](https://snapcraft.io/ubports-installer) still being published by 'mariogrip' on the Snap Store. To enable future possibilities for the project, such as having our own publisher page (see [KDE's publisher page on snapcraft.io](https://snapcraft.io/publisher/kde)), we should move the snap into a UBports namespace.

See also, GizmoChicken's discussion of the topic on the Snapcraft forums: https://forum.snapcraft.io/t/publisher-pages-how-many-exist-how-to-find-them-and-could-they-be-auto-created/19363

---
EDIT @NeoTheThird:

- [x] Move to an intermediary account called UBports
- [ ] Obtain an ogranization account as soon as the snappy people have it sorted out

**Comment by NeoTheThird** [comment]
Might be a good idea, especially if we have more snaps in the future. For now, maybe we can move it to a dummy ubuntu one account called UBports? @mariogrip you're the snaps owner, do you have access to any settings like that? I can only change the other stuff.

**Comment by NeoTheThird** [comment]
for posterity https://forum.snapcraft.io/t/request-ownership-of-ubports/20150

**Comment by NeoTheThird** [comment]
Transferred! Now to wait for snapcraft to catch up with publishers :)
