### ISSUE TITLE
Error: adb:format: Error: failed to format cache: Error: failed to parse fstab

### ISSUE THREAD

**Issue by albetron404** [ubports/ubports-installer#1351]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:false,bootstrap:true,format:false}
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.1082] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/CTt22bw53T/

**Comment by NeoTheThird** [comment]
You're trying to install the Nexus 5 image on a Oneplus 2? Very bad idea!
```
warn: The device OnePlus2 is not supported!
info: device detected: OnePlus2
```

Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
