### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by gastontancredi** [ubports/ubports-installer#1355]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/wC878DM75P/

**Comment by NeoTheThird** [comment]
Duplicate of #983
