### ISSUE TITLE
Installer needs to support multiple flavours for a device

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-installer#1356]
For the transition period between legacy and Halium ports for our core device we need a possibility to let the user choose what to install. Also needed are cleanup procedures in this case, to remove the system files properly when jumping between the flavours, to not occupy unnecessary space.

**Comment by NeoTheThird** [comment]
Depending on how big the difference is, we can either use the install properties (i.e. a checkbox) or configure it as a different operating system. Let's hear more when we know the requirements.

**Comment by tyg3rpro** [comment]
I would just configure as a separate OS as a short term fix for devices that have 5.1 and 7.1, I would set the label to be something along the lines of "Ubuntu Touch [Legacy]" and "Ubuntu Touch [Updated]" or we could set Updated to "WIP" or "Experimental" then later if it makes more sense to do a check box or something it could be modified accordingly

**Comment by NeoTheThird** [comment]
No further work required here on the installer's side, as far as i can see
