### ISSUE TITLE
No connection on windows

### ISSUE THREAD

**Issue by huanghester** [ubports/ubports-installer#1358]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [�汾 10.0.18363.1082] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/m4w6JqBGCR/

**Comment by NeoTheThird** [comment]
Hmm, so the log shows a couple failed connection attempts, then the adb error "Unable to connect because the target computer actively refused." in chinese on kill-server, but a server is started and no device is detected. What happens if you select a device and follow the instructions after that?
