### ISSUE TITLE
No connection to suzu

### ISSUE THREAD

**Issue by retro486** [ubports/ubports-installer#1360]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: suzu
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":false,"bootstrap":true}
Package: snap
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/mDxKY8KhDy/ 

Xperia X F5121 (single SIM) Ubuntu recovery doesn't appear in adb devices. When I boot TWRP, it does so it's not my USB cable or udev rules.

**Comment by NeoTheThird** [comment]
Your log tells me the last instruction was to reboot to bootloader, so the device will only respond to fastboot commands, not adb. Could you try again?

**Comment by retro486** [comment]
I can’t get to the bug report button unless I clear the dialog box that says “connection lost please try again” so when I hit that try again button it goes back into listening for fast boot. Does that reset the log? Is there a way to get it manually without clearing the try again dialog? I tested the adb issue manually after the phone reboots into UB recovery.

**Comment by NeoTheThird** [comment]
you can either look at the [log file](https://github.com/ubports/ubports-installer#logs) or start the installer with the `-V` flag vor verbose terminal output

**Comment by retro486** [comment]
So I tried again from scratch (reflashed latest 8.0 update from Sony) and now it's saying the bootloader is locked... (It's not).

Log: https://paste.ubuntu.com//p/xDcP4Cb62G/

I ran ubports-installer with -v this time; here's that output: https://pastebin.com/9ymciT0E

**Comment by NeoTheThird** [comment]
That sounds like #1327. Will make a quick fix for the next release so you can try again.

**Comment by NeoTheThird** [comment]
Alright, here's a new [prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.4.20-beta) you can try!

**Comment by retro486** [comment]
info: Welcome to the UBports Installer version 0.4.20-beta!
info: This is not the latest version of the UBports Installer! Please update: https://devices.ubuntu-touch.io/installer/?package=AppImage
info: Downloaded file 1 of 1
error: Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/tmp/.mount_ubportnJmXIn/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/root/.cache/ubports/suzu/firmware/halium-unlocked-recovery_suzu.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}
stack trace: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/tmp/.mount_ubportnJmXIn/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/root/.cache/ubports/suzu/firmware/halium-unlocked-recovery_suzu.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}
    at /tmp/.mount_ubportnJmXIn/resources/app.asar/node_modules/promise-android-tools/src/fastboot.js:72:15
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

Tool couldn't detect the device in debug mode either. I had to manually select it, then it rebooted to fastboot and this error happened. Didn't even get to flashing recovery. Report a but button does nothing now apparently... I used the AppImage version.

**Comment by NeoTheThird** [comment]
Alright, at least it's properly throwing the error now, and not interpreting it in unintended ways. Progress, but we're not there yet.

If i may ask, what OS is the phone running? The config will have prompted you to install Android 8, because we can't do some of the necessary unlocking on suzu (see #1305).

**Comment by retro486** [comment]
I'm running the last stock 8.0.0 image but with an unlocked bootloader and none of the DRM.

**Comment by retro486** [comment]
So my particular issue appears to be a problem with the bundled fastboot. When I try to manually do what the installer is failing at:

```
/tmp/.mount_ubporttDAnn9/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot /home/russ/.cache/ubports/suzu/firmware/halium-unlocked-recovery_suzu.img 
fastboot: error: Couldn't parse partition size '0x'.
```
But when I use the fastboot available in the Ubuntu repository:
```
/usr/bin/fastboot flash boot /home/russ/.cache/ubports/suzu/firmware/halium-unlocked-recovery_suzu.img 
target reported max download size of 536870912 bytes
sending 'boot' (17148 KB)...
OKAY [  0.547s]
writing 'boot'...
OKAY [  0.107s]
finished. total time: 0.655s
```

**Comment by retro486** [comment]
I got it to flash by:
1. Replacing the bundled fastboot with my system fastboot
1. Flashing the AOSP N OEM firmware
1. Wiping cache, dalvik, data, and system with TRWP
1. Manually boot to bootloader
1. Restart the ubports-installer process, and manually select Xperia X

So, yes it appears besides the fastboot issue, the steps in #1305 are also needed.

**Comment by NeoTheThird** [comment]
The bundled fastboot issue has been addressed in [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta) of the installer. This one is capable of flashing raw images, so the `Couldn't parse partition size` error can be circumvented. Any chance you could try again with that one and let me know how it goes? Thank you!

**Comment by retro486** [comment]
Suzu is correctly recognized now but it still needed the OEM image and full wipe (dalvik, cache, system, data) before the UB recovery would stabilize. Before I did these steps it continually bootlooped.

**Comment by NeoTheThird** [comment]
Okay. Let's not mix these issues and keep tracking the oem wiping and such in #1305. Thank you for your detailed reports, i'll follow up with the porters of this device and see what we can do to resolve the remaining issues properly.
