### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by franmauriz** [ubports/ubports-installer#1363]
*Automatically generated error report* 
UBports Installer Version: 0.4.19-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: AppImage
Operating System: Fedora 32 Thirty Two x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/ZTc4sNvSD8/

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
