### ISSUE TITLE
OnePlus One: "Couldn't parse partition size '0x'."

### ISSUE THREAD

**Issue by dragonmaus** [ubports/ubports-installer#1371]
*Automatically generated error report* 
UBports Installer Version: 0.4.19-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {channel:ubports-touch/16.04/stable,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.19041.508] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/g23k7kHHyb/ 

I did a wipe+reformat using TWRP to see if it fixed the issue (it didn't).

This device has been retired for a while, but it was able to boot into the previously-installed LineageOS before I attempted to use the UBPorts installer, so I'm reasonably sure that there are no hardware issues.

I also tried this from a Linux machine, but that resulted in the exact same error message.

I don't *think* this is the same thing as #1368, because the word "lock" is not found anywhere in the text of the error message.

**Comment by NeoTheThird** [comment]
Probably similar to #1032. I'll have to do some digging what happens with other OSs, specifically newer Android versions.

**Comment by NeoTheThird** [comment]
duplicate
