### ISSUE TITLE
error: getDeviceName error: Error: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by kreasnik** [ubports/ubports-installer#1372]
*Automatically generated error report* 
UBports Installer Version: 0.4.19-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Ubuntu 14.04 trusty x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/vW6hqVwHSN/

**Comment by NeoTheThird** [comment]
Hi, do you by any chance have a proxy enabled? If so, try disabling it.
