### ISSUE TITLE
[kagura] {"error":{"killed":false,"code":1,"signal":null,"cmd":"$PKG/fastboot flash boot '$CACHE/kagura/firmware/halium-unlocked-recovery_kagura.img'"},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#1380]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: kagura
OS to install: Ubuntu Touch
Settings: {"channel":"16.04/arm64/hybris/stable","wipe":true,"bootstrap":true}
Package: dmg
Operating System: macOS 10.15.619G2021 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/WcH5rTfsCK/

_Originally posted by @ressanoid in https://github.com/ubports/ubports-installer/issues/1368#issuecomment-699498604_

**Comment by NeoTheThird** [comment]
Should be fixed with with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta) of the installer? This one is capable of flashing raw images, so the `Couldn't parse partition size` error can be circumvented.

**Comment by ressanoid** [comment]
UBports Installer: `0.5.2-beta` 
Device: `kagura` 
OS to install: Ubuntu Touch 
Settings: undefined 
Package: `exe` 
Operating System: Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 
NodeJS version: `v12.0.0` 
Error log: https://paste.ubuntu.com//p/XkDS2Pc9VQ/ 
``` 
user-requested bug-report 
``` 
Tried with a different laptop fresh and the installer stuck

**Comment by NeoTheThird** [comment]
@ressanoid Huh, that's interesting. Could you just try again for me, just for good luck? I don't think the device was actually in bootloader mode there, was it? If it gets stuck again, could you try and see if you can get it recognized by running `fastboot.exe devices` in a command prompt? you can get fastboot for windows from [here](https://dl.google.com/android/repository/platform-tools-latest-windows.zip), if you don't have it. Thank you!

**Comment by ressanoid** [comment]
![image](https://user-images.githubusercontent.com/15714267/95011714-6018b080-063b-11eb-9fe7-936969c0afdd.png)
fastboot isn't detecting the device the indicator is blue but...  I'll check with the mac once I get back from work

**Comment by NeoTheThird** [comment]
Since you're on windows, do you have the required [drivers](https://docs.ubports.com/en/latest/userguide/install.html#windows-adb-drivers) installed?

**Comment by ressanoid** [comment]
this device always freaks out and restarts on MAC OS

**Comment by ressanoid** [comment]
> Since you're on windows, do you have the required [drivers](https://docs.ubports.com/en/latest/userguide/install.html#windows-adb-drivers) installed?

yes the drivers are installed

**Comment by tecywiz121** [comment]
I'm getting the same `fastboot: error: Couldn't parse partition size '0x'.` error with a kugo F5321 with installer versions 0.4.20 and 0.5.2.

**Comment by NeoTheThird** [comment]
@tecywiz121 try again with 0.5.2-beta, please

**Comment by tecywiz121** [comment]
@NeoTheThird Sorry I wasn't clear, I had used 0.4.20 and 0.5.2-BETA specifically.

**Comment by NeoTheThird** [comment]
@tecywiz121 yes, i got that ^^ i updated the config (the installer fetches the config from an api on the internet) after your comment, so please try again with 0.5.2-beta. it should work now. i did not know before kugo was affected as well, so i had not updated the config before.

**Comment by tecywiz121** [comment]
@NeoTheThird Ah! Alright, I've retried it, and the recovery gets flashed successfully! Unfortunately the recovery reboots before the transfer finished. Worth a new bug?

**Comment by NeoTheThird** [comment]
@tecywiz121 yes please, you can use the bug reporting button in the installer, at the end of a run, that way a log file is attached automatically

**Comment by NeoTheThird** [comment]
Is there something left to be done here? Btw, the installer can instruct the user to manually download binaries and handle the flashing for them starting in version 0.5.6-beta. Someone already made a PR [here](https://github.com/ubports/installer-configs/pull/40) to flash the OEM binary for suzu, could someone who has a device for testing send me a PR to enable this for kagura as well? Thanks :)
