### ISSUE TITLE
Error: adb:format: Error: failed to format system: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell cat /etc/recovery.fstab"},"stdout":"","stderr":"cat: /etc/recovery.fstab: No such file or directory"}

### ISSUE THREAD

**Issue by mrbwilliams** [ubports/ubports-installer#1381]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true,"format":true}
Package: deb
Operating System: Ubuntu 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/9wc3JtPVhP/

**Comment by NeoTheThird** [comment]
Your device introduced itself as `generic_x86_arm`. Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.

**Comment by mrbwilliams** [comment]
It's a nexus 5 one of the main supported phones

**Comment by NeoTheThird** [comment]
Then you must have another adb device connected to your PC, or an emulator running. The Nexus 5 would introduce itself as `hammerhead`. If you want to be sure, close the installer and run `adb devices` in your terminal, you should see what devices are connected. Kill any running android emulators.

**Comment by mrbwilliams** [comment]
Thanks my mistake had android studio open must have caused the issue.

All working now

**Comment by NeoTheThird** [comment]
Great, thanks for letting me know!
