### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/dima/.cache/ubports/hammerhead/firmware/boot-hammerhead.img\""},"stdout":"","stderr":"Sending 'boot' (12302 KB)                          OKAY [  0.603s]\nWriting 'boot'                                     FAILED (remote: 'not supported in locked device')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by dimant649** [ubports/ubports-installer#1386]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: deb
Operating System: Linux Mint 20 ulyana x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/bG3ht6ZYG4/

**Comment by NeoTheThird** [comment]
I don't recall seeing this error with the Nexus 5. Are you sure you selected the correct device?

**Comment by dimant649** [comment]
Good evening. The problem was an unlocked download. I bought a phone
in an online store and did not expect that someone had not used it
before me. After unlocking the bootloader, the installation proceeded
normally.


сб, 3 окт. 2020 г., 23:18 Jan Sprinz <notifications@github.com>:

**Comment by NeoTheThird** [comment]
Great, thank you for letting me know! Then we don't have to change anything, as the installer already asks users to unlock in the beginning. Thanks again :)
