### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/fastboot flash recovery '/Users/jyles.coad-ward/Library/Caches/ubports/vegetahd/recovery/recovery-vegetahd.img'"},"stdout":"","stderr":"Sending 'recovery' (10046 KB)                      OKAY [  0.506s]\nWriting 'recovery'                                 FAILED (remote: 'not allowed in locked state')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by jylescoad-ward** [ubports/ubports-installer#1389]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: vegetahd
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: dmg
Operating System: macOS 10.11.615G31 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/ntqjTD3bHB/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
