### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for tasfir: downloading 'boot.img'...OKAY [  0.443s]booting...FAILED (remote: unknown command)finished. total time: 0.445s

### ISSUE THREAD

**Issue by suman0359** [ubports/ubports-installer#139]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/wk8qBt7fSB/

**Comment by NeoTheThird** [comment]
What device is this? Log says Nexus 5, that should definitely understand the command.

**Comment by gsilvapt** [comment]
The many times it references device not found, it makes me wonder how we can confirm this is a bug actually related with command not found or device not found :thinking:

**Comment by NeoTheThird** [comment]
Probably #221.
