### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/mehrwale/.cache/ubports/bacon/firmware/boot-bacon.img\""},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by rovinapinto** [ubports/ubports-installer#1400]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/hK7Xr6GZCC/

**Comment by rovinapinto** [comment]
Any idea how to fix this?

**Comment by rovinapinto** [comment]
Just saw this already open.

**Comment by NeoTheThird** [comment]
A fix is in progress. Please stand by.

**Comment by NeoTheThird** [comment]
Ah, yeah, keep an eye on #1032. A fix is in progress.
