### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by rindusemata** [ubports/ubports-installer#1403]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: SBM206SH
OS to install: Not yet set
Settings: {}
Package: exe
Operating System: Microsoft Windows [Version 6.1.7601] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/dZzDVGnKfx/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
