### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash recovery \"/home/krlos_official/.cache/ubports/cooler/recovery/recovery-cooler.img\""},"stdout":"","stderr":"Sending 'recovery' (11436 KB)                      OKAY [  0.432s]\nWriting 'recovery'                                 FAILED (remote: 'the command you input is restricted on locked hw')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by krlosofficial** [ubports/ubports-installer#1404]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: cooler
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu undefined undefined x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/xHkKmMBF3q/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
