### ISSUE TITLE
[fixed] Error: fastboot:format: Error: formatting failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot format cache"},"stdout":"","stderr":"Couldn't parse erase-block-size '0x'.\nCouldn't parse logical-block-size '0x'.\nmke2fs 1.44.1 (24-Mar-2018)\n/tmp/TemporaryFile-IMDyHB: Function de bibliothèque ext2 non implémentée lors de l'initialisation du superbloc\n/usr/lib/android-sdk/platform-tools/mke2fs failed with status 1\nmke2fs failed: 1\nerror: Cannot generate image for cache"}

### ISSUE THREAD

**Issue by oliverfont** [ubports/ubports-installer#1410]
Hi, I need help to install Ubuntu Touch with ubport, thanks !

*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: hammerhead
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true,"format":false}
Package: deb
Operating System: Ubuntu 18.04 bionic x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/3RcVWr9vhS/

**Comment by oliverfont** [comment]
That's fixed with the last ubport 0.5 
cheers

**Comment by NeoTheThird** [comment]
Grand, thanks
