### ISSUE TITLE
[yggdrasil] error: Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"$PKG\\win\\fastboot flash boot \"$CACHE\\yggdrasil\\firmware\\halium-unlocked-recovery_yggdrasil.img\""},"stdout":"","stderr":"Sending 'boot' (16754 KB)                          OKAY [  0.565s]\r\nWriting 'boot'                                     FAILED (remote: 'not allowed in locked state')\r\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by reis818** [ubports/ubports-installer#1413]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: yggdrasil
OS to install: Ubuntu Touch
Settings: {channel:16.04/arm64/android9/edge,wipe:true,bootstrap:true}
Package: exe
Operating System: Microsoft Windows [Version 10.0.19041.508] ia32 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/gCnxsNh75p/

**Comment by NeoTheThird** [comment]
Thanks for reporting, should be fixed in the next release: https://github.com/ubports/ubports-installer/releases/tag/0.5.5-beta
