### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/fastboot flash boot '/Users/ankitku/Library/Caches/ubports/bacon/firmware/boot-bacon.img'"},"stdout":"","stderr":"fastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by ankitku** [ubports/ubports-installer#1416]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: dmg
Operating System: macOS 10.15.619G2021 x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/p9XGDYV6j2/

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta) of the installer? This one is capable of flashing raw images, so the `Couldn't parse partition size` error can be circumvented. Please let me know how it goes. Thank you!

**Comment by NeoTheThird** [comment]
Closing for now, as we have reports of it working (#1418). Feel free to re-open if you need any help. Thanks!
