### ISSUE TITLE
Error: systemimage: Error: Download failed: undefined

### ISSUE THREAD

**Issue by linuxitomio** [ubports/ubports-installer#1417]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu Linux 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/9Kg8D8y87W/

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta) of the installer? We switched out the download library, so this might resolve your issue.
