### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/deloco/.cache/ubports/bacon/firmware/boot-bacon.img\""},"stdout":"","stderr":"< waiting for any device >\nfastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by linuxitomio** [ubports/ubports-installer#1418]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":false,"bootstrap":true}
Package: deb
Operating System: Ubuntu 20.04 focal x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/qd6Nwgv5HD/

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta) of the installer? This one is capable of flashing raw images, so the `Couldn't parse partition size` error can be circumvented. Please let me know how it goes. Thank you!

**Comment by linuxitomio** [comment]
that was fast. i try it now. thanks

**Comment by linuxitomio** [comment]
download without a problem. thanks for your work guys. u are awesome

**Comment by NeoTheThird** [comment]
Thanks for the feedback, much appreciated!
