### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.432s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.435s

### ISSUE THREAD

**Issue by denkmaschine** [ubports/ubports-installer#142]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/NRYRKNRzXW/

**Comment by NeoTheThird** [comment]
Ok, so you're installing on a Bq Aquaris M10 FHD, is that correct? I'm assuming the device is running the Canonical version of Ubuntu Touch?

**Comment by denkmaschine** [comment]
Hallo Jan, wie ich sehe, studierst Du in Bayern, daher schreibe ich mal auf deutsch weiter.

Inzwischen hat alles geklappt. Letztendlich hat geholfen, dass ich TWRP als Recovery Image installiert und einen Fullwipe auf dem bisherigen Android Tablet durchgeführt habe. Erst dann war die Installation über Euer Tool problemlos möglich. Nun läuft Euer Ubuntu einwandfrei. Einzig die Meldung der Wischgeste von rechts stört den Betrieb. Somit sicherlich ein Bug. Hierzu habe ich den Dektop-Modus eingeschaltet, sodass das ausbleibt.

Euch viel Erfolg und viel Freude an dem Projekt. Ich werde jetzt daran gehen zu testen, denn Datensparsamkeit ist mein neues Gebot.

Viele Grüße
Dirk

**Comment by WLBI** [comment]
Keine Ahnung was er damit sagen möchte:
"Letztendlich hat geholfen, dass ich TWRP als Recovery Image installiert und einen Fullwipe auf dem bisherigen Android Tablet durchgeführt habe. "
Er hat die Glaskugel genommen und auf einmal ging es...

**Comment by NeoTheThird** [comment]
Verstehe ich auch nicht so ganz, ist aber auch nicht so wichtig. Der Installer kann ohnehin nicht den bootloader auf dem M10 entsperren, dafür [braucht man immer noch diesen guide](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Ich denke mal, dass er bei der TWRP-Installation dann die Entsperrung vorgenommen hat.

**Comment by WLBI** [comment]
Mizt dem Guide hat es funktioniert, dass ich Ubuntu Touch von Canonical drauf installiere.
https://storage.googleapis.com/otas/2015/Tablets/Freezer%20FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip
Dann über den UBports Installer die Version 15.04/stable 
installiert und das Tablet startete.
Anschließend habe ich unter "Aktualisierungen" bei Kanäle auf Entwicklung geschalten. Dann wurde "Version 61" in der Größe 463,2 MB heruntergeladen.
-> Bis dahin wusste ich mal noch nicht, ob 15.04 Entwicklung, oder 16.04 Entwicklung, denn 15.04 wird ja eigentlich nicht mehr entwickelt.
Dann "Neustarten & Installieren" ausgewählt.
Überraschung... öder doch nicht?  Gerät starte neu und "15.04 r61" war installiert.
Hätte aber gerne 16.04 
Also nochmal von vorne... 

UBports Installier gestartet und Tablet manuell ausgewählt + 16.04 
Tablet startet automatisch in den Fastboot Mode und diese Meldung auf dem PC: 
https://img3.picload.org/image/daclaori/image.png
nichts weiter geschieht. Esc-Taste gedrückt, damit die Meldung verschwindet.
Da steht dann "**Connect your device with an USB cable**" 
Das ist es ja schon, sonst hätte es nicht von alleine rebootet in den Fastboot mode.
USB-Kabel ausgesteckt, neu eingesteckt, aber keine Veränderung mehr... 
Gerät wieder 15 Sek. drücken auf die Power Taste ausgeschaltet und "Power+Volume up" -> Bootloader wieder eingeschaltet.
nun konnte ich 16.04 über den UBports-Installer installieren. Das ging zuvor als noch Android drauf war nicht.
Ubuntu 16.04 r56 ist nun drauf..:-) *freu*
