### ISSUE TITLE
[dora] Installation coming from Android results in boot-loop

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#1420]
Ok: wiped entire device using twrp. flashed halium-unlocked-recovery_dora.img using fastboot.

Tried to install via 0.5.2-beta. Device got i the reboot loop when using fastboot. Unticked using fastboot -> device rebooted to recocery. Installer sent files (at least that was reported), installer reported success. When device (dora) rebooted ubports-logo was shown (as always when booting after system update). But device does not boot properly (stucks with sony-logo).

_Originally posted by @FlorianPaintner in https://github.com/ubports/ubports-installer/issues/1377#issuecomment-703210613_

**Comment by FlorianPaintner** [comment]
Finally worked out. Do you still need the logfiles? How do I get them?

**Comment by NeoTheThird** [comment]
No, i think i'm good. Your descriptions from #1377 should be enough to resolve this issue eventually. Just needs some more research. Thanks!
