### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/fastboot flash boot \"/home/krishnan/.cache/ubports/bacon/firmware/boot-bacon.img\""},"stdout":"","stderr":"< waiting for any device >\nfastboot: error: Couldn't parse partition size '0x'."}

### ISSUE THREAD

**Issue by garthnix** [ubports/ubports-installer#1421]
*Automatically generated error report* 
UBports Installer Version: 0.4.20-beta 
Device: bacon
OS to install: Ubuntu Touch
Settings: {"channel":"ubports-touch/16.04/stable","wipe":true,"bootstrap":true}
Package: deb
Operating System: Ubuntu undefined undefined x64 
NodeJS version: v12.0.0 

Error log: https://paste.ubuntu.com//p/k2fDsyN9vp/

**Comment by NeoTheThird** [comment]
Hey, sorry about that. This issue has been fixed in [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.5.2-beta). Please re-open if you need more support. Thanks
