### ISSUE TITLE
[kugo] Ubports recovery reboots before installer can finish

### ISSUE THREAD

**Issue by tecywiz121** [ubports/ubports-installer#1428]
UBports Installer: `0.5.2-beta` 
Device: `kugo` 
OS to install: Ubuntu Touch 
Settings: undefined 
Package: `deb` 
Operating System: Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-48-generic x64 
NodeJS version: `v12.0.0` 
Error log: https://paste.ubuntu.com//p/CB3VT9FWZM/ 
``` 
user-requested bug-report 
``` 

I start the device in fastboot, manually select the kugo, and start the install. The installer flashes the boot and the recovery, and starts to download the system image (I assume.) In the meantime, the recovery reboots itself several times.

I was able to get some dmesg logs from the recovery: https://paste.ubuntu.com/p/93px4H8pY5/

**Comment by tecywiz121** [comment]
What would be the most productive way for me to help debug this? I can attempt to get more logs, or build/flash a particular commit if necessary.

**Comment by NeoTheThird** [comment]
Are you still experiencing this? Maybe you could try again with the current [prerelease](https://github.com/ubports/ubports-installer/releases).

**Comment by tecywiz121** [comment]
Tried it with 0.5.6-BETA and it worked!
