### ISSUE TITLE
Nexus 5 update not working

### ISSUE THREAD

**Issue by nepeee** [ubports/ubports-installer#1438]
UBports Installer: `0.5.2-beta` 
Device: `hammerhead` 
OS to install: Ubuntu Touch 
Settings: undefined 
Package: `exe` 
Operating System: Microsoft Windows 10 Pro 10.0.18362 win32 10.0.18362 x64 18362 0.0 
NodeJS version: `v12.0.0` 
Error log: https://paste.ubuntu.com// 
``` 
user-requested bug-report 
``` 

After the install process is completed with the success message the device reboots to the UBports Recovery. No log no error messages, nothing to debug the problem :(

**Comment by NeoTheThird** [comment]
Hey, sorry about this, that's #1427. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.5.3-beta) of the installer? That should have that issue fixed. Thanks!

**Comment by nepeee** [comment]
I already done the install over a Ubuntu live pendrive, it worked flawlessly.
