### ISSUE TITLE
Adb failed to reboot!, reboot failed: -1 : 

### ISSUE THREAD

**Issue by wagafo** [ubports/ubports-installer#144]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/fzfzZ2H4B7/

**Comment by NeoTheThird** [comment]
Thanks for reporting, sorry that you are experiencing issues with the installer. Duplicate of #43.
