### ISSUE TITLE
Improve instructions for installing to devices already running UT

### ISSUE THREAD

**Issue by svenha** [ubports/ubports-installer#1441]
**UBports Installer `0.5.3-beta` (snap)**
Environment: `Ubuntu 20 focal linux 5.8.10-050810-generic x64` with Node.js `v12.16.3`
Device: (device not yet detected) OnePlus 3T
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f816e9504d6b6000750b09e
Log: https://paste.ubuntu.com//p/VTTk98HF6t/

This is only a suggestion for the start screen. I tried to install a current version on a device running some older UT version without usable update channels. It took some time and help from the forum to find out that the UT device must be in fastboot mode. Something like "If your device already runs some version of UT, please boot your device to fastboot mode before starting UBports installer."

**Comment by NeoTheThird** [comment]
Hi, i'm not sure what you mean, the installer will [still prompt you to reboot to bootloader](https://github.com/ubports/installer-configs/blob/d4c69204f99c1260fc8e82161350a5e0b6cad4fd/v1/oneplus3.json#L67). Can you point me to that forum thread?

**Comment by svenha** [comment]
Hi. At the end of https://forums.ubports.com/topic/3253/oneplus-3-3t . Yes, I saw this prompt. But I didn't know what was meant (my fault, maybe confused because the prompt also shows a continue button, what should I do first?). Will this work with the device already connected?

**Comment by NeoTheThird** [comment]
Huh, interesting, you're the second person mentioning confusion about that button this this week (#1436). In my mind it is so obvious that you should reboot to bootloader and *then* click the button to continue, so i never questioned it. Clicking continue before completing the action feels *extremely* counter-intuitive to me, but maybe i'm wrong.

> Will this work with the device already connected?

Normally it should but depending on where you come from, on some devices, you'll have to hold it longer. I don't have an Oneplus 3, so maybe you can do some testing and give me a proposal on how to change this text?

I'd appreciate information about how to reboot to recovery and bootloader:

- when the phone is running the operating system
- when the phone is in recovery mode
- when the phone is in bootloader mode
- when the phone is turned off but charging
- when the phone is turned off and disconnected

That would be very helpful.

**Comment by svenha** [comment]
The text change in commit https://github.com/ubports/installer-configs/commit/d4c69204f99c1260fc8e82161350a5e0b6cad4fd is very good. I guess it would have helped me back then :-)

**Comment by svenha** [comment]
Currently, I know not much about my OP3:

> when the phone is running the operating system 

(I assume OS is UT.)
Press the Power button, select "Power off". Use the normal key combination (as already correctly shown in the installer; good!)

> when the phone is turned off but charging

Cannot reach this state, because the OP3 will turn on.

> when the phone is turned off and disconnected

Normal key combination.

**Comment by NeoTheThird** [comment]
Alright, thank you
