### ISSUE TITLE
Error: adb:format: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy

### ISSUE THREAD

**Issue by gianlucamazza** [ubports/ubports-installer#1442]
UBports Installer: `0.5.2-beta` 
Device: `flo` 
OS to install: Ubuntu Touch 
Settings: undefined 
Package: `AppImage` 
Operating System: Fedora 32 Workstation Edition linux 5.8.13-200.fc32.x86_64 x64 
NodeJS version: `v12.0.0` 
Error log: https://paste.ubuntu.com// 
``` 
Error: adb:format: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/cache on /cache failed: Device or resource busy 
```

**Comment by NeoTheThird** [comment]
Sorry about that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
