### ISSUE TITLE
snap fails to start on Fedora "cgroup v2 is not fully supported yet"

### ISSUE THREAD

**Issue by kelmes** [ubports/ubports-installer#1448]
Full output is below:
```
snap run ubports-installer
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement

undefined:0


illegal access
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by NeoTheThird** [comment]
A little googling turned up that cgroups v2 should be supported in snapd 2.46 (see https://github.com/snapcore/snapd/pull/7825, https://forum.snapcraft.io/t/fedora-32-cgroup-v2-is-not-fully-supported-yet/19295/4). Maybe [there instructions](https://snapcraft.io/install/ubports-installer/fedora) will help you update your snap installation.

**Comment by kelmes** [comment]
```
[kieran@localhost ~]$ snap --version
snap    2.45.3.1-1.fc33
snapd   2.45.3.1-1.fc33
series  16
fedora  33
kernel  5.8.14-300.fc33.x86_64

[kieran@localhost ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree
```

**Comment by NeoTheThird** [comment]
Alright, so upgrading snap / snapd to 2.46 or above should help you

**Comment by chriztheanvill** [comment]
I have the same issue:
cris@crispc:/media/cris/Panzer/Cris/Documents$ snap --version
snap    2.47.1-1.fc33
snapd   2.47.1-1.fc33
series  16
fedora  33
kernel  5.9.12-200.fc33.x86_64

cris@crispc:/media/cris/Panzer/Cris/Documents$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 33 (Thirty Three)
Release:        33
Codename:       ThirtyThree
