### ISSUE TITLE
ubports installer Internet connection lost

### ISSUE THREAD

**Issue by WittXie** [ubports/ubports-installer#1450]
Internet connection lost The installer failed to connect to the UBports servers. Are you connected to the internet? If you're using a proxy, you might have to configure it by setting the https_prOxy environment variable.
????

**Comment by WittXie** [comment]
my network is work. and all applications can google but you!!

**Comment by NeoTheThird** [comment]
That's odd. Could you try again and send me a [log](https://github.com/ubports/ubports-installer#logs)? If you are behind a proxy of some sort, check the env var by running `echo $http_proxy` and `echo $https_proxy` in a terminal.

**Comment by chnxc** [comment]
i met the same question,my computer net work is ok,and also i've tried vpn,other computer whit windows10,but nothing has changed.it always told me 'Internet connection lost The installer failed to connect to the UBports servers. Are you connected to the internet? If you're using a proxy, you might have to configure it by setting the https_prOxy environment variable.'
so how can i solve it?

**Comment by NeoTheThird** [comment]
@chnxc you, too, can send me a [log](https://github.com/ubports/ubports-installer#logs) and check the output of `echo $http_proxy` and `echo $https_proxy` in a terminal. You don't need to send me that output, just see if there's something there.

**Comment by chnxc** [comment]
sorry i don't know how to make a log.but when i type echo $http_proxy,ut told me that,$http_proxy.you can see the image


发自我的iPhone

**Comment by NeoTheThird** [comment]
@chnxc i posted a link that explains how to get the log. Here it is again: https://github.com/ubports/ubports-installer#logs

**Comment by chnxc** [comment]
@NeoTheThird here is the log:
{"level":"info","message":"Welcome to the UBports Installer version 0.5.4-beta!"}
{"level":"debug","message":"killing all running adb servers"}
{"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)","config":{"url":"https://api.github.com/repos/ubports/ubports-installer/releases/latest","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"json":true},"code":"ECONNRESET"}
{"level":"info","message":"This is not the latest version of the UBports Installer! Please update: https://devices.ubuntu-touch.io/installer/?package=exe"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOTFOUND raw.githubusercontent.com"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOTFOUND raw.githubusercontent.com"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOTFOUND raw.githubusercontent.com"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOTFOUND raw.githubusercontent.com"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"info","message":"Good bye!"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}

**Comment by chnxc** [comment]
@NeoTheThird here is another computer log,it also has some question:

{"level":"info","message":"Welcome to the UBports Installer version 0.5.4-beta!"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: 由于目标计算机积极拒绝，无法连接。 (10061)\\r\\n\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: 由于目标计算机积极拒绝，无法连接。 (10061)\\r\\n\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: 由于目标计算机积极拒绝，无法连接。 (10061)\\r\\n\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\".\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"getprop\",\"ro.product.device\"],\"error\":null,\"stdout\":\"turbo\\r\\r\\n\",\"stderr\":\"\"}"}
{"level":"error","message":"getDeviceName error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"shell\",\"echo\",\".\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"WINDOW RELOADED"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"error","message":"getDeviceSelects error: Error: getaddrinfo ENOENT raw.githubusercontent.com"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"start-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"* daemon not running; starting now at tcp:5037\\r\\n* daemon started successfully\\r\\n\"}"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"info","message":"Good bye!"}
{"level":"debug","message":"no device detected: Error: stopped waiting"}
{"level":"command","message":"adb: {\"args\":[\"-P\",5037,\"kill-server\"],\"error\":null,\"stdout\":\"\",\"stderr\":\"\"}"}

**Comment by chnxc** [comment]
@NeoTheThird it's ok now. the way to solve it is:add"199.232.68.133 raw.githubusercontent.com"to computer hosts

**Comment by NeoTheThird** [comment]
@chnxc good to hear you were able to make it work.

@WittXie do you need more assistance?

**Comment by Arechok** [comment]
How to add 199.232.68.133 raw.githubusercontent.com???

**Comment by Logic922** [comment]
I added the host, but it didn’t help. I still can’t connect to the server.
