### ISSUE TITLE
Installer on Windows 10 cannot handle white space in user directory

### ISSUE THREAD

**Issue by Zarelark** [ubports/ubports-installer#1451]
**UBports Installer `0.5.4-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19041 win32 10.0.19041 x64 19041 0.0` with Node.js `v12.16.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f8c8cd1fd51f200075a4435
Log: https://paste.ubuntu.com//p/DvKKc4KQb9/

My user director is "C:/Users/First_Name Last_Name" where First and Last name are my actual name. I didn't get a choice in this; microsoft automatically sets up windows this way with the name attached to the Microsoft account.

However, this causes an error when I try to run the installer. It says failed to start adb server (even though I can start it just fine from commandpromp). Farther along in the error message it says "C:/Users/First_Name" is not a recognized command. There you have it.

Can we get the installer to support white space in the Path?

**Comment by NeoTheThird** [comment]
Thanks for reporting! The hint about microsoft accounts seems correct, i was previously unable to reproduce this with a normal account (#847) and abandoned an attempt at a fix (#1076). Now a fix is under review (#1454) and should be included in the next release. You can try it by downloading these [artifacts](https://github.com/ubports/ubports-installer/suites/1375914983/artifacts/22582964) and running the included exe file.
