### ISSUE TITLE
weird kagura problems

### ISSUE THREAD

**Issue by ressanoid** [ubports/ubports-installer#1458]
**UBports Installer `0.5.5-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H2` with Node.js `v12.16.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f93f8339702a600079d920c
Log: https://paste.ubuntu.com//

ran the installer normally and it gave a message

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected

**Comment by ressanoid** [comment]
Hi there
I flashed the android again on the device and will try to do that on the mac again I'll get back to you ASAP

**Comment by ressanoid** [comment]
**UBports Installer `0.5.5-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H2` with Node.js `v12.16.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f941fef9702a600079d923c
Log: https://paste.ubuntu.com//p/RFHp5SKY7M/


**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/node_modules/android-tools-bin/dist/darwin/x86/fastboot\" flash:raw boot '/Users/nasseralsaeed/Library/Caches/ubports/kagura/firmware/halium-unlocked-recovery_kagura.img'"},"stdout":"","stderr":"< waiting for any device >\nSending 'boot' (18128 KB)                          ERROR: usb_write failed with status e00002ed\nFAILED (Write to device failed in SendBuffer() (Operation timed out))\nfastboot: error: Command failed"}
```

**Comment by ressanoid** [comment]
**UBports Installer `0.5.5-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H2` with Node.js `v12.16.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f94209f9702a600079d9240
Log: https://paste.ubuntu.com//

**Comment by NeoTheThird** [comment]
Weird things are happening here.

Your first run errors out with `usb_write failed with status e00002ed` and `Write to device failed in SendBuffer() (Operation timed out)` when flashing fastboot. A rare error i can not attribute to any actual problem, it might be an unreliable usb connection.

Your second run fails to reboot because `adb` can't see the device. Did the installer not complain about that? You should have seen a connection lost screen there.

```
command: adb: {"args":["-P",5037,"reboot","bootloader"],"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/node_modules/android-tools-bin/dist/darwin/x86/adb\" -P 5037 reboot bootloader"},"stdout":"","stderr":"error: no devices/emulators found\n"}
```
