### ISSUE TITLE
Meizu Pro 5 - not flashing?

### ISSUE THREAD

**Issue by paul-hammant** [ubports/ubports-installer#146]
How long should the UbPorts installer sit on this page?

![meizu pro5](https://user-images.githubusercontent.com/82182/37566351-40efdd86-2a8e-11e8-8dec-b6ce861957bd.png)

Its been there an hour without budging, and it looks like it is hanging on something but there is nothing in ordinary log output.

I freshly cloned this repo, and ran the NPM build steps.  The Installer also auto recognized the Pro-5 as soon as it was plugged in.

The phone was purchased with Ubuntu on it, and had had OTA updates previously - but only up to the end of Canonical's patronage (OTA-15).  Yes, it is in developer mode, and otherwise boots and operates normally.

Log files stuff (from one attempt after the screenshot was made):

```
$ tail /Users/paul/Library/Caches/ubports/ubports-installer.log 
{"level":"debug","message":"adb shell: cat /etc/system-image/channel.ini","timestamp":"2018-03-18T13:38:11.479Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T13:38:11.592Z"}
{"level":"debug","message":"adb shell: echo 1","timestamp":"2018-03-18T13:38:19.045Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T13:38:19.187Z"}
{"level":"debug","message":"reboot to bootloader","timestamp":"2018-03-18T13:38:19.188Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T13:38:20.408Z"}
{"level":"debug","message":"reboot to bootloader [DONE] err:null","timestamp":"2018-03-18T13:38:20.408Z"}
{"level":"debug","message":"checking password","timestamp":"2018-03-18T13:38:23.008Z"}
{"level":"debug","message":"correct password","timestamp":"2018-03-18T13:38:23.108Z"}
{"level":"debug","message":"fastboot: wait for device","timestamp":"2018-03-18T13:38:23.109Z"}
```

**Comment by NeoTheThird** [comment]
Please check if fastboot is installed and able to recognize the device (`sudo fastboot devices`). If it doesn't work, start the installer again.

**Comment by paul-hammant** [comment]
I couldn't find a homebrew installer, so did it manually. 

Trying again - it's exactly the same - log output is identical (but different times). The installer tool has the same screenshot (no progress bar). The Pro 5 has the same splash screen.

**Comment by NeoTheThird** [comment]
Could you send the full log?

**Comment by paul-hammant** [comment]
```
{"level":"debug","message":"Using native platform tools!","timestamp":"2018-03-18T17:29:14.331Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T17:29:14.475Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T17:29:14.570Z"}
{"level":"debug","message":"adb shell: echo 1","timestamp":"2018-03-18T17:29:14.683Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T17:29:18.023Z"}
{"level":"debug","message":"adb shell: getprop ro.product.device","timestamp":"2018-03-18T17:29:18.024Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T17:29:18.173Z"}
{"level":"debug","message":"getprop: turbo","timestamp":"2018-03-18T17:29:18.174Z"}
{"level":"debug","message":"adb shell: cat /etc/system-image/channel.ini","timestamp":"2018-03-18T17:29:18.990Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T17:29:19.173Z"}
{"level":"debug","message":"adb shell: echo 1","timestamp":"2018-03-18T17:29:22.172Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T17:29:22.361Z"}
{"level":"debug","message":"reboot to bootloader","timestamp":"2018-03-18T17:29:22.362Z"}
{"level":"debug","message":"","timestamp":"2018-03-18T17:29:23.644Z"}
{"level":"debug","message":"reboot to bootloader [DONE] err:null","timestamp":"2018-03-18T17:29:23.645Z"}
{"level":"debug","message":"checking password","timestamp":"2018-03-18T17:29:25.680Z"}
{"level":"debug","message":"correct password","timestamp":"2018-03-18T17:29:26.155Z"}
{"level":"debug","message":"fastboot: wait for device","timestamp":"2018-03-18T17:29:26.156Z"}
```

**Comment by aitzol76** [comment]
I had the same problem. Works if you disconnect the device, start it in fastboot(vol(-) + power) and then connect it again.

**Comment by paul-hammant** [comment]
I'll try that and report back - thanks

**Comment by paul-hammant** [comment]
That works:

1. phone boot with vol- AND power
2. ubports-installer & manual choice of PRO 5 phone
3. a few mins of installer action
4. phone reboot with vol+ AND power
6. 60 mins (slow wifi)
7. phone upgraded.

Note this screen only came up AFTER #1.  And I didn't have to heed its instructions:
![2018-03-19_1151](https://user-images.githubusercontent.com/82182/37611262-3eb15280-2b78-11e8-881b-0de2d1b23d23.png)

**Comment by paul-hammant** [comment]
So I'm upgraded now - looks to be fine.  There are two different PRO 5 variants though (I note from other forums). One is a chinese market one, and one is the international one. I bought mine from China so I don't know which it is

**Comment by NeoTheThird** [comment]
Ok, glad to hear it worked. Looks like the problem is the same as #43
