### ISSUE TITLE
File picker does not work under snap confinement

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#1464]
This is speculation, but i'm expecting some problems with the file picker for manual downloads (#1456) under snap confinement. Needs investigation, we might have to add the `home` plug or something similar. *Apparmor: Don't move at all and break things!*

**Comment by retro486** [comment]
I may have confirmed this with #1467 ...

**Comment by NeoTheThird** [comment]
yep, thanks!
