### ISSUE TITLE
FAILED (remote: ‘not supported in locked device’)\nfastboot: error: Command failed”}

### ISSUE THREAD

**Issue by DiggerNix** [ubports/ubports-installer#1468]
**UBports Installer `0.5.5-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-52-generic x64` with Node.js `v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f95ce399702a600079d9536
Log: https://paste.ubuntu.com//p/TqRFqBbbwc/

plug up nexus 5 hammerhead to ubports while dev mode and debugging enabled. ubports completes 2/2 steps then pops up error message

Error: fastboot:flash Error: flashing failed: Error: {“error”:{“killed”:false, “code”:1, “signal”:null, “cmd”:”\”/snapnubports-installer/302/app/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fast\” flash boot \”/home/user/snap/ubports-installer/302/.cache/ubports/hammerhead/firmware/boot-hammerhead.img\””}, “stdout”:””,”stderr”.”< waiting for any device >\nSending ‘boot’ (12302 kb)

OKAY [ 0.665s]\nWriting ‘boot’

FAILED (remote: ‘not supported in locked device’)\nfastboot: error: Command failed”}

**Comment by DiggerNix** [comment]
Bootloader was not unlocked. Unlocked bootloader using chainfire's program. No additional issues. Closing.

**Comment by NeoTheThird** [comment]
needs to be handled
