### ISSUE TITLE
handle oem-lock error FAILED (remote: '\tDevice not unlocked cannot flash or erase')

### ISSUE THREAD

**Issue by emko86** [ubports/ubports-installer#1473]
I did factory reset through recovery mode to wipe to cache/data and tried with few different cables but still I am getting the same error when I try to install Ubuntu Touch on Oneplus One phone.

:{"killed":false,"code":1, "singnal":null, "cmd":"\"snap/ubports-installer/302/app.asar.unpacked/note_modules/android-modules-tools-bin/dist/linux/x86/fastboot\" flash:raw boot \"/home/john/snap/ubports-installer/302/ .cache/ubports-bacon/firmware/boot-bacon.img\"" }, "stdout":"", "stderr":"<waiting for any device >\nSending 'boot' (11866)

**UBports Installer `0.5.5-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-52-generic x64` with Node.js `v12.16.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f9705cb9702a600079d9736
Log: https://paste.ubuntu.com//p/9MqvZ4XNnZ/

**Comment by NeoTheThird** [comment]
Alright, sorry about that. Will include a fix in the next release. In the mean time, you can run `sudo fastboot oem unlock` (with the device in fastboot/bootloader mode) and use the installer again.

**Comment by emko86** [comment]
I did what you said but still something is not working. I tried to try using UBports but ot can’t find the device but any ways I see a new look of the menu.
