### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal [...] serdata on /data failed: Invalid argument\r\n'true' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���"}

### ISSUE THREAD

**Issue by Lup1ng** [ubports/ubports-installer#1474]
**UBports Installer `0.5.5-beta` (exe)**
Environment: `Microsoft Windows 10 רҵ�� 10.0.19041 win32 10.0.19041 x64 19041 0.0` with Node.js `v12.16.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f971f849702a600079d9776
Log: https://paste.ubuntu.com//p/MnH36QPBWB/

**Error:**
```
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\win\\AppData\\Local\\Temp\\1jEGR4gMaC9f8ld9LBTy2FuZjXT\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe\" -P 5037 shell mount -a || true"},"stdout":"","stderr":"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument\r\n'true' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���"}
```

**Comment by NeoTheThird** [comment]
Sorry about that. A fix will be included in 0.5.7-beta

**Comment by Lup1ng** [comment]
Same happened in 0.6.0beta

**Comment by NeoTheThird** [comment]
Weird, could you send me a [log](https://github.com/ubports/ubports-installer#logs)? sorry about that...

**Comment by NeoTheThird** [comment]
Interesting, thanks. Will keep digging.

**Comment by julianpoemp** [comment]
same issue here:
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\User\\AppData\\Local\\Temp\\1jZdYrkqnbzAZoGRTA5fqH0JXK9\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe\" -P 5037 shell 'mount -a || true'"},"stdout":"","stderr":"/sbin/sh: no closing quote\r\nDer Befehl \"true'\" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden."}
Translation of the last part: _The command is either wrong typed or could not be found_

*More information*:
- Installer 0.6.0 beta and 0.5.6
- Windows 10 64bit
- ADB Driver
- Device: Nexus 6P with fresh installed stock rom angler 7.1.2

**Comment by XtofHeylands** [comment]
Same happened to me in version 0.7.0-beta

UBports Installer 0.7.0-beta (exe)
Environment: Microsoft Windows 10 Home 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3
Device: angler nexus 6P
Target OS: Ubuntu Touch
Settings: undefined
OPEN-CUTS run: https://ubports.open-cuts.org/run/5faaaa469702a600079dbcda
Log: https://paste.ubuntu.com/p/cfcNvQNMVx/

**Comment by NeoTheThird** [comment]
sigh, thanks

**Comment by NeoTheThird** [comment]
Alright, i don't think the `true` issue actually still happens with 0.7.0-beta. All reports are 0.6.0-beta or earlier.

@XtofHeylands your issue is actually different, we'll track that separately. This is your error:

```
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"The system cannot find the path specified."}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"The system cannot find the path specified."}
    at C:\Users\xtofh\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\promise-android-tools\src\fastboot.js:157:15
    at C:\Users\xtofh\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
