### ISSUE TITLE
Make unlocking more flexible

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#1479]
Some newer devices don't use `fastboot oem unlock`, so we need a new config option that's fed into the oem lock error handling. Fun! Other devices require a key such as this: `fastboot.exe -i 0x0fce oem unlock 0xKEY`.

**Comment by robiwan1** [comment]
...what about adding unlock code to the "fastboot oem unlock..." command????

**Comment by NeoTheThird** [comment]
that's exactly what's the idea here.

**Comment by robiwan1** [comment]
fantastic, i think the fastest and easiest way to implement is, to add a var in config json like this:
"unlock_code": [""],
If unlock_code is empty (default in all config files) - just run "fastboot oem unlock" as before. If there is an unlock_code, run "fastboot oem unlock 0x<unlock_code>"

**Comment by robiwan1** [comment]
How can i set my unlock code? I did not find any config or input file to pass the code to the fastboot command. I used version 0.8.0...

**Comment by NeoTheThird** [comment]
@robiwan1 Yes, this is not implemented in the installer yet. Follow the guide in the link that the installer shows you.

**Comment by robiwan1** [comment]
Sorry for making multible comments at the same matter - i was not sure which post would be the best for asking. I saw this "New unlock features" #53 and thought, this means that it is implemented yet. Specially because i saw code to "accept oem unlock code".

**Comment by NeoTheThird** [comment]
@robiwan1 sorry for the confusion. the pull request you commented on implemented prerequisites to fix this in our library that handles fastboot. The new library calls will now need to be implemented in the installer. This requires changes to the config specification, as well as changes to the installer's UI and backend code. Working as fast as we can, but it'll be at least another week before it'll be considered stable.

**Comment by robiwan1** [comment]
@NeoTheThird Thanks for the explanation. I Don't want you being in such a hurry! ;-) I unlocked now from cli with the fastbook-command from appimage (/tmp/.mount....) and the installer finished successfully. BUT now my Sony xpedia x perf. hangs in a boot loop. I have tried system images stable, devel and edge without success...

**Comment by robiwan1** [comment]
i now stuck exacly in the closed issue #1503...
