### ISSUE TITLE
Active slot not set as opposed to config value

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubports-installer#1484]
**UBports Installer `0.6.0-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-48-generic x64 NodeJS v12.16.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5f9c64349702a600079da0f7
Log: *N/A*

Issue:
Active slot silently fails to set as the slot value stays at 'b', even though 'a' is configured in the configuration.

How to reproduce:
Flash Google Pixel 3a (sargo)

**Comment by NeoTheThird** [comment]
but... why? `command: fastboot: {"args":["--set-active=a"],"error":null,"stdout":"","stderr":"Setting current slot to 'a'                        OKAY [  0.064s]\nFinished. Total time: 0.079s\n"}`

**Comment by fredldotme** [comment]
I guess we can only test it in the field, don't know what's going on here. Might try with a simple 1-step JSON only doing a slot select and see how it behaves.

**Comment by fredldotme** [comment]
The device seems to automatically go to recovery mode when on the a slot, there's no chance booting the device even though it installed the rootfs + device tarball successfully. Will investigate further.

**Comment by fredldotme** [comment]
I've set the active slot to 'b' now, in case this turns out not to be a device-specific issue I'll investigate further but that's the best I could do now. I have a theory but to verify that it needs a second device.

**Comment by NeoTheThird** [comment]
I have to admit that i don't have too much experience with A/B devices. All i can tell you is that the step executes the command exactly as you described it. To be clear, you wanted this to be run as a standalone command, correct? Something like `fastboot --set-active=a`? Not as a flag appended to the flashing steps or any other command? Let me know the results of your investigation.

**Comment by NeoTheThird** [comment]
When you are testing, be sure to use a recent version of fastboot. The installer uses fastboot `30.0.4-6686687`.

**Comment by fredldotme** [comment]
I'll rephrase my discovery and add a possible way forward:

It executed the command properly, but It seems my sargo cannot be booted if installed on `a`, no matter how many times I manually run `fastboot --set-active=a`. It will boot straight into recovery instead of the normal rootfs environment.

Something is fishy, but this seems to be a bootloader problem. Booting from `b` always works instead, and it seemed to have worked for that one guy who installed it on his bonito too.

I hope it's not a matter of luck, ie it's a randomly picking a letter depending on the device, when reinstalling the factory image, that would not be under our control.
Else we would have to remove it from the config file altogether and rely on the installation not to fail in between.

**Comment by fredldotme** [comment]
Since the value is set as expected, and it seems to be a bootloader issue, I propose this issue to be closed and sargo support to be merged in the near future.

**Comment by NeoTheThird** [comment]
Awesome, thanks!
