### ISSUE TITLE
E:You don't have enough free space in /var/cache/apt/archives/

### ISSUE THREAD

**Issue by ErikStark86** [ubports/ubports-installer#1486]
I am trying to turn ubuntu touch into a fully functional portable machine but for this purpose I have to install additional software in terminal. Very soon after installing only few commands in terminal I run out of space in /var/cache/apt. Obviously I have to extend /var/cache/apt into a different folder by mounting. My question to you is which is the best folder for that purpose?

**Comment by NeoTheThird** [comment]
This tracker is only for issues directly related to the installer. Please consult community platforms like [the forums](https://forums.ubports.com) for discussion.
