### ISSUE TITLE
UBPORT windows installer Error 

### ISSUE THREAD

**Issue by octaviusdaivnci** [ubports/ubports-installer#149]
Hi Guys, 

I get this error while installing the ubport installer for windows 
i used the following file 
"ubports-installer.0.1.12-beta.exe" 

could someone please guide me how to fix this isssue. 

![image](https://user-images.githubusercontent.com/8819939/37611575-b236ecec-2bc8-11e8-8abc-934985f5b8f2.png)

**Comment by NeoTheThird** [comment]
Argh, sorry about that, broken in #132. #151 should fix this, can you try with [this build](https://ci.appveyor.com/api/buildjobs/tfqyl641a22me037/artifacts/dist%2Fubports-installer%200.1.12-beta.exe) and report if it worked for you?

**Comment by octaviusdaivnci** [comment]
Hi NeoTheThird,

Thanks for your file it launched and took some time to load and after few minutes it came to this screen i hope it will proceed well. i will check it tomorrow by installing the OS to my mobile, need to back up my android OS and other things before proceeding for Ubuntu.

Thanks Neo

![image](https://user-images.githubusercontent.com/8819939/37618013-c0cdae82-2bda-11e8-8e5c-5c846ec1ebed.png)

**Comment by NeoTheThird** [comment]
Ok, thanks for the feedback. So it worked, that's good to hear. There's plenty of guides to back up an android device online. Good luck with the installation tomorrow!
