### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":fa [...]                  FAILED (remote: 'partition table doesn't exist')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by 007fred50** [ubports/ubports-installer#1490]
**UBports Installer `0.5.6-beta` (deb)**
Environment: `Ubuntu 16.04.7 LTS Xenial Xerus linux 4.15.0-122-generic x64` with Node.js `v12.16.3`
Device: FP2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa057d49702a600079da824
Log: https://paste.ubuntu.com//p/rczH6wkJbs/

**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot\" flash recovery \"/home/fredy/.cache/ubports/FP2/firmware/recovery-FP2.img\""},"stdout":"","stderr":"Sending 'recovery' (11442 KB)                      OKAY [  0.331s]\nWriting 'recovery'                                 FAILED (remote: 'partition table doesn't exist')\nfastboot: error: Command failed"}
```

**Comment by NeoTheThird** [comment]
Sorry about that. What OS is the device running currently?

**Comment by NeoTheThird** [comment]
Ah, okay. That's expected not to work. The OS has to be ported to every device specifically. There is a port for the Fairphone 3 in progress by the community, you can find information about it here: https://forums.ubports.com/topic/4964/fairphone-3-fp3

**Comment by 007fred50** [comment]
how can i install ubuntu touch on fairphone 3+ ?

you gave me (https://forums.ubports.com/topic/4964/fairphone-3-fp3)
but i can't find out to install it on my phone

**Comment by 007fred50** [comment]
hello,

I try to follow the guide here (https://www.youtube.com/watch?v=JFbCc3J22g8)
but my phone is stuck on bootup and reboot many times.

**Comment by NeoTheThird** [comment]
Please ask in the forum thread. That port is still in an early stage and will be added to the installer as soon as it is mature enough. This tracker is only for issues related to the UBports Installer.
