### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":fa [...]                 FAILED (remote: 'not supported in locked device')\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by loloco22** [ubports/ubports-installer#1492]
**UBports Installer `0.5.6-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-52-generic x64` with Node.js `v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa0d82c9702a600079da900
Log: https://paste.ubuntu.com//p/KcvHkpPh6c/

**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/snap/ubports-installer/305/app/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot\" flash boot \"/home/hackproton/snap/ubports-installer/305/.cache/ubports/hammerhead/firmware/boot-hammerhead.img\""},"stdout":"","stderr":"Sending 'boot' (12302 KB)                          OKAY [  0.597s]\nWriting 'boot'                                     FAILED (remote: 'not supported in locked device')\nfastboot: error: Command failed"}
```

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.6.0-beta) of the installer? The error should be handled there.
