### ISSUE TITLE
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":fa [...]                            FAILED (File is too large to download)\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by thisissanjeev** [ubports/ubports-installer#1497]
**UBports Installer `0.5.6-beta` (AppImage)**
Environment: `ManjaroLinux 20.1.2 Mikah linux 5.8.16-2-MANJARO x64 rolling` with Node.js `v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa409b59702a600079daef6
Log: https://paste.ubuntu.com//p/ZgS2Cc7tsb/

**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/tmp/.mount_ubportXeorM7/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot\" flash boot \"/home/linux/.cache/ubports/santoni/firmware/halium-boot_santoni.img\""},"stdout":"","stderr":"< waiting for any device >\nSending 'boot' (0 KB)                              FAILED (File is too large to download)\nfastboot: error: Command failed"}
```

**Comment by silveroffspring** [comment]
Same here on Windows 10

**Comment by silveroffspring** [comment]
Same problem here, Windows 10 Pro 64-bit

**Comment by NeoTheThird** [comment]
@thisissanjeev why did you close this? If you found the reason or a solution, please let me know. Thanks!

**Comment by thisissanjeev** [comment]
Found that there seems to be some issue with the link which I found at Ubports form.
Here is the form link: https://forums.ubports.com/post/42367
I thought someone else might have already reported and I had seen some duplicate issue as well so, I closed the issue.

**Comment by NeoTheThird** [comment]
should be resolved, the links have been updated
