### ISSUE TITLE
[oneplus3, hammerhead] Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":fa [...]            FAILED (remote: 'Partition flashing is not allowed')\r\nfastboot: error: Command failed"}

### ISSUE THREAD

**Issue by SerhiiZadorozhnyi** [ubports/ubports-installer#1498]
**UBports Installer `0.5.6-beta` (exe)**
Environment: `�������� Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0` with Node.js `v12.16.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa43e949702a600079daf6a
Log: https://paste.ubuntu.com//p/JWfWHrTM45/

**Error:**
```
Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\oretu\\AppData\\Local\\Temp\\1jMdTdVOhwHx82J6jvAT35OzJyY\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\fastboot.exe\" flash recovery \"C:\\Users\\oretu\\AppData\\Roaming\\ubports\\oneplus3\\firmware\\halium-unlocked-recovery_oneplus3.img\""},"stdout":"","stderr":"Sending 'recovery' (20880 KB)                      OKAY [  0.490s]\r\nWriting 'recovery'                                 FAILED (remote: 'Partition flashing is not allowed')\r\nfastboot: error: Command failed"}
```

**Comment by sajunt4** [comment]
Same issue on nexus 5

**Comment by NeoTheThird** [comment]
@SerhiiZadorozhnyi are you sure this is a oneplus 3?
@sajunt4 this is a device-specific issue, please open a new issue for the nexus 5 with the generated error report.

**Comment by NeoTheThird** [comment]
needs to be handled as a lock error in promise-android-tools
