### ISSUE TITLE
Fastboot: usb_read failed with status e00002ed ERROR

### ISSUE THREAD

**Issue by Marufke** [ubports/ubports-installer#15]
Automatically generated error report %0AVersion: 0.1.4-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v7.4.0 %0A%0AError log: http://paste.ubuntu.com/25161412/ %0A

**Comment by NeoTheThird** [comment]
Not reproducible, sorry...
