### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.471s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.473s

### ISSUE THREAD

**Issue by WLBI** [ubports/ubports-installer#150]
BQ M10 FHD Tablet with Android preinstalled. 
I tried to install UBports 16.04 with installer Snap on Ubuntu 16.04.

Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/xrZDs5sFGt/

**Comment by NeoTheThird** [comment]
Could you try this? https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices
