### ISSUE TITLE
Error: fastboot:flash: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by silveroffspring** [ubports/ubports-installer#1500]
**UBports Installer `0.6.0-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: Redmi 4x
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa52b069702a600079db122
Log: https://paste.ubuntu.com/p/H4r6RbjyX6/

Wanted to flash with Stable

Edit: Tried on MacOS 10.15.7 with DMG, same problem.

**Comment by silveroffspring** [comment]
After the link update everything works fine. Could not reproduce this again.

**Comment by NeoTheThird** [comment]
Good to hear, thanks for reporting back!
