### ISSUE TITLE
OnePlus2 not support

### ISSUE THREAD

**Issue by ahmsajid** [ubports/ubports-installer#1504]
**UBports Installer `0.6.0-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: OnePlus2
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa5e0e99702a600079db2d3
Log: https://paste.ubuntu.com/p/2p5m42Gxs2/

Connect OnePlus 2 and the installer says the device is not support. However uports website clearly states that the device is supported

**Comment by NeoTheThird** [comment]
Sorry about that, the installability status has been corrected on the website now
