### ISSUE TITLE
[kagura] FAILED (remote: 'Command not allowed')

### ISSUE THREAD

**Issue by l3modz** [ubports/ubports-installer#1506]
**UBports Installer `0.6.0-beta` (deb)**
Environment: `Ubuntu 18.04.5 LTS Bionic Beaver linux 5.4.0-52-generic x64 NodeJS v12.16.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa675879702a600079db3e9
Log: https://paste.ubuntu.com/p/GmYtzB7vp6/

i use wipe options, and just loading Flashing firmware for hours..

**Comment by NeoTheThird** [comment]
failing error is:

```
error: Error: fastboot:flash: Error: flashing failed: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"/opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/fastboot\" flash:raw boot \"/home/pias/.cache/ubports/kagura/firmware/halium-unlocked-recovery_kagura.img\""},"stdout":"","stderr":"Sending 'boot' (18128 KB)                          OKAY [  1.138s]\nWriting 'boot'                                     FAILED (remote: 'Command not allowed')\nfastboot: error: Command failed"}
```

What OS and version is the device running? Is the device unlocked?

**Comment by robiwan1** [comment]
I think this comes because "fastboot oem unlock" fails without error because no unlock code was provided in the fastboot command. in 0.7.4 error handling was improved BUT the missing unlock code in the fastboot command NOT corrected...
