### ISSUE TITLE
auto-detect user-action reboot with wait function

### ISSUE THREAD

**Issue by kodaxx** [ubports/ubports-installer#1511]
**UBports Installer `0.6.0-beta` (deb)**
Environment: `Pop 20.10 groovy linux 5.8.0-7625-generic x64 NodeJS v12.16.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa821c79702a600079db7a6
Log: *N/A*

Follow installer instructions

**Comment by NeoTheThird** [comment]
As part of our re-factoring of promise-android-tools (#1487), we could move back to the re-imagined `<tool>.wait()` functions to wait for the device to be accessible after the reboot. The old `<tool>.waitForDevice()` functions have recently been removed there, because they were too unreliable.
