### ISSUE TITLE
Ubuntu touch was not installed, just the recovery

### ISSUE THREAD

**Issue by matteo-gallo-bb** [ubports/ubports-installer#1514]
**UBports Installer `0.6.0-beta` (AppImage)**
Environment: `Debian GNU/Linux unknown linux 5.9.0-1-amd64 x64 NodeJS v12.16.3`
Device: mako
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa97cf19702a600079dba87
Log: *N/A*

On the UBports installer I just followed the steps

**Comment by NeoTheThird** [comment]
Not sure what happened here, do you know if the device was in recovery mode while the files were transferred? Maybe just try again?
