### ISSUE TITLE
setting udev rules fails

### ISSUE THREAD

**Issue by gbatiz** [ubports/ubports-installer#1516]
**UBports Installer `0.6.0-beta` (AppImage)**
Environment: `ManjaroLinux 20.2 Nibia linux 5.8.18-1-MANJARO x64 rolling NodeJS v12.16.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fa9a4099702a600079dbae2
Log: *N/A*

Use the appimage installer with a oneplus one phone on a fresh manjaro gnome install

**Error:**
```
udev issue, but installer seemed OK, just taking forever. Would expect some sign of the error.
```

**Comment by NeoTheThird** [comment]
The installer should have asked you to set udev rules, if this was the first time you used it on that machine. You can have the installer set udev rules automatically by selecting Tools > Set udev rules from the global menu. That should normally be sufficient. Please let me know how it goes.

**Comment by gbatiz** [comment]
Hey Jan,

Thanks for coming back to me!
Yes, I asked to set it but appearently it wasn't successful.
Maybe because appimage + archlinux, don't know, but had to do it manually for it to work. 

On November 12, 2020 10:37:46 AM UTC, Jan Sprinz <notifications@github.com> wrote:
>The installer should have asked you to set udev rules, if this was the
>first time you used it on that machine. You can have the installer set
>udev rules automatically by selecting Tools > Set udev rules from the
>global menu. That should normally be sufficient. Please let me know how
>it goes.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubports/ubports-installer/issues/1516#issuecomment-725994477

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NeoTheThird** [comment]
Interesting, thanks for reporting. I'll try to do some digging and experimenting to see what's going on.
