### ISSUE TITLE
"/bin/sh: 1: fastboot: not found", "The system cannot find the path specified."

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubports-installer#1517]
**UBports Installer `0.7.0-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-52-generic x64 NodeJS v12.16.3`
Device: FP2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5faa48349702a600079dbc1a
Log: https://paste.ubuntu.com/p/XRDx9MsmMy/

Try to Flash FP2 Normaly

**Comment by NeoTheThird** [comment]
I can't seem to be able to reproduce this yet, super weird issue. Thanks for reporting!

**Comment by NeoTheThird** [comment]
This and #1530 are most likely the same issue. The first time it happens is when flashing fastboot, which is also the first command that uses spawn rather than exec. Might be because spawn uses a shell?

**Comment by NeoTheThird** [comment]
Should be fixed in [0.7.2-beta](https://github.com/ubports/ubports-installer/releases/tag/0.7.2-beta), if someone wants to test. Thanks to all who helped triage this!
