### ISSUE TITLE
Adb push error:

### ISSUE THREAD

**Issue by Ashdash-git** [ubports/ubports-installer#152]
Window 7 Home Premium 64 bit
Nexus 5
ubports-installer.0.1.12-beta.exe

```
{"message":"Command failed: adb -P 5038 push 'C:\\Users\\User Name\\AppData\\Roaming\\ubports\\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/\n","stack":"Error: Command failed: adb -P 5038 push 'C:\\Users\\User Name\\AppData\\Roaming\\ubports\\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/\n\n    at ChildProcess.exithandler (child_process.js:223:12)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:885:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)","killed":false,"code":1,"signal":null,"cmd":"adb -P 5038 push 'C:\\Users\\User Name\\AppData\\Roaming\\ubports\\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/","level":"debug","timestamp":"2018-03-20T06:15:48.356Z"}
{"level":"error","message":"Devices: Error: Adb push error: ","timestamp":"2018-03-20T06:15:48.363Z"}
```

Error in earlier versions also.  File not found due to forward slash in file path following "\\ubports\\pool"

**Comment by Ashdash-git** [comment]
The recovery image etc is pushed the phone successfully so the paths to some files are correct.  The push of the main ubuntu files ( 1 - 13 on the gui) fail.  Does that help?

**Comment by Ashdash-git** [comment]
Sorry. Closed the issue by mistake.

**Comment by NeoTheThird** [comment]
Weird, this was reported fixed after #110... Could you send me the full link?

**Comment by Ashdash-git** [comment]
I'm away from the phone and computer at present.  It will be a few hours before I can send it.

**Comment by Ashdash-git** [comment]
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/1832086/ubports-installer.log)

**Comment by Ashdash-git** [comment]
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/1832088/ubports-installer.log)

oops! wrong button again.  Not closed.  Full log from which snippet above was taken.

**Comment by Ashdash-git** [comment]
I'm not sure about this issue anymore.  I think every file reference in the log has a forward slash.  Maybe the forward slash is only a logging issue and a distraction (red herring)!  My issue is the "Adb push error" when the installer tries to push the main ubuntu files to the phone.

The files downloaded to the computer ok to the correct location.  Recovery was loaded on the phone ok.  Many actions about files have worked ok.

Checks for existence, ok.  Download of some files to the phone, ok.

**Comment by NeoTheThird** [comment]
Ok, could you try again with [this build](https://ci.appveyor.com/api/buildjobs/1fmkakg5k8ifnc3c/artifacts/dist%2Fubports-installer%200.1.12-beta.exe)?

**Comment by Ashdash-git** [comment]
Fails at the same place.
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/1834388/ubports-installer.log)

**Comment by NeoTheThird** [comment]
Please delete everything in the folder `C:\\Users\Ali Ashman\AppData\Roaming\ubportsimages`

**Comment by Ashdash-git** [comment]
Same again. I'll be off the air for about an hour.
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/1834424/ubports-installer.log)

**Comment by Ashdash-git** [comment]
Back online.

**Comment by Ashdash-git** [comment]
First off, clockworkmod driver is not working for me.

I am using the android platform tools.  With those the phone is auto detected etc and the recovery is downloaded and switched to.   I have the installer in "c:\platform-tools" with the android adb etc and that folder in the PATH environment variable.

I have been doing my experimenting with v0.1.11 because v0.1.12 seems to have introduced something else to do with adb drivers.

On the same open command prompt after starting the v11 installer I execute "adb -P 5038 devices" and whenever the phone is on the recovery screen it is reported as attached.

When I get the "Adb push error:" dialogue box I copy the adb push command from the log file, change the forward slash to a back slash and change the single quote around the path/file name to **DOUBLE QUOTES**. It won't run with single quote.

adb -P 5038 push 'C:\\Users\\User Name\\AppData\\Roaming\\ubports\\pool\ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/\n fails.

adb -P 5038 push "C:\\Users\\User Name\\AppData\\Roaming\\ubports\\pool\ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz" /cache/recovery/\n downloads to the phone successfully.

Is the single quote the problem?  With the logging a little screwed with all file references having the forward slash but executing ok, it's a little hard to fathom what exactly is happening.

**Comment by NeoTheThird** [comment]
Those issues are likely caused by the [path.join](https://nodejs.org/api/all.html#path_path_join_paths) function. It's purpose is to elegantly join file paths in a cross-plattform way (eg use `/` on posix and `\` on windows) and provide some convenience functions (escape `\` and avoid double delimiters when joining paths). The problem is, that on windows we have some paths that need to be posix (because they describe something that's happening on the device) and some that need to be windows (because they describe something on the computer).

The easiest fix might be to go back in time and kill whoever came up with the terrible idea of using backslashes in file paths before they do any more damage. It would make the world a better place. The alternative would be to create another wrapper function (yay, moar code) that takes an argument if posix is needed or not. Thoughts?

**Comment by gsilvapt** [comment]
Due to our interest of having this working cross-platform, lets go moar code :smiling_imp: Besides, **moooaaaarrrrr coooodeeee** :laughing:

**Comment by NeoTheThird** [comment]
It'd probably be best to track this together w/ #110.
