### ISSUE TITLE
adb sideload: doesn't sideload

### ISSUE THREAD

**Issue by Vince1171** [ubports/ubports-installer#1520]
As said in the title, adb sideload doesn't sideload
I'm using [this](https://github.com/Vince1171/installer-configs/blob/master/v1/oneplus2.json) config for the Oneplus2
the [Lineage part](https://github.com/Vince1171/installer-configs/blob/ae243906a0a23999e8afcdcb11a0fd03522f6b51/v1/oneplus2.json#L131)  of this config is largely inspired by the VollaOS part of [yggdrasil](https://github.com/ubports/installer-configs/blob/9b91ac8a677518bd44e7bb3a191cbd0d389167f0/v1/yggdrasil.json#L141)

[Here](https://paste.ubuntu.com/p/67jK4v8Y8s/) is a full log (-vvvv) of the process... it's stuck forever at the latest line
this issue can be reproduced on any device by using the [Oneplus2 config](https://github.com/Vince1171/installer-configs/blob/master/v1/oneplus2.json) and enable the "skip boot and recovery flash" option in the Lineage 16 menu.
the installation process will go straight to the sideload step...

NOTE: adb sideload looks to work if manually executed
```
vince@vince-mint:~/Downloads$ /opt/ubports-installer/resources/app.asar.unpacked/node_modules/android-tools-bin/dist/linux/x86/adb sideload /home/vince/.cache/ubports/oneplus2/LineageOS/lineage-16.0-20200418-nightly-oneplus2-signed.zip 
serving: '/home/vince/.cache/ubports/oneplus2/LineageOS/lineage-16.0-20200418-nightly-oneplus2-signed.zip'  (~14%)
```

**Comment by NeoTheThird** [comment]
Please try again with 0.7.0-beta, that includes a new version of our library to handle adb. The changes made there have been made specifically to improve the stability of adb sideload and have been extensively tested with the vollaphone.

**Comment by Vince1171** [comment]
thx for the quick response
0.7.0 seems to not detect properly fastboot :/
```
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":2},"stderr":"/bin/sh: 1: fastboot: not found"}
stack trace: Error: Flashing failed: {"error":{"code":2},"stderr":"/bin/sh: 1: fastboot: not found"}
    at /tmp/.mount_ubport3iAeMo/resources/app.asar/node_modules/promise-android-tools/src/fastboot.js:157:15
    at /tmp/.mount_ubport3iAeMo/resources/app.asar/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
same for adb
```
error: Error: adb:sideload: Error: {"error":{"code":2},"stderr":"/bin/sh: 1: adb: not found"}
stack trace: Error: {"error":{"code":2},"stderr":"/bin/sh: 1: adb: not found"}
    at ChildProcess.<anonymous> (/opt/ubports-installer/resources/app.asar/node_modules/promise-android-tools/src/adb.js:265:15)
    at Object.onceWrapper (events.js:417:26)
    at ChildProcess.emit (events.js:322:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

**Comment by NeoTheThird** [comment]
Which package is this? I just re-built all linux packages locally, and all use the correct bundled tools...

**Comment by Vince1171** [comment]
I tried deb and AppImage

**Comment by NeoTheThird** [comment]
For a quick workaround, you can start the installer with `USE_SYSTEM_TOOLS=true ubports-installer`

**Comment by Vince1171** [comment]
yup it works using `USE_SYSTEM_TOOLS=true`
both `adb sideload` and `fastboot`

**Comment by NeoTheThird** [comment]
okay, good to hear, thanks. Closing for now, continuing to track the tools issue in #1517.
