### ISSUE TITLE
please describe the problem in a few words

### ISSUE THREAD

**Issue by sonysm** [ubports/ubports-installer#1523]
**UBports Installer `0.5.6-beta` (dmg)**
Environment: `Mac OS X 10.15.6 macOS Catalina darwin 19.6.0 x64 19G2021` with Node.js `v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fabd3679702a600079dbf43
Log: https://paste.ubuntu.com//p/jjmqmdFgSy/

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
