### ISSUE TITLE
Phone not boot, it open fastboot mode automatically

### ISSUE THREAD

**Issue by Developer-Java-learner** [ubports/ubports-installer#1527]
**UBports Installer `0.6.0-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-26-generic x64 NodeJS v12.16.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5facca0d9702a600079dc157
Log: *N/A*

i just install ubuntu touch on one plus 3T

**Comment by NeoTheThird** [comment]
What OS was the device running before?
