### ISSUE TITLE
Tried twice, Android 8 issue?

### ISSUE THREAD

**Issue by t-t0m** [ubports/ubports-installer#1528]
**UBports Installer `0.6.0-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-52-generic x64 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5face01c9702a600079dc195
Log: *N/A*

Stuck after "Installing Update"

**Comment by NeoTheThird** [comment]
What OS was the device running?
