### ISSUE TITLE
[windows] error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"The system cannot find the path specified."}

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#1530]
UBports Installer 0.7.0-beta (exe)
Environment: Microsoft Windows 10 Home 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3
Device: angler nexus 6P
Target OS: Ubuntu Touch
Settings: undefined
OPEN-CUTS run: https://ubports.open-cuts.org/run/5faaaa469702a600079dbcda
Log: https://paste.ubuntu.com/p/cfcNvQNMVx/

_Originally posted by @XtofHeylands in https://github.com/ubports/ubports-installer/issues/1474#issuecomment-724757693_

```
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"The system cannot find the path specified."}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"The system cannot find the path specified."}
    at C:\Users\xtofh\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\promise-android-tools\src\fastboot.js:157:15
    at C:\Users\xtofh\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Log is unfortunately incomplete due to #1522. We'll need a new report to reproduce this.

**Comment by NeoTheThird** [comment]
Duplicate of #1517

**Comment by XtofHeylands** [comment]
Could it be a fault on my end?

**Comment by NeoTheThird** [comment]
I was able to connect it to some reports from other people (so it's not just you), but i could not reproduce it myself yet. Have you tried multiple times?

**Comment by XtofHeylands** [comment]
Tried using different versions of the installer (0.5/0.6/0.7) Precedure I tried several times was: 
1. flashing stock android 7.1.2 image + enab dev/usb debugging etc...
2. flashing twpr recovery
3. formatting all partitions (not sure about this part, pretty badely documented imo)
4. running the installer

Always resulted in this error.

**Comment by Lup1ng** [comment]
Same here.
https://paste.ubuntu.com/p/p2sMMpRnP6/

**Comment by NeoTheThird** [comment]
@Lup1ng your issue looks different:

```
error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"ϵͳ�Ҳ���ָ����·����"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"ϵͳ�Ҳ���ָ����·����"}
    at C:\Users\win\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\promise-android-tools\src\fastboot.js:157:15
    at C:\Users\win\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

If i may ask @Lup1ng what language do you have your system set as? Do you remember what the error said, when the installer showed it? Pastebin seems to have messed it up...

**Comment by NeoTheThird** [comment]
The original issue should be fixed in [0.7.2-beta](https://github.com/ubports/ubports-installer/releases/tag/0.7.2-beta), if someone wants to test. @XtofHeylands

**Comment by XtofHeylands** [comment]
worked like a charm, thanks a lottt mate!!

**Comment by NeoTheThird** [comment]
Very good to hear, thank you for reporting back :)

**Comment by Lup1ng** [comment]
> @Lup1ng your issue looks different:
> 
> ```
> error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"ϵͳ�Ҳ���ָ����·����"}
> stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"ϵͳ�Ҳ���ָ����·����"}
>     at C:\Users\win\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\promise-android-tools\src\fastboot.js:157:15
>     at C:\Users\win\AppData\Local\Temp\1k2qLsXkOGbeMaJ8ZAVO1Be99hN\resources\app.asar\node_modules\cancelable-promise\dist\CancelablePromise.js:27:18
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```
> 
> If i may ask @Lup1ng what language do you have your system set as? Do you remember what the error said, when the installer showed it? Pastebin seems to have messed it up...

Everything working great! Thanks a lot!
