### ISSUE TITLE
Flashing fails

### ISSUE THREAD

**Issue by pematt** [ubports/ubports-installer#1535]
**UBports Installer `0.6.0-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-53-generic x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fae80f79702a600079dc4fe
Log: https://paste.ubuntu.com/p/m2JSmBfYQb/
Android version: 6.0.1
Developer mode: activated
Usb debugging: activated

FAILED (remote: 'not supported in locked device')

Use LG Nexus 5, install using default settings, just follow the prompts. I have tried with stable, devel and edge with the same result.

If I uncheck the box 'Bootstrap' then the phone reboots and then shows 'No command' on the screen and then nothing happens.

UBports downloaded the ubuntu touch files today.

**Comment by pematt** [comment]
Solved it by using android tools on ubuntu to unlock the phone, then run the UBports installer again.

For anybody interested here are the steps I took on ubuntu to unlock the phone:

sudo apt-get install android-tools*
adb devices
adb reboot bootloader
fastboot oem unlock

Source: https://schier.co/blog/how-to-root-nexus-5-in-linux

Thank you for an awesome software!

**Comment by NeoTheThird** [comment]
Hi, thank you for reporting. This issue (#1468) should be fixed in [the upcoming prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.7.2-beta). Sorry for the inconvenience!
