### ISSUE TITLE
[suzu] Linked file for manual download fails at checksum check

### ISSUE THREAD

**Issue by jonnius** [ubports/ubports-installer#1542]
**UBports Installer `0.7.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-53-generic x64 NodeJS v12.16.3`
Device: suzu
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5faf8ba79702a600079dc755
Log: *N/A*

Try to install arm64/hybris/devel channel on Xperia X

**Comment by jonnius** [comment]
Just figured that the provided download link gets you a zip file with the same name as expected except for the file extension (`zip` instead of `img`). After unpacking the zip, installation works with the `img` file. Still wonky though.

**Comment by NeoTheThird** [comment]
You're right, i can see how that'd be confusing. If you'd be willing to have some fun with the config, you could change it [here](https://github.com/ubports/installer-configs/blob/master/v1/suzu.json#L79) to take in the zip file and add an `unpack` step [as seen here](https://github.com/ubports/installer-configs/blob/master/v1/yggdrasil.json#L160).

**Comment by jonnius** [comment]
Nice scripting language :)

**Comment by NeoTheThird** [comment]
> Nice scripting language :)

Thanks, hope to make it even better soon :) https://github.com/ubports/installer-configs/pull/51

Thanks for the PR.
