### ISSUE TITLE
OP3: Stuck at 'Powered by Android' screen or Fastboot mode

### ISSUE THREAD

**Issue by mybooc** [ubports/ubports-installer#1545]
**UBports Installer `0.6.0-beta` (deb)**
Environment: `Ubuntu 18.04.5 LTS Bionic Beaver linux 4.15.0-118-generic x64 NodeJS v12.16.3`
Device: oneplus3T
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fafb54e9702a600079dc7ac
Log: *N/A*

First flash TWRP,, format system, data, cache as ext4. run UBPorts installer

Another try:

I followed the procedure (all the steps) as described here. 

https://forums.ubports.com/topic/3253/oneplus-3-3t/488

gischpelino 31 mei 2020 13:57

@Kyrylo looks like that not all partitons are ext4. May be a clean start with the device can help you. It gives you best chance to do it.

    start with twrp (fastboot boot twrp)
    set twrp to adb sideload mode
    adb sideload the latest oxygenos 9.0.6 from oneplus support page
    start the phone and make initial setup of the os
    after that 'fastboot boot twrp' again
    1st. wipe all partitions
    2nd select wipe advanced 'change filesystem' of cache, system and data and set it to ext4
    3rd wipe format data
    check with twrp terminal command 'mount' that all partitions are ext4. If not change filesystem again.
    connect device to usb (still in twrp) and start ubport-installer

Now the UBports installer completed but the result is the same. 

UBports installer:
-
Ubuntu Touch successfully installed!

Success!
The installation process from the computer is done. 
The device will now perform the remaining steps which should take less than five minutes. 
After the installation, the device will reboot and you can begin to explore Ubuntu Touch.
-

On the phone, the fastboot screen changes to Android recovery main menu:
-
Android Recovery

Use volume up/down and power:
Reboot system now
Ubuntu actions
Android actions
-

Because nothing happened, after 5 minutes I selected:
Reboot system now

OnePlus Symbol +
Powered by android

After some 20 seconds the phone gets back into the Fastboot mode.
Then I select Power off. 

Now the phone reboots and (again) keeps showing:

OnePlus Symbol +
Powered by android

Etc. 
Some help is appreciated.

Edit:
Related(?):
https://github.com/ubports/ubports-installer/issues/1527

**Comment by mybooc** [comment]
Today I followed the procedure as describe above again and success!

UT is running on the OnePlus 3t

Used the latest UBports installer 0.7.4-beta.
Phone was recognized by UBports installer. 
Not 100% sure but last time maybe I forgot the step: '3rd wipe format data'. 
I also turned the phone off and on again when asked by UBports installer. 

Thank you UBports team!

**Comment by NeoTheThird** [comment]
Good to hear! Sorry about the inconvenience in the beginning. Hope you enjoy Ubuntu Touch!
