### ISSUE TITLE
Connection continuously lost

### ISSUE THREAD

**Issue by schance995** [ubports/ubports-installer#1547]
**UBports Installer `0.6.0-beta` (AppImage)**
Environment: `LinuxMint 20 Ulyana linux 5.4.0-53-generic x64 NodeJS v12.16.3`
Device: flo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb097839702a600079dc985
Log: *N/A*

Nexus 7 2013 wifi flo, had to install multiple times and change usb cables

**Comment by NeoTheThird** [comment]
Hmm, was the device maybe really low on battery? Did you notice anything happening when the connection was lost? The logging looks like a loose cable:

```

command: adb: {"args":["-P",5037,"push","\"/home/sunshine/.cache/ubports/system-image/pool/ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz\"","/cache/recovery/"," | ( grep -v \"%]\" || true )"],"error":null,"stdout":"adb: error: failed to read copy response\n/home/sunshine/.cache/ubports/system-image/pool/ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz: 1 file pushed, 0 skipped. 7.6 MB/s (392098116 bytes in 49.001s)\nadb: error: failed to read copy response\n","stderr":""}
command: adb: {"args":["-P",5037,"push","\"/home/sunshine/.cache/ubports/system-image/pool/ubports-9931a66ffaa043182df96ea44950d640f0427b0d98b50e6dae90e9281ae1ae7b.tar.xz.asc\"","/cache/recovery/"," | ( grep -v \"%]\" || true )"],"error":null,"stdout":"adb: error: failed to get feature set: no devices/emulators found\n","stderr":""}
```

**Comment by schance995** [comment]
That makes sense, the usb port in the device is not exactly reliable. Just for future reference, are there any points in the install where a lost connection would render the device unusable/uninstallable?

**Comment by NeoTheThird** [comment]
> are there any points in the install where a lost connection would render the device unusable/uninstallable?

Most unlikely. There might be cases where a lost connection does not cause the installer to error out, thus resulting in a faulty install on the device. But then you could simply install again. A hard-brick is next to impossible as a result of a lost connection.

**Comment by schance995** [comment]
Excellent and thanks, closing this issue.
