### ISSUE TITLE
Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\000ma\\AppData\\Local\\Temp\\1jZdYrkqnbzAZoGRTA5fqH0JXK9\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe\" -P 5037 shell 'mount -a || true'"},"stdout":"","stderr":"/sbin/sh: no closing quote\r\n'true'' is not recognized as an internal or external command,\r\noperable program or batch file."}

### ISSUE THREAD

**Issue by 333majk3333** [ubports/ubports-installer#1548]
**UBports Installer `0.6.0-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3`
Device: suzu
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb155e69702a600079dcad2
Log: https://paste.ubuntu.com/p/SFsrPNv5BG/

Error: systemimage: Error: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\000ma\\AppData\\Local\\Temp\\1jZdYrkqnbzAZoGRTA5fqH0JXK9\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe\" -P 5037 shell 'mount -a || true'"},"stdout":"","stderr":"/sbin/sh: no closing quote\r\n'true'' is not recognized as an internal or external command,\r\noperable program or batch file."}

**Comment by NeoTheThird** [comment]
Should be fixed in the upcoming release: https://github.com/ubports/ubports-installer/releases/tag/0.7.2-beta
