### ISSUE TITLE
there is no supported OS for xiaomi redmi pro

### ISSUE THREAD

**Issue by arifkara86** [ubports/ubports-installer#1550]
**UBports Installer `0.6.0-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-53-generic x64 NodeJS v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb2b6bb9702a600079dcd77
Log: https://paste.ubuntu.com/p/qdq4YN2g38/

please update the repo

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
