### ISSUE TITLE
FAILED (remote: 'Fastboot command (set_active:) is not allowed when locked')

### ISSUE THREAD

**Issue by StephenLesage** [ubports/ubports-installer#1556]
**UBports Installer `0.7.2-beta` (dmg)**
Environment: `Mac OS X 10.15.4 macOS Catalina darwin 19.4.0 x64 19E287 NodeJS v12.16.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb5c9399702a600079dd388
Log: https://paste.ubuntu.com/p/8cVjhTgCCX/

i am not sure, i followed the instructions perfectly multiple times

**Comment by NeoTheThird** [comment]
You need to unlock the bootloader, like the installer asked you to: https://source.android.com/devices/bootloader/locking_unlocking#unlocking-bootloader

This error needs handling on our side:
```
stack trace: Error: failed to set active slot: Error: {"error":{"code":1,"cmd":"fastboot --set-active=b"},"stderr":"< waiting for any device >\nSetting current slot to 'b'                        FAILED (remote: 'Fastboot command (set_active:) is not allowed when locked')\nfastboot: error: Command failed"}
```

**Comment by StephenLesage** [comment]
OEM unlocking (Allow the bootloader to be unlocked) was, and is, set to on. 

When UBports sees the phone a message pops up on the phone saying "Allow USB debugging? ..." then i am able to proceed all the way until i hit "install" on UBports. under channel I chose the stable version and hit okay. but then when UBports takes over and the phone goes into the bootloader it reads 
"Device state: locked"
which doesn't make sense.

I have played with fastboot before when trying to install Plasma Mobile a few months ago on a different device, so perhaps there is a PATH problem and it is unable to find the correct version? I am just spitballing ideas here... 

Any suggestions?

**Comment by NeoTheThird** [comment]
You overlooked one part in the instructions in the link. It is not enough to just enable oem unlocking in the settings, you also need to do the actual unlocking by running `fastboot flashing unlock` in a terminal with the phone in bootloader mode and connected to your PC. While the installer can unlock the bootloader for most devices on its own, your device uses a different method of unlocking that the installer does not support yet (#1479). We're planning to fix that soon, but for the time being, you have to run that one command yourself.

**Comment by StephenLesage** [comment]
you're right, i didn't read very carefully. I will follow the proper precursor steps later today and post again with a success or failure update. thank you!

**Comment by StephenLesage** [comment]
no luck. i think the first time i used an older USB cable. it went through the whole process, but didn't seem to work. So i tried again with a newer cable and it got all the way to the "recovery screen" but "lost connection try again" kept popping up. i would click it 5 or 6 times before the "Google" screen took over on the phone. I tried ~8 times, both wiping "UserData" and not, and it keeps getting hung up in the same spot. 

I also think it successfully altered something because the Google screen can't get past the "G" with the loading bar beneath it. I think I have successfully bricked this phone. After the holidays I will try again flashing it on my own without UBports and see if I can get somewhere with it that way. For now, you can close this Bug report, work on it on your own time, and i will submit another when I try again.

Happy Holidays,
Stephen Lesage
