### ISSUE TITLE
Create a LineageOS downloader

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#1557]
There are APIs we can consume to get LineageOS artifacts: https://download.lineageos.org/api/v1/oneplus2/nightly/abc

**Comment by Vince1171** [comment]
same for OpenGapps https://api.opengapps.org/download?arch=arm64&api=7.1&variant=nano&date=20201121
but it's a tricky one because the date parameter is required
the latest date can be get in https://api.opengapps.org/list [archs][*][date]
(or just the date of last Saturday )
