### ISSUE TITLE
[yggdrasil] add unlock hint

### ISSUE THREAD

**Issue by oxydon** [ubports/ubports-installer#1558]
**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-29-generic x64 NodeJS v12.16.3`
Device: yggdrasil
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fb6ec399702a600079dd5e1
Log: https://paste.ubuntu.com/p/9ymbqmwfQg/

By a new Volla Phone with Volla OS, allow OEM and USB-debugging in the developer settings and then follow the ubports installation word by word and you will get stuck with the partitioning.

Then follow this manual https://nerdschalk.com/unlock-bootloader-via-fastboot-android/ (running the fastboot flashing unlock command) and it will work.

**Comment by NeoTheThird** [comment]
Whoops, missed that. We'll add instructions as a makeshift fix and then properly fix this in #1479.

**Comment by NeoTheThird** [comment]
Fixed in 0.8.1-beta
