### ISSUE TITLE
It keeps booting into the Ubports Recovery

### ISSUE THREAD

**Issue by Moose1005** [ubports/ubports-installer#1574]
**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-28-generic x64 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fbc853f9702a600079de0e2
Log: *N/A*

I don't know I followed the installers instructions but it keeps booting the recovery and looping there.

**Comment by NeoTheThird** [comment]
Sorry about that. Could you try again and open a new issue? The log is cut off.
