### ISSUE TITLE
Sort out file guards in promise-android-tools

### ISSUE THREAD

**Issue by DaBisounours** [ubports/ubports-installer#1575]
**UBports Installer `0.7.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fbcd5a49702a600079de17c
Log: *N/A*

I'm guessing it comes from my user name "Evan Graïne" which happen to contain a whitespace and a french character.
The error:
Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stderr":"fastboot: error: cannot load 'Gra�ne\\AppData\\Roaming\\ubports\\bacon\\firmware\\boot-bacon.img': No such file or directory"}
The path should be C\\Users\\Evan Graïne\\AppData\\....

**Comment by NeoTheThird** [comment]
A related issue:
```
command: exec: {"cmd":["fastboot","boot","\"/home/geminis65/snap/ubports-installer/320/.cache/ubports/hammerhead/firmware/recovery-hammerhead.img\""],"error":{"message":"Command failed: fastboot boot \"/home/geminis65/snap/ubports-installer/320/.cache/ubports/hammerhead/firmware/recovery-hammerhead.img\"\nfastboot: error: cannot load '\"/home/geminis65/snap/ubports-installer/320/.cache/ubports/hammerhead/firmware/recovery-hammerhead.img\"': No such file or directory","code":1},"stderr":"fastboot: error: cannot load '\"/home/geminis65/snap/ubports-installer/320/.cache/ubports/hammerhead/firmware/recovery-hammerhead.img\"': No such file or directory"}
```

The quoted fileguards do not seem to work properly with the new promise-android-tools any more. Maybe we should move to backslashes instead.
