### ISSUE TITLE
Unable to install VollaOS on Volla Phone

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-installer#1579]
**UBports Installer `0.8.0-beta` (AppImage)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-54-generic x64 NodeJS v12.16.3`
Device: yggdrasil
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fbe88869702a600079de49f
Log: https://paste.ubuntu.com/p/qvF2ff46Xk/

When installing VollaOS on the Volla Phone, a "File not found" error appears for unpacked/boot.img. If you "Try Again", the same error appears in the console but the error dialog does not appear.

**Comment by McMarius11** [comment]
i had the same problem #1568

**Comment by UniversalSuperBox** [comment]
Indeed. This is a duplicate of #1568
