### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by magm58** [ubports/ubports-installer#158]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/xK6K7jjds3/

**Comment by NeoTheThird** [comment]
There seems to be a weird issue with the adb executable. `debug 2018-03-21T05:51:31.117Z Command failed: /tmp/.org.chromium.Chromium.wdfhkr -P 5038 push '/home/michael/.cache/ubports/pool/ubports-c6d4d784716d59cc79aa93d9c74f9789c448d630f5d49fd068c4d22183287da6.tar.xz' /cache/recovery/` seems to be the problem.

What package is this? I'm assuming appimage? Could you try moving the appimage to something else than /tmp, preferably somewhere in your home dir?
