### ISSUE TITLE
[santoni] Installed, but get black screen on start up

### ISSUE THREAD

**Issue by gg-harper** [ubports/ubports-installer#1584]
**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-54-generic x64 NodeJS v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fc11cde9702a600079de92e
Log: *N/A*

I dunno. Install it on Redmi 4x

**Comment by AquUpd** [comment]
bump, same issue

**Comment by karrvel** [comment]
same problem 
UBPorts: `0.8.8 (beta)`

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
