### ISSUE TITLE
- failed to recognize nexus 5 + fantastic guidance and troubleshooting

### ISSUE THREAD

**Issue by rcomas28** [ubports/ubports-installer#1586]
**UBports Installer `0.7.4-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H15 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fc193b39702a600079dea2f
Log: *N/A*

Installer failed to recognize nexus 5 hammerhead at the beginnnig of the process (USB debugging enabled) saying that nexus 5 hammerhead is not supported by ubports installer). Restarted installer and re-enabled USB debugging and everything went smooth. Computer lost connection with the device while sending files to it but the installer guided me step by step to a succesful installation. Thank you!!!

**Comment by NeoTheThird** [comment]
Thank you for reporting, we're currently redesigning how the "not supported" prompt is coming up, so we can close this for now. Glad to hear you were able to make it through in the end!
