### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by toujirou** [ubports/ubports-installer#1587]
*Automatically generated error report* 
UBports Installer Version: 0.4.14-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: deb
Operating System: Ubuntu Linux  20.10  groovy x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/NFj3Mgmvw9/

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
