### ISSUE TITLE
UBports installer 0.8.1 and Santoni

### ISSUE THREAD

**Issue by liss21** [ubports/ubports-installer#1596]
Hello guys.
After commit bd3d410 which fixed #1580, tried to install the OS using the new installer 0.8.1. I tried installer on Windows 10 and Lubuntu 20.04

The behavior has changed. Now, after flashing the recovery, the sound of the device disconnecting is audible, but a fastboot picture remains on the screen. At the same time, the installer starts downloading files for installation, after which it gets stuck at the stage of preparing the system image. In this case, neither adb nor fastboot detects the device.
It looks like the installer just skips checking for the device. This is confirmed by the fact that if you make a `fastboot boot orangefox_recovery_santoni.img` while downloading files, the installer will not even notice this and will still get stuck on preparing the system image.

Forced entry into the UBPorts recovery by volume + and power does not give anything, the phone hangs on the Mi logo.

If I understand correctly the question about the non-working recovery should I ask Danct12?

**Comment by NeoTheThird** [comment]
Please send me a [log](https://github.com/ubports/ubports-installer#logs) so we can see what's going on exactly. I suspect this is basically #1593 combined with the device behaving a little weird.

**Comment by liss21** [comment]
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/5642263/ubports-installer.log)

**Comment by NeoTheThird** [comment]
Thanks. So we have a lot of adbd weirdness going on there (#1594), but the acual problem is #1593, as expected. You might have success if you try again a couple times.

**Comment by liss21** [comment]
Ok. This moment is clear. But what i should do with recovery? It won`t boot. I don`t think that my device is special. It run all custom firmwares includes Sailfish. But UBPorts recovery indeed fail to boot.
