### ISSUE TITLE
Finally Worked, but not as easy as described.

### ISSUE THREAD

**Issue by fapsi** [ubports/ubports-installer#1604]
**UBports Installer `0.8.1-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-56-generic x64 NodeJS v12.16.3`
Device: yggdrasil
Target OS: Ubuntu Touch (Channel RC)
Settings: `Marked Wipe Userdata and Bootstrap`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fcab1bf42e3b000074bdcac
Log: https://paste.ubuntu.com/p/2QxrCdqFQx/

I enabled developer mode as described, but the Ubports Installer couldn't itself restart the device into fastboot mode (with preinstalled ubuntu touch from volla). When trying the device becomes unresponsive and needs a reset.

When I used the Ubports Installer directly from recovery mode, it magically worked with following steps: (a.)reboots into fastboot;b)warns about warranty; c)restart into recovery and downloads ubuntu touch on computer and transfers it to teh device ;d)started installing the image;e)booted again into the new ubuntu touch.)

Note: I will try it again and try to reproduce this issue once again with the new ubuntu touch installation.

**Comment by JamiKettunen** [comment]
There is sadly a know issue with toggling developer mode under Ubuntu Touch on newer devices (such as the Volla Phone) which use ConfigFS to change the USB mode configuration: you'll have to reboot for the changes to take effect.

I think to fix this particular issue the whole USB configuration process needs to be modernized in Ubuntu Touch; we'll see if the Ubuntu 20.04 LTS base upgrade (from current 16.04 LTS) will help us with this.

**Comment by fapsi** [comment]
Sorry for the late reply. Thanks for this clarification, I will try it again with the upcoming Ubuntu Touch LTS release and open a new issue then.
