### ISSUE TITLE
[angler] Nexus 6P install failure

### ISSUE THREAD

**Issue by SL8R8R** [ubports/ubports-installer#1605]
**UBports Installer `0.7.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fcad47f42e3b000074bdce9
Log: *N/A*

Fresh install of 7.1.2 latest, then flash TWRP latest 3.3.1. Run UBports Installer, manually select device, flash. Boots to UBports Recovery, stays in recovery while installer says pushing files. Files pushed successfully, reboots back into UBports Recovery.

**Comment by eugulixes** [comment]
I've got exactly the same issue. However, I used TWRP 3.4.0.

**UBports Installer `0.8.2-beta` (deb)**
Environment: `Ubuntu 18.04.5 LTS Bionic Beaver linux 4.15.0-126-generic x64 NodeJS v12.16.3`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd7618142e3b000074bf8cb

**Comment by eugulixes** [comment]
I tried OTA-15 and now it works fine on my Nexus 6P. Thank you.
