### ISSUE TITLE
phone was not recognized eventhough it was booted in UBports recovery

### ISSUE THREAD

**Issue by wdehoog** [ubports/ubports-installer#1607]
**UBports Installer `0.8.1-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fcb93fc42e3b000074bde5b
Log: https://paste.ubuntu.com/p/vj7RvxnJfp/

please fill out this field

This is not a bug but a remark. I wanted to install (rc channel) and it worked.

But I found it weird that eventhough my phone was booted in UBports recovery it was not recognized by the installer as a
'oneplus one booted in UBports recovery'.

**Comment by NeoTheThird** [comment]
thanks for reporting. `command: exec: {"cmd":["adb","-P",5037,"kill-server"],"stderr":"cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: No connection could be made because the target machine actively refused it. (10061)"}`, looks like it's #1594
