### ISSUE TITLE
Missing "fastboot flashing unlock" lets UBports installer 0.7.4-beta hang in the "Rebooting to bootloader" step 

### ISSUE THREAD

**Issue by aryoda** [ubports/ubports-installer#1608]
**UBports Installer `0.7.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-54-generic x64 NodeJS v12.16.3`
Device: yggdrasil
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fccbac642e3b000074be0c3
Log: https://paste.ubuntu.com/p/JSjpFSQ58V/

Use a new Volla phone with locked flashing

I suggest to add a hint to the text section of the installer before trying to reboot since it is unclear if you brick your device when you kiill/close the UBports installer and restart the mobile manually.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Fixed in [the next release](https://github.com/ubports/ubports-installer/releases/tag/0.8.1-beta).

**Comment by aryoda** [comment]
I guess it is fixed with #1479

**Comment by NeoTheThird** [comment]
yep
