### ISSUE TITLE
It ends up in a boot loop.

### ISSUE THREAD

**Issue by Pavel-Sayekat** [ubports/ubports-installer#1609]
**UBports Installer `0.7.4-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-56-generic x64 NodeJS v12.16.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fce5e1042e3b000074be410
Log: *N/A*

on a Xiaomi mi a2 64/4 GB version, the issue is recurring after flashing it using twrp or the ubports installer.

**Error:**
```
It ends up in a boot loop.
```

**Comment by NeoTheThird** [comment]
@just-carlod maybe you're interested to help here?

**Comment by Pavel-Sayekat** [comment]
How?

**Comment by just-carlod** [comment]
@Pavel-Sayekat I sent you instruction how to install ut on this device, [download this rom](https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/20201205/UBTouch-jasmine_sprout-05-12-2020.zip) 
1. go to fastboot change slot to b fastboot --set-active=b
2. type in terminal/cmd fastboot boot /path/to/twrp.img
3. in recovery wipe everything and flash android 9 rom via adb sideload adb sideload /path/to/rom.zip
4. in fastboot type fastboot --set-active=a, stay in fastboot
5. run installer (select manually device) >> choose os >> download needed firmware >> when reboot to bootloader screen apears plug device (you are in fastboot) and click continue >> when reboot to recovery screen apears press volume up + power til recovery logo apears. 

If installer fails try another device

**Comment by just-carlod** [comment]
Can we change slots in the installer? If so I will make updated version of installer to flash stock rom automaticly so users I won't be confused when installing ubuntu touch

**Comment by NeoTheThird** [comment]
@just-carlod yes, you can use `fastboot:set_active`: https://github.com/ubports/installer-configs/blob/master/v2/schema/action.schema.yml#L185

**Comment by Pavel-Sayekat** [comment]
There's nothing wrong with the installer, the ported rom does not work with my mi a2 with "jdi nt36672 fhd video mode dsi panel" as the rumor is and so the display turns on and off, can ssh into the phone while the phone is not (with no GUI).

**Comment by gibcheesepuffs** [comment]
Fixed.
