### ISSUE TITLE
[yggdrasil] SIM card not detected when using Volla OS but is detected on Ubuntu Touch

### ISSUE THREAD

**Issue by dikel** [ubports/ubports-installer#1612]
UBports Installer 0.7.4-beta (AppImage)
Environment: Fedora 33 5.9.11-200
Device: yggdrasil
Target OS: VollaOS

My Volla Phone came with Ubuntu Touch but I decided to try VollaOS first. I flashed it with 0.7.4 (I had to run it as root and extract the .zip file to "unpacked" folder) and it worked but my SIM card wasn't detected. When I went to the android settings it said "SIM empty". I tried another SIM card but it wasn't recognized as well. I flashed Ubuntu Touch and the SIM was recognized. Then I tried with version 0.8.1 and flashed VollaOS again but the problem was still there. I'm not sure if anyone else has this problem. I'm now using my device with Ubuntu Touch but if someone can reproduce it or knows a fix I will try to flash it again and give logs.

**Comment by pekrahulec** [comment]
I had the same issue. I followed these steps:
Go to twrp, change data to ext2, then back to ext4, then format data.
(thank you McMarius11 - Look up issue : Volla OS install can't mount Data partition #1569)

After that both of my SIM cards work. 
PS: Also, you need to set permission for Files app to read storage, it's disabled by default.

**Comment by rachyandco** [comment]
i have a similar issue but changing to ext2, back to ext4 then formatting data, did not do the trick.

**Comment by JamiKettunen** [comment]
This is due to some critical `NVDATA` partition files losing correct permissions during normal operation of Ubuntu Touch (potentially Sailfish OS as well), I'm sending in a fix for this very soon; stay tuned and please do try again later after my patch is merged and after a new beta release comes out with it included!

**Comment by rachyandco** [comment]
While waiting for the merge, I was able to test the code

```
git clone https://github.com/JamiKettunen/installer-configs/
cd installer-configs/
git checkout origin/yggdrasil-fixes
ubports-installer -f ./v2/devices/yggdrasil.yml
```
huge succes, Android was installed and the Sim card is detected.

Thank @JamiKettunen

**Comment by NeoTheThird** [comment]
This is live now
