### ISSUE TITLE
[karin] error 404

### ISSUE THREAD

**Issue by ip6li** [ubports/ubports-installer#1613]
**UBports Installer `0.8.1-beta` (AppImage)**
Environment: `Fedora 33 Workstation Edition linux 5.9.11-200.fc33.x86_64 x64 NodeJS v12.16.3`
Device: karin
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd0d80542e3b000074be96f
Log: *N/A*

Simply try to install an image on SG771

**Comment by nmz787** [comment]
how to work around when an install hits this? I had ubports-installer from several months ago when I played with this on my Xperia F5121, and assumed everything would go smoothly as I already had all the pre-requisite setup from before. Now I have no idea what to do, or what the state of my phone is.
