### ISSUE TITLE
Phone Galaxy J7 dose not Connect

### ISSUE THREAD

**Issue by rafatahmed** [ubports/ubports-installer#1619]
**UBports Installer `0.8.1-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: (device not yet detected)
Target OS: (Galaxy J7 2016)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd406b142e3b000074bf07f
Log: https://paste.ubuntu.com/p/kxNc6Vx9kr/

i know Galaxy J7 dose not supported yet but i Cary the risk to try it its worthy

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
