### ISSUE TITLE
[yggdrasil] I had to unpack volla-9.0-20201019-nightly-k63v2_64_bsp-signed.zip in a new created unpacked folder manually.

### ISSUE THREAD

**Issue by gonzo5691** [ubports/ubports-installer#1620]
**UBports Installer `0.8.1-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-56-generic x64 NodeJS v12.16.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd4be4342e3b000074bf20f
Log: https://paste.ubuntu.com/p/z2jJxW6R4y/

Try to install Volla.

**Comment by dikel** [comment]
I had to do the same thing. Does your SIM card work on VollaOS? My phone detects the SIM card if I'm using Ubuntu Touch but not if I'm using VollaOS. Did you install twrp left it unchecked?
