### ISSUE TITLE
[oneplus2] After installation finished, Phone is stuck on Oneplus Boot logo not booting into OS, tried rebooting 3-4 times no luck

### ISSUE THREAD

**Issue by Bikramsinghy** [ubports/ubports-installer#1626]
**UBports Installer `0.8.1-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: oneplus2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd6046142e3b000074bf55b
Log: *N/A*

I will try to install it again to see if this is recurring issue

**Comment by Vince1171** [comment]
this should be fixed now that OTA-15 is out
can you confirm?

**Comment by Vince1171** [comment]
@NeoTheThird you can close this one and #1630 (they are the same as #1649 ) and it's been fixed with OTA-15
