### ISSUE TITLE
nothing happend

### ISSUE THREAD

**Issue by 4NewUsers** [ubports/ubports-installer#1629]
**UBports Installer `0.8.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-53-generic x64 NodeJS v12.16.3`
Device: flo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd6b5b842e3b000074bf6ff
Log: https://paste.ubuntu.com/p/3S24zDQb9c/

nothing happend

**Comment by NeoTheThird** [comment]
Your device is not a Nexus 7 2013, it's a 2012 (codename `grouper`). Unfortunately, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
