### ISSUE TITLE
[oneplus2] ubports-installer_0.8.2-beta_win.exe after fastboot and reboot stuck on Boot logo

### ISSUE THREAD

**Issue by Bikramsinghy** [ubports/ubports-installer#1630]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: oneplus2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd7118a42e3b000074bf7f2
Log: https://paste.ubuntu.com/p/6KB7sycW8Q/

Tried many times, kept whole night on, but still stuck on Boot Logo, Official OOS 3.6.1, TWRP 3.2.1

**Comment by Vince1171** [comment]
this should be fixed now that OTA-15 is out
can you confirm?
