### ISSUE TITLE
Ubuntu touch not install

### ISSUE THREAD

**Issue by mcujba** [ubports/ubports-installer#1635]
**UBports Installer `0.8.2-beta` (deb)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.4.0-58-generic x64 NodeJS v12.16.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd8527042e3b000074bfae9
Log: *N/A*

Sopped on Preparing system-mage. I waited all night but image was not prepared.

**Comment by mizsha** [comment]
On Xiaomi 4X same issue. 

UBports 0.8.2-beta and this is not dependant on OS ( 20.04 , 18.04, win10 ) or packaging ( deb, appimage, snap ) all variants have same issue.

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
