### ISSUE TITLE
Worked 2nd time

### ISSUE THREAD

**Issue by pematt** [ubports/ubports-installer#1638]
**UBports Installer `0.8.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-58-generic x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd8bcd042e3b000074bfbd7
Log: https://paste.ubuntu.com/p/Pk7gfGNFnH/

Nexus 5 hammerhead with Android 4.4.3 and locked. First time it managed to unlock the phone but then booted into Android instead of installing Ubuntu Touch. 2nd time with the phone now unlocked it managed to install UT.

**Comment by NeoTheThird** [comment]
Sorry about that. Difficult to reproduce what went wrong the first time now...
