### ISSUE TITLE
FAILED (remote: 'Anti-rollback check failed')

### ISSUE THREAD

**Issue by ZawYHtoo** [ubports/ubports-installer#1639]
**UBports Installer `0.8.2-beta` (dmg)**
Environment: `macOS 11.0.1 macOS darwin 20.1.0 x64 20B50 NodeJS v12.16.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fd8cd9c42e3b000074bfc15
Log: https://paste.ubuntu.com/p/6QGmF7Fhv6/

Release vendor image file, we can install manually.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
