### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Coolbijoj** [ubports/ubports-installer#1649]
**UBports Installer `0.8.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.9.11-3-MANJARO x64 NodeJS v12.16.3`
Device: oneplus2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fda9def42e3b000074c008a
Log: *N/A*

Install Stock ROM+recovery to Oneplus2.
Complete installation via UBports installer.
Device will boot to Ubuntu Touch installer ( Ubuntu touch logo appeared with blinking eye ) and proceeds installation.
After reboot, the device will show Oneplus logo only.
I can fastboot , reinstall Stock rom and repeat the same.

**Comment by Vince1171** [comment]
this should be fixed now that OTA-15 is out
can you confirm?

**Comment by Coolbijoj** [comment]
Yes, Thanks.

It's working!
