### ISSUE TITLE
bsod

### ISSUE THREAD

**Issue by forart** [ubports/ubports-installer#1659]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fde3da942e3b000074c091e
Log: *N/A*

dunno

**Comment by NeoTheThird** [comment]
There seem to have been some download errors, please check your network stability and try again
