### ISSUE TITLE
Fix typos in project

### ISSUE THREAD

**Issue by gsilvapt** [ubports/ubports-installer#166]
Throughout the code, there are methods, variables and logs containing typos that should be renamed for easy reading. This can be a tough task considering there are no tests and thus we may not know the extent of the changes.

If you agree, I can commit to fix everything in the project and integrate the other changes we made in the [`system-image-module`](https://github.com/ubports/system-image-node-module/pull/5).

**Comment by Ashdash-git** [comment]
Hello.  I opened issue #152 and I see you have commented on other issues similar to the one I raised.

For the windows installer particularly, the log entries are not an accurate representation of the events. Various file activities have an incorrect path in the log, yet the event processed correctly so I guess the log entry must be wrong.

The point of the install that fails for me is when the main ubuntu files are to be pushed to the phone.  The log entry looks similar to other entries so is of no use determining the problem. I have spent some time on the issue and have confirmed that if I copy the the 'push' command from the log, paste it into the same open command prompt window from which I started ubports-installer, correct the errors from the pasted logged entry, the file is pushed to the phone without error.

So it could be that the concatenation of the path to the local file name or the quoting is incorrect and so the file is not found and the push command fails, or it is another problem completely and the log entry is only confusing the issue.

I'll help if I can.

**Comment by gsilvapt** [comment]
Thank you for helping out resolving this. However, I must point out this change, if approved, will not cause the software to function differently. Here's an example of issue I am expecting to fix in this issue:

There's a log message that is `Done pusing files.` This can always be edited to be `Done pushing files.`. There are also method names that have typos. Again, this should really not change how the software is working. This to say, if you have found that issue, then we should move it elsewhere and also work from there to avoid confusing tasks. I'll hop on issue 152 to see if there's anything I can help with. 

Again, thanks for reporting the issue :+1:

**Comment by NeoTheThird** [comment]
@gsilvapt That would be great, thank you! Looking forward to your PR(s)! If you have a question, just ping me. The fact that the installer is untested at the moment is a big problem. We're looking to solve this in #58 at the moment, and the system-image-module is a step in the right direction. For now, we need to avoid regressions by carefully reviewing PRs.

**Comment by gsilvapt** [comment]
Sure, makes total sense. I went ahead and started fixing most typos I could found :sweat_smile: There is only one important issue I think we should discuss before sending the PR. @NeoTheThird if you think the changes in the `system-image-module` have broken this, I can quickly submit the PR to have it working again.

In `build.js`, on line 94, the icon object is referenced to a `.icns` file. I'm not sure if that's a valid extension? Can anyone confirm this is the correct extension and thus I should not change to `.icon` or `.ico`? @mariogrip since you did most of this so you input would be very appreciated.

**Comment by NeoTheThird** [comment]
> system-image-module

No, it's fine. I just have to push a new release of the system-image-module and bump its version to avoid incompatibility. Will do once your PR is here.

> .icns

No, that is correct as it is. It's a weird mip-map thing Apple made up for their application-icons. See https://en.wikipedia.org/wiki/Apple_Icon_Image_format

**Comment by gsilvapt** [comment]
PR was accepted, I'm closing this issue.
