### ISSUE TITLE
mi a2 load fail on mac

### ISSUE THREAD

**Issue by ilanbenb** [ubports/ubports-installer#1660]
**UBports Installer `0.8.2-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H15 NodeJS v12.16.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fde9ce042e3b000074c0a00
Log: *N/A*

.

**Comment by UniversalSuperBox** [comment]
Hi @ilanbenb, thanks for your report. Sorry it took so long to get back to you.

It appears that your device did not have its bootloader unlocked before you attempted to install Ubuntu Touch. Please unlock the device's bootloader and try the installation again.

I'll close this report for now, please open another one if you have trouble installing Ubuntu Touch again.
