### ISSUE TITLE
[trlte] Galaxy note 4. Can't load or flash through heidmall

### ISSUE THREAD

**Issue by tchantchan** [ubports/ubports-installer#1662]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Famille 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.16.3`
Device: trlte
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fe0942042e3b000074c0ead
Log: https://paste.ubuntu.com/p/d2TQMMNmyh/

try to install UT to TRTLE, the phone turn automaticly in fastboot mode but it can't flash througn heidmall. I had "Odin flash tool" on the computer and I tried to remove it to avoid conflict. I remove ADB also, all those tools does work inside the installer?
Sorry, this Windows computer is not mine. I only have Raspberry since my laptop died.

**Comment by NeoTheThird** [comment]
The installer comes with its own adb and heimdall (a re-implementation of odin). Looking at your log, i see heimdall is crashing with exit code `3221225781`, which might indicate a missing library. You could try running the installer from source (https://github.com/ubports/ubports-installer#set-up-for-development) on your raspberry pi.

**Comment by tchantchan** [comment]
Hi,
Thanks for answer, unfortunatly i can't do it through the raspberry as well,no worries
Thanks for the amazing job of Ubports.
