### ISSUE TITLE
Wipe data + devel version does not install

### ISSUE THREAD

**Issue by julianverweij** [ubports/ubports-installer#1669]
**UBports Installer `0.8.2-beta` (dir)**
Environment: `Arch Linux unknown linux 5.9.14-arch1-1 x64 rolling NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fe28bcd42e3b000074c1356
Log: https://paste.ubuntu.com/p/RcGQGgWZDN/

It says that the device was disconnected.

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
