### ISSUE TITLE
Uncaught Error: [20544:20591:0327/111738.084832:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process. (MainRenderer:39)

### ISSUE THREAD

**Issue by andreacazzola90** [ubports/ubports-installer#167]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/jjftyzPcGX/

**Comment by NeoTheThird** [comment]
If the getprop from the log is correct, you're installing on a Lenovo device? That won't work. See http://ubuntu-touch.io/devices for a list of supported devices.

For the GPU process error, could you try running `export BROWSER=google-chrome` before starting the installer?

**Comment by NeoTheThird** [comment]
Any news @andreacazzola90?

**Comment by NeoTheThird** [comment]
Please try again with [the latest release](https://github.com/ubports/ubports-installer/releases/latest).
