### ISSUE TITLE
Contributing config file. 

### ISSUE THREAD

**Issue by Ritvik-Sapra** [ubports/ubports-installer#1670]
I have quite a variety of phones lying around in my house and I think it will be good to contribute their config file. But I wasn't clear how. Maybe someone can help me?

**Comment by NeoTheThird** [comment]
We'd welcome your contributions. Config files can be found in [this repository](https://github.com/ubports/installer-configs). Check out the other devices' configs in the `v2` directory to get an idea. You can also look at the schema definition there.
