### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by l-4-l** [ubports/ubports-installer#1676]
**UBports Installer `0.8.2-beta` (deb)**
Environment: `Ubuntu 16.04.7 LTS Xenial Xerus linux 4.4.0-197-generic x64 NodeJS v12.16.3`
Device: deb
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fe4ebb505dd950007fc5328
Log: *N/A*

1st try: half-failed (stopped at UBPortsRecovery); @ retry: No space left on device (in logs)

**Comment by l-4-l** [comment]
I've finally installed Ubuntu Touch on Nexus 7 (deb) manually, without installer.
Problem 1:
cache partition size was ~70 Mb. I have used [parted](https://iwf1.com/iwf-repo/parted.rar) to get the list of partitions:  
```
22      614429696B   2187293695B   1572864000B   ext4         system
23      2187293696B  2263875583B   76581888B     ext4         cache
```
then basically played with `parted` to delete the partition `cache` and used part of a `userdata` as a new `cache`.

Because 400 Mb was still not enough to copy all .tar.xz-files, I have edited `ubuntu_command` file two times and restarted Nexus7 in recovery 2 times. First run (with image-master* , image-signing* ):
```
format system
load_keyring image-master.tar.xz image-master.tar.xz.asc
load_keyring image-signing.tar.xz image-signing.tar.xz.asc
mount system
format data
update ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc
unmount system
```
Second run (with files device*, keyring*, version*):
```
mount system
update device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz.asc
update keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc
update version-13.tar.xz version-13.tar.xz.asc
unmount system
```
After that it worked.

I suppose the Installer needs some smart way to check and resize

**Comment by NeoTheThird** [comment]
Thank you for the detailed writeup. Looks like #1089.
