### ISSUE TITLE
Tried to install ubuntu touch, stuck in a loop with "rebooting to recovery" and the device showing I could sideload from adb or install from local storage, I went to advanced and rebooted to recovery again but it brought the same menu. 

### ISSUE THREAD

**Issue by aibaron** [ubports/ubports-installer#1677]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fe5209405dd950007fc53a4
Log: *N/A*

I just followed the directions.

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
