### ISSUE TITLE
No success

### ISSUE THREAD

**Issue by fiixaphone** [ubports/ubports-installer#1679]
**UBports Installer `0.8.2-beta` (dmg)**
Environment: `Mac OS X 10.15.2 macOS Catalina darwin 19.2.0 x64 19C57 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fe7738b05dd950007fc58ab
Log: *N/A*

after flash complet reboot and got  to again recovery mode

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
