### ISSUE TITLE
Installs but never loads. The loading screen flickers.

### ISSUE THREAD

**Issue by AlexDumi29** [ubports/ubports-installer#1681]
**UBports Installer `0.8.2-beta` (deb)**
Environment: `Pop 20.10 groovy linux 5.9.15-xanmod1 x64 NodeJS v12.16.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fea3d3905dd950007fc5f34
Log: *N/A*

I installed jasmine_sprout_stock_android9 through twrp 3.3.1-0. Rebooted to bootloader and installed.

**Comment by NeoTheThird** [comment]
The device introduced itself as `jasmine`. Is that the same as `jasmine_sprout`?

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
