### ISSUE TITLE
Boots to UBports Recovery

### ISSUE THREAD

**Issue by 7evin** [ubports/ubports-installer#1682]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Home N 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fea600005dd950007fc5f70
Log: *N/A*

Failed to install using several older versions of the installer. Just before showing UBports Recovery, it flashes a red hexagon with an IC inside it very quickly.

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
