### ISSUE TITLE
stuck on preparing system-image screen

### ISSUE THREAD

**Issue by LukasqoSVK** [ubports/ubports-installer#1684]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5feb4def05dd950007fc615e
Log: https://paste.ubuntu.com/p/35JYRWxzWR/

I dont really know

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
