### ISSUE TITLE
htc one

### ISSUE THREAD

**Issue by manymenrise** [ubports/ubports-installer#1686]
**UBports Installer `0.8.2-beta` (deb)**
Environment: `LinuxMint 4 debbie linux 4.19.0-13-amd64 x64 NodeJS v12.16.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5febc7b105dd950007fc62a4
Log: *N/A*

failed to flash

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
