### ISSUE TITLE
Automatic Detection of device didn't work with FP2

### ISSUE THREAD

**Issue by LazLit0** [ubports/ubports-installer#1691]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 7 Professional 6.1.7601 win32 6.1.7601 x64 7601 1.0 NodeJS v12.16.3`
Device: FP2
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

On my operating system with ubport 0.8.2 the autodetection failed for Fairphone 2. After selecting it manually it worked all fine. I used  ABD Driver Installer. The other ADB didn't worked on my system. Produced an error.

**Comment by NeoTheThird** [comment]
Thanks for reporting. With windows 7 going eol in almost a year ago (https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information), i guess we don't really need to do something about this any more. Apparently windows 10 now ships working drivers ootb, so we'll probably end up removing the prompt altogether (#1708). thanks for reporting and good luck with your migration
