### ISSUE TITLE
It looks like it installed, but it is stuck on the google screen.

### ISSUE THREAD

**Issue by Just-Seb** [ubports/ubports-installer#1692]
**UBports Installer `0.8.2-beta` (deb)**
Environment: `Pop 20.10 groovy linux 5.8.0-7630-generic x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

This may be my own devices issue but I am not sure. The device was working before hand.

**Comment by NeoTheThird** [comment]
Unfortunately there's no log here. Could you try running the installer again and report a new issue if the it happens again?
