### ISSUE TITLE
looked like everything was going ok...but won't boot

### ISSUE THREAD

**Issue by nathanh1-1** [ubports/ubports-installer#1693]
**UBports Installer `0.8.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.9.16-200.fc33.x86_64 x64 NodeJS v12.16.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

I don't know. This thing does everything for you. it said it successfully ported. This was Pixel 3a Android 9 (sargo).

**Comment by NeoTheThird** [comment]
Unfortunately your report does not contain a log. Could you just try running the installer again and see if it works the second time around? If you run into the same issue, please report it again and we'll try to help ya.
