### ISSUE TITLE
stuck on boot loop

### ISSUE THREAD

**Issue by GauravXs** [ubports/ubports-installer#1694]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Home Single Language 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: santoni (redmi 4x)
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

just show

**Comment by NeoTheThird** [comment]
Try running the installer again. If you run into the same issue, please report it again, because this one's missing logs.
