### ISSUE TITLE
Installer stop working ADB

### ISSUE THREAD

**Issue by mesofranico** [ubports/ubports-installer#1695]
**UBports Installer `0.8.2-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.16.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: https://paste.ubuntu.com/p/sNsdqMwG8x/

ADB problem AMD cpu

**Comment by NeoTheThird** [comment]
#1594
