### ISSUE TITLE
ubports start with error and it doesn't work. what must i do

### ISSUE THREAD

**Issue by makombelajob** [ubports/ubports-installer#1698]
**UBports Installer `0.8.2-beta` (snap)**
Environment: `MX 20 patito feo linux 4.19.0-13-amd64 x64 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

This is the error log
"Error: unhandled rejection at [object Promise]: Error: {"error":{"code":255,"cmd":"adb -P 5037 start-server"},"stderr":"* daemon not running; starting now at tcp:5037\nADB server didn't ACK\nFull server startup log: /tmp/adb.1000.log\nServer had pid: 21958\n--- adb starting (pid 21958) ---\nadb I 01-04 03:01:27 21958 21958 main.cpp:62] Android Debug Bridge version 1.0.41\nadb I 01-04 03:01:27 21958 21958 main.cpp:62] Version 30.0.4-6686687\nadb I 01-04 03:01:27 21958 21958 main.cpp:62] Installed as adb\nadb I 01-04 03:01:27 21958 21958 main.cpp:62] \nadb F 01-04 03:01:28 21956 21956 main.cpp:153] could not install *smartsocket* listener: Operation not permitted\nadb F 01-04 03:01:28 21958 21958 main.cpp:153] could not install *smartsocket* listener: Operation not permitted\n\n* failed to start daemon\nerror: cannot connect to daemon"}
How can i solve it?

**Comment by NeoTheThird** [comment]
Try closing and re-opening the installer.
