### ISSUE TITLE
Redmi 4X stuck in bootloop 

### ISSUE THREAD

**Issue by suriyaprasanths** [ubports/ubports-installer#1706]
**UBports Installer `0.8.3-beta` (exe)**
Environment: `Microsoft Windows 10 Pro N 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ff6e3a5203a7f0007645513
Log: *N/A*

Error: unhandled rejection at [object Promise]: Error: {"error":{"code":4294967295,"cmd":"C:\\Users\\suri\\AppData\\Local\\Temp\\1mh11UV943ySIxyU7RPFgFiB4W8\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 start-server"},"stderr":"* daemon not running; starting now at tcp:5037\r\ncould not read ok from ADB Server\r\n* failed to start daemon\r\nerror: cannot connect to daemon"}

**Comment by NeoTheThird** [comment]
Sorry about that. try closing the installer and re-opening it.
