### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by VictorSproot** [ubports/ubports-installer#1707]
*Automatically generated error report* 
UBports Installer Version: 0.4.18-beta 
Device: Not detected
OS to install: Not yet set
Settings: {}
Package: dir
Operating System: Manjaro Linux 20.2.1 nibia x64 
NodeJS version: v12.18.3 

Error log: https://paste.ubuntu.com//p/HTnMFw2r7W/

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
