### ISSUE TITLE
show "update failed, contact support" on phone screen

### ISSUE THREAD

**Issue by QuectelOpen** [ubports/ubports-installer#1709]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 רҵ�� 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.18.3`
Device: turbo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ff7d1f0203a7f0007645730
Log: https://paste.ubuntu.com/p/mT9SdJSsZg/

follow the step to work

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
