### ISSUE TITLE
Snap installer on Solus doesn't see the phone

### ISSUE THREAD

**Issue by fw190d13** [ubports/ubports-installer#171]
Hi!

Operating system: Solus with latest updates
The system is able to see the phone as fastboot properly shows the device. I can also push TWRP on the phone from Solus.

The snap Ubports installer doesn't recognize the phone at all. It's in the bootloader mode, I have tried to plug it again, manually discover but no luck.

**Comment by gsilvapt** [comment]
After plugging the device can you test the `adb devices` command and report back what you got?

**Comment by fw190d13** [comment]
When the phone is turned on and booted into Ubuntu Touch I get:
``fw190@wurger ~ $ adb devices
List of devices attached
078eb0e50189bcbf	device

**Comment by NeoTheThird** [comment]
I know Ikey is pretty excited about snaps, so but just to make sure this isn't the problem: Does Solus do a) automatic refreshes and b) automatic connection of plugs?

a) Please run `snap info ubports-installer` and check if you're on the latest version. If not, run `snap refresh`.

b) Run `snap interfaces :raw-usb` to check if the UBports Installer is listed there. If not, please run `snap connect ubports-installer:raw-usb`.

**Comment by fw190d13** [comment]
`fw190@wurger ~ $ snap info ubports-installer
name:      ubports-installer
summary:   The easy way to install Ubuntu Touch on UBports devices.
publisher: mariogrip
contact:   https://github.com/ubports/ubports-installer/issues/new
description: |
  A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported
  device to your PC, follow the on-screen instructions and watch this awesome
  tool do all the rest. The snap can run in strict confinement, but you will
  have to run `sudo snap connect ubports-installer:raw-usb` before using it.
snap-id: mq0sTMV7a8744UTRBwQHimStAqsGzbjj
commands:
  - ubports-installer
tracking:    beta
installed:   0.1.11-beta (52) 106MB -
refreshed:   2018-02-28 20:32:43 +0100 CET
channels:                      
  stable:    0.1.12-beta (74)  104MB -
  candidate: 0.1.12-beta (100) 105MB -
  beta:      0.1.12-beta (100) 105MB -
  edge:      0.1.12-beta (100) 105MB -
fw190@wurger ~ $ snap refresh
All snaps up to date.
fw190@wurger ~ $ snap interfaces :raw-usb
Slot      Plug
:raw-usb  -
-         ubports-installer:raw-usb
fw190@wurger ~ $ snap refresh --list
All snaps up to date.
fw190@wurger ~ $ 
`

**Comment by fw190d13** [comment]
Refresh didn't want to update the package so I have removed it manually. Still fastboot detects the device but the installer doesn't see it.

**Comment by NeoTheThird** [comment]
It looks like the Installer has a problem w/ TWRP (#52). Could you install the factory rom and try again?
