### ISSUE TITLE
downloaded volla-*.zip is not automatically unzipped, had to unzip it manually

### ISSUE THREAD

**Issue by tbuen** [ubports/ubports-installer#1712]
**UBports Installer `0.8.2-beta` (dir)**
Environment: `Arch rolling linux 5.10.5-arch1-1 x64 rolling NodeJS v12.18.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ff9b6a5203a7f0007645b67
Log: https://paste.ubuntu.com/p/XG8VnStvHw/

**Comment by tbuen** [comment]
probably the same as #1620

**Comment by poetaster** [comment]
I'm not sure if this is relavent, but as I understand it, flashing is done via a sideload of the .zip with twrp? In my case, the zip is also not unpacked and flashing doesn't appear to work. same problem with sailfish. ubuntu works fine.
