### ISSUE TITLE
Impossible to install UT on Nexus 4 mako.

### ISSUE THREAD

**Issue by lool-lauris** [ubports/ubports-installer#1716]
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-59-generic x64 NodeJS v12.18.3`
Device: mako
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ffb2d4e203a7f0007645f19
Log: *N/A*

This device is under Android 10 [LineageOS 17](https://forum.xda-developers.com/t/rom-unofficial-lineageos-16-0-17-1-mako.3758779/) installed through TRWP recovery (twrp-3.3.1-0-mako).

Here after the error message given by UBports Installer :
`Error: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy '/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 6.7 MB/s (392330372 bytes in 55.756s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 4.4 MB/s (473 bytes in 0.000s)\nadb: error: failed to copy '/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz' to '/cache/recovery/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz': remote No space left on device\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz: 1 file pushed, 0 skipped. 6.6 MB/s (71505616 bytes in 10.398s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/device-72a91d077d15b973052cfff546d7d0a94b8bf38376c7a688a8e0754c1a468aca.tar.xz.asc: 1 file pushed, 0 skipped. 5.9 MB/s (473 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 27.9 MB/s (1504 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 8.7 MB/s (473 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/version-13.tar.xz: 1 file pushed, 0 skipped. 8.6 MB/s (460 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/pool/version-13.tar.xz.asc: 1 file pushed, 0 skipped. 9.5 MB/s (473 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/gpg/image-signing.tar.xz: 1 file pushed, 0 skipped. 17.8 MB/s (900 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/gpg/image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 6.3 MB/s (473 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/gpg/image-master.tar.xz: 1 file pushed, 0 skipped. 11.3 MB/s (864 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/gpg/image-master.tar.xz.asc: 1 file pushed, 0 skipped. 7.0 MB/s (473 bytes in 0.000s)\n/home/lool/snap/ubports-installer/334/.cache/ubports/system-image/ubuntu_command: 1 file pushed, 0 skipped. 10.8 MB/s (728 bytes in 0.000s)\n13 files pushed, 0 skipped. 6.7 MB/s (463843282 bytes in 66.457s)"}
`

**Comment by lool-lauris** [comment]
Nobody has any idea to solve this issue ?

**Comment by undone666** [comment]
hey, you need repartition to stock settings

**Comment by lool-lauris** [comment]
Thank you for the answer.
Do you have more precise indications?

**Comment by undone666** [comment]
https://forum.xda-developers.com/t/repartition-nexus-4-repartition-mako-8gb-16gb-ua-twrp.3844383/  <--- flash zip from here, follow the instruction and should be good

**Comment by lool-lauris** [comment]
Thanks !
