### ISSUE TITLE
Pressed download on update notification and instantly said failed to update

### ISSUE THREAD

**Issue by AvdonR** [ubports/ubports-installer#1717]
**UBports Installer `0.8.2-beta` (dmg)**
Environment: `macOS 11.1 macOS darwin 20.2.0 x64 20C69 NodeJS v12.16.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ffcc0c1203a7f00076462e4
Log: https://paste.ubuntu.com/p/bVzTFZR7cy/

Press download on the notification that pops up when you open the app. Happens on every launch.

"Error: uncaught exception at uncaughtException: ReferenceError: shell is not defined"

https://user-images.githubusercontent.com/10875325/104239825-1fde8080-5429-11eb-95ca-6332f5eded23.mov

**Comment by AvdonR** [comment]
Update: duplicate issue.

**Comment by stephiemtz12** [comment]
``

**Comment by stephiemtz12** [comment]
Descansa
