### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by Donieck** [ubports/ubports-installer#172]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/KNJmdfD3Km/

**Comment by gsilvapt** [comment]
Judging by the log, I'd say there was a failure while pushing and this can be many things, including cable instability. Have you tried again?

**Comment by NeoTheThird** [comment]
Thanks for reporting. I'd say this looks like #207.
