### ISSUE TITLE
phone navigation buttons are not working

### ISSUE THREAD

**Issue by jj-gh-ta** [ubports/ubports-installer#1721]
**UBports Installer `0.8.4-beta` (AppImage)**
Environment: `Ubuntu 20.04.1 LTS Focal Fossa linux 5.8.0-36-generic x64 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ffdb894203a7f000764650e
Log: https://paste.ubuntu.com/p/4K695zcbDb/

install ubuntu touch in Redmi 4X device

**Comment by jj-gh-ta** [comment]
after install ubuntu touch the phone's navigation buttons are not working.

**Comment by Danct12** [comment]
Ubuntu Touch does not use navigation buttons, everything is gesture-based.
