### ISSUE TITLE
Starting UBPorts installer gives an error

### ISSUE THREAD

**Issue by YugiFanGX** [ubports/ubports-installer#1722]
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 4.19.0-11-amd64 x64 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5ffdd061203a7f000764654e

Log: 

Error: unhandled rejection at [object Promise]: Error: {"error":{"code":255,"cmd":"adb -P 5037 start-server"},"stderr":"* daemon not running; starting now at tcp:5037\nADB server didn't ACK\nFull server startup log: /tmp/adb.1000.log\nServer had pid: 13445\n--- adb starting (pid 13445) ---\nadb I 01-12 17:39:19 13445 13445 main.cpp:62] Android Debug Bridge version 1.0.41\nadb I 01-12 17:39:19 13445 13445 main.cpp:62] Version 30.0.4-6686687\nadb I 01-12 17:39:19 13445 13445 main.cpp:62] Installed as adb\nadb I 01-12 17:39:19 13445 13445 main.cpp:62] \n--- adb starting (pid 13451) ---\nadb I 01-12 17:39:19 13451 13451 main.cpp:62] Android Debug Bridge version 1.0.41\nadb I 01-12 17:39:19 13451 13451 main.cpp:62] Version 30.0.4-6686687\nadb I 01-12 17:39:19 13451 13451 main.cpp:62] Installed as adb\nadb I 01-12 17:39:19 13451 13451 main.cpp:62] \nadb F 01-12 17:39:19 13445 13445 main.cpp:153] could not install *smartsocket* listener: Operation not permitted\n\n* failed to start daemon\nerror: cannot connect to daemon"}

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer?
