### ISSUE TITLE
After sailfish installation stuck on the splash screen (power button toggles display on and off)

### ISSUE THREAD

**Issue by redrezo** [ubports/ubports-installer#1726]
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.3.16-300.fc31.x86_64 x64 NodeJS v12.18.3`
Device: yggdrasil
Target OS: SailfishOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/5fff10cf203a7f000764682e
Log: https://paste.ubuntu.com/p/t4Rbbn7s8p/

installed on a new vollaphone with ubuntu touch preinstalled
Result:
phone boots with new splash logo (at bottom sailfish os)
after a while display switches off (power button allows to toggle display on and off)
only splash logo is shown..

**Comment by iggy-x** [comment]
I solved the problem by installing the VollaOS first and installed sailfish. The saifish flashing worked out with version 0.8.4-beta with linux mint.  The tip cam from Telegram Volla Group. The ubports flasher should show that way

**Comment by b15h0y** [comment]
I am facing the same exact issue. @iggy-x  can you please illustrate more why did you install VollaOS first? can you also share the telegram group of Volla Group?
