### ISSUE TITLE
Problems with file distribution and checksum of vendor.img

### ISSUE THREAD

**Issue by deakus** [ubports/ubports-installer#1730]
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-36-generic x64 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/600203da203a7f0007646f0d
Log: *N/A*

Just run in the installer and follow the browser that opens to perform the manual install. it takes a very long time for andriodhost to appear, Once the vendor file is download and unzipped , it complains about a checksum mismatch. Just keep clicking retry then out of the blue the installer will continue with no problems the

**Comment by ix5** [comment]
@deakus  please see whether https://github.com/ubports/ubports-installer/pull/1786 fixes your issue

**Comment by NeoTheThird** [comment]
not reproducible for me any more with @ix5's fix
