### ISSUE TITLE
Not enough storage even with partition

### ISSUE THREAD

**Issue by saurjk** [ubports/ubports-installer#1738]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6005c1b1203a7f00076477cf
Log: *N/A*

Installing ubports on Nexus 5 with UB Ports Installer

**Comment by cr1za** [comment]
Did you manage to fix this?

**Comment by saurjk** [comment]
Yea, with the following link:

https://forum.xda-developers.com/t/rom-unofficial-lineageos-16-0-for-nexus-5.3921162/post-79928889

I forgot if you had to increase size or revert the resize. But it's one of the two.
