### ISSUE TITLE
bootloops into recovery

### ISSUE THREAD

**Issue by ngudger2021** [ubports/ubports-installer#1739]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6005fb86203a7f000764786e
Log: *N/A*

NA

**Comment by NeoTheThird** [comment]
Sorry about that, duplicate of #1537
