### ISSUE TITLE
Ubports Installer (0.84-beta) failed to install Ubuntu Touch on Nexus 5

### ISSUE THREAD

**Issue by hide-from-Mike** [ubports/ubports-installer#1740]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6006f82f203a7f0007647ae8
Log: https://paste.ubuntu.com/p/CHGmSCvVFY/

Recieved the following errors: 

Error: preparing: TypeError: Cannot read property 'codename' of null . 

And at other times: 

Error: uncaught exception at uncaughtException: TypeError: Cannot read property 'condition' of undefined

Not sure what to do, and good advice helps and will be well appreciated.

Thanks

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
