### ISSUE TITLE
Unable to install Ubuntu Touch on Nexus 5 Hammerhead (Unlocked)

### ISSUE THREAD

**Issue by shsugat** [ubports/ubports-installer#1744]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro N 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/600a99a9203a7f000764837b
Log: *N/A*

Mobile reboots and remains in recovery state and UBports shows flashing firmware

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
