### ISSUE TITLE
Sony Xperia X reports checksum error of image file in ubports installer 0.8.4

### ISSUE THREAD

**Issue by josemic** [ubports/ubports-installer#1754]
I have tried to install my Sony Xperia X with ubports installer version 0.8.4.
The installer requested to download the image file from the sony web page. I did this. 
However the installer claimed that the image file has the wrong checksum. I have tested this with the zipped image file as downloaded from the sony web page as well as with the unzipped image file. 
In both cases I got a checksum error. See screenshot.

Please check the checksum calculation in ubports installer version 0.8.4.
Please also clarify, if the unzipped image file or the zipped image file is needed for the manual download.
![ubports_installer_with_XperiaX_manual_download_error](https://user-images.githubusercontent.com/803745/105675339-456b8f80-5ee9-11eb-8950-b88e0de3fe93.png)

Note:
After this failed, I took a previous ubports installer version 0.7.4 I still had on my computer. This seemed to download the file by itself and install ubuntu touch on my Xperia X flawlessly.

This was tested on the Linux distributions KDE Neon (based on Ubuntu 20.04 kernel) and Ubuntu 20.04.

**Comment by ix5** [comment]
Can confirm the issue with kagura as well. See [OPEN-CUTS report](https://ubports.open-cuts.org/run/601d89b2afa951000786dce8).

I've done another run with the `checkFile()` step commented out, but then the installer reports a failure at the "unpack" step: [OPEN-CUTS report](https://ubports.open-cuts.org/run/601d8b14afa951000786dcf0).

The failure occurs here:
https://github.com/ubports/ubports-installer/blob/95745e519351adc3189e7e285a553bc6c1e5100a/src/core/plugins/core/plugin.js#L220-L233

...which resolves to the `progressive-downloader` module from [gitlab.com/ubports/installer/progressive-downloader-node](https://gitlab.com/ubports/installer/progressive-downloader-node/-/blob/f9c12ab2102ccc4a393999cafd3d7cd46c7b187f/src/module.js#L51-66) in version `^1.0.6`.

The reported error can be ignored as `~/.cache/ubports/<device>/firmware/SW_Binaries_*.zip` and `~/.cache/ubports/<device>/firmware/unpackged/SW_Binaries_*.img` are generated/extracted.

Possibly related: https://github.com/ubports/ubports-installer/issues/1730

**Comment by ix5** [comment]
Upon further inspection, the `checkFile()` is not the culprit, rather `fs.copyFile()` fulfilling its promise prematurely. When `checkFile()` is called, the file has not actually been copied on-disk yet and `checkFile()` rightfully fails.
Same goes for skipping the verification step as I had tried out, of course the unpack step attemps to unpack a non-existent file and fails with `-2`.

Adding an artificial delay after https://github.com/ubports/ubports-installer/blob/95745e519351adc3189e7e285a553bc6c1e5100a/src/core/plugins/core/plugin.js#L209-L219

like this:
```
            // sleep for 100ms to ensure fs.copyFile() is *really* finished
            .then(() => {
              return new Promise(resolve => setTimeout(resolve, 100));
            })
```
does "fix" things.

I'm more interested in getting the `copyFile()` operation to only return once it's _really_ finished.
