### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\mihai\AppData\Roaming\ubports\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by mihaiv95** [ubports/ubports-installer#176]
![image](https://user-images.githubusercontent.com/33013698/38084993-99b393aa-3357-11e8-9671-f53cf8e43a02.png)

[ubports-installer.log](https://github.com/ubports/ubports-installer/files/1859785/ubports-installer.log)

**Comment by gsilvapt** [comment]
that's more useful. This is very closely related with #110, maybe even a duplicate.
