### ISSUE TITLE
Installer display "Success" , no error, but always android 

### ISSUE THREAD

**Issue by libermax** [ubports/ubports-installer#1769]
OPO3T with android7, bootloader unlocked, developer mode ok, USB debugging ok
PC, live USB Ubuntu 20.04, adb devices ok, fastboot devices ok
UBports Installer version 0.8.4-beta

Then in a terminal :

``
ubuntu@ubuntu:~$ sudo adb reboot bootloader
ubuntu@ubuntu:~$ sudo ubports-installer
info: Welcome to the UBports Installer version 0.8.4-beta!
info: device detected: oneplus3
info: Installing Ubuntu Touch on your Oneplus 3/3T (oneplus3)
info: configuring...
info: settings: {"channel":"16.04/arm64/hybris/stable","wipe":true,"bootstrap":true}
warn: undefined
info: All done! Your device will now reboot and complete the installation. Enjoy exploring Ubuntu Touch!
info: Good bye!
``
No error, just "warn: undefined"
Problem, the device don't reboot and when reboot is forced, the OPO3T boot under android.

Edit: In fact, an error was output, not in the terminal but on the screen of the OPO3T:
`E:failed` to read `/fstab.unknow`

So it's seems, it's somehow similar to: https://github.com/ubports/ubports-installer/issues/1674

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
