### ISSUE TITLE
Uncaught Error: [4612:4612:0329/185209.872124:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.[4612:4635:0329/185214.692168:ERROR:sandbox_ipc_linux.cc(447)] sendmsg: Brutet rör (32) (MainRenderer:39)

### ISSUE THREAD

**Issue by jetson53** [ubports/ubports-installer#177]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Linux Mint undefined
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/26pTbbKyJ9/

**Comment by NeoTheThird** [comment]
Should be fixed in the next release by #160.
