### ISSUE TITLE
Installation went good but booting....

### ISSUE THREAD

**Issue by emgi2** [ubports/ubports-installer#1770]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/601699f9afa951000786cc11
Log: *N/A*

Screen is flickering. For 2 seconds there is ubuntu touch logo and 10 seconds is black screen and it is like that in loop.

**Comment by aposster** [comment]
exactly the same problem here as with emgi2
Environment Windows 10 Pro x64
Device: Xiaomi Redmi 4x
