### ISSUE TITLE
Stuck on preparing system image

### ISSUE THREAD

**Issue by RussellHowell** [ubports/ubports-installer#1778]
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-38-generic x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/601b1569afa951000786d6f6
Log: *N/A*

Not sure

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
