### ISSUE TITLE
Adb push error: error: device not found

### ISSUE THREAD

**Issue by shaolinfrequenz** [ubports/ubports-installer#178]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/ryZ8qGFNfg/

**Comment by gsilvapt** [comment]
@shaolinfrequenz Thanks for reporting. Judging by the log, it seems adb was not able to find the device. Do you think you could try installing again? If this was not a first-time error, can you run `adb devices` and confirm if adb finds your device?

**Comment by NeoTheThird** [comment]
Please make sure you use the latest version, that is 0.1.12-beta.
