### ISSUE TITLE
Out of space error copying files to device

### ISSUE THREAD

**Issue by a8ksh4** [ubports/ubports-installer#1780]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.18.3`
Device: deb
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/601c826bafa951000786da6c
Log: *N/A*

Having trouble flashing n7 2013 lte..   will factory reset and restart.  
I'm not really sure... just try to flash a nexus 7 2013?  Maybe issue is that it was faling on stable branch and I just tried switching to rc branch.

**Comment by a8ksh4** [comment]
Immediately after reboot into ubports recovery, the windows app shows error:
Error: adb:format: Error: failed to format system: Error: failed to mount: mount: mounting /dev/block/platform/msm_sdcc.1/by-name/system on /system failed: Device or resource busy

Try again seems to fix this.

**Comment by a8ksh4** [comment]
Next is this error:

Error: systemimage:install: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy 'C:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz' to '/cache/recovery/ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz': remote No space left on device\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz: 1 file pushed, 0 skipped. 3.4 MB/s (392330372 bytes in 110.866s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\ubports-f4b4ca04e60c334391a9a105918e8701bdba53310cdce6f2cfd63798d8d89c4a.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz: 1 file pushed, 0 skipped. 3.4 MB/s (64505972 bytes in 18.267s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\device-6815e29fb004d6e703a0b0dac95ae76c6994e5c6166adc6dec5bebac4c0b5b90.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz: 1 file pushed, 0 skipped. 4.2 MB/s (1504 bytes in 0.000s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc: 1 file pushed, 0 skipped. 0.2 MB/s (473 bytes in 0.002s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\version-13.tar.xz: 1 file pushed, 0 skipped. 1.2 MB/s (460 bytes in 0.000s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\pool\\version-13.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (473 bytes in 0.001s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz: 1 file pushed, 0 skipped. 0.5 MB/s (900 bytes in 0.002s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 0.2 MB/s (473 bytes in 0.003s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz: 1 file pushed, 0 skipped. 0.4 MB/s (864 bytes in 0.002s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\gpg\\image-master.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (473 bytes in 0.002s)\r\nC:\\Users\\drnorris\\AppData\\Roaming\\ubports\\system-image\\ubuntu_command: 1 file pushed, 0 skipped. 0.0 MB/s (716 bytes in 0.016s)\r\n13 files pushed, 0 skipped. 3.3 MB/s (456843626 bytes in 131.743s)"}

**Comment by a8ksh4** [comment]
issue was that I had repartitioned for newer android on the tablet and had to revert the parittion layout before install here.  All good now.

**Comment by turbolent** [comment]
@a8ksh4 How did you revert the partition layout?
