### ISSUE TITLE
couldnt get installer to work on linux mint or windows, kept saying device disconnected. used a live usb of ubuntu

### ISSUE THREAD

**Issue by jrueamg** [ubports/ubports-installer#1783]
**UBports Installer `0.8.4-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-41-generic x64 NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/601d9201afa951000786dd0c
Log: https://paste.ubuntu.com/p/nRyV4CVc95/

windows machine and oneplus3 with everything wiped in twrp

**Comment by jrueamg** [comment]
it worked usin installer on ubuntu

**Comment by geeky-neo** [comment]
UT installation on OnePlus 3T is failing on Ubuntu 20.04 installed on a hardware.
Installer versions tried are 0.8.4 & 0.8.8.

`{"level":"info","message":"Downloaded file 1 of 12"}
{"level":"info","message":"Downloaded file 2 of 12"}
{"level":"info","message":"Downloaded file 3 of 12"}
{"level":"info","message":"Downloaded file 4 of 12"}
{"level":"info","message":"Downloaded file 5 of 12"}
{"level":"info","message":"Downloaded file 6 of 12"}
{"level":"info","message":"Downloaded file 7 of 12"}
{"level":"info","message":"Downloaded file 8 of 12"}
{"level":"info","message":"Downloaded file 9 of 12"}
{"level":"info","message":"Downloaded file 10 of 12"}
{"level":"info","message":"Downloaded file 11 of 12"}
{"level":"info","message":"Downloaded file 12 of 12"}
{"level":"verbose","message":"running core action write"}
{"level":"verbose","message":"running adb action wait"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"wait-for-any-any\"]}"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"get-state\"],\"stdout\":\"recovery\"}"}
{"level":"verbose","message":"running adb action preparesystemimage"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"shell\",\"mount -a\"],\"error\":{\"message\":\"Command failed: adb -P 5037 shell mount -a\\nmount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument\",\"code\":1},\"stderr\":\"mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument\"}"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"shell\",\"cat /etc/recovery.fstab\"],\"stdout\":\"# Android fstab file.\\n# The filesystem that contains the filesystem checker binary (typically /system) cannot\\n# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK\\n\\n#TODO: Add 'check' as fs_mgr_flags with data partition.\\n# Currently we dont have e2fsck compiled. So fs check would failed.\\n\\n#<src>                                                       <mnt_point>       <type>  <mnt_flags and options>                                                                                         <fs_mgr_flags>\\n/dev/block/bootdevice/by-name/boot                           /boot             emmc    defaults                                                                                                        defaults\\n/dev/block/bootdevice/by-name/recovery                       /recovery         emmc    defaults                                                                                                        defaults\\n/dev/block/bootdevice/by-name/system                         /system           ext4    rw,barrier=1,discard                                                                                            wait\\n/dev/block/bootdevice/by-name/userdata                       /data             ext4    nosuid,nodev,noatime,barrier=1,noauto_da_alloc                                                                  wait,check,encryptable=footer,formattable,length=-16384\\n/dev/block/bootdevice/by-name/persist                        /persist          ext4    nosuid,nodev,barrier=1                                                                                          wait\\n/dev/block/bootdevice/by-name/dsp                            /dsp              ext4    ro,nosuid,nodev,barrier=1                                                                                       wait\\n/dev/block/bootdevice/by-name/modem                          /firmware         vfat    ro,shortname=lower,uid=1000,gid=1000,dmask=227,fmask=337                                                        wait\\n/dev/block/bootdevice/by-name/bluetooth                      /bt_firmware      vfat    ro,shortname=lower,uid=1002,gid=3002,dmask=222,fmask=333                                                        wait\\n/dev/block/bootdevice/by-name/misc                           /misc             emmc    defaults                                                                                                        defaults\\n/dev/block/bootdevice/by-name/logo                           /logo             emmc    defaults                                                                                                        defaults\\n\\n/devices/soc/6a00000.ssusb/6a00000.dwc3/xhci-hcd.0.auto/usb* auto              auto    defaults                                                                                                        voldmanaged=usbdisk:auto\"}"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"shell\",\"rm -rf /cache/*\"]}"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"shell\",\"mkdir -p /cache/recovery\"]}"}
{"level":"debug","message":"adb created /cache/recovery directory"}
{"level":"verbose","message":"running adb action push"}
{"level":"command","message":"spawn:start: {\"cmd\":[\"adb\",\"-P\",5037,\"push\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/ubports-b338720c09678eb1ab6ce28b4c8e6ea5be08911b7c65e743d770eebd1521c5e4.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/ubports-b338720c09678eb1ab6ce28b4c8e6ea5be08911b7c65e743d770eebd1521c5e4.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/device-762c2b584c58b5d2ff8f89917b0e4599cd054f74cbdfa37441bc6c9575112870.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/device-762c2b584c58b5d2ff8f89917b0e4599cd054f74cbdfa37441bc6c9575112870.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/version-6.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/version-6.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-signing.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-signing.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-master.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-master.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/ubuntu_command\",\"/cache/recovery/\"]}"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"shell\",\"mount\"],\"stdout\":\"rootfs on / type rootfs (rw,size=2838236k,nr_inodes=709559)\\ntmpfs on /dev type tmpfs (rw,nosuid,relatime,size=2918868k,nr_inodes=729717,mode=755)\\ndevpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)\\nproc on /proc type proc (rw,relatime,gid=3009,hidepid=2)\\nsysfs on /sys type sysfs (rw,relatime)\\ntmpfs on /tmp type tmpfs (rw,relatime,size=2918868k,nr_inodes=729717)\\ntmpfs on /storage type tmpfs (rw,relatime,size=2918868k,nr_inodes=729717,mode=050,gid=1028)\\npstore on /sys/fs/pstore type pstore (rw,relatime)\\nadb on /dev/usb-ffs/adb type functionfs (rw,relatime)\\n/dev/block/bootdevice/by-name/system on /system type ext4 (rw,relatime,discard,data=ordered)\\n/dev/block/bootdevice/by-name/persist on /persist type ext4 (rw,nosuid,nodev,relatime,data=ordered)\\n/dev/block/bootdevice/by-name/dsp on /dsp type ext4 (ro,nosuid,nodev,relatime,data=ordered)\\n/dev/block/bootdevice/by-name/modem on /firmware type vfat (ro,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro)\\n/dev/block/bootdevice/by-name/bluetooth on /bt_firmware type vfat (ro,relatime,uid=1002,gid=3002,fmask=0333,dmask=0222,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro)\\ntmpfs on /cache type tmpfs (rw,nosuid,nodev,noatime,size=262144k,nr_inodes=729717,mode=771,uid=1000,gid=1000)\"}"}
{"level":"warn"}
{"level":"command","message":"spawn:exit: {\"cmd\":[\"adb\",\"-P\",5037,\"push\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/ubports-b338720c09678eb1ab6ce28b4c8e6ea5be08911b7c65e743d770eebd1521c5e4.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/ubports-b338720c09678eb1ab6ce28b4c8e6ea5be08911b7c65e743d770eebd1521c5e4.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/device-762c2b584c58b5d2ff8f89917b0e4599cd054f74cbdfa37441bc6c9575112870.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/device-762c2b584c58b5d2ff8f89917b0e4599cd054f74cbdfa37441bc6c9575112870.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/version-6.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/version-6.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-signing.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-signing.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-master.tar.xz\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/image-master.tar.xz.asc\",\"/home/neo/.cache/ubports/oneplus3/Ubuntu Touch/ubuntu_command\",\"/cache/recovery/\"],\"code\":1}"}
{"level":"debug","message":"attempting to handle Error: no device"}
{"level":"warn","message":"lost connection to device"}
"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"wait-for-any-any\"]}"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"get-state\"],\"stdout\":\"recovery\"}"}
{"level":"verbose","message":"running adb action preparesystemimage"}
{"level":"command","message":"exec: {\"cmd\":[\"adb\",\"-P\",5037,\"shell\",\"mount -a\"],\"error\":{\"message\":\"Command failed: adb -P 5037 shell mount -a\\nmount: mounting 
`

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
