### ISSUE TITLE
Installing Volla after SFOS fails to boot to system. twrp boot loop.

### ISSUE THREAD

**Issue by poetaster** [ubports/ubports-installer#1800]
**UBports Installer `0.8.4-beta` (deb)**
Environment: `Ubuntu 18.04.5 LTS Bionic Beaver linux 4.15.0-135-lowlatency x64 NodeJS v12.18.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6028e261afa951000786f6b6
Log: https://paste.ubuntu.com/p/5gDWcJX3fb/

Install SFOS, then Volla

**Comment by poetaster** [comment]
After  second run, it succeeds...?

**Comment by poetaster** [comment]
This occured twice. Once after an SFOS install and once after an Ubuntu Touch install.

**Comment by JamiKettunen** [comment]
@poetaster After installing Sailfish OS, did you make sure to enable `Wipe personal data` when installing Ubuntu Touch? The Sailfish OS port is a bit special as it takes over the entire `userdata` partition of the device and creates an LVM managed root filesystem.

Before flashing VollaOS after Sailfish OS, could you check whether formatting userdata in TWRP before continuing onto sideloading fixes this? We could need a new checkbox for formatting userdata during VollaOS flashing as well.

**Comment by poetaster** [comment]
Thanks, that was the problem!
