### ISSUE TITLE
Every times worry at recovery 

### ISSUE THREAD

**Issue by xiangdongping999** [ubports/ubports-installer#1805]
**UBports Installer `0.8.4-beta` (deb)**
Environment: `LinuxMint 20.1 Ulyssa linux 5.8.0-43-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/602cefa3afa951000786ff81
Log: *N/A*

Mi6X (A2)

**Comment by UniversalSuperBox** [comment]
Hi @xiangdongping999,

When you tried to install Ubuntu Touch, the `stable` channel for the Mi A2 was not available. It is now, so you should be able to install Ubuntu Touch again.

The Installer should not offer empty channels, and this issue has been filed as https://github.com/ubports/ubports-installer/issues/1879
