### ISSUE TITLE
After installing Volla Phone Software and rebooting the phone does not start the system but boots twrp

### ISSUE THREAD

**Issue by dieterzakel** [ubports/ubports-installer#1810]
**UBports Installer `0.8.4-beta` (dmg)**
Environment: `macOS 11.2.1 macOS darwin 20.3.0 x64 20D74 NodeJS v12.18.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6036c08cc439bc00076f409c
Log: https://paste.ubuntu.com/p/WzBsHdKjBw/

install volla phone softzware

**Comment by JamiKettunen** [comment]
@dieterzakel Hello, which OS did you have installed before attempting to install VollaOS? If it was Sailfish OS, you likely have to wipe (format) `userdata` manually in TWRP before continuing to sideloading as per the installer instructions.

Let me know if this helps. We might need a new checkbox (much like `Wipe personal data` currently present for Ubuntu Touch option) to allow doing this step automatically.

**Comment by dieterzakel** [comment]
I used it on a brand new Gigaset GS290 Phone.
I basically destroyed the phone because it entered into a startup loop.
Non recoverable.

**Comment by UniversalSuperBox** [comment]
Hi @dieterzakel, unfortunately the GS920 is not directly supported by the UBports Installer. You might be able to get help from Gigaset to return your device to a working state, but we can't offer help for this without a community member who knows the process.
