### ISSUE TITLE
install did not finish upload to device

### ISSUE THREAD

**Issue by maneum1** [ubports/ubports-installer#1813]
**UBports Installer `0.8.4-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6039936f16ef7600077b1b5a
Log: *N/A*

Nexus 6P install following the instructions of UBports installer

**Comment by NeoTheThird** [comment]
Sorry about that, duplicate of #1537
