### ISSUE TITLE
checksum error

### ISSUE THREAD

**Issue by hadrienmajoie** [ubports/ubports-installer#1817]
**UBports Installer `0.8.4-beta` (AppImage)**
Environment: `Gentoo unknown linux 5.8.18-pentoo-r2 x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/603dd2c782269a0007911e46
Log: https://paste.ubuntu.com/p/GsZMVKZ3F7/

standard install, default options. unsure it's reproducible . i test the image

**Comment by hadrienmajoie** [comment]
after testing the "bad" image:
it's stuck at boot.
reinstall attempts from the installer all fail.

**Comment by NeoTheThird** [comment]
Hey, sorry about that. Could you try again for me with [this](https://github.com/ubports/ubports-installer/releases/tag/0.8.5-beta) version?
