### ISSUE TITLE
Add a file chooser for defining the path of the OEM.img

### ISSUE THREAD

**Issue by borismihailov-pfmintelligence** [ubports/ubports-installer#1819]
**UBports Installer `0.8.5-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: suzu
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/603f9a8d6bfdd00007c88145
Log: *N/A*

Installing for Xperia X in which it would require the oem.img

**Comment by NeoTheThird** [comment]
Currently an issue with snap that has to be resolved by electron. Other packages have the file chooser.
