### ISSUE TITLE
MacOS Nexus 5 not detected after going into Bootloader.

### ISSUE THREAD

**Issue by shrnsubedi** [ubports/ubports-installer#182]
The installer detects phone while in android and reboots to bootloader. But after rebooting it fails to detect the phone. It waits infinitely without finding the phone.
--------------------------
Pug interceptor registered successfully
debug: Using fallback platform tools!
debug: 
debug: 
debug: adb shell: echo 1
debug: 
debug: adb shell: getprop ro.product.device
debug: 
debug: getprop: hammerhead
debug: adb shell: cat /etc/system-image/channel.ini
debug:  Error: Command failed: /var/folders/kj/1h_cx34n7qq6p643k2tck2k00000gn/T/.com.ubports.installer.6m7JPO -P 5038 shell cat /etc/system-image/channel.ini
/system/bin/sh: cat: /etc/system-image/channel.ini: No such file or directory

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
debug: adb shell: echo 1
debug: 
debug: reboot to bootloader
debug: 
debug: reboot to bootloader [DONE] err:null
debug: checking password
debug: correct password
debug: fastboot: wait for device
--------------------------
Device: Nexus 5 LineageOS 14.1 TWRP Recovery
OS: MacOS Sierra

**Comment by gsilvapt** [comment]
Do you have access to the full log of the error? It could help us figuring out the issue with this.

**Comment by shrnsubedi** [comment]
Managed to instal it through Linux. I don't know why the mac installer didn't work. Also cables were creating a lot of problem.

**Comment by gsilvapt** [comment]
Glad to hear! Often cables can give us some hard time.
