### ISSUE TITLE
Sony XZ (Kagura) Bootloop

### ISSUE THREAD

**Issue by hoainv1807** [ubports/ubports-installer#1823]
**UBports Installer `0.8.5-beta` (exe)**
Environment: `Microsoft Windows 10 Home Single Language 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: kagura
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60412059b24e590007332508
Log: *N/A*

Phone Firmware: 41.3.A.2.192, OEM Binary: SW_binaries_for_Xperia_AOSP_N_MR1_5.7_r1_v08_tone. Phone get bootloop after UBport install UT

**Comment by NeoTheThird** [comment]
Sorry about that, duplicate of #1402.
