### ISSUE TITLE
Unable to Install on OnePlus 3/3T connection lost during adb push

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubports-installer#1826]
Error installing with device signal lost when pushing files to devices using ubports installer 0.8.5.

https://pastebin.com/B1BdwSrw

{"level":"warn","message":"lost connection to device"}

Tried diferent cable and usb ports got same result.

**Comment by rubencarneiro** [comment]
Fixed on latest release 0.8.6, thank you @NeoTheThird

**Comment by NeoTheThird** [comment]
awesome, thanks!
