### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password di luca: sending 'recovery' (9578 KB)...OKAY [  0.503s]writing 'recovery'...FAILED (remote: partition 'recovery' not support flash)finished. total time: 0.509s

### ISSUE THREAD

**Issue by lucapavlidis** [ubports/ubports-installer#183]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/kfg8HK4RTZ/

**Comment by gsilvapt** [comment]
Can you tell which phone you are trying to install Ubuntu Ports? This might be the reason why it is not accepting to install an image via fastboot.

**Comment by lucapavlidis** [comment]
BQ Aquaris E4.5, UBports-installer says not supported phone

**Comment by gsilvapt** [comment]
Interesting, although it should be. Did you try manually selecting it from the list? I suppose your adb can recognize the device (you can run `adb devices` to check).

**Comment by lucapavlidis** [comment]
the failure message i received when i manually selected from list

**Comment by lucapavlidis** [comment]
if i let him recognize it, it says not supported

**Comment by lucapavlidis** [comment]
it doesnt allow me selecting manually

**Comment by lucapavlidis** [comment]
yes

**Comment by gsilvapt** [comment]
One more question: Have you ever installed another rom in that device, like TWRP?

**Comment by lucapavlidis** [comment]
it was ubuntu edition, but i installed android, and now i want go back to ubuntu

**Comment by NeoTheThird** [comment]
Thanks for reporting. Sorry, but you'll have to install the canonical version of Ubuntu Touch before switching to UBports, since installing Android on that device locks the bootloader, and there's no other way to unlock it. Here's how: #221

**Comment by lucapavlidis** [comment]
Thank you, solved all, following link "#221" and after on the new page i clicked link "the docs page about it"

**Comment by NeoTheThird** [comment]
Good to hear!
