### ISSUE TITLE
loops into fastboot with comment "no valid slot to boot" - with progress update

### ISSUE THREAD

**Issue by 45bcdf** [ubports/ubports-installer#1836]
**UBports Installer `0.8.6-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: sargo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604411877124250007ff86e2
Log: *N/A*

follow the installer? that is all I did...

UPDATE: 
So after a few manual reboots and seemingly nothing working, I decided to try and reflash. I got through the two first steps of the reflash and the phone started to work. So far everything seems fine now. I am not sure but I think maybe I didn't run the those first two steps properly the first time? Anyways, I am now happily using my Pixel 3a in UT but I definitely think there is a ways to go with the installer to make it more public-friendly! I would be happy to help out in any way I can with that. I think this is a great platform more people need!

**Comment by UniversalSuperBox** [comment]
Thanks for letting us know the issue was resolved, @45bcdf. We'll keep a watch for that issue if it happens in other cases. Maybe we can find a pattern and get it fixed.
