### ISSUE TITLE
push image connection to device lost 

### ISSUE THREAD

**Issue by dushicai** [ubports/ubports-installer#1838]
**UBports Installer `0.8.6-beta` (exe)**
Environment: `Microsoft Windows 10 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

can't install ubuntu touch 

log

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
