### ISSUE TITLE
error handling in some plugin APIs broken for non-network errors

### ISSUE THREAD

**Issue by vdagguma** [ubports/ubports-installer#1840]
**UBports Installer `0.8.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60484e2a52bd840007f91e8a
Log: *N/A*

After installing stock android 9 and rebooted into recovery mode, it is trying "Adb is scanning for devices" and finally got this error

**Comment by vdagguma** [comment]
This is for mi A2 device

**Comment by NeoTheThird** [comment]
```
error: Error: systemimage:install: TypeError: Cannot read property 'status' of undefined
stack trace: TypeError: Cannot read property 'status' of undefined
    at /snap/ubports-installer/348/app/resources/app.asar/src/core/plugins/systemimage/api.js:81:26
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Looks like we messed up the error handling a little there. That's a bug.
