### ISSUE TITLE
I tried to set it up on a Samsung S3 Neo, I received a failure message

### ISSUE THREAD

**Issue by idea-log** [ubports/ubports-installer#1843]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: s3ve3g
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60492a069442980007574e07
Log: *N/A*

try setting it up on S3 Neo instead of S3 Neo+

**Error:**
```
Installation error, ignore or restart. 
```

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
