### ISSUE TITLE
Some things failed to run or load.

### ISSUE THREAD

**Issue by Konstantin00** [ubports/ubports-installer#1845]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `�������� Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604a2309944298000757508b
Log: https://paste.ubuntu.com/p/jvxjT2TvxD/

I just try to install Ubuntu Touch on Nokia/Microsoft Lumia 630.

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
