### ISSUE TITLE
"Internet connection lost" appears immediately when starting installer on macOS or Windows

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-installer#1847]
**You can work around this issue** by downloading an older version of the UBports Installer, such as [0.8.6](https://github.com/ubports/ubports-installer/releases/tag/0.8.6-beta). After this issue is closed, there is no reason to download an older version of the UBports Installer any more.

<img width="1712" alt="UBports Installer in debug mode showing 'internet connection lost'" src="https://user-images.githubusercontent.com/21966173/110858963-56e1de80-8280-11eb-929f-d45c078dc025.png">

When starting the installer 0.8.7 or the prerelease 0.8.8, the "internet connection lost" message appears immediately. It does not appear that it's actually made any network requests at this point, or it's made requests that the Chrome devtools can't see.

The only log is:

```
info: Welcome to the UBports Installer version 0.8.8-beta!
```

I do feel rather welcomed, at least!

**Comment by NeoTheThird** [comment]
dev tools only show requests made from the ui process, not from the main process (where all the magic happens nowadays). Requests made at startup include fetching the list of supported devices, as well as confirming the running version of the installer is the latest version.

**Comment by Keneda-ut** [comment]
Seems a reccurrent issue :
https://github.com/ubports/ubports-installer/issues/1854 
https://github.com/ubports/ubports-installer/issues/1868

**Comment by UniversalSuperBox** [comment]
More investigation today reveals that the issue is the Heimdall binary exiting without any output on Windows and macOS. This is even happening with the newest version of Heimdall available from their website.

```
PS C:\Users\Dalton\Downloads\Heimdall Suite> .\heimdall.exe
PS C:\Users\Dalton\Downloads\Heimdall Suite> .\heimdall.exe help
PS C:\Users\Dalton\Downloads\Heimdall Suite> .\heimdall.exe detect
PS C:\Users\Dalton\Downloads\Heimdall Suite> .\heimdall.exe help
```

**Comment by UniversalSuperBox** [comment]
There are two problems here:

1. The UBports Installer reports "No internet connection" when any of its tools (adb, fastboot, heimdall) fail to run their `wait()` promise, as ["no device" in index.js](https://github.com/ubports/ubports-installer/blob/master/src/core/plugins/index.js#L133) bubbles up to ["failed to resolve device name" in core.js](https://github.com/ubports/ubports-installer/blob/master/src/core/core.js#L80) accidentally. I believe that this error should be caught in `plugins.wait()` instead.
2. There is no way that the Heimdall plugin has ever worked on Windows or macOS. Heimdall requires a shared object or dll file of libusb 1.0 be available on the system prior to running. On Windows, it also requires the Microsoft Visual C++ 2012 Redistributables for x86 (NOT x86_64) are installed.

**Comment by UniversalSuperBox** [comment]
The issue with Heimdall is now filed as https://gitlab.com/ubports/installer/android-tools-bin/-/issues/1. I still don't think it should cause an "Internet connection lost" error.

**Comment by UniversalSuperBox** [comment]
The error on macOS is actually different:

```
error: Failed to wait on a plugin: Error: {"error":{"code":1,"cmd":"adb -P 5037 wait-for-any-any"},"stderr":"* daemon not running; starting now at tcp:5037\nADB server didn't ACK\nFull server startup log: /var/folders/8h/2l6_vm5j1q12cj21_mgm1tm00000gn/T//adb.501.log\nServer had pid: 3793\n--- adb starting (pid 3793) ---\nadb I 04-12 10:06:33  3793 26088 main.cpp:62] Android Debug Bridge version 1.0.41\nadb I 04-12 10:06:33  3793 26088 main.cpp:62] Version 30.0.4-6686687\nadb I 04-12 10:06:33  3793 26088 main.cpp:62] Installed as adb\nadb I 04-12 10:06:33  3793 26088 main.cpp:62] \nadb E 04-12 10:06:33  3791 26087 usb_osx.cpp:161] Unable to create an interface plug-in (e00002be)\nadb E 04-12 10:06:33  3793 26094 usb_osx.cpp:161] Unable to create an interface plug-in (e00002be)\nadb I 04-12 10:06:33  3791 26081 auth.cpp:417] adb_auth_init...\nadb I 04-12 10:06:33  3791 26081 auth.cpp:152] loaded new key from '/Users/ddurst2/.android/adbkey' with fingerprint 1146A2FEC71BDF2822FE7518B92EFA3C335E3CE6133C1DA631BF7B096D1A15CE\nadb F 04-12 10:06:34  3793 26088 main.cpp:153] could not install *smartsocket* listener: Address already in use\n\n* failed to start daemon\nerror: cannot connect to daemon"}
```

Interesting enough, the error doesn't occur on the `start-server` command, but on the first command after it. It appears that the server starts correctly, but maybe it crashes, or maybe the new client tries to use it too quickly.
