### ISSUE TITLE
Worked great, just needed to try again when mounting cache

### ISSUE THREAD

**Issue by morgandbusch** [ubports/ubports-installer#1849]
**UBports Installer `0.8.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-44-generic x64 NodeJS v12.18.3`
Device: deb
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604bc56094429800075754c4
Log: *N/A*

Nexus 7 (2013)

Turned on device from power off, enabled developer mode+usb debugging and quickly flashed (possibly while device was still finishing after-boot setup). When UBports rebooted the device, several apps stopped responding. During setup in bootloader, I got an error while trying to wipe the cache that said something about the device being busy while trying to mount it. Trying again fixed it. From someone used to manually flashing through adb and twrp, I LOVE how easy this was to use!

**Comment by doniks** [comment]
> Trying again fixed it

Do you mean the 'try agaiin' button that the installer showed? Are you sure it wasn't 'ignore'? I'm trying to get an understanding what's actually causing this

**Comment by UniversalSuperBox** [comment]
Since we haven't had any new activity on this report, let's assume that it's a part of #1591 and continue tracking it there.
