### ISSUE TITLE
With UBports Installer 4 hours in "Cleaning up..."  Formating system partition

### ISSUE THREAD

**Issue by Miscelo** [ubports/ubports-installer#1850]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Debian GNU/Linux 10 buster linux 4.19.0-14-amd64 x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604be0189442980007575502
Log: https://paste.ubuntu.com/p/25DmvByRnD/

More information to read in Installing Mode. I realy do not know if its installing or if system is broken. Show process on work.

**Comment by umbernhard** [comment]
I am also experiencing this issue. It appears that uninstalling and reinstalling the snap of the installer fixes it.

**Comment by UniversalSuperBox** [comment]
Hi @Miscelo,

It appears that your device's bootloader was locked when you attempted to install Ubuntu Touch (the line `FAILED (remote: 'Flashing is not allowed in Lock State')` appears in the log). Please unlock the bootloader on your device and try using the UBports Installer again.

@umbernhard, we can continue tracking the problem you're having with the installer in your issue at https://github.com/ubports/ubports-installer/issues/2097
