### ISSUE TITLE
ended up with volla + sailfish os logo

### ISSUE THREAD

**Issue by PawelSpoon** [ubports/ubports-installer#1852]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `elementary 5.1.7 Hera hera linux 5.4.0-65-generic x64 NodeJS v12.18.3`
Device: yggdrasil
Target OS: SailfishOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604c82dd944298000757566c
Log: https://paste.ubuntu.com/p/BdDHC8ZmVV/

i have tried to install sailfish option
i did follow the instructions until it says:  if your phone shows ... select fastboot

i think that i screwed it up when installer says you should go to fastboot option.
the phone shows:
- reboot
- ubuntu actions
- android actions

and i did not went for android option.
the installer would then do something, tell me to reboot phone, phone would show volla and sailfish but like forever.
shutting down would restart phone to that screen

the 5th volume+ and power would finally lead me again to boot menu.
android actions > advanced > reboot to bootloader
now i went for android and after some submenues i did find fastboot
that i have to select android first was not clear enough on the first try.
now try to flash again.

**Comment by PawelSpoon** [comment]
i was able to help myself to return back to volla os and a workin phone using ubports install to flash volla os again.

**Comment by UniversalSuperBox** [comment]
Hi @PawelSpoon, thanks for letting us know you were able to resolve the issue. Please file a new issue on this repository if you have any other issues with the UBports Installer.
