### ISSUE TITLE
UBports 0.8.7-beta fails to find an internet connection

### ISSUE THREAD

**Issue by MrT10001** [ubports/ubports-installer#1854]
![UBport 8-7 beta issue](https://user-images.githubusercontent.com/32995557/111033338-b1a64200-8408-11eb-8ba9-b9ba627e27d4.jpg)
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: Nexus 4 (Mako)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604ccc52944298000757574e
Log: *N/A*

Open it up.

**Comment by xrad** [comment]
The error message may be misleading, it seem the installer may not be able to connect to the phone in this case. I needed to put the device into fastboot mode first to get past this error. When I checked the log ($HOME/Library/Caches/ubports/ubports-installer.log, macOS) I saw the installer tries multiple approaches to connect to the device including adb, fastboot and heimdall.

**Comment by MrT10001** [comment]
Hi, thanks for you response. I tried various things. The phone was connected in fastboot mode, it showed up each time in Windows command prompt. I tried a different cable, same error (definitely connected to the internet). Went back to the 0.8.5-beta installer and that worked flawlessly. I will try in Linux next time, I am only using windows 10 for convenience. I didn't try another phone though, but the fact it worked with the earlier version of the installer tells me there is a possible bug.

**Comment by kalinbogatzevski** [comment]
> Hi, thanks for you response. I tried various things. The phone was connected in fastboot mode, it showed up each time in Windows command prompt. I tried a different cable, same error (definitely connected to the internet). Went back to the 0.8.5-beta installer and that worked flawlessly. I will try in Linux next time, I am only using windows 10 for convenience. I didn't try another phone though, but the fact it worked with the earlier version of the installer tells me there is a possible bug.

I got the same issue with a Nexus 5. But unfortunately, I can't find the 0.8.5 version installer. Is there an archive somewhere? :)

**Comment by kalinbogatzevski** [comment]
> > Hi, thanks for you response. I tried various things. The phone was connected in fastboot mode, it showed up each time in Windows command prompt. I tried a different cable, same error (definitely connected to the internet). Went back to the 0.8.5-beta installer and that worked flawlessly. I will try in Linux next time, I am only using windows 10 for convenience. I didn't try another phone though, but the fact it worked with the earlier version of the installer tells me there is a possible bug.
> 
> I got the same issue with a Nexus 5. But unfortunately, I can't find the 0.8.5 version installer. Is there an archive somewhere? :)

Got it! 0.8.5 works here as well.

**Comment by Keneda-ut** [comment]
Same issue here with 0.8.7-beta on windows 7 Pro.

Last ubports installer i had before is 0.4.18 beta and no internet error with it.

**Comment by UniversalSuperBox** [comment]
Hi everyone, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
