### ISSUE TITLE
Hangs on Google logo

### ISSUE THREAD

**Issue by llorban** [ubports/ubports-installer#1855]
**UBports Installer `0.8.4-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H524 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/604e6c64b4f6d800072ee559
Log: *N/A*

the installation appears to have succeeded according to the ubports installer app on the computer, but the phone hangs on the Google logo

**Comment by UniversalSuperBox** [comment]
Hi @llorban,

Usually the Nexus 5 will continue booting after a while at the Google logo. Were you able to resolve this issue since filing it?

**Comment by UniversalSuperBox** [comment]
Hi @llorban,

Since we haven't heard from you for a while, we'll assume that you've either resolved this issue or moved on. Please let us know if this problem is still relevant.
