### ISSUE TITLE
Failed to download latest version Error: Request failed with status code 404

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubports-installer#1863]
**UBports Installer `0.8.5-beta` (deb)**
Environment: `Ubuntu 20.10 Groovy Gorilla linux 5.8.0-45-generic x64 NodeJS v12.18.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/605494c9cc3fc50007af5a12
Log: *N/A*

tried again same result

**Comment by UniversalSuperBox** [comment]
Hi @Dave1152000,

Unfortunately, we no longer have the logs from this run (our fault, not yours). If you are still having trouble with the UBports Installer with the newest version, please let us know.
