### ISSUE TITLE
FAILED!!!

### ISSUE THREAD

**Issue by pankaj-rspy** [ubports/ubports-installer#1864]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Home Single Language 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60549f58cc3fc50007af5a3d
Log: *N/A*

failed to install os. won't even open....shows failed internet connection even though i am connected to the internet

**Comment by UniversalSuperBox** [comment]
Hi @pankaj-rspy, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
