### ISSUE TITLE
Stuck on flashing firmware partitions using fastboot

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [ubports/ubports-installer#1867]
**UBports Installer `0.8.6-beta` (exe)**
Environment: `Microsoft Windows 10 Enterprise 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6055f365cc3fc50007af5e1b
Log: *N/A*

Phone is working on LineageOS16.0. I selected device manually, installer rebooted it to fastboot and then stuck with 'flashing firmware partitions using fastboot' message. Nothing happened for a long time.

![installer](https://user-images.githubusercontent.com/19704782/111870607-bd5cb000-8996-11eb-9ea2-634638c176df.png)

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
