### ISSUE TITLE
internet connection lost on wirelles network

### ISSUE THREAD

**Issue by ihusky02** [ubports/ubports-installer#1868]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: Xiaomi Mi A 2
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6056cc3ccc3fc50007af6083
Log: https://paste.ubuntu.com/p/JfJwGHWm2z/

I don`t know

**Comment by Keneda-ut** [comment]
Not only with wireless...
https://github.com/ubports/ubports-installer/issues/1854

**Comment by UniversalSuperBox** [comment]
Hi @ihusky02, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
