### ISSUE TITLE
Nexus 4 Failure

### ISSUE THREAD

**Issue by MrT10001** [ubports/ubports-installer#1876]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: mako
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/605b666c54459b000787d225
Log: https://paste.ubuntu.com/p/jz3HPvWGBd/

Just try and install ubports

**Comment by MrT10001** [comment]
Still an issue with the Windows 10 installer for 0.8.7-beta. Fails every time. If it is not connected to the internet (which it is) error, it will reboot the phone in the middle of the install. Has done this on 6 Nexus 4's and 1 Nexus 5 so far. Installer 0.8.5-beta works every time.

**Comment by Rufusdotrufus** [comment]
Confirming issue.  Tried to install on Nexus 4 on 03/25/21.  Despite being connected to the internet, fails to connect to ubports server every time.  Have tried dozens of times.

Error: unhandled rejection at [object Promise]: Error: {"error":{"code":1,"cmd":"C:\\Users\\"User"
![UBports snip #1]\\AppData\\Local\\Temp\\1pQNDpI5Kn6teIMMfkwxEiCc0hT\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 kill-server"},"stderr":"error: failed to read response from server"}

**Comment by Rufusdotrufus** [comment]
Was able to successfully install on Ubuntu 20.10 today without issue.  Definitely an issue with Windows 10.

**Comment by MrT10001** [comment]
Hi, great stuff, I have yet to try it out on Ubuntu and I had a suspicion that this might be the case.
