### ISSUE TITLE
Unsure of how to press power + VolUp-button correctly AND installer confusing at the end

### ISSUE THREAD

**Issue by Trolliverpust** [ubports/ubports-installer#1877]
**UBports Installer `0.8.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-48-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/605bc2be54459b000787d32d
Log: *N/A*

While installing the installer showed a picture of the device not resembeling the actual button layout. This made me push the buttons wrongly. With a few tries i finally made it. AND the installer needs to tell that you actually have to wait a few minutes after it says "finished"

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
