### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\julia\AppData\Roaming\ubports\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by susuking** [ubports/ubports-installer#188]
it can't find the file even though the file exist.

**Comment by gsilvapt** [comment]
Hi! Thanks for reporting! Can you try posting the log generated here for us to have a look?

This issues seems close to #110, judging by the error message you wrote in the title.

**Comment by NeoTheThird** [comment]
Duplicate of #110.
