### ISSUE TITLE
Error trying to flash device.

### ISSUE THREAD

**Issue by yeyeto2788** [ubports/ubports-installer#1887]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Enterprise 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Open the application, and just wait for the error to occurred.
Error:
```javascript
Error: unhandled rejection at [object Promise]: Error: {"error":{"code":4294967295,"cmd":"C:\\Users\\locouser\\AppData\\Local\\Temp\\1pQNDpI5Kn6teIMMfkwxEiCc0hT\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 start-server"},"stderr":"* daemon not running; starting now at tcp:5037\r\ncould not read ok from ADB Server\r\n* failed to start daemon\r\nerror: cannot connect to daemon"}
```
![image](https://user-images.githubusercontent.com/6363686/113258563-632fe900-92cc-11eb-9812-c565b6bf720f.png)

**Comment by UniversalSuperBox** [comment]
Hi @yeyeto2788, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
