### ISSUE TITLE
pls fix this

### ISSUE THREAD

**Issue by jsjsj-jjs** [ubports/ubports-installer#1889]
**UBports Installer `0.8.7-beta` (beta-win)**
Environment: `Microsoft Windows 10 Home 10.0.18363 win32 10.0.18363 x64 18363 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6066c6d8df085800073e4f72
Log: https://paste.ubuntu.com/p/zTTBcPCzjz/

they told me internet connection lost but it was connected please fix this

**Comment by UniversalSuperBox** [comment]
Hi @jsjsj-jjs, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
