### ISSUE TITLE
Nexus 5 not identified by installer

### ISSUE THREAD

**Issue by torfix** [ubports/ubports-installer#189]
I try to install Ubuntu Touch on my Nexus 5. ADB Drivers are installed, but the installer does not recognize the device. At the moment I reach the step were you should boot into bootloader, if done, nothing happens.
My notebook runs under Windows 10, ADB driver installed. My Nexus 5 is the 32 GB version, running Android 6 and trwp recovery due to LineageOS tests. It is not rooted, variant is hammerhead D821(E) 32GB, HW version rev_11, bootloader version HHZ20h.
Btw, I am able to access the Nexus when connected, so this works. It would be really kind of you, if you could help. 
Thanks a lot and best regards
Torsten

**Comment by gsilvapt** [comment]
Hi! Thanks for reporting! 

Could you please paste the log generated during the installation? Judging by your message, it might have generated one in the process and it would help us figuring out what happened.

Thanks!

**Comment by torfix** [comment]
Hi Gustavo,
thank you for your prompt answer. Can you tell me where I can find the log ? I could not find one in the folder I use the installer.
Found something, that might be interesting. I tried "adb devices" to verify, if the nexus is found, and it is ok, so the driver should work. But in the installation video on ubports.com, while the process is shown, no hint is upcoming from the installer about the needed adb driver. In my installation proces, it's always indicated "ADB Drivers needed". I am not sure, if this is important, but I simply noticed that and might be perhaps depend on the version of the installer.
Cheers
Torsten

**Comment by gsilvapt** [comment]
Hi @torfix ,

I'm not totally sure the logs hang around. They should be somewhere inside the directory where you installed the installer executable. I believe the default location is `AppData/Roaming/ubports`.

Regarding your update, I think there are usually problems with Windows and adb drivers as there is no common driver to work with all devices. I don't know which one you installed though but have you tried using the Nexus' 5 official? There's [this](https://developer.android.com/studio/run/oem-usb.html) guide from Google but I'm pretty certain more can be found online if you search. Often the common one is using the universal but I'm uncertain how reliable that is. 

Thanks!

**Comment by torfix** [comment]
Hi Gustavo,
hope you're doing well, I found the log
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/1904319/ubports-installer.log)
Btw I tried the original google driver, but they regrettably haven't changed anything. Hope this will help.
Thank you a lot and cheers
Torsten

**Comment by gsilvapt** [comment]
Hi @torfix,
Thanks for the report and apologies for the trouble.

We have been having many reports with failed recognized devices. Perhaps you are also affected with this bug. We have to take a look into this. Just for the sake of having you running Ubuntu Touch, have you tried manually selecting your device in the installer and see where that takes you to? My installer does not recognize the device either but I was able to install by selecting it manually.

Sorry for the bummer. We will work on this very soon.
Cheers!

**Comment by torfix** [comment]
Hi Gustavo,
I also selected my device manually, but wasn't able to forward. On my desk there is another notebook, where I will install Ubuntu and see, if there is a difference with the installer ;)
So far thank you a lot for your help and commitment, I will of course revert to you, if there's something new. Cheers
Torsten

**Comment by torfix** [comment]
Hi Gustavo,
finally I did it. Woooohoooo, UT is running on my Nexus. I installed Ubuntu on my notebook, used that installer and it worked. All seems fine now and I am really happy with it. At the moment, I am playing around with it and will see, if I can use it for daily life. (Do you ubports guys use it for daily life ?). Perhaps I can get rid of the Android ;)
Thank you again for your help and patience
Have a great weekend, cheers
Torsten

**Comment by gsilvapt** [comment]
Despite being off-topic, I can say many people are using Ubuntu Phone devices as their mainly driver. Glad you were able to have it running in your device.

I think we should leave this issue open because it is another problem related with hardware recognition.

**Comment by jerome83136** [comment]
Hi,
Don't know if it could help; but I had the same issue and solved it.

I'm on a notebook running Windows 10

When I run the installer it never detects I have the Universal driver installed; while I installed it several times from the link provided by the installer.

If I try to select my device manually (Nexus 5) I can go to the install step; but I can't go further.

If I try to go to the location of the adb.exe and launch the command "adb.exe devices"; I can see my device is listes.
But The installer does not seem to detect it and therefore cannot process to the flashing process.

What I did:

I installed the Andoir SDK platform tools from there: https://developer.android.com/studio/releases/platform-tools

Then I had to update my "PATH" environment variable so it can find the adb.exe file
(After this if I open a terminal and type adb.exe devices; it works no matters the current directory is)

Then I ran the installer again. It still didn't detect the Universal driver; but when I selected my Nexus 5 manually; I was finaly able to proceed to the installation.

Hope it could help

I personnaly think the main problem is arround the "PATH" environment variable not being correctly updated by the installer ;-)

Best regards

Jérôme

**Comment by graphik55** [comment]
Hello,

thank you very much Jérôme. I had the same problem.

At the beginning even adb or fastboot did not recognize my phone until I change MTP to PTP.  But the ubports installer still did not recognize my Nexus 5. Than I found your comment, added the directory for minimal adb and fastboot to my PATH variable under Windows 10 and the ubports installer recognized my phone after manually selct of Nexus 5.

Regards,
graphik_55
