### ISSUE TITLE
I have Internet Connection Still it shows you need to configure the proxy variables and my device(Huawei GR3 2017) is not registered on ubports. 

### ISSUE THREAD

**Issue by nightshawk** [ubports/ubports-installer#1890]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6066dce8df085800073e4fa2
Log: https://paste.ubuntu.com/p/xDrscwNtNt/

Error: unhandled rejection at [object Promise]: Error: {"error":{"killed":true,"signal":"SIGTERM","cmd":"C:\\Users\\User\\AppData\\Local\\Temp\\1pQNDpI5Kn6teIMMfkwxEiCc0hT\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 kill-server"}}

**Comment by Duheeeme** [comment]
Follow the steps in the 3rd comment.

https://forums.ubports.com/topic/5451/struggle-to-install-ubuntu-touch-on-nexus-5-with-windows10-installer/4

**Comment by puntiko1213** [comment]
i have the same problem with the redmi note 7

**Comment by UniversalSuperBox** [comment]
Hi @nightshawk and @puntiko1213, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.

You can see if your device is supported by Ubuntu Touch at https://devices.ubuntu-touch.io. If your device is not supported, it will need a custom image made for it. You can find out how to do that at https://docs.ubports.com/porting.
