### ISSUE TITLE
Internet

### ISSUE THREAD

**Issue by Futtyy** [ubports/ubports-installer#1894]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6068bb1f6525970007177bc8
Log: https://paste.ubuntu.com/p/CVBJBr2FZq/

open the program

**Comment by Duheeeme** [comment]
Follow the steps in the 3rd comment.

https://forums.ubports.com/topic/5451/struggle-to-install-ubuntu-touch-on-nexus-5-with-windows10-installer/4

**Comment by UniversalSuperBox** [comment]
Hi @Futtyy, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
