### ISSUE TITLE
The installer failed to connect to the UBports servers

### ISSUE THREAD

**Issue by hguenot** [ubports/ubports-installer#1896]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Professionnel 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/606bf9d269c4ed0007f08b98
Log: https://paste.ubuntu.com/p/7fTBXT8PdN/

Launch the installer on Windows 10

**Comment by UniversalSuperBox** [comment]
Hi @hguenot, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into https://github.com/ubports/ubports-installer/issues/1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
