### ISSUE TITLE
provide means to flash original Canonical images

### ISSUE THREAD

**Issue by elmo2018** [ubports/ubports-installer#190]
Would it be possible to provide means to flash original Canonical UT images?  Use case is to go back to original image to ease RMA process. (And after that go back to ubports of course.)

**Comment by gsilvapt** [comment]
Hi!

I'm not totally sure about this but since Canonical has put this project a side and no longer actively supports or develops Ubuntu Phones, my bet is we no longer have Canonical Images.

**Comment by dobey** [comment]
The system-image server from Canonical is no longer being hosted, and therefore the images are no longer there. All retail devices should have original OEM images available from the manufacturers though. You should follow the manufacturer process for re-flashing to the stock image for RMA, if necessary.

**Comment by elmo2018** [comment]
I have been able to flash an image that looks like Canonical's OTA-15 following [this tutorial (in German)](www.mibqyyo.com/de-artikel/2015/12/18/ubuntu-android-auf-dem-aquaris-e4-5-und-e5-installieren/).  No certainty about the image, but for RMA purposes it can't be worse than a ubports image. :-)  Only issue was that `flash_tool.sh` complained about a missing `libpng12` (on Debian 9).  I fixed it by [installing the library manually](https://askubuntu.com/questions/978294/how-to-fix-libpng12-so-0-cannot-open-shared-object-file-no-such-file-or-direc/978338) and it worked.  Given that Canonical images aren't available anymore, this issue can be closed.

**Comment by elmo2018** [comment]
Yes, I know.  What I meant was that I have no certainty the image I flashed is bit for bit identical to Canonical's image. It may as well contain malware.

**Comment by gsilvapt** [comment]
Yes, that could happen. That said, I'd really recommend looking only in the materials UBPorts made available and try from there installing on your device :+1:

**Comment by dobey** [comment]
@elmo2018 Well, don't install images from anywhere that aren't official. So, at this point that means don't install images that aren't from UBports, or the manufacturer.

**Comment by advocatux** [comment]
The download links and install process is the official documentation already.

https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices

**Comment by elmo2018** [comment]
Which points to the same ressource I downloaded the image.  Are there any image checksums available on Ubuntu servers still?

**Comment by advocatux** [comment]
Well you asked 
> Would it be possible to provide means to flash original Canonical UT images?

and I just said 
> The download links and install process is the official documentation already.

Anyway as you can see most of those images are not, and never were really, on Ubuntu servers so the place to look for checksums is in the same place where the images are.

For example, in the Spanish version of the page for E4.5 downloads (http://www.mibqyyo.com/descargas/categorias/aquaris-e4-5-ubuntu-edition/) you can see the MD5s:

- MD5: 7FE6238686B24C376971BB504B4AE95F

- MD5 developers: 6441248C037718B89778CC02C035DF6C

BR

**Comment by dobey** [comment]
The images hosted on ubports servers have detached GPG signatures, as you can see at http://system-image.ubports.com/ubports-touch/15.04/stable/krillin/ for example.

The OEM images hosted by BQ or Meizu are not exactly the same as the OTA images hosted on ubports (nor on the old Canonical image server), but are special files to be flashed using the OEM flash tooling.

**Comment by NeoTheThird** [comment]
The [canonical system-image server](http://system-image.ubuntu.com/ubuntu-touch/) seems to be still online, so if you really want to go back to a Canonical image, you could still use ubuntu-device-flash. But I do not want to include this in the UBports Installer, since it's not recommended, and will just add unneeded complexity. Also, there is no way around [the SP flash-tool method](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices) to unlock the bootloader for legacy devices that run android, so it would not even solve that problem (see #221 ). I hope you will understand that I will close this issue.
