### ISSUE TITLE
fails to install while downloading files to installer connection to device lost, device drops to android recovery. happened on the snap too

### ISSUE THREAD

**Issue by rumney909** [ubports/ubports-installer#1904]
**UBports Installer `0.8.7-beta` (AppImage)**
Environment: `Fedora 33 Workstation Edition linux 5.11.11-200.fc33.x86_64 x64 NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/606f0d30b8eb290007b2b09d
Log: *N/A*

try and install using same device

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
