### ISSUE TITLE
not installed

### ISSUE THREAD

**Issue by 3kage** [ubports/ubports-installer#1905]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `�������� Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60708b0cb8eb290007b2b456
Log: https://paste.ubuntu.com/p/knG8drTxnP/

not installed

**Comment by UniversalSuperBox** [comment]
Hi @3kage, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
