### ISSUE TITLE
installer tells me that it cannot access the internet, and tell me something about ADB not being installed (It is).

### ISSUE THREAD

**Issue by Hellmanx** [ubports/ubports-installer#1906]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: Ulefone Armor 3WT
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6070f66bbb3ec50007dcc0b4
Log: https://paste.ubuntu.com/p/Bh9Hm7QtqF/

Just open the program

**Comment by UniversalSuperBox** [comment]
Hi @Hellmanx, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
