### ISSUE TITLE
Installer works fine, but after it says "installing update" on phone, I reboot and stuck at google logo

### ISSUE THREAD

**Issue by Kevin8675** [ubports/ubports-installer#1909]
**UBports Installer `0.7.2-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19041 win32 10.0.19041 x64 19041 0.0 NodeJS v12.16.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

On Nexus 5, run the install, it works fine but once done, after it says "Installing Update" on phone, it goes back to recovery and if I manually reboot, it gets stuck and google logo and doesn't boot.
Help?

**Comment by Kevin8675** [comment]
I tried with many versions of the installer including the latest one.

**Comment by Keneda-ut** [comment]
"it goes back to recovery and if I manually reboot"

Did you try to not manually reboot and wait?

The latest working version of the installer for windows is this one : https://github.com/ubports/ubports-installer/releases/tag/0.8.6-beta

I have a N5 and installed without problem using 0.4.18 at the time, on windows 7.

**Comment by Kevin8675** [comment]
I waited around 15 minutes and it still did not automatically reboot as it is supposed to. But I will try the version of the install you posted.

**Comment by Kevin8675** [comment]
I just tried it with installer 0.8.7 and it automatically rebooted! Thanks for the help! Ill mark this as closed now.

**Comment by Keneda-ut** [comment]
@Kevin8675 Glad it helped you ^^
