### ISSUE TITLE
Installing Ubuntu touch on Nokia 3.2

### ISSUE THREAD

**Issue by sridharkasukhela** [ubports/ubports-installer#1910]
**UBports Installer `0.8.7-beta` (dmg)**
Environment: `Mac OS X 10.14.6 macOS Mojave darwin 18.7.0 x64 18G8022 NodeJS v12.18.3`
Device: Nokia 3.2
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6075c5fee99f3a00070bd361
Log: *N/A*

Started Ubuntu touch v.0.8.7 and connected Nokia 3.2 phone running Android 11. This error pops up immediately. The device is also not detected

**Comment by Keneda-ut** [comment]
https://devices.ubuntu-touch.io/

Your device is not supported, neither by ubports installer, nor by any port...

Androïd 11 is still not supported yet as a basis for installing uTouch anyway...

**Comment by UniversalSuperBox** [comment]
Hi @sridharkasukhela, thanks for filing an issue on the UBports Installer.

You can find our list of supported devices at https://devices.ubuntu-touch.io. If your device is not there, you can learn more about porting Ubuntu Touch to your device at https://docs.ubports.com/porting/

Someone who owns the device must be the one who creates the port.
