### ISSUE TITLE
failed, my android os correpted

### ISSUE THREAD

**Issue by iamsrikanthnani** [ubports/ubports-installer#1911]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.8.0-48-generic x64 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6076bdb3e99f3a00070bd5c1
Log: *N/A*

The phone, not turning on :(

**Comment by UniversalSuperBox** [comment]
Hi @iamsrikanthnani,

The log you submitted does not indicate that the UBports Installer took any action on your device. What steps did you take to prepare your device for Ubuntu Touch before running the installer?
