### ISSUE TITLE
on reboot, error and reboot to reset, on reset twrp boot loop

### ISSUE THREAD

**Issue by poetaster** [ubports/ubports-installer#1915]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `Ubuntu 18.04.5 LTS Bionic Beaver linux 4.15.0-140-lowlatency x64 NodeJS v12.18.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6079b58ea1d1c00007cd29e1
Log: https://paste.ubuntu.com/p/5k2C8tsqxy/

I just did an install.

**Comment by JamiKettunen** [comment]
Hey, what OS did you have flashed before attempting to install **VollaOS**? If it was **Sailfish OS** you will have to format `userdata` partition from TWRP before continuing with the sideload process.
I think we need a new toggle for this also just in case someone wants to start fresh as well.

**Comment by poetaster** [comment]
That's exactly it! I was on Sailfish which I develop for, had screwed up the sensors and wanted to find out if Volla was ok. It turned out that the sensors issue was completely unrelated (developer repos in the sailfish install instead of testing which clobbered the sensorfw libs). Thanks! I also noted that it's possible without too much pain to install on the gigaset gs290.

**Comment by poetaster** [comment]
This is a dupe ;)
