### ISSUE TITLE
Redmi note 9 pro 

### ISSUE THREAD

**Issue by shahbazkarimi123** [ubports/ubports-installer#1920]
There is no any version for redmi note 9 pro

**Comment by UniversalSuperBox** [comment]
Hi @shahbazkarimi123, thanks for filing an issue on the UBports Installer.

You can find our list of supported devices at https://devices.ubuntu-touch.io. If your device is not there, you can learn more about porting Ubuntu Touch to your device at https://docs.ubports.com/porting/

Someone who owns the device must be the one who creates the port.
