### ISSUE TITLE
cannot connect to network

### ISSUE THREAD

**Issue by XenonChau** [ubports/ubports-installer#1921]
**UBports Installer `0.8.7-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H2 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/607ec97ed6cca900074ab4cf
Log: *N/A*

any way to use this os at china mainland?

**Comment by UniversalSuperBox** [comment]
Hi, thanks for letting us know you had a problem with the UBports Installer. It sounds like you're running into #1847, and I've added information to work around the problem there.

I'll close this issue report to keep the issue tracker cleaner and help us know what work we need to do.
