### ISSUE TITLE
Fails immediatley

### ISSUE THREAD

**Issue by jsolo7861** [ubports/ubports-installer#1924]
**UBports Installer `0.8.7-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6085e51620f6e10007402942
Log: https://paste.ubuntu.com/p/3vYvk5xHF8/

have twrp installed and the ex kernel

**Comment by UniversalSuperBox** [comment]
Hi @jsolo7861,

This issue was fixed in ubports-installer version 0.8.8. Please update to the newest version of the UBports Installer from https://github.com/ubports/ubports-installer/releases.
