### ISSUE TITLE
Error 404. This time I have no about the error's nature. Wiped everything and formatted from TWRP about three times over. During the install, I got some error 404 message.

### ISSUE THREAD

**Issue by enragegit** [ubports/ubports-installer#1925]
**UBports Installer `0.8.7-beta` (deb)**
Environment: `LinuxMint 19.2 Tina linux 4.15.0-129-generic x64 NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6085fe3620f6e1000740297e
Log: https://paste.ubuntu.com/p/4vJpX4Bt8X/

Tried TWRP 3.4.0, after my initial attempts with TWRP 3.5.1 were unsuccessful.

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
