### ISSUE TITLE
doesnt boot after instaling

### ISSUE THREAD

**Issue by Tharun4104** [ubports/ubports-installer#1928]
**UBports Installer `0.8.8-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.9.16-1-MANJARO x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6089b65f20f6e1000740329e
Log: *N/A*

after installing there was just the android logo and boots into fastboot

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
