### ISSUE TITLE
arriving at push file and at half sequence stop

### ISSUE THREAD

**Issue by FRAMANSZ** [ubports/ubports-installer#1930]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Ubuntu 21.04 Hirsute Hippo linux 5.11.0-16-generic x64 NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/608a9f94e31fbf00072b3574
Log: https://paste.ubuntu.com/p/nmz6YVDSHD/

just execute all regular step but not finalizing

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
