### ISSUE TITLE
Volla Image not Downloading - UBPorts Installer

### ISSUE THREAD

**Issue by VollaFan** [ubports/ubports-installer#1936]
Hello  there,

Since a week, I can no longer install Volla OS on my Volla phone. This is the error I receive:

Error: core:download: Error: core:download Error: Error: Download Error: https://ota.volla.tech/builds/volla-9.0-20201019-nightly-k63v2_64_bsp-signed.zip Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: ota.volla.tech. is not in the cert's altnames: DNS:volla.tech

My internet connection works as I can install UT without issues and Sailfish works, too.

I am on Mint Linux, but also tried Ubuntu, and Windows 10 all with the same error message.

I also downgraded to the Installer 0.8.7 as this worked for me before, same issue, though.

**Comment by Termalator** [comment]
Same here. Have they closed the service?
I Installed Ubuntu Touch on that device and wanted to go back to Volla OS but no chance.
Sailfish installs but no boot possible. Now i have a Ubuntu Touch with a Sailfish start screen :/.

It was impossible to update the Volla OS and i got no answer from Volla so i decided to try Ubuntu Touch. Are you broke?

I think that phone is another brick on my table.

**Comment by NevilleDubuis** [comment]
I have just writed a mail to the support asking where i can find this build. this is their answer :

`We are currently transitioning our OTA server infrastructure due to Volla OS 10. Therefore, there is temporarily no access to the update area. The files for Volla OS 9 will be located elsewhere in the future.`

So we need to wait for a bit i guess

**Comment by Termalator** [comment]
I hope that it will work somehow, but i think mine is allready bricked
