### ISSUE TITLE
Flashing Unsuccessful

### ISSUE THREAD

**Issue by gemris** [ubports/ubports-installer#1937]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Home Single Language 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/609361664b99020007a29a95
Log: *N/A*

Phone stuck at Fastboot screen and error popped up after 40 - 45 mins.

**Comment by fredericoschardong** [comment]
[This](https://github.com/ubports/ubports-installer/issues/1922) was enough for me to flash on a Nexus 4.

**Comment by gemris** [comment]
Finally after some driver updates, my issue is resolved. Thanks @fredericoschardong for your help.
