### ISSUE TITLE
The phone is locked

### ISSUE THREAD

**Issue by dylaw** [ubports/ubports-installer#1956]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Professionnel 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60a7aca99184760007d401bd
Log: https://paste.ubuntu.com/p/xVffQ8F9KN/

reboot and stop black screen fastboot

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
