### ISSUE TITLE
initial fastboot process failed

### ISSUE THREAD

**Issue by salclem2** [ubports/ubports-installer#1964]
**UBports Installer `0.8.8-beta` (snap)**
Environment: `Ubuntu Core 20 linux 4.19.0-16-amd64 x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60b0ff5c999fb70007e16ae5
Log: https://paste.ubuntu.com/p/kMW3fSFngd/

ubports-installer under Debian 10.9 on Xiaomi Mi A2

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
