### ISSUE TITLE
Phone keeps rebooting

### ISSUE THREAD

**Issue by IM-TechieScientist** [ubports/ubports-installer#1968]
**UBports Installer `0.8.7-beta` (dmg)**
Environment: `Mac OS X 10.15.6 macOS Catalina darwin 19.6.0 x64 19G73 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60b34a467aafbc000765d5bf
Log: *N/A*

I just flashed UBPOrts to my device and when i start it it shows Ubuntu touch logo but after that it keeps rebooting and showing that screen alone..

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
