### ISSUE TITLE
Installer completed successfully but phone boots to Fastboot only

### ISSUE THREAD

**Issue by nevarsin** [ubports/ubports-installer#1970]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `LinuxMint 20.1 Ulyssa linux 5.8.0-53-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/60b3b18cadf3e1000794fad3
Log: *N/A*

Flashed the rom provided by the installer with TWRP 3.5.2. Booted and enabled ADB Debugging. Ran the installer. File copy was fine but after reboot I get the "Android One" logo and then Fastboot only. UT recovery is still there tho.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
