### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubports-installer#1990]
Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired

**Comment by zlamalp** [comment]
Can confirm, yesterday it happened to me too.

**Comment by myxor** [comment]
Certificate of https://ubports.open-cuts.org is still expired since Tue, 22 Jun 2021 12:37:36 GMT

**Comment by JoshuaMulliken** [comment]
Same for me

**Comment by libermax** [comment]
Certificate of https://ubports.open-cuts.org is still expired since Tue, 22 Jun 2021 12:37:36 GMT

**Comment by NeoTheThird** [comment]
fixed.
