### ISSUE TITLE
Connection to device lost when pushing ubuntu touch files to device

### ISSUE THREAD

**Issue by laborim** [ubports/ubports-installer#1994]
**UBports Installer `0.8.8-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.8.0-59-generic x64 NodeJS v12.18.3`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

After twmp wipe and format, when pushing ubuntu files to device, phone goes to android recovery and on installer shows connection to device lost

**Comment by toscatsui** [comment]
where can i download zipfiles manually?  which directory should i put them in my oneplus?  i really wanna send them by myself.

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by toscatsui** [comment]
感谢您的来信！请谅解我未及时回复。如有必要，我会在查收后第一时间回复您~

**Comment by toscatsui** [comment]
感谢您的来信！请谅解我未及时回复。如有必要，我会在查收后第一时间回复您~
