### ISSUE TITLE
Bootloop - It is stuck in bootloop, ubuntu loading screen keeps coming

### ISSUE THREAD

**Issue by Shaztry** [ubports/ubports-installer#2002]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Parrot 4.11 rolling linux 5.10.0-6parrot1-amd64 x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

just installed with the installer.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
