### ISSUE TITLE
failed in second step 

### ISSUE THREAD

**Issue by Aditya0612raj** [ubports/ubports-installer#2004]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 11 Home Single Language 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

does not boot into ubuntu recovery

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
