### ISSUE TITLE
Fastboot: Unknown error:  writing 'recovery'...FAILED

### ISSUE THREAD

**Issue by JennUB** [ubports/ubports-installer#201]
UBports-Installer
Host: Ubuntu 17.10
to target: BQ Aquaris M10 FHD
(as normally supported at UBport-installer)

Fastboot: Unknown error:  target reported max download size of 134217728 bytes sending 'recovery' (11450 KB)...OKAY [  0.510s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.513s

Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/VVvd227nSR/

**Comment by NeoTheThird** [comment]
What OS is that device running at the moment? This might be a case of #221.
