### ISSUE TITLE
Error message on the command line, doesn't seem to affect the installation process itself

### ISSUE THREAD

**Issue by sjentsch** [ubports/ubports-installer#2020]
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.11.8-051108-generic x64 NodeJS v12.18.3`
Device: violet
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: https://paste.ubuntu.com/p/CzqwXRgbt8/

The following error message appears on the command line:
error: Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired
stack trace: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired
    at /snap/ubports-installer/358/app/resources/app.asar/node_modules/open-cuts-reporter/lib/module.cjs:111:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10196) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
error: Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired
stack trace: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired
    at /snap/ubports-installer/358/app/resources/app.asar/node_modules/open-cuts-reporter/lib/module.cjs:111:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by NeoTheThird** [comment]
fixed
