### ISSUE TITLE
cache partition not found and is bootlooping

### ISSUE THREAD

**Issue by cyan-2048** [ubports/ubports-installer#2023]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Pop 21.04 hirsute linux 5.11.0-7620-generic x64 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

dunno

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
