### ISSUE TITLE
Uncaught Error: socket hang up (MainRenderer:182)

### ISSUE THREAD

**Issue by ron-debajyoti** [ubports/ubports-installer#203]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/BzHzhBSyHh/

**Comment by NeoTheThird** [comment]
Duplicate of #196.
