### ISSUE TITLE
not able to install Ubuntu touch in Acer Aspire Switch 

### ISSUE THREAD

**Issue by skmathew1110** [ubports/ubports-installer#205]
HI, Guys,
 I am using a basic windows touch tablet, model Acer Aspire Switch. 
I tried to install it with Ubuntu Touch
Unfortunately for me the installer is not recognizing the tablet. 
If you have any solutions for me please help me out.

**Comment by NeoTheThird** [comment]
Sorry, that device is not supported. For a list of supported devices, see http://ubuntu-touch.io/devices.

If you want to get started with porting to devices running android, check out docs.halium.org. If you're looking for a way to install and play with Unity8 on Ubuntu, check out www.unity8.io, but keep in mind that this is still experimental.
