### ISSUE TITLE
Bug in front camera

### ISSUE THREAD

**Issue by authntcG** [ubports/ubports-installer#2056]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Home Single Language 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

when switching to front camera using camera app getting freezed, sorry for my bad english

**Comment by NeoTheThird** [comment]
please report that in https://github.com/ubports/ubuntu-touch
