### ISSUE TITLE
"Error: preparing: TypeError: Cannot read property 'codename' of null"

### ISSUE THREAD

**Issue by supersalbai** [ubports/ubports-installer#2059]
Hi guys, I want to set up UT on an Xiaomi Mi A2. I get an error "Error: preparing: TypeError: Cannot read property 'codename' of null". I am stuck - any help apprechiated.

**UBports Installer `0.8.8-beta` (deb)**
Environment: `Pop 21.04 hirsute linux 5.11.0-7620-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Don't know. Something with my phone?

**Comment by supersalbai** [comment]
Anybody? Any help?

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
