### ISSUE TITLE
Installer problem

### ISSUE THREAD

**Issue by driainanderson** [ubports/ubports-installer#206]
Under Windows 10 the installer does not recognize ADB driver even after installation of UniversalAdbDriverSetup.msi. Installation not possible.

Under Debian Linux 9 the installer asks for the administrator password but then stops with an error. The installer actually wants the user password and the inclusion of this user in the sudoers. 

Now it is downloading; hope for the best!

Iain

**Comment by NeoTheThird** [comment]
> Under Windows 10 the installer does not recognize ADB driver even after installation of UniversalAdbDriverSetup.msi. Installation not possible.

What device are you installing on?

> Under Debian Linux 9 the installer asks for the administrator password but then stops with an error. The installer actually wants the user password and the inclusion of this user in the sudoers.

Right. I guess those of us who never step outside the Ubuntu world tend to forget that there are distros where you can log in as root. What alternative text do you propose? The challenge with wording this is that even a not very technical user needs to understand that it's not the phone password. Suggestions for clear wording would be appreciated
