### ISSUE TITLE
not installed

### ISSUE THREAD

**Issue by vijayskk** [ubports/ubports-installer#2078]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Ubuntu 20.04.2 LTS Focal Fossa linux 5.11.0-25-generic x64 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

by installing

**Comment by UniversalSuperBox** [comment]
Hello @vijayskk, thanks for your report.

Unfortunately, the information that you have provided is not enough. We need to know more information about what happened to be able to help.

I'll close this report now, but please let us know if you have any more details to provide.
