### ISSUE TITLE
nexus 5 - no space left on device

### ISSUE THREAD

**Issue by sabag** [ubports/ubports-installer#2089]
**UBports Installer `0.8.8-beta` (dmg)**
Environment: `macOS 11.4 macOS Big Sur darwin 20.5.0 x64 20F71 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

nexus 5 try to flash UT

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? see https://github.com/ubports/ubports-installer/issues/1107#issuecomment-590136145 and try again. thanks :)
