### ISSUE TITLE
Installer seemed to work, but get a boot loop after completion

### ISSUE THREAD

**Issue by umbernhard** [ubports/ubports-installer#2097]
**UBports Installer `0.8.8-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.13.13-arch1-1 x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

I flashed TWRP onto the boot partition and installed the provided android 9 package. Then I ran the installer and everything seemed to work, except the system wouldn't boot into UBTouch. After several boot loops, my device complained about an unlocked boot loader, so I relocked and Android reinstalled itself.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
