### ISSUE TITLE
Installer states it loses the connection to the phone during pushing the files

### ISSUE THREAD

**Issue by ghost** [ubports/ubports-installer#2098]
**UBports Installer `0.8.8-beta` (AppImage)**
Environments: `Arch rolling linux 5.13.13-zen1-1-zen x64 rolling NodeJS v12.18.3`, as well as Pop!_OS 21.04 
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Just follow the instructions to first install OxygenOS, then wiping the device and finally installing UBPorts. During the "Pushing files" phase, when the orange bar is at about 3/4, the tool will consitently say the connection to the phone is lost, even though `adb devices` in a terminal will list the phone.

Workaround: 
Prior to installing UBPorts, I issued the following on the command line: `astboot format:ext4 cache`
After this, the installation could be started and finished without problem.

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
