### ISSUE TITLE
Support Volla Phone X

### ISSUE THREAD

**Issue by Silicomancer** [ubports/ubports-installer#2109]
Currently UBports installer does not support Volla Phone X devices. 

I ordered and received a Volla Phone X, assuming I could switch between operating systems and test them. Now I'm stuck with a phone that doesn't do what I bought it for. A kick in the teeth. 

So please support installing (especially UT and VollOS) on Volla Phone X devices.
Thank you very much for your effort!

**Comment by Guergans** [comment]
Volla Phone X is a great Smartphone just leave a bit of time to get the OS growing, so the security systems will be great too. I do have it too, and I learn a lot with it already like installing a hide.me VPN and if you have problems to install just use this tutorial to install it correctly:
https://forums.ubports.com/topic/6683/vpn-hide-me-with-volla-phone
Soon the update for the X will come out too, and you will appreciate a great tool.
Security and anonymous first...

**Comment by NeoTheThird** [comment]
Completed in https://github.com/ubports/installer-configs/pull/126

**Comment by Silicomancer** [comment]
> Soon the update for the X will come out too, and you will appreciate a great tool.
> Security and anonymous first...

Well, UT is fine, the phone as well. The apps are the problem. I was not able to install encrypted matrix messaging and also no PGP or S/MIME encrypted mailing. I consider both very important for security and anonymity. I will wait a bit but at the end these two things will be required unconditionally.
