### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.512s]writing 'recovery'...FAILED (remote: failed to get download permission for partition 'recovery')finished. total time: 0.515s

### ISSUE THREAD

**Issue by leArthurDent** [ubports/ubports-installer#211]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Debian 9.4
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/QHkyR7VWsV/

**Comment by leArthurDent** [comment]
Hey guys,

problem was that my locked oem. I bought an BQ Aquaris M10 FHD with Ubuntu and intalled Android after canonical ceased developing it. Now I wanted to switch back what didn't work. I needed to flash canonicals ubuntu-touch via BQ's Software tools. Afterwards the OEM was unlocked again and the UBPorts Installer worked flawlessly.

**Comment by NeoTheThird** [comment]
Thanks for reporting. Right, we need to add a warning for the BQ and Meizu devices, that you can not install from the android version, and maybe link to https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices

**Comment by NeoTheThird** [comment]
I created https://github.com/ubports/ubports-installer/issues/221.
