### ISSUE TITLE
не установилось!

### ISSUE THREAD

**Issue by vladimir6732** [ubports/ubports-installer#2114]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `�������� Windows 10 ������� ��� ������ �몠 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

что то с ядром телефон редми нот 7???? как исправить?????

**Comment by NotKit** [comment]
No logs, so have to close this. Please open a new report with mode details.

**Comment by UniversalSuperBox** [comment]
Hello @vladimir6732,

We can not determine the problem with your device with the information you have provided. Please provide more information with your next report. If you are having trouble installing Ubuntu Touch, you may be able to find help in the `@ubports_ru` group on Telegram.
