### ISSUE TITLE
Redmi note 7 auto unlocking not working

### ISSUE THREAD

**Issue by RAYTEKO** [ubports/ubports-installer#2117]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Professionnel 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

The auto unlocking doesn't work and I tried a bunch of software to unlock my phone on Ubuntu but nothing worked. I had others issues with Windows 11 and was forced to install Win 10 to successfully unlock my phone.
So I did manage to install ubuntu touch

**Comment by NotKit** [comment]
Not a bug, bootloader on Xiaomi devices can be unlocked only with Xiaomi own tool.
