### ISSUE TITLE
Lineage OS checksum error then locked in Redmi splash screen

### ISSUE THREAD

**Issue by joebpimentel** [ubports/ubports-installer#2120]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Ubuntu 20.04.3 LTS Focal Fossa linux 5.4.0-84-generic x64 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

I guess you should try to install on device. Could not download lineage OS 16 directly by browser on androidfilehost. Then downloaded thru wget -c. Then started process with ubports installer 0.8.8-beta. Choosing downloaded lineage OS zip file, it shows a checksum error. I just ignored, after retrying a lot of times. Installer goes thru the final step, transfering files. First boot was almost working showing lineage splash, but then rebooted and is locked in Redmi splash screen.

**Comment by Danct12** [comment]
You need to extract the vendor zip and then choose the extracted vendor image.

**Comment by joebpimentel** [comment]
> You need to extract the vendor zip and then choose the extracted vendor image.

Thank you @Danct12. Successfully installed!
