### ISSUE TITLE
device doesn't boot, "Google" on screen with open padlock icon

### ISSUE THREAD

**Issue by georgeb1962** [ubports/ubports-installer#2127]
**UBports Installer `0.8.8-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-84-generic x64 NodeJS v12.18.3`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Initially wiped device, and then ran installer

**Comment by Flohack74** [comment]
Did you install stock Android 7.1.2 before installing?

**Comment by georgeb1962** [comment]
Possibly not. That was my second try, but subsequent attempts were
successful. Probably because I then installed the stock android to get that
going first.

Thanks,

Is there an effort to get ubuntu touch to run based on a later ubuntu?
-- George

**Comment by Flohack74** [comment]
Yes we are upgrading to 20.04 base now, but that will not make much difference for you as a user :)
