### ISSUE TITLE
Swiping in all modes is not as responsive or smooth as it needs to be - sluggish and jerky. Otherwise very promising!

### ISSUE THREAD

**Issue by cyberfling** [ubports/ubports-installer#2128]
**UBports Installer `0.8.8-beta` (dmg)**
Environment: `Mac OS X 10.15.7 macOS Catalina darwin 19.6.0 x64 19H1323 NodeJS v12.18.3`
Device: bacon
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Try it on a OnePlus One with optical glass screen protector. The previous OS was LineageOS 18.1 and it was, if anything, too responsive.

**Comment by cyberfling** [comment]
Just installed UT on my OnePlus One, previously running LineageOS 18.1. Installation went without a hitch. Unfortunately, I find that swiping in all modes is rather sluggish, just not responsive as it needs to be. Otherwise, the system seems to be working (early days as yet), camera functions and no problem connecting to wifi. I would like to be 'de-googled' on this system and I have no idea how to go about that - or if it is even possible. This all looks promising - a great effort by all concerned. My OnePlus One has a glass screen protector fitted - although this made no difference on LineageOS, which I found a little too responsive to touch gestures. Thanks.

**Comment by UniversalSuperBox** [comment]
Hello @cyberfling,

Thanks for your kind words about Ubuntu Touch. If you have any trouble, you can learn more about filing issue reports on Ubuntu Touch at https://docs.ubports.com/en/latest/contribute/bugreporting.html

Since there is no actionable problem with the UBports Installer here, I'll close this report. Thanks again!
