### ISSUE TITLE
Android device 

### ISSUE THREAD

**Issue by User0w0** [ubports/ubports-installer#2131]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device:  yezz Andy35EI
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/614ece4d1653920008aacc31
Log: *N/A*

Unsupported device

**Comment by NotKit** [comment]
See https://t.me/UTFAQ/4. Each device needs to be ported before it's available in the installer.
