### ISSUE TITLE
Unable to connect to internet but have internet connection!

### ISSUE THREAD

**Issue by Guergans** [ubports/ubports-installer#2132]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Famille 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: VollaPhone X
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/614f42e21653920008ab0781
Log: *N/A*

Internet connection lost The installer failed to connect to the UBports servers. Are you connected to the internet? If you're using a proxy, you might have to configure it by setting the https_proxy environment variable.

**Comment by UniversalSuperBox** [comment]
Hello @Guergans, thanks for your report.

Unfortunately, we have lost the log included with this issue report. If you continue to experience this issue, please file a new report using the "report a bug" button in the installer.

**Comment by Guergans** [comment]
I send it back with the last log but mayby 3 times !

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
