### ISSUE TITLE
stuck in bootloop after flash ubports

### ISSUE THREAD

**Issue by MagicalGirlXi** [ubports/ubports-installer#2136]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Ubuntu 20.04.3 LTS Focal Fossa linux 5.11.0-36-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/61517b64d3b7ed0008028d46
Log: *N/A*

i buy a second hand Mi A2 with the bootloader unlocked, and flash twrp,flash the recommended Android 9 rom by twrp, then boot in Android 9, enable the adb debug, then start the ub installer, all the process were running well. Then the phone boot into a LineageOS logo, after a little while, the phone automatically reboot, then stuck in bootloop. The ubports installed in slot B stuck in it, but the Android9 in slot A runs well.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
