### ISSUE TITLE
Everything dowloaded correctly, yet I get this error upon the 'preparing system image' phase

### ISSUE THREAD

**Issue by Wouter-Kool** [ubports/ubports-installer#2137]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: enchilada
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6151afa8d3b7ed0008028ee2
Log: *N/A*

I dont know, I just followed every step of the way to the letter.

**Error:**
```
Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"C:\\Users\\WK\\AppData\\Local\\Temp\\1raG3Aut6N5DTMPVp2eiGFFUdbP\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Required key not available"}
```

**Comment by NeoTheThird** [comment]
please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.
