### ISSUE TITLE
Installation had some errors, but then its bootlooping.

### ISSUE THREAD

**Issue by galaxxyafonso** [ubports/ubports-installer#2143]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6152221cd3b7ed0008029bc1
Log: *N/A*

Just install it. I will try to re-install it.

**Comment by galaxxyafonso** [comment]
Yup. Got another error, it says it does not have permissions trying to write to cache of the recovery.

**Comment by NotKit** [comment]
Original issue was because of not selected wipe when switching from Android. But then it seems to have pushed files successfully. Did you try to boot into recovery manually?

**Comment by galaxxyafonso** [comment]
> Original issue was because of not selected wipe when switching from Android. But then it seems to have pushed files successfully. Did you try to boot into recovery manually?

Yup. I tried that on my other attempt. I will retry it soon, because i had to give that phone to one of my family members for a while.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
