### ISSUE TITLE
Not boot to os

### ISSUE THREAD

**Issue by franciscomirasg** [ubports/ubports-installer#2144]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/61524833d3b7ed0008029f74
Log: *N/A*

The device boot on recovery mode

**Comment by UniversalSuperBox** [comment]
Hello @franciscomirasg,

What operating system was your device running before you installed Ubuntu Touch? Did you check the option to "Wipe data" in the UBports Installer?
