### ISSUE TITLE
Update of the UBports installer fail I download the last version from the website

### ISSUE THREAD

**Issue by Guergans** [ubports/ubports-installer#2151]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Famille 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: (device not yet detected)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/61549206d3b7ed000802c5b6
Log: *N/A*

I try to update the installer it asked me to update but I got an error message without having the Volla Phone x connected

**Comment by Guergans** [comment]
I download the new version of the installer and try it from there, but it looks like it can't find the device connected on a USB port?
"Waiting for device....
Fastboot is scanning for devices"
I went manually to the fastboot mode, but it does not see the Volla Phone X

**Comment by Guergans** [comment]
UBports Installer 0.8.9-beta (exe)
Environment: Microsoft Windows 10 Famille 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3
Device: yggdrasilx
Target OS: Ubuntu Touch
Settings: undefined
OPEN-CUTS run: https://ubports.open-cuts.org/run/6154968ad3b7ed000802c74a
Log: N/A

Here the log with the update of the Installer and the log

**Comment by UniversalSuperBox** [comment]
More details of these runs at #2138
