### ISSUE TITLE
Still not find the device Volla Phone X

### ISSUE THREAD

**Issue by Guergans** [ubports/ubports-installer#2152]
**UBports Installer `0.8.9-beta` (exe)**
Environment: `Microsoft Windows 10 Famille 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: yggdrasilx
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6154968ad3b7ed000802c74a
Log: *N/A*

Here the log with the update of the Installer and the log

**Comment by UniversalSuperBox** [comment]
More details of these runs at https://github.com/ubports/ubports-installer/issues/2138
