### ISSUE TITLE
Error: adb:preparesystemimage: Error: {"error":{"code":126,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: Exec '/system/bin/sh' failed: Too many symbolic links encountered"}

### ISSUE THREAD

**Issue by kleinermob** [ubports/ubports-installer#2157]
**UBports Installer `0.8.9-beta` (AppImage)**
Environment: `Arch Linux unknown linux 5.14.8-arch1-1 x64 rolling NodeJS v12.18.3`
Device: miatoll
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

try to flash

**Comment by gatifun** [comment]
Hello, I got the same error when I went from an android 11 custom rom. When I put with TWRP and android10, ubports worked perfectly

**Comment by kleinermob** [comment]
i flashed from android 10 too, form orangefox

**Comment by kleinermob** [comment]
you need to flash the newest android 10 miui, i flashed curtana_eea_global_images_V12.0.4.0.QJWEUXM_20210422.0000.00_10.0_eea_c04ff6eb7f but it got into a bootloop, then i flashed the newest firmware but for global fw_curtana_miui_CURTANAGlobal_V12.0.6.0.QJWMIXM_ef9b200d31_10.0 and then i tried it again and it worked

**Comment by kleinermob** [comment]
mmh, it stays at the redmi logo but doesnt boot into ubuntu touch, im gonna try to flash the global 12.0.6.0 fully via fastboot now and see if it boots

**Comment by kleinermob** [comment]
i think you need to make sure you flash the latest miui with android 10 but make sure you flash the correct one, like europe model needs to flash eea and global flashes global rom, but im not sure yet its still downloading my rom

**Comment by kleinermob** [comment]
finally boots, you need to wait a little long for the ubuntu touch logo to appear
