### ISSUE TITLE
I keep getting: Installing - connection to device lost on Op3

### ISSUE THREAD

**Issue by MoemUT** [ubports/ubports-installer#2160]
**UBports Installer  0.8.9-beta   deb ** Environment:  LinuxMint 20.2 Uma linux 5.4.0-88-generic x64 NodeJS v12.18.3  Device: oneplus3 Target OS: Ubuntu Touch Settings:  undefined  OPEN-CUTS run: *N/A* Log: *N/A* Try to install on a Op3. !- thank you for reporting! -> 

FWIW, I'm also getting a popup from the OS stating that something inside the device's file system can't be mounted.

I tried the appimage as well and it's not making a difference for me.

**Comment by enragegit** [comment]
Tried this: #1907 ?

**Comment by MoemUT** [comment]
Thanks, my Op3 is running fine by now. I had to uncheck the 'wipe user data' tick box in the installer and then it worked!
