### ISSUE TITLE
Same  connection lost  error on older version of installer

### ISSUE THREAD

**Issue by MoemUT** [ubports/ubports-installer#2161]
**UBports Installer  0.8.8-beta   AppImage ** Environment:  LinuxMint 20.2 Uma linux 5.4.0-88-generic x64 NodeJS v12.18.3  Device: oneplus3 Target OS: Ubuntu Touch Settings:  undefined  OPEN-CUTS run: *N/A* Log: *N/A* Try to install UT on Op3 !- thank you for reporting! ->

**Comment by NeoTheThird** [comment]
Sorry, only the [latest version](github.com/ubports/ubports-installer/latest) of the installer is considered supported.

**Comment by MoemUT** [comment]
That is fine. I just tried the older one because the newest one is not working for me and the installer asked me to report the failure. So I did.
