### ISSUE TITLE
Simply ran installation, however it failed.

### ISSUE THREAD

**Issue by devtux** [ubports/ubports-installer#2164]
**UBports Installer `0.8.9-beta` (deb)**
Environment: `Debian GNU/Linux 10 buster linux 4.19.0-12-amd64 x64 NodeJS v12.18.3`
Device: mako
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Error: adb:push: Error: {"error":{"code":1},"stdout":"adb: error: target '/cache/recovery/' is not a directory"}

**Comment by devtux** [comment]
Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired

+ here

**Comment by NeoTheThird** [comment]
fixed
