### ISSUE TITLE
It would not work UNTIL I unticked the Wipe Personal Data box! I did tick First Install.

### ISSUE THREAD

**Issue by MoemUT** [ubports/ubports-installer#2165]
**UBports Installer  0.8.9-beta   deb ** Environment:  LinuxMint 20.2 Uma linux 5.4.0-88-generic x64 NodeJS v12.18.3  Device: oneplus3 Target OS: Ubuntu Touch Settings:  undefined  OPEN-CUTS run: *N/A* Log: *N/A* Do as above. !- thank you for reporting! ->

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
