### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by VsevolodDanChul** [ubports/ubports-installer#2170]
**UBports Installer `0.9.1-beta` (exe)**
Environment: `Microsoft Windows 11 Pro 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v16.5.0`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/615b3ce5d3b7ed0008030d8a

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
You need to install the version of android you were instructed to install in the beginning of the installation process. Otherwise it will not work on this device: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
