### ISSUE TITLE
Xiaomi mi A2 does not work with the latest installer 0.9.1 beta

### ISSUE THREAD

**Issue by nicktelindert** [ubports/ubports-installer#2175]
After selecting the vendor.img the continue button  is not working. There is no error and no warning it just does not do anything on click

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
