### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by atmitch75** [ubports/ubports-installer#2181]
[**UBports]
![IMG_20211007_003505 1](https://user-images.githubusercontent.com/53789357/136336017-3513913a-351d-4f3d-802e-349d383052eb.jpg)
 Installer `0.9.1-beta` (exe)**
Environment: `Microsoft Windows 11 Home 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v16.5.0`
Device: miatoll
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/615e9ae9b26de20008d38cf1

**Error:**
```
Unknown Error
```

**Comment by UniversalSuperBox** [comment]
Hi @atmitch75,

Did you check the option to "Wipe userdata" during your installation? If Android was the most recently running operating system on your device, you almost always need to check the "Wipe userdata" option.

**Comment by joanisc** [comment]
Yes @UniversalSuperBox. I selected the wipe data. Now the error, tring with an old installer version is that it cannot download this: https://github.com/UbuntuTouch-sagit/ubuntu-touch-sagit/releases/download/v1.0/recovery.img
![image](https://user-images.githubusercontent.com/5494786/136527628-9fdbcf09-f7d7-4fe4-8bd4-d572b51a244c.png)

**Comment by UniversalSuperBox** [comment]
@joanisc, if you're reporting an issue with a different device, please file a new issue report. This issue is for the Redmi Note 9S (with many other names elsewhere).

**Comment by Verevka** [comment]
> Yes @UniversalSuperBox. I selected the wipe data. Now the error, tring with an old installer version is that it cannot download this: https://github.com/UbuntuTouch-sagit/ubuntu-touch-sagit/releases/download/v1.0/recovery.img ![image](https://user-images.githubusercontent.com/5494786/136527628-9fdbcf09-f7d7-4fe4-8bd4-d572b51a244c.png)

Fix
https://github.com/ubports/installer-configs/pull/143

**Comment by atmitch75** [comment]
apologies for duplicate entries and thank you for the help
