### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for victor: target reported max download size of 1073741824 bytessending 'recovery' (11844 KB)...OKAY [  0.638s]writing 'recovery'...FAILED (remote: not supported in locked device)finished. total time: 0.738s

### ISSUE THREAD

**Issue by vsantosv** [ubports/ubports-installer#22]
Automatically generated error report 
Version: 0.1.4-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.4.0 

Error log: http://paste.ubuntu.com/25426032/

**Comment by NeoTheThird** [comment]
Thanks for reporting. Please try again with the latest release.

**Comment by mariogrip** [comment]
This fixed in later releases, please try the latest one
