### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by ronbillock** [ubports/ubports-installer#2219]
**UBports Installer `0.9.1-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.11.0-37-generic x64 NodeJS v16.5.0`
Device: enchilada
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/616d8356a5d4010008aa6544

Error I receive on installer: Error: adb:preparesystemimage: Error: {“error”:{“code”:1,”cmd”:”adb -P 5037 shell mkdir -p /cache/recovery”},”stderr”:”mkdir: ‘/cache/recovery’: Required key not available”}

**Error:**
```
Unknown Error
```

This was resolved by using an older (0.8.8) version of the UbPorts installer!!!!!!

**Comment by NeoTheThird** [comment]
please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.
