### ISSUE TITLE
Yikes!

### ISSUE THREAD

**Issue by GuimoVHS** [ubports/ubports-installer#2221]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Ubuntu 21.10 Impish Indri linux 5.13.0-19-generic x64 NodeJS v12.18.3`
Device: lancelot
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Idk

**Error:**
```
Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Required key not available"}
```

**Comment by aasami** [comment]
Same error here.
UBports Installer 0.9.1-beta (deb)
Environment: Manjaro linux 5.14.0-10-1-MANJARO x64 NodeJS v16.11.0-1
Device: fajita
Target OS: Ubuntu Touch
Settings: undefined
OPEN-CUTS run: N/A
Log: N/A

Error:

Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Required key not available"}

What can I do to help to resolve this error?
