### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Shaalan15** [ubports/ubports-installer#2230]
**UBports Installer `0.9.1-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v16.5.0`
Device: angler
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/617056eea5d4010008aa9363

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
this is seems to be a a duplicate of #1537. Please try [these steps](https://github.com/ubports/ubports-installer/issues/1537#issuecomment-792346472) to get it to work. sorry for the inconvenience :)
