### ISSUE TITLE
Recovery seems to be working well however.

### ISSUE THREAD

**Issue by electricbrain-code** [ubports/ubports-installer#2238]
**UBports Installer `0.8.9-beta` (exe)**
Environment: `Microsoft Windows 10 Home 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: citrus
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

This is a second attempt. UBPorts Recovery is working well though.
Error: adb:preparesystemimage: Error: {"error":{"code":1,"cmd":"C:\\Users\\phill\\AppData\\Local\\Temp\\1ygKXdvCrW1JOtZdfAC3c0dUbus\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Required key not available"}

**Comment by NeoTheThird** [comment]
please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.
