### ISSUE TITLE
Phone stays in boot

### ISSUE THREAD

**Issue by satyatejatanuku** [ubports/ubports-installer#2241]
**UBports Installer `0.9.1-beta` (exe)**
Environment: `Microsoft Windows 11 Pro 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v16.5.0`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/61728fbaa5d4010008aad9e0

It showed that it started the procedure and moved things to phone completed procedure in system. But, in phone it stayed in boot page and if i press reboot now then it just stays rebooting and only shows logo of mi and at bottom "ubuntu touch powered by the UBports Foundation" and stays forever there neither goes back to boot menu or shutdown.  Same happens even if  i use ubports in ubuntu pc 

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
