### ISSUE TITLE
yggdrasilx installation critical fail

### ISSUE THREAD

**Issue by TronFortyTwo** [ubports/ubports-installer#2246]
**UBports Installer `0.8.9-beta` (AppImage)**
Environment: `Arch rolling linux 5.13.12-arch1-1 x64 rolling NodeJS v12.18.3`
Device: yggdrasilx
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

To reproduce:
Attempt installing on yggdrasilx, enabling wipe and bootstrap mode.
You'll soon get the error:
`Error: core:download: Error: core:download Error: Error: Download Error: https://volla.tech/filedump/volla-yggdrasilx-9.0-ubports-installer-bootstrap.zip Error: certificate has expired`

Update:
version 0.8.8: same error

**Comment by probonopd** [comment]
Same error for yggdrasil using the UBports Installer AppImage:
https://github.com/ubports/ubports-installer/issues/2240#issuecomment-951174234

**Comment by saidinesh5** [comment]
volla.tech 's certificates are updated , so this shouldn't be a problem anymore.
ubports-installer has to update their electron dependency: https://github.com/electron/electron/issues/31212 , so other download locations like this shouldn't cause a problem

**Comment by probonopd** [comment]
This means we need a new version of Electron just to use the latest certificates?

**Comment by saidinesh5** [comment]
Not for files from volla.tech . Those certificates are updated on the server.

For other download locations (if any) that use the old letsencrypt certificates that expired recently, you'd need a new build of ubports installer with the updated electron. They also backported the changes to v 15.0 branch that is used by ubports installer, so just a new build should do i think.

**Comment by probonopd** [comment]
Today it worked for me again.
