### ISSUE TITLE
Udev rules weirdness for Meizu

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#225]
A manual workaround is to add `SUBSYSTEM=="usb", ATTRS{idVendor}=="2a45", MODE="0666", GROUP="plugdev"` to `/etc/udev/rules.d/51-android.rules`. We should get a patch for this accepted upstream.

**Comment by NeoTheThird** [comment]
Are you still interested in working on this, @gsilvapt?

**Comment by gsilvapt** [comment]
Although I am, I do not think I have enough time to juggle all things. Ubucon is taking a toll on me. Sorry

**Comment by NeoTheThird** [comment]
Ok, no worries! Keep up the good work over there :)

Will unassign you and mark this help wanted. If you ever find yourself having lots of time on your hands, you can come back to it ;)

**Comment by NeoTheThird** [comment]
Since we're not using the upstream packages any more since 0.3.x_beta, we can try and tackle this ourselves. The thing is, Udev rules and vendor ids for meizu are all over the place. For once, the devices report different vendor ids for recovery/system (meizu vendor id) and fastboot mode (MX4 seems to report the HTC id, the Pro 5 `3938`, [which is not assigned](http://www.linux-usb.org/usb.ids)). What the fuck, meizu.

Also, the rules for the snap don't seem to work 100% reliably for the MX4, despite [seemingly all needed rules should be set](https://github.com/zyga/snapd/blob/master/interfaces/builtin/adb_support.go). Needs some investigation.

**Comment by NeoTheThird** [comment]
I think we can consider this closed. Very few meizu MX4 devices out there nowadays, and if someone comes along and this issue now only exists in the deb package.
