### ISSUE TITLE
The installer failed to unlock the bootloader

### ISSUE THREAD

**Issue by alemswaj** [ubports/ubports-installer#2255]
**UBports Installer `0.8.9-beta` (AppImage)**
Environment: `Arch rolling linux 5.10.76-1-lts x64 rolling NodeJS v12.18.3`
Device: merlin
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Installing ubuntu touch on Xiaomi Redmi note 9

**Comment by zeusricote** [comment]
well. unlock it with a specific tool, and later use this again. unlock it with https://www.xiaomitool.com/v2/

**Comment by alemswaj** [comment]
Thank you, I tried with xiaomitoolv2, but I always got an error. I don't know what to do, I tried  with the official tool, but it doesn't work too. Do you know if there is another way to unlock the bootloader ?

**Comment by zeusricote** [comment]
you need a machine with windows or a vm. i dont know any other way without it. you can try with https://we.tl/t-nypoQ0R4aF works with java

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alemswaj** [comment]
Thank you, it worked !! But now I have to wait 168h.
But thanks, in one week I will be able to install Ubuntu touch .

**Comment by zeusricote** [comment]
good luck.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
