### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by Mathiesen88** [ubports/ubports-installer#2258]
**UBports Installer `0.8.9-beta` (deb)**
Environment: `Ubuntu 20.04.3 LTS Focal Fossa linux 5.11.0-38-generic x64 NodeJS v12.18.3`
Device: OnePlus 5T
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Error: core:download: Error: core:download Error: Error: Download Error: https://deac-ams.dl.sourceforge.net/project/crdroid/dumpling/6.x/firmware/firmware_9.0.11_oneplus5T.zip Error: certificate has expired

**Comment by TomatDividedBy0** [comment]
Can confirm, getting a similar error for the firmware on my Oneplus 5.

>      Error: core:download: Error: core:download Error: Error: Download Error: https://phoenixnap.dl.sourceforge.net/project/crdroid/cheeseburger/6.x/firmware/firmware_9.0.11_oneplus5.zip Error: certificate has expired

**Comment by Mathiesen88** [comment]
I got around this by chosing NOT to update firmware in installer.

**Comment by NeoTheThird** [comment]
please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.
