### ISSUE TITLE
The installation process seemingly finished, but the device does not boot.

### ISSUE THREAD

**Issue by zoitrok** [ubports/ubports-installer#2260]
**UBports Installer `0.8.8-beta` (AppImage)**
Environment: `ManjaroLinux 21.1.6 Pahvo linux 5.15.0-1-MANJARO x64 rolling NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

It gets stuck on the android one boot screen. I had flashed both partitions with the stock android 9 as instructed for this model.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
