### ISSUE TITLE
Xiaomi Mi A2 install failed to create /cache/recovery: mkdir: '/cache/recovery': Operation not permitted

### ISSUE THREAD

**Issue by supernany** [ubports/ubports-installer#2268]
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.11.0-40-lowlatency x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

adb -P 5037 shell mkdir -p /cache/recovery

**Comment by supernany** [comment]
Hello,

Finally I was able to install Ubuntu Touch with the 0.8.5-beta version of UBports-installer.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
