### ISSUE TITLE
No installation, does not start

### ISSUE THREAD

**Issue by carlossoy** [ubports/ubports-installer#2278]
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-90-generic x64 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

After completing the installation, just boot into fastboot, there is no operational system.

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? Also, Your device must be running a specific android 9 build before installing Ubuntu Touch. You can use the link below to download it. You can use either use stock recovery or TWRP recovery to flash it. Flash it to both slots to be safe: https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/jasmine_sprout_stock_android9.zip
