### ISSUE TITLE
32-bit Windows

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#228]
Seeing multiple issues with 32-bit arch on Windows, i'm actually not entirely sure we provide 32-bit binaries (and I'm also not entirely sure if we should). Also, could it be that #224 only occurs on 32-bit hosts?

**Comment by UniversalSuperBox** [comment]
We do currently provide a 32-bit binary for Windows. 

`file` on the installer builds we're shipping gives `ubports-installer.exe: PE32 executable (GUI) Intel 80386, for MS Windows`. PE32 is the 32-bit only version of the Portable Executable format. On the other hand, `file` on a known 64-bit binary gives `PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows`.

**Comment by NeoTheThird** [comment]
Nvm then, you are right, it seems to work. It might still be worth keeping an eye on #224 on 32 bit, since i have not seen that occur on x64 so far.
