### ISSUE TITLE
[Fix included] VollaOS doesn't download for Volla Phone

### ISSUE THREAD

**Issue by Ashiette** [ubports/ubports-installer#2285]
**UBports Installer `0.8.9-beta` (deb)**
Environment: `Zorin 16 focal linux 5.11.0-40-generic x64 NodeJS v12.18.3`
Device: yggdrasil
Target OS: VollaOS
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

When connecting VollaPhone for flashing, VollaOS doesn't download.
Certificate has expired

Error: core:download: Error: core:download Error: Error: Download Error: https://ota.volla.tech/volla-9.0-20201019-nightly-k63v2_64_bsp-signed.zip Error: certificate has expired

**Comment by JoeBeach** [comment]
I have had this same error with the same installer. I was attempting to install Volla OS on a VollaPhone. I had previously used the same installer to install UBports onto it.

**Comment by Ashiette** [comment]
I found a fix, I'm putting it here for future reference. I tried downgrading to UBports-0.8.8 and even previous versions, to no avail. I even tried putting the file on my own server and modify the yggdrasil.yml file which contains all of the info on where to download the repositories, once again to no avail. 

Finally I found a fix :

1. Download the following zip using your favourite browser : https://ota.volla.tech/volla-9.0-20201019-nightly-k63v2_64_bsp-signed.zip 
2. For linux users : copy the zip in ~/.cache/ubports/yggdrasil/VollaOS
For Windows Users : copy the zip in C:\Users\youraccountname\AppData\Roaming\ubports\yggdrasil\VollaOS
3. Close all instances of UBports
4. Launch UBPorts and run the procedure as you would normally. As the file is now cached, it can be accessed directly by the application, hence there is no download error

For advanced users : 
You can also download directly the latest version of VollaOS 10 to be installed by UBports, without having to download VollaOS9, upgrading it 1 time, then upgrading to VollaOS10, and then a third update (~4Gb download size vs 1Gb). 

1. Download the following zip : https://ota.volla.tech/volla-10.0-20210927-release-k63v2_64_bsp-signed.zip 
2. Run a SHA-256 checksum on the file
3. Go to https://github.com/ubports/installer-configs and download v2/devices/yggdrasil.yml
4. Open the file in a text editor and go to the the following lines : `steps:
      - actions:
          - core:download:
              group: "VollaOS"
              files:
                - url: "http://ota.volla.tech/volla-10.0-20210927-release-k63v2_64_bsp-signed.zip"
                  checksum:
                    sum: "0837f19481c9962e9ff3f1249b809942e2563e478f8735236436bd719b49fd5c"
                    algorithm: "sha256"`
5. Change the url with the one provided before and the checksum with the one you got
6. Place the zip in ~/.cache/ubports/yggdrasil/VollaOS for linux or C:\Users\youraccountname\AppData\Roaming\ubports\yggdrasil\VollaOS for Windows
7. Close all instances of UBports and launch UBports. It should install the latest version of VollaOS10 as of November 2021.

**Comment by aszmal** [comment]
Hello, I have a similar problem, I would like to ask for Android 14 software for Volla Quintus phone, I also tried to install Ubuntu Touch and Sailfish via Ubuntu ubports, but there was a problem and that is why I need the original software for Volla Quintus
