### ISSUE TITLE
An SSL Certificate timed out

### ISSUE THREAD

**Issue by JohannesPosch** [ubports/ubports-installer#2306]
**UBports Installer `0.8.9-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: OnePlus 5T
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

When starting to download the phone OS there is an ssl certificate timeout error.

**Comment by JohannesPosch** [comment]
Error: core:download: Error: core:download Error: Error: Download Error: https://deac-ams.dl.sourceforge.net/project/crdroid/dumpling/6.x/firmware/firmware_9.0.11_oneplus5T.zip Error: certificate has expired

This is the error message

**Comment by NeoTheThird** [comment]
please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.
