### ISSUE TITLE
bootloader locked

### ISSUE THREAD

**Issue by ChenxiWong** [ubports/ubports-installer#2317]
**UBports Installer `0.8.9-beta` (deb)**
Environment: `Ubuntu 18.04.6 LTS Bionic Beaver linux 5.4.0-91-generic x64 NodeJS v12.18.3`
Device: cheeseburger
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

show me a document ....

**Comment by NeoTheThird** [comment]
please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.
