### ISSUE TITLE
Installationabbruch  bei UBports Installer  bei Ubuntu-Touch auf Xiaomi Mi A2

### ISSUE THREAD

**Issue by wMKeepassUser** [ubports/ubports-installer#2325]
**UBports Installer `0.8.9-beta` (exe)**
Environment: `Microsoft Windows 7 Professional 6.1.7601 win32 6.1.7601 x64 7601 1.0 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Gerät zeigt Fastboot Mode an

**Comment by wMKeepassUser** [comment]
Das Gerät wird Cleaning Up  system partition wird formatiert.

**Comment by Fazarel** [comment]
It looks like this issue #2330 
Did you try to install the fastboot driver?

_Es sieht aus wie dieses Problem #2330 
Haben Sie versucht, den Fastboot-Treiber zu installieren?
(Automatische Übersetzung)_
