### ISSUE TITLE
had to manually install the drivers for fastboot or the installation would be stuck at fastboot

### ISSUE THREAD

**Issue by 4zv4l** [ubports/ubports-installer#2331]
**UBports Installer `0.9.1-beta` (exe)**
Environment: `Microsoft Windows 10 Famille 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v16.5.0`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/61aa27082eed5d0008ab3bef

fastboot driver requiered

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
