### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by gabreitenbach** [ubports/ubports-installer#234]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/g2s4KDgxqV/

**Comment by NeoTheThird** [comment]
Thanks for reporting, this should be fixed in the next release by #161. For now, you can just try again until it works ;)
