### ISSUE TITLE
Bug on Redmi Note 9 Pro

### ISSUE THREAD

**Issue by N1Kitoxa** [ubports/ubports-installer#2346]
**UBports Installer `0.8.9-beta` (exe)**
Environment: `�������� Windows 11 Pro 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: miatoll
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Error: adb:preparesystemimage: Error: {"error":{"code":126,"cmd":"C:\\Temp\\1ygKXdvCrW1JOtZdfAC3c0dUbus\\resources\\app.asar.unpacked\\node_modules\\android-tools-bin\\dist\\win32\\x86\\adb.exe -P 5037 shell mkdir -p /cache/recovery"},"stderr":"error: Exec '/system/bin/sh' failed: Too many symbolic links encountered"}

**Comment by supechicken** [comment]
Please try again with ubports-installer 0.8.8, see [here](https://gitlab.com/ubports/community-ports/android10/xiaomi-redmi-note-9-pro/xiaomi-miatoll/-/issues/3)
