### ISSUE TITLE
Remote no space left on device

### ISSUE THREAD

**Issue by patrick-tang** [ubports/ubports-installer#2350]
**UBports Installer `0.8.9-beta` (AppImage)**
Environment: `Fedora Linux 35 Workstation Edition linux 5.15.7-200.fc35.x86_64 x64 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Just try to use ubports to flash ubuntu touch

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? see https://github.com/ubports/ubports-installer/issues/1107#issuecomment-590136145 and try again. thanks :)
