### ISSUE TITLE
read properties of null error

### ISSUE THREAD

**Issue by ANIL80531** [ubports/ubports-installer#2374]
**UBports Installer `0.9.1-beta` (source)**
Environment: `Debian GNU/Linux 11 bullseye linux 5.4.151-16908-gff376e5d5ee1 arm64 NodeJS v16.5.0`
Device: oneplus3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A* 

try on arm debain

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
