### ISSUE TITLE
it did not install ubuntu touch

### ISSUE THREAD

**Issue by tikendraw** [ubports/ubports-installer#2377]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Ubuntu 20.04.3 LTS Focal Fossa linux 5.11.0-43-generic x64 NodeJS v12.18.3`
Device: miatoll
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

i had evolution x android 11 and trying to install ubuntu touch

**Comment by nitanmarcel** [comment]
Please, pay attention at the instructions given by the installer. You need to downgrade to stock Android 10 before flashing UT:

  
![image](https://user-images.githubusercontent.com/41646249/148076937-d18f3154-0b86-4ebb-9a9a-d9c4a97a5afd.png)
