### ISSUE TITLE
Could not install firmware - certificate has expired error

### ISSUE THREAD

**Issue by KittDoesntCode** [ubports/ubports-installer#2389]
UBports Installer 0.8.8-beta (deb)
Environment: LinuxMint 20.2 Uma linux 5.11.0-44-generic x64 NodeJS v12.18.3
Device: cheeseburger
Target OS: Ubuntu Touch
Settings: undefined
OPEN-CUTS run: N/A
Log: N/A

Error: core:download: Error: core:download Error: Error: Download Error: https://phoenixnap.dl.sourceforge.net/project/crdroid/cheeseburger/6.x/firmware/firmware_9.0.11_oneplus5.zip Error: certificate has expired

I could open the URL above in Chrome without any error. Received a similar (certificate expired) error when submitting feedback:

Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired

**Comment by NeoTheThird** [comment]
fixed.
