### ISSUE TITLE
"Pushing files to device" keeps getting stuck (Nexus 5)

### ISSUE THREAD

**Issue by andrewwakeling** [ubports/ubports-installer#239]
I am trying to install Ubuntu Touch on my Nexus 5.

I keep getting up to the "Pushing files to device" step. I have not managed to get it to complete. It keeps getting stuck. Sometimes this happens right away. I managed to get about halfway (~50%) through the (1 of 13) files.

I'm currently installing via Ubuntu 16.04 on VirtualBox in Windows 10.

I also installed ubports-installer via snap and ran it in verbose mode.

I get the following output:

```
info: ADB push 9%
debug:
info: ADB push 9%
debug:
```
At some point, this hangs. I don't see any errors and I don't see anything in the log.

I have also tried changing USB cables with no luck/improvement. Any tips on how I can get this to work?

**Comment by andrewwakeling** [comment]
I did some of my own digging. It looks like the command which updates the status is blocking.

```
adb -P 5038 shell stat -t /cache/recovery//ubports- ... .tar.xz
```

If I run this in another tab, it just sits there and never returns. I've also confirmed in the code that the callback is never invoked.

I'll need to dig further to understand why this is happening. Any feedback would be appreciated.

**Comment by NeoTheThird** [comment]
I can not reproduce that. Could you try that with a different usb cable or a different usb slot on your PC? Sometimes the connection gets lost during the process if the cable is of poor quality.

You could also try with the [windows version](https://github.com/ubports/ubports-installer/releases/download/0.1.10-beta/ubports-installer.0.1.10-beta.exe), virtualbox might be doing stuff to the usb connection. Please also send me the full log from `~/.cache/ubports/ubports-installer.log`?

**Comment by andrewwakeling** [comment]
I'm having different issues with Windows. However, the USB communication looks to be much more reliable and faster. (I think you're right about VirtualBox messing up the connection).

It looks like I'm getting very close to getting it working in Windows. I'll raise another issue/PR once I figure out what caused me the issues. Thanks.

**Comment by andrewwakeling** [comment]
I'm closing this issue as I suspect that my original issues were caused by VirtualBox in Windows 10.
