### ISSUE TITLE
I do not get Vodafone network display, I have only WLAN.....

### ISSUE THREAD

**Issue by Juergen-Coding** [ubports/ubports-installer#2398]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Enterprise 10.0.19042 win32 10.0.19042 x64 19042 0.0 NodeJS v12.18.3`
Device: merlin
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

At he end of the installation. ubports given an error: Error: unhandled rejection at [object Promise]: Error: Failed to create run: FetchError: request to https://ubports.open-cuts.org/graphql failed, reason: certificate has expired

**Comment by NeoTheThird** [comment]
fixed.
