### ISSUE TITLE
Support for Samsung Grand 2 (G7105)

### ISSUE THREAD

**Issue by PhilHaiduc** [ubports/ubports-installer#240]
Please Build an image for the Samsung Grand 2 (G7105) because it would be nice :)

**Comment by NeoTheThird** [comment]
Hey there, thanks for your interest in Ubuntu Touch. Creating a port for an Android device is a lot of work, so there are currently no plans for that device. If you want to look into porting yourself, this is where to get started: https://docs.halium.org/en/latest/
