### ISSUE TITLE
My tablet has not been recognised. The software said me that my table (flo) wasn't supported, but it was.

### ISSUE THREAD

**Issue by Baptno** [ubports/ubports-installer#2406]
**UBports Installer `0.8.8-beta` (AppImage)**
Environment: `LinuxMint 20.2 Uma linux 5.4.0-94-generic x64 NodeJS v12.18.3`
Device: flo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Just plug a Nexus 7 2013 WIfi on a Linux Mint PC ?

**Comment by NeoTheThird** [comment]
impossible to reproduce without logs. please open a new issue if this problem arises again.
