### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by ArthurAdinArchi3A** [ubports/ubports-installer#241]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/YGJVjjgkBz/

**Comment by NeoTheThird** [comment]
That bug was fixed in the latest version, please update: https://github.com/ubports/ubports-installer/releases/latest
