### ISSUE TITLE
Bricked my Vollaphone X with Waydroid

### ISSUE THREAD

**Issue by IanHasman** [ubports/ubports-installer#2412]
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-92-generic x64 NodeJS v12.18.3`
Device: yggdrasil
Target OS: Volla OS
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Tried to load waydroid from the app on openstore. Phone rebooted and stuck at Volla splashscreen. Rebooted to recovery mode and attempted to re-install UBports. Failed and phone would not go into recovery mode. Tried to install Volla but had to manually select Vollaphone X as it would not auto detect. Failed part way through. Eventually got phone back to select "fastboot" and tried again with UBports - still hoping to recover my data. Again failed, downloads to phone then PC sits "waiting for device". 

Had another go and autodetected as Vollaphone (not Vollaphone X) and completed installation. Now the phone will not even turn on. Quite annoyed as it was an expensive phone. Can be contacted on i.hasman@ntlworld.com.

UPDATE 27/1/22
Managed to get my phone back up and running thanks to the UB Ports forum:-

https://forums.ubports.com/topic/6740/bricked-volla-x-phone/43?_=1643121164922

See comments added 25/1/22

Any chance of looking into why the phone autodetected as the wrong "flavour" on the installer?

**Comment by Flohack74** [comment]
Waydroid is not yet an officially released prodcut and considered devel stage - as such there are risks involved installing it, and we do not recommend it for people that have to rely on their device.

Glad that you could fix it though!
