### ISSUE TITLE
UBports Installer - flashing stable failed on Fairphone 3. 

### ISSUE THREAD

**Issue by TK1987** [ubports/ubports-installer#2419]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19043 win32 10.0.19043 x64 19043 0.0 NodeJS v12.18.3`
Device: FP3
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

After first reboot, the device showing "Installing update". On second reboot, the device only boots to fastboot.
Just used the installer.
Previously installed OS: LineageOs 18.1.

**Comment by dimitri-bourreau** [comment]
@TK1987 did you manage to process the installation properly?
