### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.406s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.407s

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-installer#242]
Happens when trying to install 16.04 devel on FP2

Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/9ZFHgZ4JpJ/

**Comment by Flohack74** [comment]
![grafik](https://user-images.githubusercontent.com/16186470/39838848-cb01f25a-53da-11e8-857b-c758b105b75b.png)

**Comment by jonnius** [comment]
Duplicate of #184?

**Comment by Flohack74** [comment]
Yes but then during the popup I cannot see this right away ;)
