### ISSUE TITLE
Do not install if UBports recovery is not identified

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-installer#2420]
See https://github.com/ubports/halium_bootable_recovery/issues/22 - Installer needs to stop installation if a different recovery than UBports recovery is identified for various reasons, mostly that TWRP et.al. cannot handle fake cache and also do not have the system-image preparation script inside.

**Comment by amartinz** [comment]
This is possible now with https://github.com/ubports/ubports-installer/pull/2529 and needs installer config changes done by the maintainers.
