### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11436 KB)...OKAY [  0.538s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.541s

### ISSUE THREAD

**Issue by Jimsat2000** [ubports/ubports-installer#243]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/cyNhHbdwy8/

**Comment by Jimsat2000** [comment]
I can not install ubuntu on my BQ M10 HD

**Comment by fabrei** [comment]
i had the same log messages. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)
