### ISSUE TITLE
installation instructions for my device are not clear and my device (s8) is stuck in boot loop.

### ISSUE THREAD

**Issue by v5916** [ubports/ubports-installer#2444]
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.13.0-28-generic x64 NodeJS v12.18.3`
Device: trltetmo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Either we can make UBports universal for all devices or we can add support for more old but usable devices.

**Comment by NeoTheThird** [comment]
what instructions are unclean in particular?

**Comment by v5916** [comment]
I tried installing ubuntu touch on my s8(exynos) and I am  aware that ubport does not support my device but i want to help in adding support for my device but i only have limited skills in c++.

**Comment by sanathusk** [comment]
If the device is not listed among the list of supported devices , i will most probably require to ported.Please feel free to join the telegram group
https://t.me/halium to get help on Halium porting guide.
Refer the following porting guides :

https://docs.ubports.com/en/latest/porting/introduction.html

**Comment by sanathusk** [comment]
@NeoTheThird  May we can close the issue.It is not specific to UBports installer

**Comment by v5916** [comment]
thanks for support
