### ISSUE TITLE
m

### ISSUE THREAD

**Issue by Kapytus** [ubports/ubports-installer#2446]
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.11.0-40-generic x64 NodeJS v12.18.3`
Device: onclite
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

k

**Comment by sanathusk** [comment]
@Kapytus Can you please add more details about the issue that you are facing.Looks like you have missed adding the details.
