### ISSUE TITLE
no boot

### ISSUE THREAD

**Issue by ltkun** [ubports/ubports-installer#2452]
**UBports Installer `0.8.9-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.13.0-27-generic x64 NodeJS v12.18.3`
Device: violet
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

THIS TIME is android 9  cn stock

**Comment by NeoTheThird** [comment]
please try again with [the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) and open a new issue if the problem persists.
