### ISSUE TITLE
Managed to install but the installer crashed at one point so I had to redo

### ISSUE THREAD

**Issue by rambonette** [ubports/ubports-installer#2463]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `Ubuntu 20.04.3 LTS Focal Fossa linux 5.4.0-97-generic x64 NodeJS v12.18.3`
Device: flo
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

don't know how to reproduce, sorry. Went fine the second time.

**Comment by NeoTheThird** [comment]
thanks for letting us know, but there's not much we can do just like that. glad it worked the second time!
