### ISSUE TITLE
 Download is toooooooooooooslow

### ISSUE THREAD

**Issue by ZH-XiJun** [ubports/ubports-installer#2470]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 11`
Device: cancro
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

it is VERY slow when I was downloading the file. at last, i found the server(system-image.ubports.com, right?) and downloaded with aria2. Maybe you can try to use another download tool to reach faster speed. Thx a lot and my phone can use ubt normally now.

**Comment by NeoTheThird** [comment]
no idea how your network is configured, but normally it should be fine. likely not an issue on our side. in any case, happy you got it to work for yourself :)
