### ISSUE TITLE
"manual instructions for every device" link fails to open

### ISSUE THREAD

**Issue by nmz787** [ubports/ubports-installer#2472]
I just hit this error with the installer, which was not present late last year `Error: systemimage:install: Error: 404`

so now that my phone only reboots to the "ubports recovery", I wanted to try "manual instructions for every device", but when I click that, I just see this in my terminal:
`user-open error: dbus: invalid bus address (invalid or unsupported transport)`

**Comment by NeoTheThird** [comment]
no longer present in 0.9.x. thanks for reporting
