### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by saltboy77** [ubports/ubports-installer#2475]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 7 Professional 6.1.7601 win32 6.1.7601 x64 7601 1.0 NodeJS v12.18.3`
Device: lancelot
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

fail run to ubports

**Comment by Fuseteam** [comment]
hi what error did you see?
