### ISSUE TITLE
Cannot install on my Nexus 5

### ISSUE THREAD

**Issue by mys31f** [ubports/ubports-installer#2477]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 11 Pro 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: hammerhead
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

I have not been able to install Ubuntu onto my Nexus 5 at all, both on Windows and a Fedora laptop using the AppImage file.
adb returned this:
```Error: adb:push: Error: {"error":{"code":1},"stdout":"adb: error: failed to copy 'C:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\ubports-5787dba4839ad2a99e420d9a1e58ce6d0940796598db4c0a31f3908e2d2e01c6.tar.xz' to '/cache/recovery/ubports-5787dba4839ad2a99e420d9a1e58ce6d0940796598db4c0a31f3908e2d2e01c6.tar.xz': remote No space left on device\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\ubports-5787dba4839ad2a99e420d9a1e58ce6d0940796598db4c0a31f3908e2d2e01c6.tar.xz: 1 file pushed, 0 skipped. 10.5 MB/s (369132452 bytes in 33.597s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\ubports-5787dba4839ad2a99e420d9a1e58ce6d0940796598db4c0a31f3908e2d2e01c6.tar.xz.asc: 1 file pushed, 0 skipped. 0.2 MB/s (488 bytes in 0.002s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\device-48f008aae9f1a867b50ee435b8abd982f596098effd459c02d13ff55729b6242.tar.xz: 1 file pushed, 0 skipped. 10.4 MB/s (59674516 bytes in 5.483s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\device-48f008aae9f1a867b50ee435b8abd982f596098effd459c02d13ff55729b6242.tar.xz.asc: 1 file pushed, 0 skipped. 0.2 MB/s (488 bytes in 0.002s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz: 1 file pushed, 0 skipped. 6.2 MB/s (1564 bytes in 0.000s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\keyring-28992f008be20d562ea06745f563d3abe00b08da1b16e5b92e448e2d4ba21e9f.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (488 bytes in 0.002s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\version-20.tar.xz: 1 file pushed, 0 skipped. 2.1 MB/s (472 bytes in 0.000s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\version-20.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (488 bytes in 0.001s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\image-signing.tar.xz: 1 file pushed, 0 skipped. 0.7 MB/s (940 bytes in 0.001s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\image-signing.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (488 bytes in 0.001s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\image-master.tar.xz: 1 file pushed, 0 skipped. 0.4 MB/s (900 bytes in 0.002s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\image-master.tar.xz.asc: 1 file pushed, 0 skipped. 0.3 MB/s (488 bytes in 0.002s)\r\nC:\\Users\\Lam Bui Bao\\AppData\\Roaming\\ubports\\hammerhead\\Ubuntu Touch\\ubuntu_command: 1 file pushed, 0 skipped. 0.4 MB/s (727 bytes in 0.002s)\r\n13 files pushed, 0 skipped. 10.2 MB/s (428814499 bytes in 40.018s)"}```

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? see https://github.com/ubports/ubports-installer/issues/1107#issuecomment-590136145 and try again. thanks :)

**Comment by mys31f** [comment]
Somehow I couldn't repartition at all whatsoever, no matter what script I try. I'mma try ticking the "Format system partition" option in the installer, let's see if it helps.
