### ISSUE TITLE
Uncaught Error: [21819:21833:0512/095805.698452:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process. (MainRenderer:39)

### ISSUE THREAD

**Issue by SEVY1** [ubports/ubports-installer#248]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/gzK5xYDgJW/

**Comment by NeoTheThird** [comment]
Please try again with [the latest release](https://github.com/ubports/ubports-installer/releases/latest).
