### ISSUE TITLE
Download from sourceforge failed due to expired cert

### ISSUE THREAD

**Issue by jbagwell-premier** [ubports/ubports-installer#2480]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19044 win32 10.0.19044 x64 19044 0.0 NodeJS v12.18.3`
Device: dumpling
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Attempt to install oneplus 5t

**Error:**
```
Failed to download
```

**Comment by NeoTheThird** [comment]
seems to be fixed on their side now
