### ISSUE TITLE
Unable to flash the OS as Redmi4 stuck at FASTBOOT stage

### ISSUE THREAD

**Issue by pradiptapks** [ubports/ubports-installer#2490]
**UBports Installer `0.8.8-beta` (deb)**
Environment: `LinuxMint 20.3 Una linux 5.4.0-104-generic x64 NodeJS v12.18.3`
Device: santoni
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

In Redmi4, I unlock the OEM and USB debug mode. UBport easily recognised the device and proceed with the Redmi4X profile with the stable release. After it triggers a reboot and once the device gets rebooted the device gets stuck at the FIRSTBOOT stage.

**Comment by NeoTheThird** [comment]
Please make sure you followed the steps the installer instructed before installation:

- **OEM unlock**: If you haven't done so already, make sure to OEM unlock your device first: https://en.miui.com/unlock
- **Support**: For details about Ubuntu Touch support for the Redmi 4X, please head over to the UBports forum thread: https://forums.ubports.com/topic/3682/xiaomi-redmi-4x-santoni

Then, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
