### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by TomRausner** [ubports/ubports-installer#250]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/fXpDcgXn8j/

**Comment by TomRausner** [comment]
tried to install without develloper mode and without wipe

**Comment by NeoTheThird** [comment]
This was fixed in [the latest release](https://github.com/ubports/ubports-installer/releases/latest). Please update.
