### ISSUE TITLE
I recived Error: core:manual_download: Error:checksum mismatch

### ISSUE THREAD

**Issue by lauris0910** [ubports/ubports-installer#2506]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 10 Education 10.0.19044 win32 10.0.19044 x64 19044 0.0 NodeJS v12.18.3`
Device: lavender
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Not sure myself, but it keeps happening
Error: core:manual_download: Error: checksum mismatch

**Comment by NeoTheThird** [comment]
[from looking at the config](https://github.com/ubports/installer-configs/blob/master/v2/devices/lavender.yml#L61), my guess is you'll have to unzip the file and feed the `vendor.img` file into the installer. please let me know if that worked, then i'll update the config accordingly.

**Comment by NeoTheThird** [comment]
alright, you can now just load the zip file, the checksum has been updated accordingly. no need to unpack manually. sorry for the inconvenience :)
