### ISSUE TITLE
Fastbooting took too much time

### ISSUE THREAD

**Issue by neatsdude** [ubports/ubports-installer#2507]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 11 Home Single Language 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: jasmine_sprout
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Flashbooting the partition took too much time

**Comment by NeoTheThird** [comment]
Hey, sorry about this. Could you try again with [this prerelease version](https://github.com/ubports/ubports-installer/releases/tag/0.9.2-beta) of the installer? If the issue persists, please report it again (the new version should automatically include a log, which is missing here. Thanks!
