### ISSUE TITLE
впр

### ISSUE THREAD

**Issue by Egorckaaa** [ubports/ubports-installer#2510]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `�������� Windows 11 Pro 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: X00TD
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

не может отформатировать систему

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
