### ISSUE TITLE
Sometimes when i start installer it gives some error but after ignore it goes, but it don't install os on devices. After relaunch installer its work fine.

### ISSUE THREAD

**Issue by sauravptl** [ubports/ubports-installer#2512]
**UBports Installer `0.8.8-beta` (exe)**
Environment: `Microsoft Windows 11 Pro 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: oneplus3t
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

It will come when device in TWRP and start install ubuntu recovery.

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
