### ISSUE TITLE
Rebooting

### ISSUE THREAD

**Issue by WizardOfWor1969** [ubports/ubports-installer#2513]
**UBports Installer `0.9.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.10.0-12-amd64 x64 NodeJS v16.13.0`
Device: [oneplus3]
(https://devices.ubuntu-touch.io/device/oneplus3)
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6235f9695f24330008986815
Pastebin: https://snip.hxrsh.in/ubi-1647704424911

Installer says rebooting, phone goes to FASTBOOT more (START) and sits there.

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:

- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/

After that, please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
