### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by WizardOfWor1969** [ubports/ubports-installer#2515]
**UBports Installer `0.9.2-beta` (AppImage)**
Environment: `Debian GNU/Linux 11 bullseye linux 5.10.0-12-amd64 x64 NodeJS v16.13.0`
Device: [oneplus3]
(https://devices.ubuntu-touch.io/device/oneplus3)
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6235fd595f24330008986b50

Installer stops on Waiting for Device, Phone says Android Recovery with menu that has options Reboot system now, Ubuntu actions and Android actions

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
Please double check you followed the instructions in the beginning of the installation:
- **TWRP**: The installation instructions for this device are not fully tested yet. If you come from Android, you will have to install TWRP and format to ext4 `/data` and `/system` from inside TWRP before you can install Ubuntu Touch. If errors occur, it is recommended to wipe all partitions, reboot to recovery again, then wipe all partitions again. More info: https://twrp.me/oneplus/oneplusthree.html
- **Update to latest available version**: Before installing anything, make sure the OnePlus3/3T is updated to the latest version of OxygenOS (9.0.6). More info: https://www.oneplus.com/support/softwareupgrade/
