### ISSUE TITLE
helper run full cpu core

### ISSUE THREAD

**Issue by gshmu** [ubports/ubports-installer#2517]
**UBports Installer `0.9.2-beta` (dmg)**
Environment: `macOS 12.3 macOS Monterey darwin 21.4.0 x64 21E230 NodeJS v16.13.0`
Device: [dumpling]
(https://devices.ubuntu-touch.io/device/dumpling)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6237050e5f24330008987bac

limit or remove the render will be better
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/1797676/159158591-06aa4a59-014d-4bf0-8fa8-3edb5b135263.png">

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
you can disable the animations in the settings
