### ISSUE TITLE
Program stop at Cleaning up/Formating userdata partition screen,and no longer go next

### ISSUE THREAD

**Issue by commandoccz** [ubports/ubports-installer#2523]
**UBports Installer `0.9.3-beta` (exe)**
Environment: `Microsoft Windows 10 专业版 10.0.19044 Windows 10.0.19044 x64 19044 0.0 NodeJS v16.13.0`
Device: [sagit]
(https://devices.ubuntu-touch.io/device/sagit)
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/623a04095f2433000898b3f2
Pastebin: https://snip.hxrsh.in/ubi-1647969287842

Program stop at Cleaning up/Formating userdata partition screen,and no longer go next

**Error:**
```
Unknown Error
```

[ubports-installer.log](https://github.com/ubports/ubports-installer/files/8326606/ubports-installer.log)

![image](https://user-images.githubusercontent.com/76011848/159540816-f46f71bf-09cd-4d10-87c2-cdd404eb0867.png)

**Comment by commandoccz** [comment]
![image](https://user-images.githubusercontent.com/76011848/159542154-b127ad98-c3ee-4c65-bb5f-1b7a86bc6251.png)

**Comment by commandoccz** [comment]
(bootloader) crc:1
(bootloader) anti:1
(bootloader) DP:0x0
(bootloader) token:D/k3KbUDSdiDU432N0Ma80=
(bootloader) board_version:1.4.0
(bootloader) unlocked:yes
(bootloader) off-mode-charge:1
(bootloader) charger-screen-enabled:1
(bootloader) battery-soc-ok:yes
(bootloader) battery-voltage:4269
(bootloader) version-baseband:`酎
(bootloader) version-bootloader:`酎
(bootloader) variant:MSM UFS
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache: 0x10000000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata: 0x1C09FFB000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system: 0x140000000
(bootloader) wcnss:1
(bootloader) serial:c4gfse49
(bootloader) product:sagit
(bootloader) max-download-size:536870912
(bootloader) kernel:uefi

**Comment by NeoTheThird** [comment]
This should be a windows driver issue, fastboot does not see your device. Please see #1922 for hints to resolve this.
