### ISSUE TITLE
Wi-fi doesn't work after update on nexus 5

### ISSUE THREAD

**Issue by fw190d13** [ubports/ubports-installer#253]
Phone: Nexus 5 with latest radio
OS: Solus
Installer: snap package

Version flashed: 16.04

Expected behavior: after updating via the OTA and after the phone reboots Wi-fi should work normally but it doesn't - no wi-fi networks are available and connected

Workaround: turn on GPS and Blootooth and after a while Wi-Fi is again working

**Comment by NeoTheThird** [comment]
Might be a hardware issue (wifi issues are not unprecedented on the nexus 5) or an issue with the xenial devel image, but it's not related to the Installer.
