### ISSUE TITLE
UBinstaller got stuck on {"level":"verbose","message":"running adb action wait"}

### ISSUE THREAD

**Issue by cecacodes** [ubports/ubports-installer#2531]
**UBports Installer `0.9.2-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-91-generic x64 NodeJS v16.13.0`
Device: [hammerhead]
(https://devices.ubuntu-touch.io/device/hammerhead)
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/623c6919bfb7110008fb3da5
Pastebin: https://snip.hxrsh.in/ubi-1648126232663

I rebooted the phone in recovery mode which seems to have done the trick.  Attached is my log:

[ubports-installer.log](https://github.com/ubports/ubports-installer/files/8341545/ubports-installer.log)

**Comment by NeoTheThird** [comment]
Sounds like your device just wasn't in developer mode, so it wasn't listening on adb. The installer tells you that :cowboy_hat_face:. But glad it worked in the end. Sounds like a small usability issue that might be improved by #1593. Thanks for reporting :)
