### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by mmetzler1** [ubports/ubports-installer#2538]
**UBports Installer `0.9.3-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-74-generic x64 NodeJS v16.13.0`
Device: [jingpad_a1]
(https://devices.ubuntu-touch.io/device/jingpad_a1)
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/623e0848bfb7110008fb541e
Pastebin: https://snip.hxrsh.in/ubi-1648232519847

After Update Jingpad was hanging with the boot logo. Cache reset and Factory reset didn't help.
Trying to reinstall with UBPorts-Installer failed know too.

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
Sorry, should be fixed in [the next version](https://github.com/ubports/ubports-installer/releases/0.9.5-beta). The stable channel does not work rn, use the devel channel please. Thanks!
