### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by killed2** [ubports/ubports-installer#2539]
**UBports Installer `0.9.3-beta` (snap)**
Environment: `Solus linux 5.15.30-212.current x64 NodeJS v16.13.0`
Device: [beryllium]
(https://devices.ubuntu-touch.io/device/beryllium)
Target OS: (target os not yet set)
Settings: `undefined`
OPEN-CUTS run: https://ubports.open-cuts.org/run/623e1a58bfb7110008fb54a3
Pastebin: https://snip.hxrsh.in/ubi-1648237141679

For the last flashing step (adb looking for device) it would be nice to be notified that you should reboot to recovery. other than that, it worked great.

**Error:**
```
Unknown Error
```

**Comment by NeoTheThird** [comment]
there should be a notification in the configs now, afaics
