### ISSUE TITLE
Installer stuck at "Flashing firmware..."

### ISSUE THREAD

**Issue by lk108** [ubports/ubports-installer#2540]
**UBports Installer `0.9.3-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.10.0-12-amd64 x64 NodeJS v16.13.0`
Device: [`FP2`](https://github.com/ubports/installer-configs/blob/70fb56f596bce91548d9cb3d25da345883d4f582/v2/devices/FP2.yml) ([Fairphone 2](https://devices.ubuntu-touch.io/device/FP2/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"channel":"ubports-touch/16.04/stable"}`
OPEN-CUTS run: https://ubports.open-cuts.org/run/623e3f88bfb7110008fb5b56
Pastebin: https://snip.hxrsh.in/ubi-1648246664591

FP2 with UT already installed. Trying to reinstall to test the new installer. Installer detects the device, it reboots to bootloader and the installer shows "Flashing firmware... Flashing firmware partitions using fastboot". Nothing happens after this, the installation does not continue.

**Comment by lk108** [comment]
When de-selecting Bootstrap, the installer downloads some files, then the device reboots to the Recovery and the installer shows "Waiting for device... Adb is scanning for devices". Again, it's stuck and the installation does not continue.

**Comment by NeoTheThird** [comment]
Hi there, sorry about that. Seems like the installer can't recognize the device. Here's some things you can try: https://docs.ubports.com/en/latest/userguide/install.html#device-not-detected
