### ISSUE TITLE
Trouble auto detecting device

### ISSUE THREAD

**Issue by TraceHadfield** [ubports/ubports-installer#2544]
**UBports Installer `0.9.5-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.4.0-105-generic x64 NodeJS v16.13.0`
Device: [`jasmine_sprout`](https://github.com/ubports/installer-configs/blob/c5134298e2002f7284fc6b2663435971e43b5d54/v2/devices/jasmine_sprout.yml) ([Xiaomi Mi A2](https://devices.ubuntu-touch.io/device/jasmine_sprout/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: https://ubports.open-cuts.org/run/623f9bc3bfb7110008fb70dd
Pastebin: https://snip.hxrsh.in/ubi-1648335810902

I did normal install per instructions

**Comment by TraceHadfield** [comment]
Was not jasmine_sprout, I choice Halium 9.0.

**Comment by NeoTheThird** [comment]
fixed, thanks for reporting
