### ISSUE TITLE
Installer 0.9.5 - OnePlus5T

### ISSUE THREAD

**Issue by acranglesim** [ubports/ubports-installer#2545]
Hi,

The new installer no longer throws an error about certificates (#2422) however when it has finished downloading the files, it says rebooting to bootloader, and the device is powered off rather than rebooted.

Current OS is ubuntu touch, with developer mode on. Bootloader unlocked already.

Expected outcome: device rebooted, ubuntu touch installed.

Actual outcome: device powered off, no re-install of the OS.

**Comment by acranglesim** [comment]
as a follow up, i tried to manually run adb reboot fastboot, and it powered the device off.

**Comment by Flohack74** [comment]
Rebooting the live UT device into recovery or fastboot might fail, to confirm, if you manually reboot into recovery, can you continue from there?

**Comment by acranglesim** [comment]
I was able to finish the install by getting to that step, unplugging the phone, manually booting it into recovery, and plugging it back in :)
