### ISSUE TITLE
\n

### ISSUE THREAD

**Issue by colbobs** [ubports/ubports-installer#256]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/XCcSxZNQrt/

**Comment by NeoTheThird** [comment]
Please upgrade to [the latest version](https://github.com/ubports/ubports-installer/releases/latest).
