### ISSUE TITLE
Uncaught Error: EACCES: permission denied, mkdir '/home/fw190/snap/ubports-installer/122/.cache/ubports/pool' (MainRenderer:90)

### ISSUE THREAD

**Issue by fw190d13** [ubports/ubports-installer#257]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Solus 3.9996
Package: Snap 
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/njv6Q2yBKr/

**Comment by NeoTheThird** [comment]
Is this really the latest official build? We had that problem w/ an early version of the system-image-module just before the release of 0.1.13-beta, but it was fixed! Could you send me the output of `snap info ubports-installer`?

**Comment by fw190d13** [comment]
`name:      ubports-installer
summary:   The easy way to install Ubuntu Touch on UBports devices.
publisher: mariogrip
contact:   https://github.com/ubports/ubports-installer/issues/new
license:   unknown
description: |
  A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported
  device to your PC, follow the on-screen instructions, and watch this awesome
  tool do all the rest!
commands:
  - ubports-installer
snap-id:   mq0sTMV7a8744UTRBwQHimStAqsGzbjj
tracking:  stable
refreshed: 2018-05-02T21:20:48+02:00
installed:   0.1.13-beta (122) 105MB -
channels:                      
  stable:    0.1.13-beta (122) 105MB -
  candidate: 0.1.13-beta (122) 105MB -
  beta:      0.1.13-beta (122) 105MB -
  edge:      0.1.13-beta (122) 105MB -
`

**Comment by NeoTheThird** [comment]
Huh. `which ubports-installer` please. For multi-line codeblocks on github, you can use three backticks, btw.

**Comment by fw190d13** [comment]
How to check which one? It's a snap on Solus and from the above output I presume the stable one.

**Comment by NeoTheThird** [comment]
`which` is a command that shows you what binary is run. That's why I want you to run `which ubports-installer` and send me the output.

**Comment by fw190d13** [comment]
Sorry for that. I read it as "Which" would not be a command. 

```
fw190@wurger ~ $ which ubports-installer
/snap/bin/ubports-installer
```

**Comment by NeoTheThird** [comment]
It might be that solus doesn't implement the confinement properly... Please try `snap refresh ubports-installer --devmode --edge` and see if it works then.

**Comment by fw190d13** [comment]
```
fw190@wurger ~ $ snap refresh ubports-installer --devmode --edge
ubports-installer (edge) 0.1.13-beta from 'mariogrip' refreshed
fw190@wurger ~ $ 
```

**Comment by NeoTheThird** [comment]
yeah, so does the installer work now?

**Comment by fw190d13** [comment]
It works !!!
Had Android slapped back on it yesterday to see if WiFi works as expected and today pushed 16.04 and for the first time in months I was able to install Ubuntu Touch from Solus! Thank you for your assistance!

**Comment by NeoTheThird** [comment]
Sure, always happy to help. I'm just a little confused why this particular problem ocurred, it might be that snappy isn't correctly implemented in solus, since that path should have been reachable for the snap... Let's keep this open for now.
