### ISSUE TITLE
Windows: Link to the SDK Platform Tools instead of Universal ADB Drivers

### ISSUE THREAD

**Issue by andrewwakeling** [ubports/ubports-installer#260]
In Windows, the installer pops open a dialog as below:
![image](https://user-images.githubusercontent.com/1066963/40059347-303c5d16-5897-11e8-94ba-24af4563c30d.png)

When I install the linked Universal ADB drivers it only appears to install `adb.exe` at `C:\Program Files (x86)\ClockworkMod\Universal Adb Driver`.

It's possible download the small subset of SDK tools (including adb and fastboot) on the official website here: https://developer.android.com/studio/releases/platform-tools

Can this link be updated to point there?

**Comment by NeoTheThird** [comment]
But you still need the device-specific drivers, right? The goal in linking to the universal driver was to have generic instructions.

**Comment by andrewwakeling** [comment]
I'm unsure what you mean by device-specific. For me, Windows 10 automatically detects my phone so there was no need to install drivers.
If anything, can there a be a link to both sites? (ie. The SDK & and the Universal ADB driver sites?)

**Comment by NeoTheThird** [comment]
When you say "detects", you mean it opened an mtp connection? I think you still need to install an ADB driver for the device manually, right?

**Comment by andrewwakeling** [comment]
Yep, I must be misunderstanding the purpose of the Universal ADB drivers. In my case, I probably need to use both.
I was fiddling around with a few things and I'm fairly sure that the bundled adb/fastboot binaries weren't working for me.

**Comment by NeoTheThird** [comment]
If you say you tweaked paths, you were running the installer from source, right? In that case, the system binaries are used

**Comment by andrewwakeling** [comment]
I was tweaking paths in the adb.js and fastboot.js modules, to point to the binaries I installed via the SDK platform tools.

**Comment by NeoTheThird** [comment]
Yeah, but did you clone the repo and run it with npm, or download and edit the .exe?

**Comment by andrewwakeling** [comment]
Yep, I cloned the repo and ran via npm.

**Comment by NeoTheThird** [comment]
Yeah, then it's looking for them in your system. For the record, where are they in your case?

**Comment by andrewwakeling** [comment]
I extracted them to `C:\android-platform-tools\platform-tools` then added this to my PATH as a system environment variable.
I might be wrongfully assuming that the bundled binaries aren't working though. It could have been https://github.com/ubports/ubports-installer/issues/262 causing problems.

**Comment by Flohack74** [comment]
@andrewwakeling Well Windows 10 might detect your phone, but for example Windows 7 does not. So some INF files for USB are necessary, and we want coherent instructions for all users. So the universal package is the one what geve most people success with the installer. Plus, we had some issues in the installer itself, which might have been resolved now. Please try this test build: https://ci.appveyor.com/api/buildjobs/6y6may7umpkpscfj/artifacts/dist%2Fubports-installer%200.1.17-beta.exe

**Comment by NeoTheThird** [comment]
Please try again with [the latest release](https://github.com/ubports/ubports-installer/releases/latest).
