### ISSUE TITLE
Suggestion: Allow users to specify paths to adb and fastboot binaries

### ISSUE THREAD

**Issue by andrewwakeling** [ubports/ubports-installer#261]
It's a little unclear how the installer resolves paths to the adb and fastboot binaries.

I think it would be really beneficial for there to be an advanced option to allow users to specify a custom path (e.g. via a file picker).

(FYI, I actually got the Windows installer working after hardcoding the paths in a few modules).

**Comment by NeoTheThird** [comment]
The binaries are shipped with the application, i don't really see why you would need to run custom ones. But if you want to make that, feel free to send a PR ;)

The path issue is tracked in #110.
