### ISSUE TITLE
adb module using single quotes for command line parameters (Windows)

### ISSUE THREAD

**Issue by andrewwakeling** [ubports/ubports-installer#262]
I believe the usage of single quotes in this line:
https://github.com/ubports/ubports-installer/blob/master/src/adb.js#L149

... is causing issues in Windows. Changing this to double quotes seemed to help me to get the installer working in Windows.

**Comment by NeoTheThird** [comment]
Okay, could you send a PR with your changes? Also interesting for @mariogrip for the new node module.
