### ISSUE TITLE
\n

### ISSUE THREAD

**Issue by colbobs** [ubports/ubports-installer#263]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/ScQdTq2BF3/

**Comment by colbobs** [comment]
Following instructions at https://forum.xda-developers.com/nexus-5x/general/guides-how-to-guides-beginners-t3206930
I have been able to get adb version, adb devices and fastboot devices to recognise my device but not fastboot oem unlock, where terminal returns
<...
FAILED (remote: oem unlock is not allowed)
finished. total time: 0.010s
>

So I am now stuck.
Ubports installer still returns the same error.

Help?

**Comment by NeoTheThird** [comment]
What device is this? The guide you linked to is for the Nexus 5x, but we only support the Nexus 5. Those are completely different devices... Sorry!
