### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizesending 'recovery' (13708 KB)...OKAY [  0.700s]writing 'recovery'...FAILED (remote: Security deny - Err:0x2017 )finished. total time: 0.766s

### ISSUE THREAD

**Issue by bellka** [ubports/ubports-installer#265]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/bwFzSQV6N6/

**Comment by NeoTheThird** [comment]
Please try again with the [latest version](https://github.com/ubports/ubports-installer/releases/latest).
