### ISSUE TITLE
Fastboot: Unknown error:  [sudo] contrasenya per a josepjc: downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by josepjc** [ubports/ubports-installer#266]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/Jqvj3bqzvh/

**Comment by josepjc** [comment]
remains on the screen: FAIRPHONE Powered by android

**Comment by jonnius** [comment]
May be a duplicate of #184
