### ISSUE TITLE
Error executing Ubuntu update, exit code: 256; nothing in recovery logs

### ISSUE THREAD

**Issue by omaemae** [ubports/ubports-installer#2666]
**UBports Installer `0.9.5-beta` (AppImage)**
Environment: `Arch rolling linux 5.17.9-zen1-1-zen x64 rolling NodeJS v16.13.0`
Device: [`miatoll`](https://github.com/ubports/installer-configs/blob/ba175c839031d0f84281bb9a2603efaf144b7210/v2/devices/miatoll.yml) ([Xiaomi Redmi Note 9 Pro/Pro Max/9S - Poco M2 Pro](https://devices.ubuntu-touch.io/device/miatoll/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: https://ubports.open-cuts.org/run/6291738bf2a65855f3be3a07
Pastebin: https://snip.hxrsh.in/ubi-1653699467058

**Comment by omaemae** [comment]
I've installed MIUI 11.0.2.0 through recovery ZIP prior to installing Ubuntu Touch.

**Comment by CilekciGs** [comment]
I have the same issue on joyeuse. It used to install just fine.

**Comment by nitanmarcel** [comment]
Something's wrong with your system. Just checked and Ubuntu Touch installs correctly.

Please check you have the correct adb and fastoot drivers for xiaomi.

**Comment by CilekciGs** [comment]
I don't think so, I tried installing on multiple systems (windows/linux) and it didn't fix it. I couldn't find drivers for linux and the drivers for windows were from 2012 and they didn't work. When I was trying to install the drivers from mi flash tool it crashed. I don't think it's about my system(s).

**Comment by nitanmarcel** [comment]
> I don't think so, I tried installing on multiple systems (windows/linux) and it didn't fix it. I couldn't find drivers for linux and the drivers for windows were from 2012 and they didn't work. When I was trying to install the drivers from mi flash tool it crashed. I don't think it's about my system(s).

See the logs from a successful installation. there are 12 files that needs downloading, yours downloads only 4.

for example this is recent

https://github.com/ubports/ubports-installer/issues/2680

**Comment by nitanmarcel** [comment]
Other than that part I don't see anything related to the crash.

**Comment by omaemae** [comment]
there might be some luck on `joyeuse` with a newer version of MIUI ([V12.0.3.0.QJZMIXM](https://xiaomifirmwareupdater.com/miui/joyeuse/stable/V12.0.3.0.QJZMIXM/), still Android 10)

**Comment by omaemae** [comment]
worked for me https://ubports.open-cuts.org/run/62a5ca6436b2d590f5efbbfd

**Comment by nitanmarcel** [comment]
> 

those logs are only for the installer mentainer. Can't read that but glad it worked
