### ISSUE TITLE
Fastboot: Unknown error:  [sudo] пароль для ufuran: < waiting for any device >target reported max download size of 1073741824 bytessending 'recovery' (11802 KB)...OKAY [  0.590s]writing 'recovery'...FAILED (status read failed (No such device))finished. total time: 6.352s

### ISSUE THREAD

**Issue by ufuran** [ubports/ubports-installer#267]
Automatically generated error report 
Version: 0.1.11-beta 
Host OS: linux 
Host Dist: Arch Linux undefined
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/wfzCnkfgwF/

**Comment by NeoTheThird** [comment]
please try agian with the [latest version](https://github.com/ubports/ubports-installer/releases/latest).
