### ISSUE TITLE
Phone stuck at the "turning on" screen

### ISSUE THREAD

**Issue by TeaCupInspector** [ubports/ubports-installer#2680]
**UBports Installer `0.9.5-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.18.1-arch1-1 x64 NodeJS v16.13.0`
Device: [`miatoll`](https://github.com/ubports/installer-configs/blob/ba175c839031d0f84281bb9a2603efaf144b7210/v2/devices/miatoll.yml) ([Xiaomi Redmi Note 9 Pro/Pro Max/9S - Poco M2 Pro](https://devices.ubuntu-touch.io/device/miatoll/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/devel"}`
OPEN-CUTS run: https://ubports.open-cuts.org/run/629e80d27c35084c641adfee
Pastebin: https://snip.hxrsh.in/ubi-1654558215076

Right after finishing the installation the bug appears

**Comment by nitanmarcel** [comment]
Please install the latest Android 10 fastboot image for the device and try again.

https://github.com/miatoll-linux/miatoll-linux/blob/main/README.md

**Comment by TeaCupInspector** [comment]
The same error is happening after I installed the latest fast-boot image but now there is the following error message on my phone screen during the installation: "E:Failed to save locale to /cache/recovery/last_locale:No such file or directory".
    After searching about it online i found someone else had the issue [#2142](https://github.com/ubports/ubports-installer/issues/2142) and it lead to issue [#2147](https://github.com/ubports/ubports-installer/issues/2147) which is supposedly fixed if I didn't misunderstand.
    ¿Do you have an idea of something else i could do to fix this? 
Thanks for the help

**Comment by nitanmarcel** [comment]
> The same error is happening after I installed the latest fast-boot image but now there is the following error message on my phone screen during the installation: "E:Failed to save locale to /cache/recovery/last_locale:No such file or directory". After searching about it online i found someone else had the issue #2142 and it lead to issue #2147 which is supposedly fixed ( [#173](https://github.com/ubports/installer-configs/pull/173)) if I didn't misunderstand. ¿Do you have an idea of something else i could do to fix this? Thanks for the help

Latest **Android 10** image? what version did you install?

**Comment by TeaCupInspector** [comment]
> Latest Android 10 image? what version did you install?

I installed the global version which is the one that my phone had when I had bought it.
https://xiaomifirmwareupdater.com/miui/joyeuse/stable/V12.5.7.0.RJZMIXM/

I will try the installation again... Maybe I screwed it up. I will update you when I finish installing it.

**Comment by nitanmarcel** [comment]
> > Latest Android 10 image? what version did you install?
> 
> I installed the global version which is the one that my phone had when I had bought it. https://xiaomifirmwareupdater.com/miui/joyeuse/stable/V12.5.7.0.RJZMIXM/
> 
> I will try the installation again... Maybe I screwed it up. I will update you when I finish installing it.

That's Android 11. Ubuntu Touch requires Android 10 to be installed. And it has to be the stock MIUI ROM

**Comment by TeaCupInspector** [comment]
Oh, I am so dumb... I will try with that one. Thank you very much.

**Comment by TeaCupInspector** [comment]
Thank you!! The phone was able to successfully install Ubuntu, I am configuring the phone now and I didn't have any issues yet.
Thanks for all the help.

**Comment by nitanmarcel** [comment]
> Thank you!! The phone was able to successfully install Ubuntu, I am configuring the phone now and I didn't have any issues yet. Thanks for all the help.

Glad it worked. If you can, close this issue to mark it as solved. Thanks

**Comment by sanedeeer** [comment]
Hello, i have the same problem. I have installed android 10 but it's don't work.
