### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by flytodream3** [ubports/ubports-installer#2686]
**UBports Installer `0.9.5-beta` (exe)**
Environment: `Microsoft Windows 10 Pro 10.0.19044 Windows 10.0.19044 x64 19044 0.0 NodeJS v16.13.0`
Device: [`miatoll`](https://github.com/ubports/installer-configs/blob/ba175c839031d0f84281bb9a2603efaf144b7210/v2/devices/miatoll.yml) ([Xiaomi Redmi Note 9 Pro/Pro Max/9S - Poco M2 Pro](https://devices.ubuntu-touch.io/device/miatoll/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: https://ubports.open-cuts.org/run/62a0c56402f3d832209b0b6a
Pastebin: https://snip.hxrsh.in/ubi-1654703460632

**Comment by NastyaGrifon** [comment]
Logs indicate no issue. What problem did you experience?

**Comment by nitanmarcel** [comment]
Something's wrong with your system. Just checked and Ubuntu Touch installs correctly.

Please check you have the correct adb and fastoot drivers for xiaomi.

**Comment by flytodream3** [comment]
Installer said that installation complited succesfully, but system didn't boot correct. There was just Redmi screen and nothing else.

**Comment by nitanmarcel** [comment]
> Installer said that installation complited succesfully, but system didn't boot correct. There was just Redmi screen and nothing else.

Have you installed Android 10 stock MIUI before flashing?

**Comment by flytodream3** [comment]
Now it's OK, I tried with stock Android 10.
