### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by kleines-o** [ubports/ubports-installer#269]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/QbZNDyswPx/

**Comment by NeoTheThird** [comment]
Please try again with the [latest version](https://github.com/ubports/ubports-installer/releases/latest)
