### ISSUE TITLE
Does not fail gracefully when device reports that its battery is low

### ISSUE THREAD

**Issue by Mohannes** [ubports/ubports-installer#27]
Installer fails to catch error when battery is low: http://paste.ubuntu.com/25620309/

**Comment by PerinaElectronic** [comment]
Try charging your device before installing

Hope it Helps
Yanko

_(Really sorry for the bad english :/)_

**Comment by PerinaElectronic** [comment]
@Mohannes , try charging your device before installing/updating Ubuntu

hope it helps
Yanko

_(Really sorry for the bad english :/)_
