### ISSUE TITLE
Firmware download impossible

### ISSUE THREAD

**Issue by MiniToffe** [ubports/ubports-installer#2706]
Computer system: Debian 11
Target phone: OnePlus 5
version of UBports: 0.9.5-Beta

Hello,
I'm trying to install UBports on a Oneplus5 (CheeseBurger) but i've some issues with UBports installer. When it tries to download the firmware, the website (https://phoenixnap.dl.sourceforge.net) seems unreachable. I checked with firefox and the website is offline!!
If I try to proceed without the firmware (checkbox option), the installer reboot the phone in fastboot mode and nothing happen anymore...

Thanks for your time and help!!
Toffe

**Comment by Flohack74** [comment]
@MiniToffe please jsut skip that step, its optional. The installer will anyways install complete vendor and system partition for this device. I will remove that OxygenOS udate step since its broken.

**Comment by Flohack74** [comment]
I dont have a device under my fingers now, but I installed it multiple times without this option being checked so I am pretty sure that will work. What had you installed before?

**Comment by MiniToffe** [comment]
Hello and thanks for your answers Flohack74!!  :)

Again, I tryed from OxygenOS 10.0.1, without the option for the firmware in the installer. The installer says "Rebooting to bootloader", the phone restarts in fastboot mode. Then installer says "flashing firmware partitions using fastboot".... and that's all. Both phone & installer are stucked waiting forever....

I made another try with the phone directly in fastbot mode:
Installer: "device not supported (msm8998). Try anyway?" I choose to go on, selecting the OnePlus5 device. Phone reboots in recovery mode. The recovery is now the one with the UBports robot. On the bottom is written "Halium 9". Phone is waiting.
Installer says "Adb is scanning for device..." and that's all....

Any idea?? 
Thanks for help!! Time to go to bed for me!! :)

**Comment by MiniToffe** [comment]
I just made the test. With the phone in UBports recovery mode, the command "adb devices" isn't listing any device.

**Comment by MiniToffe** [comment]
I also noticed that in the fastboot mode, the bootloader is unlocked, but it's also written "secured boot enabled".
Don't know if that's a clue or not...!?

**Comment by MiniToffe** [comment]
Got it!! I had some install try with a previous version of installer (0.9.0) and it worked like a charm!!
A good thing to know for those which have installation problem with 0.9.5 version...
Enjoy!! ;)
