### ISSUE TITLE
Uncaught TypeError: systemImage.getLatestVesion is not a function (MainRenderer:75)

### ISSUE THREAD

**Issue by shiqishao** [ubports/ubports-installer#272]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: ia32 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/sY2Fnv5Bdp/

**Comment by NeoTheThird** [comment]
Please try again with the latest version.
