### ISSUE TITLE
Adb failed to reboot!, reboot failed: -1 : 

### ISSUE THREAD

**Issue by userj** [ubports/ubports-installer#273]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/VTHDmT5xts/

**Comment by NeoTheThird** [comment]
Please try again with [the latest version](https://github.com/ubports/ubports-installer/releases).
