### ISSUE TITLE
Device not supported

### ISSUE THREAD

**Issue by ronbass** [ubports/ubports-installer#2734]
**UBports Installer `0.9.5-beta` (exe)**
Environment: `Microsoft Windows 7 Enterprise 6.1.7601 Windows 6.1.7601 x64 7601 1.0 NodeJS v16.13.0`
Device: `939AX05Y84`
Target OS: undefined
Settings: `{}`
OPEN-CUTS run: https://ubports.open-cuts.org/run/62bdf37be30c706c14a44889
Pastebin: https://snip.hxrsh.in/ubi-1656615800209

I have the Pixel 3a XL and followed instruction to replace Android 12 with 9 Bonito PQ3B.190801.002 (5674421) but it is not recognized by the UBports installer
![image](https://user-images.githubusercontent.com/53493239/176757771-b996199e-4ffb-4013-bfe6-e1a5b2f0a6c5.png)

**Comment by amartinz** [comment]
@fredldotme bonito is not officially listed anywhere but `sargo`s config says "3a/3a XL".

Is this a mistake or should `bonito` be added to aliases?

https://github.com/ubports/installer-configs/blob/ba175c839031d0f84281bb9a2603efaf144b7210/v2/devices/sargo.yml#L4

**Comment by ronbass** [comment]
@amartinz The page link of the 3a/3a XL model (https://devices.ubuntu-touch.io/device/sargo/) shows the following:
![image](https://user-images.githubusercontent.com/53493239/176892042-417b13ee-169d-4b72-86dc-fbc09997e876.png)
The same factory image has different name depending on 3a or 3a XL.
If the Bonito is not supported then **3a XL** link should not be indicated in the Preparatory step.
I am not an Android user but bought a couple of days ago a refurbished 3a XL for that purpose and that leaves me very disappointed. Thank you

**Comment by fredldotme** [comment]
As a volunteer I must admit: I'm saddened all the work is on my shoulders and nobody takes off the weight of fixing the alias by themselves.

I'll look into it...

**Comment by fredldotme** [comment]
And as usual: selecting the device manually from the installer works *right now*

**Comment by ronbass** [comment]
I share your frustration.
But sincerely I have tried the manual installation and got the same result.
I had to upload for the 3rd time the v.9 to get my phone back working because it was stuck on Halium 9 with few options.
Thank you for the hard work, I wish I could help more.

**Comment by amartinz** [comment]
Please wait a few minutes until automation kicks in and deploys the updated installer config. :)

If it still does not find `bonito`, please reopen this issue.

If you run into another issue afterwards (i hope you don't), please open a new issue (so we can have a look at the new installer logs).

**Comment by fredldotme** [comment]
> I share your frustration. But sincerely I have tried the manual installation and got the same result. I had to upload for the 3rd time the v.9 to get my phone back working because it was stuck on Halium 9 with few options. Thank you for the hard work, I wish I could help more.

Follow the hints during the installation and select "Wipe" and "Bootstrap". Everything else I cannot guarantee.
Also, don't touch the device while the UBports Installer is pushing the files to it.

**Comment by ronbass** [comment]
Thank you for the update.
So using the same installation file : _ubports-installer_0.9.5-beta_win_x64_ will get me running now?
Or there is something else I have to consider?

**Comment by ronbass** [comment]
I have just tried again and got to the same issue.
YES it does recognize the 3a XL but after rebooting to recovery the screen shows Halium 9 with 3 options:
Reboot, Factory reset and Advanced.
On the Windows side this is the screenshot, still turning and waiting for device because the Pixel driver is not recognized maybe::
![image](https://user-images.githubusercontent.com/53493239/176897720-4c3c924e-e3ec-4a31-9ac5-9a6de2959e36.png)

**Comment by amartinz** [comment]
Great, that means the device is detected now with the alias properly in place.

The issue you got now is because it lacks drivers. It needs different drivers for normal system operation, while in recovery mode, while in bootloader mode etc.

Usually it is enough to install the Google USB drivers: https://developer.android.com/studio/run/win-usb

**Comment by ronbass** [comment]
Hi Martinz, I did install the Google USB drivers in a prior trial and it showed both ADB drivers with the yellow triangle along with the Pixel one, so it did not really recognize it either.
I will try again and let you know.
Thank you

**Comment by ronbass** [comment]
@amartinz just installing the USB drivers doesn't help. But replacing the Pixel driver with Android **ADB Interface** ( do not use the 2 others ) in the Device manager did push the files through. I think this is important to mention for beginners.
It is working now, thank you for your patience and support.
![image](https://user-images.githubusercontent.com/53493239/176901285-ce6c04c3-656d-4893-b847-ad9a3dc328a2.png)
