### ISSUE TITLE
Pixel 3a XL unable to enter the Ubuntu system

### ISSUE THREAD

**Issue by chanshunli** [ubports/ubports-installer#2759]
Unable to enter the Ubuntu system,  ubports installer directly entered  UBports Recorvery after installation.

![image](https://user-images.githubusercontent.com/6021537/178149999-7c8d434d-ede0-4262-bf1a-f198aab5c5dc.png)

**Comment by lenkhulu** [comment]
Me too! Pixel 3a. 
/tmp/last_kmsg has, at end of ile, many 'cannot get SElinux label on /dev/block/mcblk... device no data available'.

**Comment by lenkhulu** [comment]
But the colour was orange, not yellow; and Slot b

**Comment by lenkhulu** [comment]
It seems the phone cannot now be switched off. From the screen with the message 'Your device is corrupt. etc' pressing vol down and/or power results in screen going blank for about 1 second, but then the message screen reappears.

**Comment by chanshunli** [comment]
It takes many attempts to succeed. ubports-installer is unstable. I tried to install ubports-installer on Mac, Ubuntu, and Windows, and it took many times to succeed. The last success is the success of flashing on Windows. @lenkhulu

**Comment by chanshunli** [comment]
In terms of process: first successfully brush into the UT recovery partition, then enter the UT recovery mode, and brush into the system partition.

**Comment by lenkhulu** [comment]
In the end, I flashed Android 9 and ran UBports again: success. Thanks for your comments, chanshunli.

**Comment by chanshunli** [comment]
@lenkhulu 👍 me too ，But I also installed Android 9 and flashed many times before it worked.
