### ISSUE TITLE
UBports install to Nexus 5"Adb push error:" 

### ISSUE THREAD

**Issue by jpraybs87** [ubports/ubports-installer#276]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: win32 
Host Dist: undefined undefined
Host Arch: ia32 
Node: v7.4.0 

Error log: http://past

**Comment by NeoTheThird** [comment]
Please try again with [version 0.1.9-beta](https://github.com/ubports/ubports-installer/releases/download/0.1.9-beta/ubports-installer.0.1.9-beta.exe). The latest one seems to have problems on Windows.

**Comment by jpraybs87** [comment]
Discovered the previously reported issue only a few hours ago. Sorry for the trouble. Ran the indicated install version. UB Touch is up and running on Nexus 5! Thank you!

**Comment by NeoTheThird** [comment]
Good to hear! Sorry about the trouble. Enjoy your device!
