### ISSUE TITLE
Petition to lock UBports Installer 0.1.13-beta version

### ISSUE THREAD

**Issue by advocatux** [ubports/ubports-installer#278]
Following @Flohack74 suggestion and due to the many problems we are facing in the Install group with UBports Installer 0.1.13-beta version, problems that are quickly solved using UBports Installer 0.1.12-beta, I think we should lock or remove 0.1.13-beta version.

Thank you

**Comment by NeoTheThird** [comment]
No, the update also fixed a lot of issues, like for example failing api downloads and reboots. I don't think 0.1.12 was more stable generally more stable.

**Comment by NeoTheThird** [comment]
Yeah, no, definitely not. I just closed 20 duplicate reports for issues fixed in the latest version that only occur in 0.1.12. I feel like trying to get to a solid 0.1.14 soon is a better way forward.
