### ISSUE TITLE
GS290 is not recognized as vollaphone

### ISSUE THREAD

**Issue by nanu-c** [ubports/ubports-installer#2780]
**UBports Installer `0.9.6-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.15.0-41-generic x64 NodeJS v16.14.2`
Device: [`yggdrasil`](https://github.com/ubports/installer-configs/blob/6c4f2e637714d3c1f62d069e0de0e79d9fbaa60f/v2/devices/yggdrasil.yml) ([VollaPhone](https://devices.ubuntu-touch.io/device/yggdrasil/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/devel"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1658768773490

**Comment by nanu-c** [comment]
The previously installed lineageOS has to be blamed.

**Comment by amartinz** [comment]
We could still add an alias to ensure compatibility and covering this case, what do you think?
