### ISSUE TITLE
Installer does not recognize Oneplus One when it identifies itself as A0001

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-installer#28]
Reported by @Destrocados on Telegram.

For whatever reason, his USB Product string is A0001 instead of One. The Installer fails to do anything because of this.

http://paste.ubuntu.com/25624042/

**Comment by UniversalSuperBox** [comment]
We've got another report of this today. The device was in Fastboot and identified by Windows, but the installer sat dumbfounded.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/21966173/32172322-2f6de272-bd49-11e7-852c-3a84b1a431d7.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/21966173/32172346-4255cd3c-bd49-11e7-9630-2483fa395313.png">

**Comment by NeoTheThird** [comment]
Kind of a hack-fix, but it should do it: https://github.com/ubports/ubports-installer/blob/master/src/adb.js#L60
