### ISSUE TITLE
Device not recognizing 

### ISSUE THREAD

**Issue by Anukul59** [ubports/ubports-installer#280]
I have oneplus1 phone and it was running on cm13 and rooted with supersu, and i tried to install ubuntu touch using latest beta version 0.1.13 also with 0.1.12 but neither this app detects my phone at start nor on fastboot option after selecting device manually. Again i tried to downgrade my phone into CM12 and repeated the same process but nothing happened. And also i tried to use multirom, and flashed multirom twrp but which is not working , it does not letting me to install Multirom v33b/ v32j.

**Comment by NeoTheThird** [comment]
Could you try installing the stock rom? There might be an issue with TWRP...
