### ISSUE TITLE
oneplus 5 install error

### ISSUE THREAD

**Issue by michliu** [ubports/ubports-installer#2805]
Error: core:download: Error: core:download Error: Error: Download Error: https://phoenixnap.dl.sourceforge.net/project/crdroid/cheeseburger/6.x/firmware/firmware_9.0.11_oneplus5.zip Error: connect ETIMEDOUT 184.164.141.26:443

**Comment by Flohack74** [comment]
Please uncheck the option to install those OxygenOS drivers. Its not neede din general, and the download is broken, we will remove that soon.

**Comment by michliu** [comment]
I have uncheck the option , But still fail...
https://ibb.co/z5W9RsS
