### ISSUE TITLE
GUI: drop tsparticles and replace with a different approach

### ISSUE THREAD

**Issue by amartinz** [ubports/ubports-installer#2808]
Currently the installer's rendering process is very crash happy, which be reproduced 10/10 times on my machine (Fedora 36).

After some investigation we came up with the idea to remove `tsparticles` to reduce the ressource usage of the installer and replace it with a different approach, which is still to be discussed.

Jami proposed:
> we could also instead have some slideshow with images/screenshots about Ubuntu Touch
> (similar to what Ubuntu's `ubiquity` installer does)

This issue is meant to start a discussion and track work that needs to be done.

For a first step, however, `tsparticles` should be dropped from the installer.

/cc @Flohack74 @JamiKettunen @maciek134 @NeoTheThird @pajlow

**Comment by maciek134** [comment]
As a quick fix, removing tsparticles here should be enough: [src/ui/partials/Animation.svelte](https://github.com/ubports/ubports-installer/blob/master/src/ui/partials/Animation.svelte)

**Comment by amartinz** [comment]
PR for dropping tsparticles: https://github.com/ubports/ubports-installer/pull/2809

`particle` animations are replaced with `square` animations.
CPU and memory usage have decreased.

![image](https://user-images.githubusercontent.com/2779871/185649651-1aca15b0-b3ef-468c-b4bb-be44df59a81b.png)

**Comment by pajlow** [comment]
@capsia37 made some designs we could use as a start. https://github.com/ubports/ubports-installer/pull/1552#issuecomment-934736910
 Maybe we can still have some moving stuff as a background layer.

**Comment by amartinz** [comment]
> @capsia37 made some designs we could use as a start. [#1552 (comment)](https://github.com/ubports/ubports-installer/pull/1552#issuecomment-934736910)

Nice, thanks for pointing it out!

> Maybe we can still have some moving stuff as a background layer.

Only the "lines" animation was removed and replaced with the "square" animation.
So we still got animations but the `tsparticles` dependency is gone.

Regarding any future GUI planning, i realized this also needs to be done per OS, as if you flash anything else than Ubuntu Touch, it should not show Ubuntu Touch sliders :sweat_smile:

**Comment by pajlow** [comment]
> Regarding any future GUI planning, i realized this also needs to be done per OS, as if you flash anything else than Ubuntu Touch, it should not show Ubuntu Touch sliders

Since we don't really "advertise" the other options (LineageOS, AsteroidOS and Stock Roms) we can probably show the slides for Ubuntu Touch installations only. Other installations would only show Yumi inside the loading circle.

If we want to go with this approach, I would like to work on it. We would need some graphics + texts though.

**Comment by maciek134** [comment]
@pajlow we should probably have it in a way that would allow adding slides for other OSes easily, in case someone would like to contribute them

**Comment by pajlow** [comment]
@amartinz I think we should have another release before the slide show is included. The particles are really causing heavy CPU load.

**Comment by amartinz** [comment]
I agree, however i can not do releases. Only @NeoTheThird and @mariogrip can.

**Comment by amartinz** [comment]
The latest installer release `0.9.7-beta` has tsparticles dropped.

**Comment by Flohack74** [comment]
So can we close it? @amartinz

**Comment by amartinz** [comment]
I think yes, as we could open a new one for the slideshow feature.

**Comment by Flohack74** [comment]
Then do so ;)
