### ISSUE TITLE
MacOS-device not recognised in bootloader mode

### ISSUE THREAD

**Issue by NGStaph** [ubports/ubports-installer#281]
ubports installer cannot connect with phone in bootloader mode.

**Comment by NGStaph** [comment]
Nexus 5

**Comment by harshkalra** [comment]
same issue. cannot connect to nexus 5 in bootloader mode

**Comment by NGStaph** [comment]
Build via cli, that works.

**Comment by NeoTheThird** [comment]
Duplicate of #182
