### ISSUE TITLE
Disk partition customized

### ISSUE THREAD

**Issue by YanqingZhang** [ubports/ubports-installer#2815]
Will it be possible to allow users to choose the partition size themselves in the future?

**Comment by Flohack74** [comment]
Hello,

unfortunately this is quite complicated, as we should not mess with Android firmware partitions (radio, bootloader etc) too much. Ultimately repartitioning means that certain partitions need to be moved. And this will be next to impossible without the risk of bricking the device.

Remember that we still rely on Android low-level parts quite much. We start an Android container that expects certain partitions to be mountable and with the right content. Also bootloader mus tnot be touch to ensure that the device can always be restored/flashed.

There is one example where repartitioning would make sense: The Google Pixel has only 2GB of system partition, but UT would need 2,5-3GB. As such the device cannot be installed properly right now and is dead in the water.

You can however try to partition with TWRP and Android tools, and then install UT on top.
