### ISSUE TITLE
Adb push error: error: device not found

### ISSUE THREAD

**Issue by Blaafot** [ubports/ubports-installer#283]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/xMqKVqcM8V/

**Comment by Blaafot** [comment]
Trying to install Ubuntu touch into Fairphone 2 from a Ubuntu Linux 16.04  I have very little experience with computer programming and code, but my experience with Ubuntu on pc is that this is not really needed so I figured the same for the phone. But installation keeps failing. What to do now? And how to reinstall android 6.0 if Ubuntu does want to install?

**Comment by NeoTheThird** [comment]
Please try again with the [latest version](https://github.com/ubports/ubports-installer/releases/latest) of the Installer. The guide to install android can be found on code.fairphone.com.
