### ISSUE TITLE
VollaPhoneX detected as VollaPhone

### ISSUE THREAD

**Issue by OlThHoCa** [ubports/ubports-installer#2833]
**UBports Installer `0.9.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.10.0-17-amd64 x64 NodeJS v16.15.0`
Device: [`yggdrasilx`](https://github.com/ubports/installer-configs/blob/7753a640fb774d915e358f1db28f396c54827172/v2/devices/yggdrasilx.yml) ([Volla Phone X](https://devices.ubuntu-touch.io/device/yggdrasilx/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"channel":"16.04/arm64/android9/stable"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1662915708146

Connected VollaPhoneX in fastboot mode and started ubports-installer. After this always the wrong VollaPhone device is selected. First time I bricked my Phone this way.

**Comment by NotKit** [comment]
They identify with same BSP codename while in bootloader, so I have no idea how to tell them apart. Ideally bootloader should display a window to select the device between Volla and Volla X with picture.

**Comment by maciek134** [comment]
Should we disable the ability to start the installation in fastboot for both until we can figure this out then?

**Comment by amartinz** [comment]
> Should we disable the ability to start the installation in fastboot for both until we can figure this out then?

I think we should, as bootloaders are not guaranteed to report the correct product name / model.

**Comment by OlThHoCa** [comment]
In this case I would not be able to flash again about ubports-
installer. Currently only the fastboot mode is available.

**Comment by OlThHoCa** [comment]
Currently the phone responds correct following to the model request:
***@***.***:~$ fastboot devices -l
GX290Pro0029432 fastboot usb:1-4

VollaPhone should respond with GS290Pro......

so fastboot responds with correct GX290... Id.

**Comment by maciek134** [comment]
That's just the device ID, on most devices it doesn't include the model information so we can't rely on that. Maybe there is some info in the build versions, can you run `fastboot getvar all` and post the output somewhere (making sure to mask any potentially sensitive information like IMEI)

**Comment by Flohack74** [comment]
Yes thats supposed to be the serial number of your device or whatever the vendor puts there :) - Of course we can create a mandatory device selection in this case. Auto-detection will not be possible in this case. Some vendors have that issue.

**Comment by OlThHoCa** [comment]
The output of  fastboot getvar all was:
(bootloader) max-download-size: 0x8000000
(bootloader) variant:
(bootloader) logical-block-size: 0x200
(bootloader) erase-block-size: 0x80000
(bootloader) hw-revision: ca01
(bootloader) battery-soc-ok: yes
(bootloader) battery-voltage: 4148mV
(bootloader) partition-size:sgpt: 4200
(bootloader) partition-type:sgpt: raw data
(bootloader) partition-size:flashinfo: 1000000
(bootloader) partition-type:flashinfo: raw data
(bootloader) partition-size:userdata: d416fbe00
(bootloader) partition-type:userdata: ext4
(bootloader) partition-size:cache: 1b000000
(bootloader) partition-type:cache: ext4
(bootloader) partition-size:system: e0000000
(bootloader) partition-type:system: ext4
(bootloader) partition-size:vendor: 32000000
(bootloader) partition-type:vendor: raw data
(bootloader) partition-size:tee2: c00000
(bootloader) partition-type:tee2: raw data
(bootloader) partition-size:tee1: 500000
(bootloader) partition-type:tee1: raw data
(bootloader) partition-size:dtbo: 800000
(bootloader) partition-type:dtbo: raw data
(bootloader) partition-size:logo: 800000
(bootloader) partition-type:logo: raw data
(bootloader) partition-size:boot: 2000000
(bootloader) partition-type:boot: raw data
(bootloader) partition-size:lk2: 100000
(bootloader) partition-type:lk2: raw data
(bootloader) partition-size:lk: 100000
(bootloader) partition-type:lk: raw data
(bootloader) partition-size:nvram: 4000000
(bootloader) partition-type:nvram: raw data
(bootloader) partition-size:gz2: 1000000
(bootloader) partition-type:gz2: raw data
(bootloader) partition-size:gz1: 1000000
(bootloader) partition-type:gz1: raw data
(bootloader) partition-size:sspm_2: 100000
(bootloader) partition-type:sspm_2: raw data
(bootloader) partition-size:sspm_1: 100000
(bootloader) partition-type:sspm_1: raw data
(bootloader) partition-size:spmfw: 100000
(bootloader) partition-type:spmfw: raw data
(bootloader) partition-size:md1dsp: 1000000
(bootloader) partition-type:md1dsp: raw data
(bootloader) partition-size:md1img: 4000000
(bootloader) partition-type:md1img: raw data
(bootloader) partition-size:sec1: 200000
(bootloader) partition-type:sec1: raw data
(bootloader) partition-size:persist: 3000000
(bootloader) partition-type:persist: ext4
(bootloader) partition-size:seccfg: 800000
(bootloader) partition-type:seccfg: raw data
(bootloader) partition-size:protect2: e78000
(bootloader) partition-type:protect2: ext4
(bootloader) partition-size:protect1: 800000
(bootloader) partition-type:protect1: ext4
(bootloader) partition-size:metadata: 2000000
(bootloader) partition-type:metadata: raw data
(bootloader) partition-size:nvdata: 4000000
(bootloader) partition-type:nvdata: ext4
(bootloader) partition-size:nvcfg: 2000000
(bootloader) partition-type:nvcfg: ext4
(bootloader) partition-size:frp: 100000
(bootloader) partition-type:frp: raw data
(bootloader) partition-size:expdb: 1400000
(bootloader) partition-type:expdb: raw data
(bootloader) partition-size:para: 80000
(bootloader) partition-type:para: raw data
(bootloader) partition-size:recovery: 2000000
(bootloader) partition-type:recovery: raw data
(bootloader) partition-size:boot_para: 100000
(bootloader) partition-type:boot_para: raw data
(bootloader) partition-size:proinfo: 300000
(bootloader) partition-type:proinfo: raw data
(bootloader) partition-size:pgpt: 8000
(bootloader) partition-type:pgpt: raw data
(bootloader) partition-size:preloader: 40000
(bootloader) partition-type:preloader: raw data
(bootloader) serialno: GX290Pro0029432
(bootloader) off-mode-charge: 1
(bootloader) warranty: no
(bootloader) unlocked: yes
(bootloader) secure: no
(bootloader) kernel: lk
(bootloader) product: k63v2_64_bsp
(bootloader) is-userspace: no
(bootloader) slot-count: 0
(bootloader) version-baseband: MOLY.LR12A.R2.MP.V138.11
(bootloader) version-bootloader: k63v2_64_bsp-aa07ba143a-
20210814151502-
(bootloader) version-preloader:
(bootloader) version: 0.5
all: Done!!
Finished. Total time: 0.008s

Also here the serialno is GX290.... what means the right one for
VollaPhoneX.

**Comment by maciek134** [comment]
That was run in fastbootd, can you check again in normal
fastboot/bootloader? Again, serial number is supposed to be unique for each
device, this is the first time I see the model included in it.

**Comment by OlThHoCa** [comment]
That was run in fastbootd, can you check again in normal
fastboot/bootloader? Again, serial number is supposed to be unique for
each
device, this is the first time I see the model included in it.
>>
OK the device doesn't start with power button. After this the Volla-
Logo comes up an the Phone hangs.
Starting the device with volume down and power button causes that the
modeselection comes and the Phone hangs.
Starting the device with volume up and power button has the result that
the modeselection menue reacts to the buttons.
from here the recovery mode will hang.
The boot system option shows again the Volla-Logo and the system hangs.
the Bootloader option starts the fastboot mode I used to generate the
output last time.
So from here i did following actions:
***@***.***:~$ fastboot reboot bootloader
Rebooting into bootloader OKAY [ 0.003s]
Finished. Total time: 0.053s
***@***.***:~$ fastboot getvar all
(bootloader) max-download-size: 0x8000000
(bootloader) variant:
(bootloader) logical-block-size: 0x200
(bootloader) erase-block-size: 0x80000
(bootloader) hw-revision: ca01
(bootloader) battery-soc-ok: yes
(bootloader) battery-voltage: 4106mV
(bootloader) partition-size:sgpt: 4200
(bootloader) partition-type:sgpt: raw data
(bootloader) partition-size:flashinfo: 1000000
(bootloader) partition-type:flashinfo: raw data
(bootloader) partition-size:userdata: d416fbe00
(bootloader) partition-type:userdata: ext4
(bootloader) partition-size:cache: 1b000000
(bootloader) partition-type:cache: ext4
(bootloader) partition-size:system: e0000000
(bootloader) partition-type:system: ext4
(bootloader) partition-size:vendor: 32000000
(bootloader) partition-type:vendor: raw data
(bootloader) partition-size:tee2: c00000
(bootloader) partition-type:tee2: raw data
(bootloader) partition-size:tee1: 500000
(bootloader) partition-type:tee1: raw data
(bootloader) partition-size:dtbo: 800000
(bootloader) partition-type:dtbo: raw data
(bootloader) partition-size:logo: 800000
(bootloader) partition-type:logo: raw data
(bootloader) partition-size:boot: 2000000
(bootloader) partition-type:boot: raw data
(bootloader) partition-size:lk2: 100000
(bootloader) partition-type:lk2: raw data
(bootloader) partition-size:lk: 100000
(bootloader) partition-type:lk: raw data
(bootloader) partition-size:nvram: 4000000
(bootloader) partition-type:nvram: raw data
(bootloader) partition-size:gz2: 1000000
(bootloader) partition-type:gz2: raw data
(bootloader) partition-size:gz1: 1000000
(bootloader) partition-type:gz1: raw data
(bootloader) partition-size:sspm_2: 100000
(bootloader) partition-type:sspm_2: raw data
(bootloader) partition-size:sspm_1: 100000
(bootloader) partition-type:sspm_1: raw data
(bootloader) partition-size:spmfw: 100000
(bootloader) partition-type:spmfw: raw data
(bootloader) partition-size:md1dsp: 1000000
(bootloader) partition-type:md1dsp: raw data
(bootloader) partition-size:md1img: 4000000
(bootloader) partition-type:md1img: raw data
(bootloader) partition-size:sec1: 200000
(bootloader) partition-type:sec1: raw data
(bootloader) partition-size:persist: 3000000
(bootloader) partition-type:persist: ext4
(bootloader) partition-size:seccfg: 800000
(bootloader) partition-type:seccfg: raw data
(bootloader) partition-size:protect2: e78000
(bootloader) partition-type:protect2: ext4
(bootloader) partition-size:protect1: 800000
(bootloader) partition-type:protect1: ext4
(bootloader) partition-size:metadata: 2000000
(bootloader) partition-type:metadata: raw data
(bootloader) partition-size:nvdata: 4000000
(bootloader) partition-type:nvdata: ext4
(bootloader) partition-size:nvcfg: 2000000
(bootloader) partition-type:nvcfg: ext4
(bootloader) partition-size:frp: 100000
(bootloader) partition-type:frp: raw data
(bootloader) partition-size:expdb: 1400000
(bootloader) partition-type:expdb: raw data
(bootloader) partition-size:para: 80000
(bootloader) partition-type:para: raw data
(bootloader) partition-size:recovery: 2000000
(bootloader) partition-type:recovery: raw data
(bootloader) partition-size:boot_para: 100000
(bootloader) partition-type:boot_para: raw data
(bootloader) partition-size:proinfo: 300000
(bootloader) partition-type:proinfo: raw data
(bootloader) partition-size:pgpt: 8000
(bootloader) partition-type:pgpt: raw data
(bootloader) partition-size:preloader: 40000
(bootloader) partition-type:preloader: raw data
(bootloader) serialno: GX290Pro0029432
(bootloader) off-mode-charge: 1
(bootloader) warranty: no
(bootloader) unlocked: yes
(bootloader) secure: no
(bootloader) kernel: lk
(bootloader) product: k63v2_64_bsp
(bootloader) is-userspace: no
(bootloader) slot-count: 0
(bootloader) version-baseband: MOLY.LR12A.R2.MP.V138.11
(bootloader) version-bootloader: k63v2_64_bsp-aa07ba143a-
20210814151502-
(bootloader) version-preloader:
(bootloader) version: 0.5
all: Done!!
Finished. Total time: 0.009s

I hope that helps...
On any questions please ask me.

**Comment by JamiKettunen** [comment]
I think there's a simpler solution, we just don't include `k63v2_64_bsp` in `aliases` of [yggdrasil.yml](https://github.com/ubports/installer-configs/blob/7753a64/v2/devices/yggdrasil.yml#L4-L5) so the device doesn't get autodetected incorrectly in bootloader mode and the user instead has to choose it manually. Thoughts?

**Comment by OlThHoCa** [comment]
This would be nice. You can ask me to check it, if you want to verify
the result.

**Comment by OlThHoCa** [comment]
This could be a solution.

**Comment by JamiKettunen** [comment]
@OlThHoCa That solution indeed was chosen already a month ago and has gone live, you could double-check this issue if you want :)
Perhaps in the future a bootloader fix to report a more unique model for each device (`yggdrasil` and `yggdrasilx`) will be done so that they can still be auto-detected in bootloader mode as well.
