### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:419)

### ISSUE THREAD

**Issue by seekr** [ubports/ubports-installer#284]
Automatically generated error report %0AVersion: 0.1.12-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v8.2.1 %0A%0AError log: http://paste.ubuntu.com/p/RQ8fdqJTd9/ %0A

Additionally my nexus 5 appears "unsupported":

![image](https://user-images.githubusercontent.com/2786460/40866338-897598ae-65d3-11e8-8350-5be2f9a187e8.png)

**Comment by NeoTheThird** [comment]
Please use the latest version: https://github.com/ubports/ubports-installer/releases/latest
