### ISSUE TITLE
Stuck in boot loop on JingPad

### ISSUE THREAD

**Issue by readtedium** [ubports/ubports-installer#2844]
**UBports Installer `0.8.9-beta` (exe)**
Environment: `Microsoft Windows 11 Pro 10.0.22000 win32 10.0.22000 x64 22000 0.0 NodeJS v12.18.3`
Device: jingpad_a1
Target OS: Ubuntu Touch
Settings: `undefined`
OPEN-CUTS run: *N/A*
Log: *N/A*

Not sure how it's doing it, but I followed this guide closely: https://docs.google.com/document/d/1otTXHDPcN72O4i31D6jMBDsucy44jxclUfq7P7uEzFU/edit

**Comment by Flohack74** [comment]
@fredldotme maybe?

**Comment by readtedium** [comment]
I was able to resolve by moving to the stable channel.
