### ISSUE TITLE
Uncaught Error: (/usr/lib/firefox/firefox:4596): dconf-WARNING **: Unable to open /var/lib/flatpak/exports/share/dconf/profile/user: Permission denied (MainRenderer:39)

### ISSUE THREAD

**Issue by Gashi007** [ubports/ubports-installer#286]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Linux Mint undefined
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/5tgDfx8Kkj/

**Comment by NeoTheThird** [comment]
please use the [latest version](https://github.com/ubports/ubports-installer/releases/latest)
