### ISSUE TITLE
Adb failed to reboot!, reboot failed: -1 : 

### ISSUE THREAD

**Issue by Gashi007** [ubports/ubports-installer#287]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Linux Mint undefined
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/H7jS6TpCqN/

**Comment by NeoTheThird** [comment]
Please use the [latest release](https://github.com/ubports/ubports-installer/releases/latest)
