### ISSUE TITLE
Fastboot: Unknown error:  Password:target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.386s]writing 'recovery'...FAILED (remote: failed to get download permission for partition 'recovery')finished. total time: 0.389s

### ISSUE THREAD

**Issue by tihom7** [ubports/ubports-installer#29]
Automatically generated error report %0AVersion: 0.1.5-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v7.9.0 %0A%0AError log: http://paste.ubuntu.com/25698004/ %0A

**Comment by NeoTheThird** [comment]
Thanks for reporting. This should be fixed by now, please let us know if it happes again.
