### ISSUE TITLE
Adb failed to reboot!, reboot failed: -1 : 

### ISSUE THREAD

**Issue by hoh61** [ubports/ubports-installer#292]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Linux Mint undefined
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/WrBKWbsdkp/

**Comment by NeoTheThird** [comment]
Please use the latest version.

**Comment by hoh61** [comment]
It's the version available in the ubuntu repositorie for 16.04!!!!
