### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by mawil1013** [ubports/ubports-installer#295]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/rxJDfRBY46/ 

Had Touch on phone, did a wipe but was unable to install again, I think because there is no OS on phone, Just Ubports Recovery, which only allows bootloader. It worked before but I cannot access any controls/setting not on Ubports Recovery.

**Comment by PhoenixLandPirate** [comment]
I also get this error.
I tried to update my OPO to the latest version of the OS yesterday, or the day before, that didn't install, and my phone wouldn't boot, (Stays on the ubuntu loading screen) 

So I decided to try and use ubports installer, in which I get the same error.
https://paste.ubuntu.com/p/bwb8KstxBc/

**Comment by PhoenixLandPirate** [comment]
I installed the ubports deb, and it worked fine.

**Comment by mawil1013** [comment]
ubports  ubports-installer_0.1.13-beta_amd64.deb already installed, I tried it, no joy...

**Comment by NeoTheThird** [comment]
@PhoenixLandPirate It might be this https://github.com/ubports/ubuntu-touch/issues/673

**Comment by NeoTheThird** [comment]
https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices
