### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for shargar: target reported max download size of 134217728 bytessending 'recovery' (11436 KB)...OKAY [  0.453s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.455s

### ISSUE THREAD

**Issue by shargarr** [ubports/ubports-installer#297]
Automatically generated error report 
Version: 0.1.5-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/p/7zc5pc8WGz/

**Comment by shargarr** [comment]
hello ! I try to install ubuntutouch on a tablatt bq m10 HD.

**Comment by advocatux** [comment]
Please come to https://forums.ubports.com/category/37/support to get help

**Comment by NeoTheThird** [comment]
You might have to use this guide if your device is running android: https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices
