### ISSUE TITLE
download speed too slow

### ISSUE THREAD

**Issue by buyufan** [ubports/ubports-installer#2972]
**UBports Installer `0.9.7-beta` (dmg)**
Environment: `macOS 13.0.1 macOS Ventura darwin 22.1.0 x64 22A400 NodeJS v16.15.0`
Device: [`sagit`](https://github.com/ubports/installer-configs/blob/5b999fac996acb85e4a6e2a861744385064840ac/v2/devices/sagit.yml) ([Xiaomi Mi 6](https://devices.ubuntu-touch.io/device/sagit/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"16.04/arm64/android9/devel"}`
OPEN-CUTS run: https://ubports.open-cuts.org/run/63a5d79105d25b2dc4cbbaad
Pastebin: https://snip.hxrsh.in/ubi-1671813005855

download speed too slow

**Comment by Vaguesunrain** [comment]
i faced the same problem
