### ISSUE TITLE
Adb push error- BQ e5 ubuntu edition - Windows 10 laptop

### ISSUE THREAD

**Issue by rdrowe** [ubports/ubports-installer#300]
Error when trying to flash BQ e5 Ubuntu edition with ubports.
Using Windows 10 on a Toshiba Satellite Pro laptop. :

Adb push error: cannot stat ''C:\Users\User\AppData\Roaming\ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

**Comment by rdrowe** [comment]
Update - 0.1.9beta worked

**Comment by NeoTheThird** [comment]
Thanks for reporting and sorry for the inconvenience!

**Comment by rdrowe** [comment]
No problem. Got it sorted, thanks.
