### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Passwort für thomas: downloading 'boot.img'...OKAY [  0.363s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.365s

### ISSUE THREAD

**Issue by Mondschein93** [ubports/ubports-installer#304]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Linux Mint undefined
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/2Hm8js7MYr/

**Comment by jonnius** [comment]
duplicate of #184
