### ISSUE TITLE
[xenial] UT 16.04 RC failed to install on Arale

### ISSUE THREAD

**Issue by ic3d** [ubports/ubports-installer#306]
I was trying to install UT 16.04/rc on my Meizu MX4 (with ota3). 
First time I launched UBports installer, but it hangs with no error, and the phone show what it's in the attached image. I quit UBports installer, and reboot the phone.

![wp_20180621_20_54_35_pro](https://user-images.githubusercontent.com/6413651/41739804-7b05bc2c-7596-11e8-9247-3fdec74854fa.jpg)

I tried a second time, launching UBports installer from command line (no sudo), and then again it happens the same error, but this time I can see the errors on the terminal, and UBports installer show the error below.

I quit UBports installer and rebooted the phone, it's still with ota3.

Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/tQn65cF5Y3/

**Comment by NeoTheThird** [comment]
Hey there, it seems like your machine is missing the correct udev rules. We have patches for upstream pending for that, but they are not live yet. [Here's how to work around](https://github.com/ubports/ubports-installer#device-not-detected-linux) that issue. If you continue to have problems, please let me know!
