### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for tihoto: target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.489s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.492s

### ISSUE THREAD

**Issue by tihom7** [ubports/ubports-installer#307]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/p/gRvPYDB9fV/

**Comment by NeoTheThird** [comment]
Please try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest).
