### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by GraK31Data** [ubports/ubports-installer#3076]
**UBports Installer `0.9.7-beta` (snap)**
Environment: `Ubuntu Core 20 linux 5.15.0-58-generic x64 NodeJS v16.15.0`
Device: [`sargo`](https://github.com/ubports/installer-configs/blob/8287d36c35b1b1da1532a9800d1941411443c1cd/v2/devices/sargo.yml) ([Google Pixel 3a/3a XL](https://devices.ubuntu-touch.io/device/sargo/))
Target OS: Ubuntu Touch
Settings: `{"bootstrap":true,"wipe":true,"channel":"20.04/arm64/android9plus/rc"}`
OPEN-CUTS run: *N/A* 
Pastebin: https://snip.hxrsh.in/ubi-1675273075225

I've chosen the ubuntu version, the mobile type and one the next step when the installation process should start it hangs in infinity loop. 

![image](https://user-images.githubusercontent.com/120024021/216120514-15468b15-0fc2-4f64-9f1a-6d85c0ee4879.png)

**Comment by GraK31Data** [comment]
![20230201_183538](https://user-images.githubusercontent.com/120024021/216121909-a0b63854-20a9-48c1-9ccb-e765bf364a1b.jpg)
and the Pixel screen

**Comment by aetherfaerber** [comment]
I just had the same symptoms with a Nexus 5.
The screen in the photo says "Press volume keys to select different menu". Use your volume keys and select "boot to recovery" by confirming with a press on the power key. As soon as the phone has entered recovery mode and is connected via usb the installer will proceed.

**Comment by GraK31Data** [comment]
> I just had the same symptoms with a Nexus 5. The screen in the photo says "Press volume keys to select different menu". Use your volume keys and select "boot to recovery" by confirming with a press on the power key. As soon as the phone has entered recovery mode and is connected via usb the installer will proceed.

yes, exactly. I thought it's failer, but I've retried few times, and after 4th time it work fine. Now I can see the Ubuntu on a Pixel.
The issue could be that the screen/step switched fast, and I didn't noticed the infromatiom. On the scond time I could see description about the buttons and 'what if'.
Anyways I close the bug as it worked. And good thing is that I didn't break it on the first time. I could rerun the process till it worked fine.
