### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#308]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/jBRBCcDMf6/

**Comment by NeoTheThird** [comment]
Please try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest).
