### ISSUE TITLE
Uncaught Error: (/usr/lib/firefox/firefox:3135): dconf-WARNING **: 09:59:21.309: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission denied (MainRenderer:39)

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#311]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/JN4pYKXjns/

**Comment by NeoTheThird** [comment]
Could you try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest)?
