### ISSUE TITLE
Support LineageOS 20

### ISSUE THREAD

**Issue by PanderMusubi** [ubports/ubports-installer#3141]
Please support installing LineageOS version 20

**Comment by amartinz** [comment]
With above commit applied:
`verbose: running step {"actions":[{"core:download":{"group":"LineageOS","files":[{"url":"https://mirrorbits.lineageos.org/full/axolotl/20230301/lineage-20.0-20230301-nightly-axolotl-signed.zip","checksum":{"sum":"a5376eeb9ba7fec81e84ed6f5a5dfbf8655e8d5d898f903d52780e459200c6cc","algorithm":"sha256"},"name":"lineageos_rootfs_axolotl.zip"}]}}]}`

Without above commit applied it downloads `lineage-19.1-20230104-nightly-axolotl-signed.zip`.

Thanks for the report!
