### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizesending 'recovery' (13708 KB)...FAILED (data transfer failure (Protocol error))finished. total time: 4152.610s

### ISSUE THREAD

**Issue by Cieniek** [ubports/ubports-installer#32]
Automatically generated error report 
Version: 0.1.5-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/25709955/

**Comment by NeoTheThird** [comment]
Thanks for reporting. This should be fixed by now, please let us know if it happes again.
