### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:230)

### ISSUE THREAD

**Issue by woorifis** [ubports/ubports-installer#321]
Automatically generated error report %0D%0AVersion: 0.1.13-beta %0D%0AHost OS: darwin %0D%0AHost Dist: undefined undefined%0D%0AHost Arch: x64 %0D%0ANode: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/T7fsXRMrS5/ %0D%0A

**Comment by NeoTheThird** [comment]
Please use the [latest version](https://github.com/ubports/ubports-installer/releases/latest).
