### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 1323098112 bytessending 'recovery' (9578 KB)...OKAY [  1.377s]writing 'recovery'...FAILED (remote: flash_cmds error!)finished. total time: 2.075s

### ISSUE THREAD

**Issue by miigangls** [ubports/ubports-installer#322]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/hwYjwNby3J/

**Comment by NeoTheThird** [comment]
What OS is your Bq E4.5 running right now?

**Comment by NeoTheThird** [comment]
Also, could you try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest)?

**Comment by miigangls** [comment]
Hello, I'm installing in a tablet dell venue 8 pro.

**Comment by NeoTheThird** [comment]
Sorry, the UBports Installer only works with supported devices: devices.ubuntu-touch.io
