### ISSUE TITLE
Failed to auto-boot on recovery mode on Meizu PRO5 (turbo)

### ISSUE THREAD

**Issue by vkareh** [ubports/ubports-installer#333]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/hNxnwczNXK/

**Comment by vkareh** [comment]
To follow up on this, this phone (Meizu PRO5 "turbo") doesn't seem to properly boot into recovery mode from `fastboot`, so it has to be done manually (hold volume-up and power). But then the installer UI hangs with the above error.

So, I manually flashed the [recovery-turbo.img](http://cdimage.ubports.com/devices/recovery-turbo.img) file by running `fastboot flash recovery recovery-turbo.img`. Then I git-cloned the ubports-installer repo and called it from the cli: `./cli.js -d turbo -c 16.04/rc` (alternatively, you can comment out this whole chunk of code: https://github.com/ubports/ubports-installer/blob/0.1.15-beta/src/devices.js#L343-L352 (and the extra `}` on L357, of course).

After that the installer works like a charm - up until it's done, at which point the installer GUI says a big "Success!" message, but when you reboot on recovery, you get a white screen on the phone with "Update failed, contact support.". If you reboot on normal mode, it just has a black screen with the "Meizu" logo in it - nothing else moves.

I get the same behavior from the UI or the cli.js, with both 16.04/rc and 16.04/devel. 15.04/* channels don't seem to be available from this app.

**Comment by NeoTheThird** [comment]
Could you try again with [the latest version](https://github.com/ubports/ubports-installer/releases/latest)?

**Comment by vkareh** [comment]
Most certainly! I'll give it a shot this week, thanks for following up :)

**Comment by vkareh** [comment]
@NeoTheThird - Unfortunately, no luck.
I needed to do the same thing as described above, and get the same "Success!" message from the UI, but the recovery screen shows "Update failed, contact support.".

At this point, in trying to manually flash the `recovery-turbo.img` to the recovery partition, I no longer get the Ubuntu logo, but I still get the Update failed white screen... even after a full device wipe.

Flashing TWRP works just fine, so the device doesn't seem to be bricked, but I just downloaded a fresh `recovery-turbo.img` (although it shows it as being the same file since last year) and I still get the white screen with the utouch recovery :confused:

I'll keep playing with this on my side, but I don't see a way forward with the PRO5 at this point.

**Comment by vkareh** [comment]
Also, just to update - even with the white screen error in recovery mode, I can still `adb shell` properly into it and navigate the file system. adb seems to work normally, so maybe the error screen is a red herring?

running `system-image-updater` manually seems to succeed, but nothing happens

**Comment by vkareh** [comment]
Also, just to update - even with the white screen error in recovery mode, I can still `adb shell` properly into it and navigate the file system. adb seems to work normally, so maybe the error screen is a red herring?

running `system-image-updater` manually seems to succeed, but nothing happens

**Comment by NeoTheThird** [comment]
Does the recovery give you any *helpful* error messages to work on? "Update failed" might be that the cache is running out of space. You might want to try `fastboot erase cache` from bootloader or (if the recovery you have installed right now has root access) `adb shell "rm -rf /cache/*"`.

**Comment by NeoTheThird** [comment]
Sorry about the delay... Solved in #710, will be [included in the next release](https://github.com/ubports/ubports-installer/releases/tag/0.2.0-beta). Thanks for reporting!

**Comment by vkareh** [comment]
Thanks! I'll give it a try as soon as I can :)

**Comment by vkareh** [comment]
welp, the installer itself worked like a charm, so that was definitely fixed. Once the install was "successful", however, I still got the white screen with "Update failed..." on my phone

Tried erasing the cache and now the phone won't even turn on, at all... probably bricked? :(
