### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blacklist' of undefined (MainRenderer:360)

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#335]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/Fr8FQTVqvS/

**Comment by NeoTheThird** [comment]
Please use [the latest version](https://github.com/ubports/ubports-installer/releases/latest).
