### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizesending 'recovery' (11366 KB)...OKAY [  0.594s]writing 'recovery'...FAILED (remote: partition 'recovery' not support flash)finished. total time: 0.650s

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#337]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/9yxRRYKFDK/

**Comment by NeoTheThird** [comment]
Please use [the latest version](https://github.com/ubports/ubports-installer/releases/latest).
