### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.761s]booting...FAILED (remote failure)finished. total time: 0.761s

### ISSUE THREAD

**Issue by geekceara** [ubports/ubports-installer#338]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/whZ8G6wHFJ/

**Comment by geekceara** [comment]
error flash ubports installer Meizu Pro 5 android version

**Comment by NeoTheThird** [comment]
Hey there, sorry, the Android version of the Meizu Pro 5 is very locked down, so the installer won't be able to install it just like that. You might want to try [these experimental instructions](https://nc.ubports.com/s/9yd88Xo4CWzRbMq). Sorry about the inconvenience!
