### ISSUE TITLE
Fastboot: Unknown error:  [sudo] пароль для tengo: target reported max download size of 535822336 bytessending 'recovery' (11390 KB)...OKAY [  0.392s]writing 'recovery'...(bootloader) is_partition_need_check.FAILED (status read failed (No such device))finished. total time: 5.510s

### ISSUE THREAD

**Issue by xozonimus** [ubports/ubports-installer#339]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/Cg98PK7FXc/

**Comment by xozonimus** [comment]
will in the future be supported by ubuntu on smartphones asus sony motorola
htc?


კვი, 1 ივლ. 2018, 12:24-ში Jan Sprinz <notifications@github.com> დაწერა:

**Comment by NeoTheThird** [comment]
Yes, new devices are being enabled by community developers all the time, as soon as they are stable enough, they can be set up as community devices or core devices. Here's a list of the devices we support at the moment: devices.ubuntu-touch.io

Do I understand that correctly, that your tried to install on an unsupported device? In that case, it makes sense that the installation failed, of course.

**Comment by xozonimus** [comment]
yes i wanted to install it on my asus zenfone 3 laser

კვი, 1 ივლ. 2018, 12:44-ში Jan Sprinz <notifications@github.com> დაწერა:

**Comment by NeoTheThird** [comment]
Yeah, that won't work. Sorry. If you want to look into porting Ubuntu Touch, docs.halium.org will get you started, but I'm afraid there's nothing I can do for you at the moment. The installer only works with supported devices.

**Comment by xozonimus** [comment]
Thank you very much

კვი, 1 ივლ. 2018, 13:06-ში Jan Sprinz <notifications@github.com> დაწერა:

**Comment by NeoTheThird** [comment]
Sure, sorry I couldn't give you a more satisfying answer. :/
