### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.525s]booting...FAILED (remote failure)finished. total time: 0.526s

### ISSUE THREAD

**Issue by Sephirono** [ubports/ubports-installer#343]
Automatically generated error report 
Phone: Meizu Pro 5
Phone OS: Flyme
Computer OS: Windows 10

After the installer detected the device and the process started, the reboot did not take the device into fastboot mode. I held the power and volume down to force it to fastboot mode, the installer detected it and begun but then failed trying to flash boot.img

**Comment by NeoTheThird** [comment]
Is it an Ubuntu Edition Meizu Pro 5, or did it come with Android?

**Comment by Sephirono** [comment]
It is a Android Edition Meizu Pro 5, last year I changed operating system to Ubuntu and changed it back to Android. don tunderstan why im having issues now.

**Comment by NeoTheThird** [comment]
The Pro 5 is very locked down, so there is not a lot the UBports Installer can do. We have a set of [experimental things](https://nc.ubports.com/s/9yd88Xo4CWzRbMq) you can try out, but i can't guarantee anything. I guess you have done this before, when you switched your device over last time? Good luck!

**Comment by Sephirono** [comment]
yes i tried several things from different sites, i have already installed UBUNTU TOUCH on my Meizu Pro 5 but i had to use the last version a use to install it and select 15.04 stable in order to achieve this, now im trying to update to 16.04 but and update doesn't appear in my phone

**Comment by NeoTheThird** [comment]
Okay, so right now it's running Ubuntu Touch OTA-3 by UBports?

**Comment by Sephirono** [comment]
i attach the image of my OS Build Details Screen
![screenshot20180702_140933792 1](https://user-images.githubusercontent.com/40744418/42184352-774b4420-7e02-11e8-957b-7bd06390ce3b.png)

**Comment by NeoTheThird** [comment]
Please try again with [the latest release](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by NeoTheThird** [comment]
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.
