### ISSUE TITLE
Adb push error: failed to copy 'C:\Users\amos2\AppData\Roaming\ubports\pool/device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz' to '/cache/recovery//device-60f53a5768e93

### ISSUE THREAD

**Issue by Sephirono** [ubports/ubports-installer#350]
Using Ubports 0.1.9 beta
only when I try to install 16.04/devel
Meizu Pro 5 originally Android already installed Ubuntu Touch 15.04/stable I'm trying to update to 16.04/devel

**Comment by Sephirono** [comment]
Yes, I'm using Ubports Installer 0.1.9 beta and get this error

**Comment by NeoTheThird** [comment]
Could you try again [using the latest version](https://github.com/ubports/ubports-installer/releases/latest)?
