### ISSUE TITLE
Impossible to install UBports on the latest Fairphone 2

### ISSUE THREAD

**Issue by Anne017** [ubports/ubports-installer#36]
What happened:
Impossible to install UBports on the latest Fairphone 2

Steps to reproduce:
- Latest Appimage from https://github.com/ubports/ubports-installer/releases downloaded.
- AppImage [made executable](https://discourse.appimage.org/t/how-to-make-an-appimage-executable/80).
- Double-click on the file.
- Fairphone 2 received last week (with Android 6.1) and connected to the computer with a USB cable.
- Device not found, selected manually ("Fairphone 2" in the list).
- Channel "15.04/devel" selected in the install options, and "Wipe" checkbox ticked.
Note: the devel channel is used instead of stable to allow the compatibility with Android 6.1, as explained in [this issue](https://github.com/ubports/ubuntu-touch/issues/253).
- Password from the computer entered.
- Power and volume down buttons pressed down until reboots (bootloader black screen with FAIRPHONE POWERED BY ANDROID).
- Nothing happens after several minutes (no feed-back, no "Next" button in the GUI).

What I expected to happen:
Continuation of the installation (UBports robot with eyes blinking, restart on Ubuntu Touch).

Logs:
None (?).

Software Version: 
Computer on Ubuntu 16.04 LTS (updates done).

**Comment by NeoTheThird** [comment]
Might be caused by #39. There's no problem with installing FPs.

**Comment by NeoTheThird** [comment]
Thanks for reporting! I'm pretty sure it's related to #39, so let's track it there.
