### ISSUE TITLE
FP2 not detected using snap

### ISSUE THREAD

**Issue by jetpereira** [ubports/ubports-installer#364]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/NQRtXG4dCX/

**Comment by jetpereira** [comment]
I also tried with version 0.1.13 without success. FP2 does not receive the update. It stands stoped without progress in the process.

**Comment by NeoTheThird** [comment]
Could you try this? https://github.com/ubports/ubports-installer#device-not-detected-linux

**Comment by jetpereira** [comment]
FP2 rebooting and stooped to complete the update

**Comment by jetpereira** [comment]
problem solved
