### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (13708 KB)...FAILED (remote: not support on security)finished. total time: 0.013s

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#366]
Automatically generated error report 
Version: 0.1.9-beta

**Comment by NeoTheThird** [comment]
Hey there, please try again with the [latest version](https://github.com/ubports/ubports-installer/releases/download/0.1.20-beta/ubports-installer.0.1.20-beta.exe).

What device is this? The response the installer is getting suggests that flashing the recovery is not allowed. Are you installing on a [supported device](devices.ubuntu-touch.io)? If it's a Bq or Meizu device running android, [you'll need this guide](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
