### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349)

### ISSUE THREAD

**Issue by Charley94** [ubports/ubports-installer#368]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/nC9S3MTg7R/

**Comment by NeoTheThird** [comment]
What device is this? `HWTRTQ` is not a device id I recognize. What did you do just before this error appeared?

**Comment by KasperJanssens** [comment]
FWIW I've got the same error with a BQ Aquaris, happens when launching the ubports-installer on bionic from CLI. Nothing being clicked, just have the bq connected and launch ubports-installer.

**Comment by Lin-Buo-Ren** [comment]
Just reproduced this with BQ Aquaris M10 FHD (Android 6.0); Ubports Installer 0.1.20-beta (170) from Snap Store

**Comment by advocatux** [comment]
@Lin-Buo-Ren if you still have Android on your tablet, you need to follow this guide first https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices

**Comment by Lin-Buo-Ren** [comment]
@advocatux  I did follow the guide, but the error still occurred if I attempt to let Ubports Installer to autodetect my device.
