### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349)

### ISSUE THREAD

**Issue by Charley94** [ubports/ubports-installer#370]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/f3YkY542t3/

**Comment by NeoTheThird** [comment]
duplicate of #368.
