### ISSUE TITLE
Stuck on "Please reboot to bootloader" even though drivers are installed and device can be seen by fastboot.

### ISSUE THREAD

**Issue by Shad0wKn1ght93** [ubports/ubports-installer#371]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 4
Package: exe
Operating Syst

**Comment by SirSharanChakradhar** [comment]
Have same issue here, much appreciated if someone can help.

UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: exe
Operating Syst

**Comment by ALFTavares** [comment]
same here

UBports Installer Version: 0.1.21-beta 
Device: BQ Aquaris E4.5
Package: exe
Operat

**Comment by fabrei** [comment]
i had a similar problem. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)
