### ISSUE TITLE
ubinstaller debian package: apt autoremove complains about not being able to parse /usr/share/applications/ubports-installer.desktop

### ISSUE THREAD

**Issue by javierpuche** [ubports/ubports-installer#372]
Could not parse file "/usr/share/applications/ubports-installer.desktop": Key file contains line 'A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported device to your PC, follow the on-screen instructions and watch this awesome tool do all the rest.' which is not a key-value pair, group, or comment

*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Meizu MX4
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/RqqcHWJcWF/

**Comment by NeoTheThird** [comment]
Gnarf. We build the deb package using electron-builder, the idea was not to have to worry about packaging. That did not work out at all...

Thanks for reporting.

**Comment by javierpuche** [comment]
I think it might not have to do anything with packaging, it is just that the file  /usr/share/applications/ubports-installer.desktop  it has no proper syntax and I think the fix it is just to delete or escape with backslash the colon y the Comment line , that way indeed we would have the GUI launcher as now I had to run it from the command line.
Thanks for your great work.
