### ISSUE TITLE
"You are not using the latest stable version of the UBports installer" just after installing snap

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [ubports/ubports-installer#373]
![screenshot_20180717_001624](https://user-images.githubusercontent.com/13408130/42770066-a9261934-8956-11e8-8a30-bf4bf55221a5.png)

```
$ snap info ubports-installer
name:      ubports-installer
summary:   The easy way to install Ubuntu Touch on UBports devices.
publisher: mariogrip
contact:   https://github.com/ubports/ubports-installer/issues/new
license:   unknown
description: |
  A friendly cross-platform Installer for Ubuntu Touch. Just connect a supported device to your PC,
  follow the on-screen instructions, and watch this awesome tool do all the rest!
commands:
  - ubports-installer
snap-id:      mq0sTMV7a8744UTRBwQHimStAqsGzbjj
tracking:     stable
refresh-date: yesterday at 22:48 CST
channels:                            
  stable:    0.1.20-beta (170) 107MB -
  candidate: 0.1.20-beta (170) 107MB -
  beta:      0.1.20-beta (170) 107MB -
  edge:      0.1.20-beta (170) 107MB -
installed:   0.1.20-beta (170) 107MB -
```

**Comment by tatonuta** [comment]
The same message ("You are not using the latest stable version of the UBports installer") just after downloading the .deb from https://devices.ubuntu-touch.io/device/hammerhead (version 0.1.21-beta-371) and installing through "Software" on Ubuntu 18.04.

**Comment by dayrover** [comment]
Seems like the problem is the github API latest does not have a 'version' element.
See the JSON from 'https://api.github.com/repos/ubports/ubports-installer/releases/latest'
This is compared with the 'package.json' file installed by the following code in utils.js:
function getUpdateAvailable() {
  return getLatestInstallerVersion().then((latestVersion) => {
    return latestVersion != version;
  });
}

**Comment by bloops98** [comment]
Hi,
Currently experiencing this with version 0.1.20

**Comment by ilya-bystrov** [comment]
Same thing
```
# snap install ubports-installer
ubports-installer 0.1.20-beta from Marius Gripsgård (mariogrip) installed
# snap refresh ubports-installer --stable
snap "ubports-installer" has no updates available
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

```

**Comment by NeoTheThird** [comment]
Fix released
