### ISSUE TITLE
\n

### ISSUE THREAD

**Issue by iozudono** [ubports/ubports-installer#377]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: BQ Aquaris E5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/h5JdSZVXBn/

**Comment by NeoTheThird** [comment]
Hey there, sorry about the huge delay. Were you able to solve or work around this issue?
