### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (12592 KB)...OKAY [  0.403s]writing 'recovery'...FAILED (remote: image is not a boot image)finished. total time: 0.406s

### ISSUE THREAD

**Issue by jbaruffa** [ubports/ubports-installer#379]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 7 2013 (LTE)
Package: unknown
Operating System: Ubuntu Linux 14.04 trusty x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/5SzwQxSD4x/

**Comment by fabrei** [comment]
i had the same log messages. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by NeoTheThird** [comment]
Duplicate of #639.
