### ISSUE TITLE
README.md doesn't mention the snap installer

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubports-installer#38]
https://github.com/ubports/ubports-installer/blob/master/README.md

snap info ubports-installer 
name:      ubports-installer
summary:   GUI installer for ubports devices
publisher: mariogrip
contact:   https://ubports.com
description: |
  This is an GUI installer for ubports ubuntu touch devices.
snap-id: mq0sTMV7a8744UTRBwQHimStAqsGzbjj
commands:
  - ubports-installer
tracking:    stable
installed:   0.1.7-beta (6) 88MB devmode
refreshed:   2017-09-22 18:18:27 +0300 EEST
channels:                   
  stable:    0.1.7-beta (6) 88MB -
  candidate: 0.1.7-beta (6) 88MB -
  beta:      0.1.7-beta (6) 88MB -
  edge:      0.1.7-beta (6) 88MB -

**Comment by NeoTheThird** [comment]
Thanks for reporting.

**Comment by NeoTheThird** [comment]
Fixed in 88882286c320524ed4d09e0b0dd14ff5554b024e

**Comment by pixelr0** [comment]
np! Thanks! o/
