### ISSUE TITLE
UBport installer for nexus 4. Its not performing any installation. It works till installer screen and ask to reboot to bootloader After that nothing happen

### ISSUE THREAD

**Issue by ankitmishra0111** [ubports/ubports-installer#381]
UBport installer for nexus 4. Its not performing any installation. It works till installer screen and ask to reboot to bootloader After that nothing happen:

*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.20-beta %0D%0ADevice: Nexus 4%0D%0APackage: dmg%0D%0AOperating System: macOS 10.13.617G65 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/zpqXgPfC46/ %0D%0A

**Comment by NeoTheThird** [comment]
Could you try running the installer with sudo?

**Comment by ankitmishra0111** [comment]
i am using a mac, i simply open the app, connect my nexus (already rooted/unlocked) and nothing happen. It shows message Please reboot to Bootloader, When I go to bootloader on phone nothing happen. Both phone and app sit ideal

**Comment by NeoTheThird** [comment]
Yeah, i got that. Please open the terminal and run `sudo ubports-installer`.

**Comment by kgj** [comment]
cd /Applications/ubports-installer.app/Contents/MacOS/
sudo ./ubports-installer

**Comment by ankitmishra0111** [comment]
Thanks kgj. This time it did something different. It booted to bootloader but nothing beyond. 
**** Dump ****
Ankits-MacBook-Pro:MacOS ankitmishra$ cd /Applications/ubports-installer.app/Contents/MacOS/
Ankits-MacBook-Pro:MacOS ankitmishra$ sudo ./ubports-installer
Pug interceptor registered successfully
debug: Welcome to the party
debug: Killing all running adb servers...
debug: Using fallback platform tools!
debug: 
debug: 
debug: adb shell: echo 1
debug: Successfully downloaded devices list
warn: Running latest stable version.
debug:  message=Command failed: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/.com.ubports.installer.qoBXZX -P 5038 shell echo 1
* daemon not running; starting now at tcp:5038
* daemon started successfully
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
, stack=Error: Command failed: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/.com.ubports.installer.qoBXZX -P 5038 shell echo 1
* daemon not running; starting now at tcp:5038
* daemon started successfully
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=1, signal=null, cmd=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/.com.ubports.installer.qoBXZX -P 5038 shell echo 1
debug: adb shell: echo 1
debug:  message=Command failed: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/.com.ubports.installer.qoBXZX -P 5038 shell echo 1
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
, stack=Error: Command failed: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/.com.ubports.installer.qoBXZX -P 5038 shell echo 1
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=1, signal=null, cmd=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/.com.ubports.installer.qoBXZX -P 5038 shell echo 1
debug: adb shell: echo 1
debug: 
debug: adb shell: getprop ro.product.device
debug: 
debug: getprop: mako
debug: adb shell: cat /etc/system-image/channel.ini
debug: 
debug: adb shell: echo 1
debug: 
debug: reboot to bootloader
debug: fastboot: wait for device
debug: 
debug: reboot to bootloader [DONE] err:null
**** And nothing beyond this ****

**Comment by developer-sp** [comment]
not happen here too with my nexus4, I tried in ubuntu18.10 and W10, how can i to install it?

**Comment by NeoTheThird** [comment]
Sorry, many issues on macos right now. Working on it...
In the meantime, you can use the manual install instructions on https://devices.ubuntu-touch.io
