### ISSUE TITLE
UBPorts installer downloads the images in clear

### ISSUE THREAD

**Issue by garro95** [ubports/ubports-installer#382]
The ubports installer does not use HTTPS to download the images. This exposes the users to some risks like hijacking the connection to trick them to download the wrong file or privacy violations.

**Comment by NeoTheThird** [comment]
The integrity of the downloaded files are checked using the sha256 hash, so a man-in-the-middle attack can not go undetected.

**Comment by garro95** [comment]
There was a discussion in the Telegram group. Also other members of the community found that an encrypted channel should be used when available

**Comment by NeoTheThird** [comment]
Actually, we are already using https on system-image. I ran a package analysis, and the only thing i found downloaded in plain are the pre-requisites from http://cdimage.ubports.com/ that are flashed in the very beginning. The checksums for these images are compared against a separate api server that has encrypted communication, so i was correct about package-injection being impossible (also, in most cases the prerequisite images is overwritten by the corresponding images from the device tarball in the end of the installation).

So, still no security risk there, but i'll talk to infra to set up tls on cdimage so we can change the data sources on the api to https. Not necessary in this case, but it might be nice to have for other applications in the future, for example when downloading stuff from cdimage in another context.
