### ISSUE TITLE
Uncaught Error: user-open error: Object does not implement the interface (MainRenderer:39)

### ISSUE THREAD

**Issue by Silverbackmusic** [ubports/ubports-installer#383]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/8pH3Qf3J9k/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
