### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.583s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.586s

### ISSUE THREAD

**Issue by jh-frank** [ubports/ubports-installer#386]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: source
Operating System: Ubuntu Linux 16.04 xenial ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/XGxsjvvdRw/

**Comment by jonnius** [comment]
duplicate of #184
