### ISSUE TITLE
Nexus 5: Fastboot: Unknown error... target didn't report max-download-size sending 'recovery' 

### ISSUE THREAD

**Issue by tatonuta** [ubports/ubports-installer#388]
The ubuntu-installer stops after the reset with a following error message:

```
Fastboot: Unknown error: [sudo] _password of user adminek_: target didn't report max-download-size sending 'recovery' (11828 KB)...
FAILED (command write failed (Protocol error))
finished. total time: 0.000s
```

![ubports-installer_error_nexus5_2018 07 25](https://user-images.githubusercontent.com/40709402/43221993-ed3764d0-904e-11e8-8dc3-fc7e871f4ed6.png)

Device: Nexus 5, until now was on Android
Ubuntu-installer just downloaded a .deb from https://devices.ubuntu-touch.io/device/hammerhead and installed from "Software"
Computer: Ubuntu 18.04
I chose 16.04/rc and "wipe data" during the installation.

Additionally, a message appeared: "You are not using the latest stable version of the UBports installer" (similar to issue #373)

**Comment by tatonuta** [comment]
SOLVED

After I reproted this bud I clicked on "Try again", and tried again. This time the installation was successful!

In the second run I have chosen exactly the same options, i.e.:
- Choose your device -> Nexus 5
- Wipe data
- 16.04/rc

So in the second run I did **exactly** the same things as in the first run. 

The only difference was that in the second run I was not asked about removing OEM (the warining message and the dialogue on the phone, somewhere after the reset).

**Comment by NeoTheThird** [comment]
Sorry about the late reply. The missing report of download size and the protocol error are actually unrelated. The Protocol error occurs when the connection to the device is lost during the installation, so it make sense that this worked on the second try. This error is handled in #710. Thanks for the detailed report!
