### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:247)

### ISSUE THREAD

**Issue by rometc** [ubports/ubports-installer#389]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 10
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/JKG7KKCtpd/

**Comment by NeoTheThird** [comment]
Sorry, the Nexus 10 is not supported. For a list of supported devices see https://device.ubuntu-touch.io.
