### ISSUE TITLE
Installation gets stuck due to out-of-date adb server

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#39]
Sometimes the installer gets stuck with an out-of-date adb server as indicated by eg. the installer waiting for the device to enter recovery mode for ages. When running from source, this can be fixed by running `adb devices` in a seperate terminal, so adb automatically restarts the adb server and the installation proceeds.

**Comment by NeoTheThird** [comment]
More information in duplicates of this issue: #41 #40 #36

**Comment by NeoTheThird** [comment]
As a workaround, older versions of the installer that are not affected can still be used, of course: https://github.com/ubports/ubports-installer/releases/tag/0.1.5-beta

**Comment by Anne017** [comment]
Thanks @NeoTheThird , but I still get stucked at the bootloader screen with the 0.1.5 AppImage.
I tried the 0.1.7 AppImage, the snap package and the source...

**Comment by NeoTheThird** [comment]
This should be fixed in the latest version, please try again, everybody. Sorry it took so long and thanks for your patience!

**Comment by NeoTheThird** [comment]
> And I also tried with the magic-device-tool but I now get a blue screen...

Blue screen is caused by the new display of the FP2, which is not supported in the stable channel yet (will be with ota-3, eta 21. of december). Please try installing the rc channel for now.

**Comment by frthjf** [comment]
I have the same issue with my Fairphone 2 that has been upgraded to Android 7. 

![image](https://user-images.githubusercontent.com/5411942/50549345-1c696980-0c53-11e9-8838-255a9f2c26cd.png)
