### ISSUE TITLE
Adb push error: cannot stat ''C:\Users\...\AppData\Roaming\ubports\pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz'': No such file or directory

### ISSUE THREAD

**Issue by montage114** [ubports/ubports-installer#392]
I use installer 0.1.12-beta on windows 10 since the latest version 0.1.21-beta gives me issue #184 
It happens after the installer checked Ubuntu Touch files, and i even confirmed that the file is there myself.

**Comment by montage114** [comment]
I tried installer 0.1.9 and it works.

**Comment by NeoTheThird** [comment]
Should be solved in #710. Sorry about the delay...
