### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349)

### ISSUE THREAD

**Issue by impearker** [ubports/ubports-installer#393]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/QRcTNffcxk/

**Comment by NeoTheThird** [comment]
Please run `snap refresh` and try again.
