### ISSUE TITLE
Uncaught Error: Gtk-Message: 16:50:43.377: Failed to load module "unity-gtk-module"(firefox:26784): Gtk-WARNING **: 16:50:43.475: Theme parsing error: gtk.css:126:40: Expected ')' in color definition(firefox:26784): Gtk-WARNING **: 16:50:43.512: Theme parsing error: gtk.css:8673:128: Expected a valid selectorGtk-Message: 16:50:43.554: Failed to load module "unity-gtk-module"Gtk-Message: 16:50:43.621: Failed to load module "unity-gtk-module" (MainRenderer:39)

### ISSUE THREAD

**Issue by ffmnc** [ubports/ubports-installer#394]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/nfRKvRZ46n/

**Comment by NeoTheThird** [comment]
Sorry for the late reply, but what flavor of Ubuntu was this? Wayland or X?

**Comment by ffmnc** [comment]
No worries, it was Wayland

**Comment by NeoTheThird** [comment]
Okay, should work now. Closing for now.
