### ISSUE TITLE
Deb / App image stuck at "Waiting for device to enter recovery mode"

### ISSUE THREAD

**Issue by Elderberry4Linux** [ubports/ubports-installer#396]
I've tried the Deb, Snap, and App image Ubports-installer but none are working right.
Using Linux Mint and a Nexus 5 btw.

With a Deb or App image install, my pc doesn't auto detect my Nexus 5 and I choose manually. It does flash the recovery but I get stuck at "Waiting for device to enter recovery mode" while my Nexus 5 has switched to Ubports Recovery.

The Snap install also doesn't detect my Nexus 5 and I get stuck at installing the recovery.

Thanks for any help. :)

Eventually got 16.04 rc installed on my Nexus 5 using a Elementary OS laptop. :)

**Comment by Danfro** [comment]
Yep, same here with my BQ E5 running ubuntu 18.04 on my laptop.
Also not detected although I could adb into my phone.
I selected manually, could not start into bootloader, did _"adb reboot bootloader"_ to fix this.
I did actually solve this hang with a hint from Telegram Welcome Group: unplug USB cable, plug in again. Then it would continue. All up and running now!
