### ISSUE TITLE
Uncaught Error: Gtk-Message: Failed to load module "canberra-gtk-module"Gtk-Message: Failed to load module "canberra-gtk-module" (MainRenderer:39)

### ISSUE THREAD

**Issue by xemexpress** [ubports/ubports-installer#398]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Not detected
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/9ss6GdV2TC/

**Comment by NeoTheThird** [comment]
Sorry for the late reply, but what flavor of Ubuntu was this? Wayland or X?
