### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:247)

### ISSUE THREAD

**Issue by MITeoRIte** [ubports/ubports-installer#399]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Samsung Galaxy Note 2 LTE%0D%0APackage: dmg%0D%0AOperating System: macOS 10.13.617G65 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/C8N8S6Vs53/ %0D%0A

**Comment by NeoTheThird** [comment]
Sorry, the Samsung Galaxy Note 2 LTE is not supported. For a list of supported devices see https://device.ubuntu-touch.io.

**Comment by NeoTheThird** [comment]
Sorry, the Samsung Galaxy Note 2 LTE is not supported. For a list of supported devices see https://device.ubuntu-touch.io.
