### ISSUE TITLE
ubports-installer does not detect fp2

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubports-installer#40]
ubports-installer does not detect fp2
i'm using ubports-installer snap - installed:   0.1.7-beta (6) 88MB devmode - on Ubuntu 16.04
and i'm on 15.04/devel r183 on the phone
![err](https://user-images.githubusercontent.com/333589/31899756-250664a4-b825-11e7-8b77-4d309034597a.jpg)

i can see the phone in nautilus, and "adb shell" works fine, i can connect to the phone. i also have developer mode enabled

**Comment by NeoTheThird** [comment]
Try running `adb devices` while the installer is waiting for the device. If that helps, the problem is #39.

**Comment by pixelr0** [comment]
doesn't seems to help :'(

adb devices
adb server is out of date.  killing...
cannot bind 'tcp:5037'
ADB server didn't ACK
* failed to start daemon *
error:

**Comment by pixelr0** [comment]
ok, flashed 15.04/stable/r2 and it's the same ubports-installer does not detect fp2

should i proceed with manual?

**Comment by pixelr0** [comment]
same with the appimage, so it's not snap related

**Comment by NeoTheThird** [comment]
> doesn't seems to help :'(

If you get that error, try running `adb devices` again, please.

**Comment by NeoTheThird** [comment]
Please also try running the installer from source. See README.md

**Comment by Anne017** [comment]
It seems to be the same issue than #36

**Comment by Anne017** [comment]
I tried to run the installer from source without success:

git clone git@github.com:ubports/ubports-installer.git
Cloning into 'ubports-installer'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by pixelr0** [comment]
right, same permission denied (publickey) error here. you can workaround that error by using "git clone https://github.com/ubports/ubports-installer". even so on my PC ubuntu 16.04 ./setup-dev.sh hangs at loadDevDep:unzip → network

**Comment by pixelr0** [comment]
phew!! finally managed to install fp2 devel. i had to run ./setup-dev.sh a couple of time since it kept hanging on random steps in npm-install. running from source recognized fp2 straight up. 

![fp2](https://user-images.githubusercontent.com/333589/32047632-40df0a92-ba4f-11e7-9d1b-272d7a032c89.jpg)

**Comment by Anne017** [comment]
OK, this time everything went fine typing into the terminal:
git clone https://github.com/ubports/ubports-installer.git
cd ubports-installer
./setup-dev.sh
npm start

But after that, I still get an error between the password and the bootloader screens.
It seems the installer has been modified and now it is possible to send a bug report.
Reference is #41

**Comment by NeoTheThird** [comment]
Thanks for reporting! I'm pretty sure it's related to #39, so let's track it there.
