### ISSUE TITLE
Uncaught Error: [Parent 8187, Gecko_IOThread] WARNING: pipe error (60): Die Verbindung wurde vom Kommunikationspartner zurückgesetzt: file /build/firefox-oscv9o/firefox-61.0.1 build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353 (MainRenderer:39)

### ISSUE THREAD

**Issue by ghost** [ubports/ubports-installer#403]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: OnePlus One
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/gm55YVMJkj/

**Comment by NeoTheThird** [comment]
Sorry for the late reply... Do you remember what package you used here?
