### ISSUE TITLE
Command failed: echo '' | sudo -S echo correct[sudo] salasana henkilölle janek: Yritä uudelleen.[sudo] salasana henkilölle janek: sudo: 1 väärä salasana yritetty

### ISSUE THREAD

**Issue by tedeja** [ubports/ubports-installer#406]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: OnePlus One
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/s9PqdgChGr/

**Comment by Mickaelbou** [comment]
Hi, this problem comes from your Linux distro, on my gentoo I hadn't "sudo" command, I installed it and it worked perfectly after that!
