### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, chmod '/var/folders/fh/_z5q3v3n08s0cf1yvbq31lfr0000gn/T/tmp-88293IqE5E5hrgGEB/adb' (MainRenderer:250)

### ISSUE THREAD

**Issue by quacklabs** [ubports/ubports-installer#408]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Not detected%0D%0APackage: source%0D%0AOperating System: macOS 10.12.616G1408 x64 %0D%0ANodeJS version: v8.9.3 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/xrv78Bp5yh/ %0D%0A

**Comment by NeoTheThird** [comment]
Solved in #710
