### ISSUE TITLE
Uncaught Error: [Parent 8063, Gecko_IOThread] WARNING: pipe error (61): La màquina remota ha reiniciat la connexió: file /build/firefox-mWstsA/firefox-61.0.1 build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353 (MainRenderer:39)

### ISSUE THREAD

**Issue by Juakote** [ubports/ubports-installer#409]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/BXjVY82b3g/

**Comment by NeoTheThird** [comment]
Sorry about that. You might be able to work around this by simply trying again. This problem is solved in the latest version, but unfortunately that has other problems, which I assume are the reason you are using this old version. We're trying to fix the latest version asap... Sorry about that.
