### ISSUE TITLE
Command failed: echo  | sudo -S echo correct/bin/sh: 1: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by Anne017** [ubports/ubports-installer#41]
Automatically generated error report 
Version: 0.1.5-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/25825674/

**Comment by NeoTheThird** [comment]
Thanks for reporting! I'm pretty sure it's related to #39, so let's track it there.
