### ISSUE TITLE
ubports-installer doesn't see devices

### ISSUE THREAD

**Issue by Donieck** [ubports/ubports-installer#413]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/CfKCVDSdcd/

**Comment by NeoTheThird** [comment]
Sorry about the late reply. If you're still interested, this issue can be solved by running `snap connect ubports-installer:adb-support`.
