### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by Donieck** [ubports/ubports-installer#415]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/PyG82S8Dyc/

**Comment by NeoTheThird** [comment]
Looks like the device got disconnected during the installation. You could just try again or use a different usb cable, if this one sits a little loose.
