### ISSUE TITLE
"fastboot: wait for device"

### ISSUE THREAD

**Issue by ghost** [ubports/ubports-installer#416]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Arch Linux undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/w8Y4k22YFG/ 

I can't get it to go past fastboot mode.  I have tried all of my cables in every USB port available on two computers and it won't budge.

**Comment by ridobe** [comment]
It doesn't matter if I supply the adb/fastboot drivers or if I let the installer use it's own, as soon as I hit the install button it automatically reboots to the bootloader.  It never gives me the opportunity to do it on my own.  Then, it asks me to either "connect your device using a usb cable" or "are you ready for ubuntu touch on your nexus 5"?  The last line in the ubports-installer log is always {"level":"debug","message":"fastboot: wait for device","timestamp":"2018-08-24T13:06:48.515Z"}

I have the correct line in my udev rules as I had purchased it at launch.

**Comment by ridobe** [comment]
Current ubports-installer.log looks completely clean until it reaches the fastboot line.

{"level":"debug","message":"Welcome to the party","timestamp":"2018-08-24T15:28:48.138Z"}
{"level":"debug","message":"Killing all running adb servers...","timestamp":"2018-08-24T15:28:48.162Z"}
{"level":"debug","message":"Using fallback platform tools!","timestamp":"2018-08-24T15:28:48.181Z"}
{"level":"debug","message":"","timestamp":"2018-08-24T15:28:48.225Z"}
{"level":"debug","message":"","timestamp":"2018-08-24T15:28:48.253Z"}
{"level":"debug","message":"adb shell: echo 1","timestamp":"2018-08-24T15:28:48.302Z"}
{"level":"warn","message":"Running latest stable version.","timestamp":"2018-08-24T15:28:48.626Z"}
{"level":"debug","message":"Successfully downloaded devices list","timestamp":"2018-08-24T15:28:48.636Z"}
{"level":"debug","message":"","timestamp":"2018-08-24T15:28:51.338Z"}
{"level":"debug","message":"adb shell: getprop ro.product.device","timestamp":"2018-08-24T15:28:51.339Z"}
{"level":"debug","message":"","timestamp":"2018-08-24T15:28:51.391Z"}
{"level":"debug","message":"getprop: hammerhead","timestamp":"2018-08-24T15:28:51.391Z"}
{"level":"debug","message":"adb shell: cat /etc/system-image/channel.ini","timestamp":"2018-08-24T15:28:52.463Z"}
{"level":"debug","message":"","timestamp":"2018-08-24T15:28:52.540Z"}
{"level":"debug","message":"adb shell: echo 1","timestamp":"2018-08-24T15:29:05.318Z"}
{"level":"debug","message":"","timestamp":"2018-08-24T15:29:05.396Z"}
{"level":"debug","message":"reboot to bootloader","timestamp":"2018-08-24T15:29:05.396Z"}
{"level":"debug","message":"","timestamp":"2018-08-24T15:29:05.530Z"}
{"level":"debug","message":"reboot to bootloader [DONE] err:null","timestamp":"2018-08-24T15:29:05.530Z"}
{"level":"debug","message":"checking password","timestamp":"2018-08-24T15:29:12.725Z"}
{"level":"debug","message":"correct password","timestamp":"2018-08-24T15:29:12.762Z"}
{"level":"debug","message":"fastboot: wait for device","timestamp":"2018-08-24T15:29:12.763Z"}

**Comment by te-online** [comment]
> 4. before launching i needed to change the port in src/adb.js from const PORT = 5038 to const PORT = 5037

This actually worked – but why? Shouldn't it be the default then?

**Comment by fabrei** [comment]
take a look at [line 20](https://github.com/ubports/ubports-installer/blob/master/src/adb.js#L20). the comment suggests that port `5037` is default. but i don't know why it is commented out. the developers should know it ;-) i cannot remember, but when i flushed my device a few months ago for the first time, i got this trick somehow..

**Comment by dmaglio** [comment]
same issue for me, Oneplus one and fedora 29 x86_64

`debug: Welcome to the party
debug: Killing all running adb servers...
debug: Using native platform tools!
debug: Running platform tool exec cmd adb kill-server
debug: 
debug: Running platform tool exec cmd adb -P 5038 kill-server
debug: 
debug: adb shell: echo 1
debug: Running platform tool exec cmd adb -P 5038 shell echo 1
debug: Successfully downloaded devices list
warn: Running latest stable version.
debug: 
debug: adb shell: getprop ro.product.device
debug: Running platform tool exec cmd adb -P 5038 shell getprop ro.product.device
debug: 
debug: getprop: A0001
debug: adb shell: cat /etc/system-image/channel.ini
debug: Running platform tool exec cmd adb -P 5038 shell cat /etc/system-image/channel.ini
debug:  message=Command failed: adb -P 5038 shell cat /etc/system-image/channel.ini
cat: /etc/system-image/channel.ini: No such file or directory
, stack=Error: Command failed: adb -P 5038 shell cat /etc/system-image/channel.ini
cat: /etc/system-image/channel.ini: No such file or directory

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=1, signal=null, cmd=adb -P 5038 shell cat /etc/system-image/channel.ini
debug: adb shell: echo 1
debug: Running platform tool exec cmd adb -P 5038 shell echo 1
debug: 
debug: reboot to bootloader
debug: Running platform tool exec cmd adb -P 5038 reboot bootloader
debug: 
debug: reboot to bootloader [DONE] err:null
debug: checking password
debug: correct password
debug: fastboot: wait for device
`

**Comment by dmaglio** [comment]
> i had the same issue with one plus one on debian stretch and installer version 0.1.21-beta. but i could fix it.
> 
>     1. `apt install adb fastboot`
> 
>     2. my device was not detected, so i followed [these instructions](https://github.com/ubports/ubports-installer#device-not-detected-linux)
> 
>     3. then i downloaded the [sources](https://github.com/ubports/ubports-installer#how-to-run-the-program-from-source)
> 
>     4. before launching i needed to change the port in `src/adb.js` from `const PORT = 5038` to `const PORT = 5037`
> 
>     5. enable developer mode on device
> 
>     6. then i plugged the device in and unlocked it
> 
>     7. start the installer `npm start`
> 
> 
> the installer detected the device immediately and i chose the newest stable version. i used nodejs v10.9.0 and npm 6.2.0
> hope this helps :)

tried but i have same issue...

**Comment by NeoTheThird** [comment]
Since multiple issues are mixed here, and some time has passed, i will close this issue. If you continue to have problems, please open new issues and we will deal with them individually.
