### ISSUE TITLE
UBports Installer Update available but there is none

### ISSUE THREAD

**Issue by thisismyownusername** [ubports/ubports-installer#418]
If I start UBports Installer I get the message "Update available" but if I run "snap refresh ubports-installer --stable" there is none and I get "snap 'ubports-installer' has no updates available"

*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux  16.04  xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/sZb3Q3qWpH/

**Comment by NeoTheThird** [comment]
fixed, sorry
