### ISSUE TITLE
Uncaught Error: (firefox:25383): Gtk-WARNING **: 23:39:25.871: Theme parsing error: gtk.css:6777:29: Missing opening bracket in color definition(firefox:25383): Gtk-WARNING **: 23:39:25.871: Theme parsing error: gtk.css:6779:34: Missing opening bracket in color definition(firefox:25383): Gtk-WARNING **: 23:39:25.871: Theme parsing error: gtk.css:6785:28: Missing opening bracket in color definition (MainRenderer:39)

### ISSUE THREAD

**Issue by Joseph-k-iype** [ubports/ubports-installer#419]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: mh
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/CWfWnqd6YT/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
