### ISSUE TITLE
Cannot install OTA-4 on Nexus 5 running Android

### ISSUE THREAD

**Issue by tihom7** [ubports/ubports-installer#420]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Nexus 5%0D%0APackage: dmg%0D%0AOperating System: macOS 10.13.617G65 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/kgYYwVVFbW/ %0D%0A

**Comment by ewentual** [comment]
16/04 rc also bootloops

**Comment by ewentual** [comment]
Found a fix: install TWRP, change /data filesystem to ext4

Wipe -> advanced wipe > check data -> repair or change filesystem -> ext4

Successfully installed 16.04/stable after that on 0.1.12 on mac

**Comment by mmxgn** [comment]
Can confirm that doing the steps ewentual suggested allowed me to pass that stage.

**Comment by NeoTheThird** [comment]
Sorry about the late reply. There are different issues mixed here, most of them should be fixed in #710 and will be included in the next release.
