### ISSUE TITLE
Fastboot: Unknown error:  [sudo] logan 的密码： downloading 'boot.img'...OKAY [  0.673s]booting...FAILED (remote: unknown command)finished. total time: 0.686s

### ISSUE THREAD

**Issue by xjlongfeiyu** [ubports/ubports-installer#423]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu MX4
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/CmHK6gN4dx/

**Comment by NeoTheThird** [comment]
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.
