### ISSUE TITLE
Properly handle errors in another language

### ISSUE THREAD

**Issue by lasselarsendk** [ubports/ubports-installer#425]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ Aquaris E4.5
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/NmjFZC2gp7/

**Comment by NeoTheThird** [comment]
My translator tells me "Beklager, prøv igen" means "Sorry, please try again". So it looks like you mistyped your password :) Please try again.

But we need to find a solution for errors in different locales...
