### ISSUE TITLE
Adb failed to reboot!, reboot failed: -1 : 

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubports-installer#43]
Automatically generated error report 
Version: 0.1.8-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/25925980/

**Comment by NeoTheThird** [comment]
Could you try again with the latest version?

**Comment by gabriel-lucas** [comment]
This looks related.
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1613966

**Comment by tim-sueberkrueb** [comment]
I can reproduce this issue when trying to reflash my Nexus 5 already running Ubuntu Touch on Ubuntu 17.10.

**Comment by NeoTheThird** [comment]
This is not reproducible for me. Are you sure you are running the latest version of the installer?

**Comment by NeoTheThird** [comment]
Okay, i saw this on my M10 now, but i still have not found a reliable way of reproducing this issue. I don't think it's something we can fix inside the installer, but what we need is proper error handling that tells the user how to re-boot manually.
