### ISSUE TITLE
MacOS Desktop installer app

### ISSUE THREAD

**Issue by ernmander** [ubports/ubports-installer#430]
The MacOS desktop ubports-installer app freezes and hangs after detecting the mobile device. Device boots into fastboot then the installer app freezes. Even the report bug button doesn't respond.

**Comment by ernmander** [comment]
Damian Thank you for the heads up I'll try that workaround.

**Comment by Benoit9** [comment]
You also need to have adb and fastboot in your path, otherwise the installer gets stuck. 

If your run the installer from the command line you see all the "command failed" errors.

**Comment by raveesh-me** [comment]
<img width="269" alt="image" src="https://user-images.githubusercontent.com/15698263/217435840-ae1a1d54-f336-44f5-8e54-df5d5bdeaee6.png">

Solution continues to fail in the latest MacOS
