### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Passwort für jochen: downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.362s

### ISSUE THREAD

**Issue by Jochen2701** [ubports/ubports-installer#432]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/SVfvhVCFDx/

**Comment by blaubaer01** [comment]
Test UBports Installer 0.1.12-beta. In my case this version run without this issue.

**Comment by fabrei** [comment]
i had the same log messages. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by jonnius** [comment]
duplicate of #184

**Comment by NeoTheThird** [comment]
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.
