### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.435s]writing 'recovery'...FAILED (remote: failed to get download permission for partition 'recovery')finished. total time: 0.438s

### ISSUE THREAD

**Issue by ersanchez** [ubports/ubports-installer#438]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: BQ M10 FHD
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/PGq9CZDHCP/

**Comment by fabrei** [comment]
i had the same log messages. maybe [this](https://github.com/ubports/ubports-installer/issues/416#issuecomment-417250720) helps :)

**Comment by ersanchez** [comment]
Ok, thanks :)

I'll give it a try when I get home.

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
