### ISSUE TITLE
installer stuck 0.1.8

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubports-installer#44]
i'm running ubports-installer-0.1.8-beta-x86_64.AppImage on ubuntu 16.04
i have 16.04/devel and want to flash 15.04/stable
ubports installer detects the Fairphone 2 but then it hangs at the next step (install) with the "please connect your device with an usb cable". but that's silly because it is connected and detected the phone just fine. 

![ub2](https://user-images.githubusercontent.com/333589/32617197-005e4256-c57d-11e7-8a39-4b167479f845.png)

the last debug line is "debug: fastboot: wait for device". so.. should i manually put the phone into fastboot? o_O

 ./ubports-installer-0.1.8-beta-x86_64.AppImage  
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: echo 1
debug: adb shell: getprop ro.product.device
debug: getprop: FP2
debug: adb shell: cat /etc/system-image/channel.ini
debug: adb shell: echo 1
debug: reboot to bootloader
debug: checking password
debug: correct password
debug: fastboot: wait for device

**Comment by pixelr0** [comment]
so yeah.. you have to manually put the phone into fastboot "hold Volume Down + Power" until the phone reboots and vibrates. so.. if you don't launch the installer from CLI you are pretty clueless about what's going on, the CLI just tell you to connect your device but the actual problem is that it can't automatically reboot/fasboot. another problem is the ubports image servers are sometimes slow, i had to wait 15 min to download the images

**Comment by pixelr0** [comment]
ok, so if you don't launch from the CLI and have trouble using the installer, you can check the log in 
~/.cache/ubports/ubports-installer.log

**Comment by NeoTheThird** [comment]
Hey, this should be resolved with the latest version of the installer. If it still does not work, please run `echo 0x2ae5 >> ~/.android/adb_usb.ini` in the terminal and try again. Please report your results, issues like this are always a little tricky to resolve. Thanks.
