### ISSUE TITLE
Uncaught Error: (/usr/lib/firefox/firefox:6976): dconf-WARNING **: 20:45:51.910: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission denied(/usr/lib/firefox/firefox:7082): dconf-WARNING **: 20:48:47.361: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission denied

### ISSUE THREAD

**Issue by craigynotknow** [ubports/ubports-installer#440]
What should I do to install Ubuntu on my nexus 5 ?

**Comment by NeoTheThird** [comment]
Sorry about the late reply. This seems to be a configuration error with your operating systems snapd. Please try a different package (the appimage should work) and look into fixing your snapd configuration.
