### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by MykolasJokubauskas** [ubports/ubports-installer#447]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/FqkTfK6kZg/

**Comment by NeoTheThird** [comment]
Looks like the device got disconnected during the installation. You could just try again or use a different usb cable, if this one sits a little loose.
