### ISSUE TITLE
Fastboot: Unknown error:  [sudo] senha para ***: target didn't report max-download-sizesending 'recovery' (24080 KB)...FAILED (remote: permission denied!)finished. total time: 0.002s

### ISSUE THREAD

**Issue by ratattuile** [ubports/ubports-installer#448]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/WfcR27fhmZ/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
