### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 1073741824 bytessending 'recovery' (11828 KB)...FAILED (data transfer failure (Protocol error))finished. total time: 0.175s

### ISSUE THREAD

**Issue by SuperH-0630** [ubports/ubports-installer#449]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/B8Wb8X2XMV/

**Comment by NeoTheThird** [comment]
Fixed in 17269e0933dc85b2c982d1ca58f55ecd1bdfaccd
