### ISSUE TITLE
Old fastboot for High Sierra

### ISSUE THREAD

**Issue by Rudi9719** [ubports/ubports-installer#45]
In order to use this on High Sierra you must download the source, run npm install then update platform-tools/mac/fastboot with [this one](https://issuetracker.google.com/issues/64292422#comment8)

**Comment by Rudi9719** [comment]
Not sure how plausible this is- but maybe check/use the user's adb/fastboot if available?

**Comment by NeoTheThird** [comment]
> Not sure how plausible this is- but maybe check/use the user's adb/fastboot if available?

That should work now, actually. Could you try again with the latest dmg?
