### ISSUE TITLE
Uncaught Error: user-open error: Object does not implement the interface (MainRenderer:39)

### ISSUE THREAD

**Issue by coffeepotprotocol** [ubports/ubports-installer#451]
Running OpenSuse LEAP 15, I'm unable to update the installer
Linux version 4.12.14-lp150.12.16-default (geeko@buildhost) (gcc version 7.3.1 20180323 [gcc-7-branch revision 258812] (SUSE Linux) ) #1 SMP Tue Aug 14 17:51:27 UTC 2018 (28574e6)

snap refresh ubports-installer --stable 
snap "ubports-installer" has no updates available  

Tried to update it using yast :
snapd wird heruntergeladen (Downloadgröße 9,08 MiB)
snapd-2.33.1-lp150.1.1.x86_64.rpm wird installiert (installierte Größe: 46,80 MiB)
The installer still tells me it isn't up to date.                  

When running it :
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: BQ Aquaris E5
Package: snap
Operating System: Raspbian  16  undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/h9crF8qKP8/

**Comment by coffeepotprotocol** [comment]
There's no "Channel" shown by default and I also can't switch to another one (empty dropdown), is this possibly relevant ?

**Comment by coffeepotprotocol** [comment]
Managed to install UBports using the latest Ubuntu desktop version, but it also took some time until a channel was shown. Had a E5 Android version plugged in for a couple of minutes to test the difference, meanwhile the channel showed up and I could switch my (Canonical) Ubuntu touch to UBports.

**Comment by NeoTheThird** [comment]
Sorry about the late reply. Glad it worked for you in the end, we'll still have to investigate this.

**Comment by NeoTheThird** [comment]
Hasn't been reported again in a long time, i suspect this has been fixed by an update in our electron deps.
