### ISSUE TITLE
BQ Aquaris E5 (with Ubuntu touch): ubports installation stuck with "Please reboot to bootloader"

### ISSUE THREAD

**Issue by ragsna** [ubports/ubports-installer#452]
on the Aquaris E5 "FASTBOOT mode ..." is displayed. 
Also when attempting a boot on device it stays at "FASTBOOT mode ..." (other options are Recovery and Normal mode).

*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: BQ Aquaris E5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/pv29GqYtCm/

**Comment by ragsna** [comment]
worked when using fastboot program to reboot device into FASTBOOT mode before using ubports-installer

**Comment by MKarstens** [comment]
I had the same problem and solved it by a temporary disconnection of phone and computer.
https://github.com/ubports/ubports-installer/issues/1969
