### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Passwort für franziska: downloading 'boot.img'...OKAY [  0.493s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.494s

### ISSUE THREAD

**Issue by Mondschein93** [ubports/ubports-installer#457]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/crfG7qSvZG/

**Comment by jonnius** [comment]
duplicate of #184

**Comment by NeoTheThird** [comment]
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.
