### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >target reported max download size of 134217728 bytessending 'recovery' (10046 KB)...OKAY [  0.386s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.388s

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#460]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/Gvh9YfVVZ6/

**Comment by NeoTheThird** [comment]
Sorry about that. You might be able to work around this by simply trying again. This problem is solved in the latest version, but unfortunately that has other problems, which I assume are the reason you are using this old version. We're trying to fix the latest version asap... Sorry about that.
