### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.380s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.382s

### ISSUE THREAD

**Issue by chrigustoll** [ubports/ubports-installer#461]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/7BttYq2txc/

**Comment by jonnius** [comment]
duplicate of #184
