### ISSUE TITLE
Uncaught Error: [19715:19715:0918/204450.230329:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process. (MainRenderer:39)

### ISSUE THREAD

**Issue by bedna-KU** [ubports/ubports-installer#462]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 4
Package: source
Operating System: Ubuntu Linux undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/ytbr2qx8Jy/

**Comment by NeoTheThird** [comment]
Sorry about the late reply. I guess you were holding broken platform tools, should be solved by running the setup script again, or installing adb and fastboot.
