### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.361s]booting...FAILED (remote: dtb not found)finished. total time: 0.398s

### ISSUE THREAD

**Issue by nareshkadali9** [ubports/ubports-installer#463]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 FHD
Package: unknown
Operating System: Ubuntu Linux    18.04    bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/P46FT3r3yW/

**Comment by blaubaer01** [comment]
On Fairphone 2 the Version 0.1.12 works, maybe it will run with BQ M10 FHD too

**Comment by NeoTheThird** [comment]
Duplicate of #699.
