### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.759s]booting...FAILED (remote: dtb not found)finished. total time: 0.810s

### ISSUE THREAD

**Issue by nareshkadali9** [ubports/ubports-installer#464]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Ws7rRxXrc7/

**Comment by blaubaer01** [comment]
On Fairphone 2 the Version 0.1.12 works, maybe it will run with Meizu Pro 5 too

**Comment by NeoTheThird** [comment]
Duplicate of #699.
