### ISSUE TITLE
FP2 fastboot mode does not start; unlike shown in minute 1:24 of Ubuntu Touch Install video 2018

### ISSUE THREAD

**Issue by ClaudiaKoltzenburg** [ubports/ubports-installer#466]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: exe
Operating

(via computer with OS Windows and universal adb drivers installed)
Ubuntu Touch Install video 2018 via https://devices.ubuntu-touch.io/device/FP2

**Comment by Ingo-FP-Angel** [comment]
The install video doesn't show a Fairphone 2. There, the fastboot mode looks different (just the boot screen wih white "Fairphone Powered by Android").
I guess this is more like the many other bugs where the installer doesn't detect that the phone is already in fastboot mode, e.g. #416
