### ISSUE TITLE
Uncaught Error: user-open error: Object does not implement the interface (MainRenderer:39)

### ISSUE THREAD

**Issue by apoo7rv** [ubports/ubports-installer#467]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/zVZBDFRw6R/ 
at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12), killed=false, code=255, signal=null, cmd=adb -P 5038 shell echo 1
info: Instructing manual reboot
debug: fastboot: wait for device
info: Download startCheck
error: Not existing /home/apoo7rv/snap/ubports-installer/172/.cache/ubports/images/turbo/recovery-turbo.img
info: Starting download of 1 files
info: Downloading file, 1% complete
info: Downloading file, 6% complete
info: Downloading file, 14% complete
info: Downloading file, 23% complete
info: Downloading file, 33% complete
info: Downloading file, 42% complete
info: Downloading file, 51% complete
info: Downloading file, 59% complete
info: Downloading file, 68% complete
info: Downloading file, 77% complete
info: Downloading file, 85% complete
info: Downloading file, 93% complete
info: Download checking file
info: checked: recovery-turbo.img
info: Download complete
info: done downloading(once listener)
debug: fastboot: flash; [{"type":"recovery","url":"http://cdimage.ubports.com/devices/recovery-turbo.img","checksum":"632dae343d026d755867c43ba8634c42edcc5d2b81856e790ebc8d71eaf18c03","path":"/home/apoo7rv/snap/ubports-installer/172/.cache/ubports/images/turbo"}]
info: Booting into recovery image...
error: Devices: Error: Fastboot: Unknown error:  downloading 'boot.img'...
OKAY [  0.764s]
booting...
FAILED (remote failure)
finished. total time: 0.765s

warn: snap

**Comment by NeoTheThird** [comment]
Should be solved in #710. Sorry for the late reply.
