### ISSUE TITLE
Improve password request dialog

### ISSUE THREAD

**Issue by kwah-gh** [ubports/ubports-installer#47]
For me as a user it was unclear, which password is needed. I assumed device lock password. Luckily, I was not the first one to stumble on it e.g. https://forums.ubports.com/post/2071

**Comment by NeoTheThird** [comment]
Thanks for reporting

**Comment by slicer69** [comment]
I agree. Having the installer's password prompt say something like "Please enter sudo password" or "Please enter your computer's admin password" would be more clear. I thought it was asking for my phone's PIN at first.

**Comment by NeoTheThird** [comment]
Fixed in 39e91897a5880214bba66faead0bf7969f5f5ca1.
