### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...FAILED (data transfer failure (Protocol error))finished. total time: 0.551s

### ISSUE THREAD

**Issue by nareshkadali9** [ubports/ubports-installer#473]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/R3WgJ9hK87/

**Comment by blaubaer01** [comment]
On Fairphone 2 the Version 0.1.12 works

**Comment by Ingo-FP-Angel** [comment]
I had the same problem just now with a Fairphone 2 and running 0.1.21-beta.
It worked to click "Try again" and simply start over the whole procedure.

**Comment by NeoTheThird** [comment]
Fixed in 17269e0933dc85b2c982d1ca58f55ecd1bdfaccd
