### ISSUE TITLE
Fastboot: Unknown error:  [sudo] yuankangkai 的密码： target didn't report max-download-sizesending 'recovery' (10046 KB)...OKAY [  1.976s]writing 'recovery'...FAILED (remote: (InvalidSize))finished. total time: 2.266s

### ISSUE THREAD

**Issue by ykk0612** [ubports/ubports-installer#474]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ Aquaris E5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/s9zHfWxNwV/

**Comment by blaubaer01** [comment]
On Fairphone 2 the version 0.1.12 works

**Comment by 5kup** [comment]
Not for me...

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
