### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 536870912 bytessending 'recovery' (11442 KB)...OKAY [  0.364s]writing 'recovery'...FAILED (status read failed (No such device))finished. total time: 25762.642s

### ISSUE THREAD

**Issue by nareshkadali9** [ubports/ubports-installer#475]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Y4Hc8P5gYp/

**Comment by blaubaer01** [comment]
Run the programm verison 0.1.12

**Comment by NeoTheThird** [comment]
Fixed in 17269e0933dc85b2c982d1ca58f55ecd1bdfaccd
