### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:221)

### ISSUE THREAD

**Issue by userj** [ubports/ubports-installer#476]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/HTWBY5cHmG/

**Comment by NeoTheThird** [comment]
That log looks weird. Can you try again?

**Comment by userj** [comment]
I think it was a onetime thing that will have to wait until it happens again (or not!)

**Comment by NeoTheThird** [comment]
Oh, just saw the version number, this error is handled in newer versions. It's a network connection issue.
