### ISSUE TITLE
Is there anyway use CLI install ubuntu touch ?

### ISSUE THREAD

**Issue by 0312birdzhang** [ubports/ubports-installer#478]
The GUI tools is toooooo `difficult`, i switch from Windows to Ubuntu and one hour passed, only entered recovery mode.

Why don't you provide one CLI tool ? I think if you give me the instruction, i can install ubports in minutes.

![image](https://user-images.githubusercontent.com/1762041/46246699-5fd5f100-c434-11e8-9e55-4dd31ab7b63f.png)

**Comment by Iolaum** [comment]
Have enabled developer mode from your device and then enabled USB debugging from your computer?

**Comment by 0312birdzhang** [comment]
Sure, i switched to Windows 10 and completed the installation

**Comment by NeoTheThird** [comment]
Manual cli instructions will soon be on the devices page and the installer will get its own cli interface. In the works on the refactor branch, but not done yet.
