### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349) (Meizu Pro 5 Ubuntu Edition)

### ISSUE THREAD

**Issue by RenaldoJay** [ubports/ubports-installer#479]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux  16.04  xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/vzPYShSRVk/

**Comment by NeoTheThird** [comment]
Please run `snap refresh` and try again.
