### ISSUE TITLE
Better checks for success

### ISSUE THREAD

**Issue by DiogoConstantino** [ubports/ubports-installer#483]
Recently the installer reported me successful operation while flashing a device, however the operation failed. This means that current checks aren't robust enough, better checks should be made.

**Comment by NeoTheThird** [comment]
We can't get any information out of the device after we pushed all installation files and initiated the reboot. At that point, UBports Recovery kicks in and works its magic. It is true however, the installer sometimes does not throw errors when it should, related to the callback hell we're fixing right now on the refactor branch.
