### ISSUE TITLE
Install gets stuck at reboot to fastboot stage

### ISSUE THREAD

**Issue by slicer69** [ubports/ubports-installer#49]
When trying to install UBports on my device, the process starts out well. The installer gets me to select an image/branch, gets me to plug in the device, enable developer mode, asks if I want to wipe the device. and then it asks me to reboot into fastboot mode.

At this point the installer stops. I reboot my device, make sure it's at the proper screen, but the installer remains stuck, asking me to reboot. I've tried running through the steps three times and each time the installer appears to be unaware the phone has rebooted and is waiting on the fastboot screen.

This happens with both installer versions 0.1.6-beta and 0.1.7-beta. I'm trying to upgrade a Meizu Pro 5 phone which currently runs Ubuntu Touch 15.04. The UBports installer I am using is the one bundled as an AppImage package.

The output displayed by the installer to my terminal is as follows:

debug: adb shell: echo 1
debug: fastboot: wait for device

I was told on Twitter by a UBports member that this issue is known, but I did not see a report for it, so I'm posting this so I can track the bug's progress.

**Comment by NeoTheThird** [comment]
Hey there, thanks for reporting. Could you try again with the latest version of the installer? This issue should be resolved now. Sorry it took so long.

**Comment by slicer69** [comment]
I gave the new installer, version 0.1.9-beta, a try. After selecting my phone's model (Meizu Pro 5) and asking the installer not to wipe my data, I'm prompted for my sudo password and asked to reboot the phone. The fastboot screen comes up, displaying status as "unlocked, unrooted" on my device and the UBports installer displays the following output to my terminal:

debug: checking password
debug: correct password
debug: fastboot: wait for device
debug: Using fallback platform tools!
debug: Running platform tool fallback exec asar cmd echo **mypassword** | sudo -S fastboot devices
debug: Running platform tool fallback exec asar cmd echo **mypassword** | sudo -S fastboot devices
...

The last debug message repeats every few seconds.

Side note: I'm not a big fan of having my sudo password echoed to the terminal, perhaps the next version of the installer could simply report the sudo password is correct and then replace the password with stars?

I wasn't sure if fastboot was included in the UBports AppImage I downloaded so I installed it separately (fastboot wasn't installed before and no error was given by the installer). With fastboot instaled separately, the installer gives the same output shown above.

**Comment by NeoTheThird** [comment]
>  I'm not a big fan of having my sudo password echoed to the terminal.

Definitely, that is a problem, sorry about that. Looking into it at the moment: #54.

> I tried running "sudo fastboot devices" manually while my phone was plugged in, both in its normal state and on the fastboot screen with developer mode enabled.

Interesting. Could you try using a different usb cable or a different usb port on your pc?  You can also try to disconnect your device and connect it again.

**Comment by slicer69** [comment]
I tried disconnecting and reconnecting the phone with another USB port. Also tried it on another computer entirely, just to rule out PC trouble. Got the same result, with "sudo fastboot devices" not returning anything. The result is the same whether the phone is running normally (in developer mode) or on the fastboot screen.

I'll try another USB cable next to see what happens. The phone charges over this one and I can transfer files, so I think the cable is good, but I'll give another a try to confirm.
