### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >(bootloader) has-slot:recovery: not foundtarget reported max download size of 536870912 bytessending 'recovery' (24080 KB)...OKAY [  1.010s]writing 'recovery'...(bootloader) Image size exeeded partition limits(bootloader) Preflash validation failedFAILED (remote failure)finished. total time: 1.015s

### ISSUE THREAD

**Issue by robertpsouza** [ubports/ubports-installer#494]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/dQhgm6tP3H/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
