### ISSUE TITLE
Installer doesn't recognize N5 on Debian

### ISSUE THREAD

**Issue by riccardovidotto** [ubports/ubports-installer#495]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: snap
Operating System: Debian 9.5 undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/f4B5nXXM5g/

**Comment by NeoTheThird** [comment]
Sorry about the late reply. This can be solved by running `snap connect ubports-installer:adb-support` now.
