### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by Beko1981Lokmani** [ubports/ubports-installer#498]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 4
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/BfcYpq3G3X/

**Comment by DioginisLima** [comment]
flashing images...

flashing recovery and boot 

??
