### ISSUE TITLE
Fastboot: Unknown error:  [sudo] senha para ***: target didn't report max-download-sizesending 'recovery' (11366 KB)...FAILED (command write failed (Success))finished. total time: 0.000s

### ISSUE THREAD

**Issue by ratattuile** [ubports/ubports-installer#50]
Automatically generated error report 
Version: 0.1.5-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/26071127/

**Comment by NeoTheThird** [comment]
Hey there, could you try again with the latest version?
