### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349)

### ISSUE THREAD

**Issue by Who223222** [ubports/ubports-installer#501]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Wnw3zGYrjK/

**Comment by NeoTheThird** [comment]
Please run `snap refresh` and try again.
