### ISSUE TITLE
could not find latest version

### ISSUE THREAD

**Issue by Albin-John** [ubports/ubports-installer#502]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/M7WYSS3T5v/

**Comment by ernesst** [comment]
I can confirm

**Comment by NeoTheThird** [comment]
That's a network issue. Just try again. Newer version of the installer also present you with a prompt to try again and check your connection.
