### ISSUE TITLE
Adb push error: error: device not found

### ISSUE THREAD

**Issue by Albin-John** [ubports/ubports-installer#503]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/ZzMymvCqT4/

**Comment by NeoTheThird** [comment]
Looks like the device got disconnected during the installation. You could just try again or use a different usb cable, if this one sits a little loose.

**Comment by NeoTheThird** [comment]
Duplicate of #207
