### ISSUE TITLE
Uncaught Error: ExceptionHandler::GenerateDump cloned child 14729ExceptionHandler::SendContinueSignalToChild sent continue signal to childExceptionHandler::WaitForContinueSignal waiting for continue signal... (MainRenderer:39)

### ISSUE THREAD

**Issue by mionescu2018** [ubports/ubports-installer#506]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 FHD
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/YXsG43YcKH/

**Comment by NeoTheThird** [comment]
Not seen again in a while, closing. Probably an issue with one of our dependencies.
