### ISSUE TITLE
Phone not rebooting

### ISSUE THREAD

**Issue by PatrickTSudlow** [ubports/ubports-installer#507]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Not detected
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/3NhbjbH4jV/

**Comment by NeoTheThird** [comment]
Fixed in #710. Sorry for the late reply.
