### ISSUE TITLE
Adb push error: failed to copy '/home/erik/snap/ubports-installer/170/.cache/ubports/pool/ubports-1e002fd7e685421651a9b8dc15b0147c4460993169acd0519183533f17331c84.tar.xz' to '/cache/recovery//ubports-1e002fd7e685421651a9b8dc15b0147c4460993169acd0519183533f17331c84.tar.xz': No space left on device

### ISSUE THREAD

**Issue by wurzer** [ubports/ubports-installer#511]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: BQ Aquaris E4.5
Package: snap
Operating System: Ubuntu Linux  undefined  undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/D2FkjfHzfJ/

**Comment by NeoTheThird** [comment]
That should be a temporary issue. Please try again.
