### ISSUE TITLE
It seems that the installer bricked my phone

### ISSUE THREAD

**Issue by hiredgunhouse** [ubports/ubports-installer#513]
It seems that the installer bricked my phone. I tried using ubports-installer on a OnePlus One that had CyanogenMod installed. The installer detected the phone and was able to reset it fastboot or something ( sorry, I'm a total noob in the subject) and the installer was waiting and waiting and seemed to have frozen in that state without any progress for a long time. After I disconnected the phone it seemed to be frozen as well, the screen would be on and the phone would not react to buttons, I had to let it discharge.
Now when I try to charge it I get a screen saying that the battery is low and this screen is on forever and after hours of charging there seems to be no progress and the phone does not react to any buttons and I can on leave it and let it discharge slowly due to the screen being on.
I noticed that there seems to be no way to open up the phone to i.e. take out the batter, etc.
Is there anything I can do to somehow fix the phone?
Also if there's nothing I can do with this phone I'd be worried to buy another one and use the installer on the new one. Is there any manual procedure that can be used?
Sorry for the non-technical description, I really am a noob when it comes to flashing phones ;/
Any help would appreciated.

**Comment by NeoTheThird** [comment]
Incredibly sorry for the late reply. Were you able to revive your device? What version of CyanogenMod was the device running before the installation?

**Comment by hiredgunhouse** [comment]
No problem.
No, I haven't got round to it and since I don't have the skills I will have to try some local repair shop.
As for the version of CyanogenMod unfortunately I have idea, sorry.

Anyway I would love to get back to Ubuntu Touch, I liked it and I think it has incredible potential. I'm on Sailsifh OS now, it has its pros and cons, but I don't see it having as much potential as UBPorts.
Keep up the good work!

**Comment by NeoTheThird** [comment]
Okay, so you did get it working again, that's good :)

It's planned to do this automatically in the installer in future versions, but for now you can follow the steps i described [in this post on the forums](https://forums.ubports.com/topic/1054/phone-reboots-if-releasing-the-usb-connection-to-my-computer/10) to flash some required partitions and then just run the installer again. This is kind of technical, though... Unfortunately we have other tasks with higher priorities right now, so it will be at least another month before i can put in the work to make this user-friendly in the installer, sorry... Maybe you have a tech-savy acquaintance who could help you with that? I'm of course also happy to answer any questions on here, or (if you're a telegram user) you can join the [install group](https://t.me/WelcomePlus) where there are many people who are always happy to help.

**Comment by hiredgunhouse** [comment]
Thank you, I'm closing this issue then.

**Comment by NeoTheThird** [comment]
Okay, good luck!
