### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.765s]booting...FAILED (remote failure)finished. total time: 0.765s

### ISSUE THREAD

**Issue by ratattuile** [ubports/ubports-installer#518]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/grhQQW84hk/

**Comment by NeoTheThird** [comment]
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.
