### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.357s]booting...FAILED (remote: dtb not found)finished. total time: 0.377s

### ISSUE THREAD

**Issue by Mack6767** [ubports/ubports-installer#520]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/jgMhMxqxsH/

**Comment by NeoTheThird** [comment]
Duplicate of #699.
