### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizeSending 'recovery' (13708 KB)...OKAY [  0.748s]Writing 'recovery'...FAILED (remote: Security deny - Err:0x2017 )Finished. Total time: 0.948s

### ISSUE THREAD

**Issue by Oscar-Macdonald** [ubports/ubports-installer#523]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu MX4
Package: source
Operating System: Raspbian undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/N5HbymNj2r/ 
*End of automatically generated error report*
Linux kernel: 4.18.16-arch1-1-ARCH
ubports-installer built from source code (github)
Running Android version: 5.1
Running build number: Flyme 6.3.0.2A

**Comment by NeoTheThird** [comment]
Please follow the legacy instructions [here](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices)
