### ISSUE TITLE
ubuntu touch didn't available for ASUS_T00F1

### ISSUE THREAD

**Issue by hikenone** [ubports/ubports-installer#527]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: ASUS_T00F1
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Qh97g878Pv/

**Comment by NeoTheThird** [comment]
Sorry. You can try to enable your device yourself using [halium](https://halium.org) if you want.
