### ISSUE TITLE
Fastboot: Unknown error:  [sudo] yuankangkai 的密码： target didn't report max-download-sizesending 'recovery' (10044 KB)...OKAY [  1.984s]writing 'recovery'...FAILED (remote: (InvalidSize))finished. total time: 2.269s

### ISSUE THREAD

**Issue by ykk0612** [ubports/ubports-installer#529]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 (wifi)
Package: unknown
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/TT3CBS3T6z/

**Comment by NeoTheThird** [comment]
Sorry about the late reply. We had a broken image on the server, that has been fixed now. Please try again.
