### ISSUE TITLE
Uncaught TypeError: log.warning is not a function (MainRenderer:200)

### ISSUE THREAD

**Issue by lavadew** [ubports/ubports-installer#53]
Got this error message, when i start the ubports-installer on macOS Sierra 10.12.6..
![issue_ubports_installer](https://user-images.githubusercontent.com/33376325/33661671-4148fe2a-da89-11e7-8aa8-61aab8cfbe18.png)

**Comment by NeoTheThird** [comment]
Yikes, sorry about that. Fixed in 7c1e85f5887e6f5387fafa92b827d528687f12c4.
