### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for elina: downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by GiveMeManner** [ubports/ubports-installer#532]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/C36szsmw2n/

**Comment by jonnius** [comment]
duplicate of #184
