### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.371s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.372s

### ISSUE THREAD

**Issue by OlofRJA** [ubports/ubports-installer#535]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Fairphone 2%0D%0APackage: dmg%0D%0AOperating System: macOS 10.12.616G1510 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/gm25mJNJdf/ %0D%0A

UBports Installer Version: 0.1.21-beta
Device: Fairphone 2
OS: MacOS 10.12.6

**Comment by jonnius** [comment]
duplicate of #184
