### ISSUE TITLE
UBport installer not detecting oneplus one in bootloader also not performing installation

### ISSUE THREAD

**Issue by rashvin** [ubports/ubports-installer#538]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: OnePlus One%0D%0APackage: dmg%0D%0AOperating System: macOS 10.13.617G65 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/RyWkmpKsw5/ %0D%0A

**Comment by NeoTheThird** [comment]
Sorry about the late reply. Should be fixed in #710.
