### ISSUE TITLE
Password visible if app is launch within a shell

### ISSUE THREAD

**Issue by rapha8l** [ubports/ubports-installer#54]
Hi,

Thanks for your installer, which is very helpful.
A little thing bothered me, as I launched the app from within a shell, I saw my password clearly written in stdout in the shell.
I think it would be better if it was obfuscated, even if launching from a shell may be not the main way to start ubports-installer.
regards

**Comment by NeoTheThird** [comment]
Weird, that shouldn't happen... https://github.com/ubports/ubports-installer/blob/master/src/utils.js#L140. I'll have to investigate where that's coming from.

**Comment by rapha8l** [comment]
Thanks for you reply.
I used the UBports Installer 0.1.8-beta deb package (maybe it's working normally in head)

**Comment by NeoTheThird** [comment]
No, it doesn't. Something is going wrong.

**Comment by tim-sueberkrueb** [comment]
Hey Jan, I believe it's coming from here:
https://github.com/ubports/ubports-installer/blob/9b8d6e29059cce3fbd55085d30c492dc0c64b8f3/src/utils.js#L244

**Comment by mjsir911** [comment]
This is a problem for me too, makes it harder to report logs.

Difference between just copy-pasting and having to go through the logs myself to remove any sensitive data

`debug: Running platform tool exec asar cmd echo ***password*** | sudo -S fastboot devices`

**Comment by tim-sueberkrueb** [comment]
This is particularly alarming as the automatic bug report feature leads to user passwords being uploaded to paste.ubuntu.com.
@mariogrip @NeoTheThird

**Comment by NeoTheThird** [comment]
Fixed in https://github.com/ubports/ubports-installer/commit/598841da87c7520de951f1c3b33d3eed6c4fac11 for now. Sorry it took so long, everyone!
