### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  1.103s]booting...FAILED (remote failure)finished. total time: 1.105s

### ISSUE THREAD

**Issue by petrus-hanks** [ubports/ubports-installer#542]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/djJV27tGDx/

**Comment by NeoTheThird** [comment]
What OS is the device running now? possible duplicate of #221.

**Comment by NeoTheThird** [comment]
Sorry about that. Solved on the refactor branch, will be included in the next release. Duplicate of #716.
