### ISSUE TITLE
Fastboot: Unknown error:  [sudo] Mot de passe de kapussinettes : downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.362s

### ISSUE THREAD

**Issue by Kapu06** [ubports/ubports-installer#543]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/RCqtvmvCxG/

**Comment by jonnius** [comment]
duplicate of #184
