### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.323s]booting...FAILED (remote: dtb not found)finished. total time: 0.345s

### ISSUE THREAD

**Issue by Aladio** [ubports/ubports-installer#544]
*Automatically generated error report* 
UB

**Comment by Aladio** [comment]
Phone bricked

**Comment by NeoTheThird** [comment]
Sorry about that (and the late answer). Were you able to restore your device? What device was this, what OS and version was it running?
Duplicate of #699.
