### ISSUE TITLE
App hangs on indefinitely after booting to recovery (FP2)

### ISSUE THREAD

**Issue by pbarnoux** [ubports/ubports-installer#55]
Hello,

This is probably a duplicate but since #44 was tagged 0.1.8 and #52 was flagged as not needed anymore, I think it deserves a new issue.

Everything is going fine till the GUI asks to reboot to recovery mode. I press the buttons till the phone vibrates and the program does not detect the phone anymore. I get a dialog box from my OS warning that the phone cannot be mounted, and the terminal shows only the following lines:

```
debug: adb shell: echo 1
debug: Running platform tool exec cmd adb -P 5038 shell echo 1
debug:  Error: Command failed: adb -P 5038 shell echo 1
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

Few words about how I got there:

The FP2 is running Fairphone Open (latest stable) with developer mode enabled.
On Debian GNU/Linux 9 with node 6.12.2, I cloned this repository and ran (from commit 9b8d6e) :

```
npm install
npm start
```

Enabled debugging on FP2 OS (dialog popping up), the app detects the FP2, switched to 15.04/devel + no wipe and everything went well till the reboot to recovery procedure.

I also tried the `echo 0x2ae5 >> ~/.android/adb_usb.ini` command given in other issues, and restarted (had to reboot to bootloader manually and select FP2 manually but the app managed to connect to the phone nevertheless). Yet the end result is the same from my point of view.

Note that my knowledge about android is quite limited, but I'd gladly run any command you may deem necessary to help you pinpoint the issue.

**Comment by NeoTheThird** [comment]
> I also tried the echo 0x2ae5 >> ~/.android/adb_usb.ini command given in other issues, and restarted (had to reboot to bootloader manually and select FP2 manually but the app managed to connect to the phone nevertheless). Yet the end result is the same from my point of view.

Just for clarity, did you do this *while* the installation was running? If so, please try starting the installation process again, that command sets the adb vendor key, but the adb server needs to be restarted in order for the changes to take effect.

**Comment by pbarnoux** [comment]
I am almost sure I broke the process in the terminal to run the echo command, but this morning I wanted to give a new try.
I connect the phone, `npm start`, do you want to enable remote debugging? and then I am fed up with this dialog box so I check always allow and ok, 15.04/devel, no wipe, reboot to recovery and it works Oo.

So either I made a mistake yesterday when issuing the echo command and retrying, or the computer has to be granted remote debugging rights forever before rebooting. Many thanks for the hard work!

**Comment by NeoTheThird** [comment]
Ok, great! I'm glad it worked, i was starting to question my sanity. Hope you have a better experience from now on...
