### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349)

### ISSUE THREAD

**Issue by tukilo** [ubports/ubports-installer#552]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux  18.10  cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/dgVK9MZYb8/

**Comment by NeoTheThird** [comment]
Please run `snap refresh` and try again.
