### ISSUE TITLE
15.04 should no longer be offered

### ISSUE THREAD

**Issue by SamuelBrucksch** [ubports/ubports-installer#554]
Hi,

i tried to install 15.04 as i have wifi probs on 16.04 but it always installs 16.04 when i select 15.04. Is there a way to provide images manually so i can install 15.04?

*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 4
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/QbFZ6xHVP8/

**Comment by NeoTheThird** [comment]
Sorry about that, the 15.04 channels have been closed and redirected for security purposes. Why do you need to install 15.04?

**Comment by NeoTheThird** [comment]
For the record, this should be fixed in [the system-image-node-module](https://github.com/ubports/system-image-node-module). We need to check if a channel is redirected and not return it if it is.

**Comment by SamuelBrucksch** [comment]
Hi, i had problems with BT that i did not have on an earlier version so i tried a lower version...
