### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for joe: target didn't report max-download-sizesending 'recovery' (24080 KB)...FAILED (data transfer failure (Protocol error))finished. total time: 0.640s

### ISSUE THREAD

**Issue by kigula23** [ubports/ubports-installer#555]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/bxQXZs7zpc/

**Comment by NeoTheThird** [comment]
What OS is the device running?

**Comment by NeoTheThird** [comment]
Fixed in 17269e0933dc85b2c982d1ca58f55ecd1bdfaccd
