### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 300941312 bytessending 'recovery' (11442 KB)...OKAY [  0.378s]writing 'recovery'...FAILED (remote: size too large)finished. total time: 0.397s

### ISSUE THREAD

**Issue by SithuInnovate** [ubports/ubports-installer#558]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/DM4JyjnKhZ/

**Comment by NeoTheThird** [comment]
That was a temporary issue, should be fixed now.
