### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by G-Bigo** [ubports/ubports-installer#560]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 (wifi)
Package: exe

Installation from Windows on Nexus 7 Wifi (2013) is impossible. 
Developer mode on Nexus 7 activated. Bootloader unlocked. 
Universal ADB on Windows installed and started.
Windows recognizes the Nexus 7. ADB input is accepted on Nexus.
ADB finds the Nexus 7. E.g.: 'adb reboot bootloader' works fine.

UBPorts installer does NOT find the device. Tested on three different Windows computers. 
I have manually have choosen device and clicked 'Install'. UBPorts installer is stuck at the window 'Please reboot to bootloader', even though an 'Android Bootloader Interface' is even shown in the Windows device manager.

**Comment by NeoTheThird** [comment]
Sorry, the installer has a lot of issues on Windows at the moment. You might get somewhere with an older version, there are some reports of 0.1.12-beta working on windows, but it has other issues as well. We're working to fix this.
