### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.590s]booting...FAILED (remote failure)finished. total time: 0.590s

### ISSUE THREAD

**Issue by robertoduwe** [ubports/ubports-installer#563]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/p5RqYtPyyd/

**Comment by NeoTheThird** [comment]
What OS is the device running right now?

**Comment by NeoTheThird** [comment]
Duplicate of #716.
