### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by LarrydeHobit** [ubports/ubports-installer#564]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Pj4ctBfNKy/

**Comment by NeoTheThird** [comment]
Looks like the device got disconnected during the installation. You could just try again or use a different usb cable, if this one sits a little loose.
