### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [ 13.522s]booting...FAILED (status read failed (No such device))finished. total time: 18.636s

### ISSUE THREAD

**Issue by JoTiZ** [ubports/ubports-installer#567]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/xkkcSDKp9D/

**Comment by JoTiZ** [comment]
Same problem with the older installer version: ubports-installer_0.1.20-beta_amd64

This was used for the successful OTA5 install.

**Comment by JoTiZ** [comment]
No problem with :

UBports Installer Version: 0.1.21-beta
Device: Nexus 5
Package: unknown
Operating System: Deepin 15.8

Install Log: http://paste.ubuntu.com/p/YHQ5GMFRkN/

**Comment by NeoTheThird** [comment]
Fixed in 17269e0933dc85b2c982d1ca58f55ecd1bdfaccd
