### ISSUE TITLE
UBport not available for my architecture

### ISSUE THREAD

**Issue by Olivier688** [ubports/ubports-installer#571]
Hello.
I'm still on ubuntu 14.04 LTS.
I c'an't install the UBPorts intaller.
It says the architecture is incorrect.
When I try with snap, i've got this message 
erreur : snap "ubports-installer" is not available on stable for this
          architecture (i386) but exists on other architectures (amd64)
Is there any version for 32 bits processors ?
Thanks.

**Comment by NeoTheThird** [comment]
Sorry, not at the moment. But you can just follow the manual install instructions for your device on https://devices.ubuntu-touch.io.
