### ISSUE TITLE
Account for linux operating systems w/o sudo

### ISSUE THREAD

**Issue by straygrey** [ubports/ubports-installer#574]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Debian 9.6 stretch x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/rC3ngywFWS/ 

Error thrown: "Command failed: echo '' | sudo -S echo correct/bin/sh: 1: sudo: not found"

**Comment by PerinaElectronic** [comment]
It happened to me too, it happens when your password contains a special character like `\`
I solved it by opening the program from Terminal with `sudo`

`sudo ubports-installer` worked for me in Linux Mint 19.1 and Ubuntu 18.10

Hope it helps
Yanko

_(Really sorry for the bad english :/)_
