### ISSUE TITLE
Last Screen Needs Don't Unplug Till Finished Warning

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/ubports-installer#579]
Good day.
I was installing a fresh version of UT on my N5 and Installation went well, but last screen gave no warning to leave device plugged in but it was still going.  These two screens were on at the same time:

![ubports_installer_last_screen_needs_warning](https://user-images.githubusercontent.com/16578346/49693565-45eb1580-fb2b-11e8-8864-1a0f9c3fc3e7.png)

![ubports_n5_stil_installing_after_done_message](https://user-images.githubusercontent.com/16578346/49693566-47b4d900-fb2b-11e8-9e1e-559e6cc8071d.jpg)

**Comment by UniversalSuperBox** [comment]
There is no need to keep the device plugged in after the recovery reboots itself and starts the install process. At that point "The process from the computer is finished".

**Comment by wayneoutthere** [comment]
Then what we need is a clear message that says "IT IS NOW SAFE TO UNPLUG YOUR PHONE!"  Surely i'm not the only person who has run into this?
