### ISSUE TITLE
Uncaught TypeError: stdout.includes is not a function (MainRenderer:103)

### ISSUE THREAD

**Issue by silvernode** [ubports/ubports-installer#584]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Not detected (OnePlus One
Package: unknown (appimage)
Operating System: Void Linux 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/P3vhjwjgwg/

**Comment by NeoTheThird** [comment]
Interesting. What rom is the device running?
