### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:247)

### ISSUE THREAD

**Issue by greenpeteuk** [ubports/ubports-installer#585]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5X
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/NFyp5jFc7F/

**Comment by NeoTheThird** [comment]
Sorry, the Nexus 5X is not supported. For a list of supported devices see https://device.ubuntu-touch.io.
