### ISSUE TITLE
Uncaught Error: [24461:24461:1217/044345.974853:ERROR:browser_dm_token_storage_linux.cc(93)] Error: /etc/machine-id contains 0 characters (32 were expected).Gtk-Message: Failed to load module "overlay-scrollbar" (MainRenderer:39)

### ISSUE THREAD

**Issue by mochafauzan** [ubports/ubports-installer#588]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux  14.04  trusty x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/wXXsZpJRSw/

**Comment by NeoTheThird** [comment]
Please open a bug against trusty or your desktop environment.

**Comment by metux** [comment]
Actually, it's a bug in chrome, which expects being on a Lennartware-controlled machine. Chrome wants it to globally identify the machine, eg. for their "enterprise" bloat and better sourveillance.

--mtx
