### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >target didn't report max-download-sizesending 'recovery' (11828 KB)...FAILED (data transfer failure (Protocol error))finished. total time: 0.256s

### ISSUE THREAD

**Issue by NatTuck** [ubports/ubports-installer#590]
Recovery is already installed. It won't install again, and there's no way to skip this now useless step in this awful graphical installer.

*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/GQR8J924Rb/

**Comment by advocatux** [comment]
Hi, I've answered you in #589 

In short, please, try another different USB cable.
