### ISSUE TITLE
could not find latest version

### ISSUE THREAD

**Issue by Zahrun** [ubports/ubports-installer#591]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 4
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/brbnpKmtqJ/

**Comment by NeoTheThird** [comment]
Network issue. Just try again. :)
