### ISSUE TITLE
need to clean cache before installing

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubports-installer#6]
need to clean cache before installing

also check for mounted files and swap images

**Comment by NeoTheThird** [comment]
This was fixed in https://github.com/ubports/ubports-installer/commit/4b4a2f0bd113ccfa82a77700acb125a5c29b9e0a.

**Comment by NeoTheThird** [comment]
As it seems, it actually was not fixed. So we need to run `fastboot erase cache` before commencing installation.
