### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:247)

### ISSUE THREAD

**Issue by VinaChiong** [ubports/ubports-installer#600]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Nexus 7 (wifi)%0D%0APackage: dmg%0D%0AOperating System: macOS 10.14.218C54 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/9htpQDNQ5p/ %0D%0A

**Comment by Tijnert** [comment]
Got this error as well. Trying to flash a Nexus 5X using the UBports installer on MacOS.
When ignoring the error, nothing happens.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/46578738/51343461-c9871300-1a96-11e9-9e3e-1e43b05a1074.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/46578738/51343484-d441a800-1a96-11e9-86be-e097d42cadff.png">

**Comment by NeoTheThird** [comment]
Sorry, the Nexus 5X is not supported. For a list of supported devices see https://device.ubuntu-touch.io.

**Comment by diplomatic-dev** [comment]
This should definitely be acknowledged by the software itself; if ubports-installer automatically detects the 5X, then one would easily assume that it is treated the same as the Nexus 5. Recommending that such a warning/error be added to prevent future confusion.

**Comment by NeoTheThird** [comment]
Yep, that's tracked in #692. Already solved on the refactor branch and will be included in the next release.

**Comment by NeoTheThird** [comment]
Sorry about the confusion...
