### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  0.601s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.603s

### ISSUE THREAD

**Issue by Dave1152000** [ubports/ubports-installer#601]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/nZ6pFGxtdN/

**Comment by NeoTheThird** [comment]
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.
