### ISSUE TITLE
could not find latest version

### ISSUE THREAD

**Issue by quevallier** [ubports/ubports-installer#602]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 FHD
Package: unknown
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/PvrwdS7ydN/

**Comment by NeoTheThird** [comment]
That's a network issue. Try again.
