### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by ISBolshakov** [ubports/ubports-installer#604]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: GalaxyS9
Package: unknown
Operating System: Ubuntu Linux   18.04   bionic x64 
NodeJS version: v8.2.1 
I Want to install ubuntu on my phone but it has unknown model
Error log: http://paste.ubuntu.com/p/ncwZjQSgG2/

**Comment by NeoTheThird** [comment]
That device is not supported, sorry. See https://devices.ubuntu-touch.io
