### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by jaezcurra** [ubports/ubports-installer#605]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu PRO 5
Package: unknown
Operating System: Ubuntu Linux  18.10  cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/GWccYzWQHC/

**Comment by NeoTheThird** [comment]
Looks like the device got disconnected during the installation. You could just try again or use a different usb cable, if this one sits a little loose.
