### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.359s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by AnotherElk** [ubports/ubports-installer#607]
*Automatically generated

I'm trying to install on a Fairphone 2 using Windows 10 Pro 1809 with ubports-installer.0.1.21-beta.exe.
For what it's worth and for what I can see, the message "bootimage: incomplete or not signed" seems to be correct.

As far as I see, the installer downloads recovery-FP2.img to the directory C:\Users\username\AppData\Roaming\ubports\images\FP2 and apparently attempts to "fastboot boot" this image on the Fairphone 2 (in fastboot mode, aka bootloader).
This is bound to fail, because "fastboot boot"ing an image on the Fairphone 2 requires this image to be signed, and recovery-FP2.img is not signed.

I signed it myself, confirmed that it could indeed be "fastboot boot"ed, but I can't bring the installer to use the signed image.
So I'm not getting any further at the moment.

Details about how to sign are here: https://forum.fairphone.com/t/fastboot-boot-is-broken/23235/2?u=anotherelk
How to sign on Windows is here: https://forum.fairphone.com/t/twrp-3-1-1-1-boot-issue/34370/10?u=anotherelk 

It would be helpful to know what the installer tries to do step by step. As a non-developer but experienced user I tried to somehow see this in the sources, but it seems needlessly complicated.
What does the installer do what can't be done with a shell or batch script?

**Comment by Xiakit** [comment]
To get rid of your issue i had to download version 0.1.12-beta.
https://github.com/ubports/ubports-installer/releases/tag/0.1.12-beta

Just to run in to another issue, while  executing the adb push command.
From my point of view it seems to be something with joining paths in windows "\ and / mixed up".
This issue i was solve by using the 0.1.12-beta installer on ubuntu and not on windows.

**Comment by NeoTheThird** [comment]
A manual installation instructions will soon be published on devices.ubuntu-touch.io, see https://github.com/ubports/devices.ubuntu-touch.io/pull/15
