### ISSUE TITLE
The installation on top of Android fails without any error message for encypted Nexus 5

### ISSUE THREAD

**Issue by thetraumer** [ubports/ubports-installer#609]
1. Run installation from Windows for Nexus 5 with Android installed and encryption enabled
2. After the PC part is done, the phone is left with open recovery. No error message is shown.

Formatting and wiping the phone fixes the probem, but having some warning and/or error message would be nice
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: exe
OS: Windows

**Comment by NeoTheThird** [comment]
The installation completed for you on Windows?

**Comment by thetraumer** [comment]
I saw the screen that indication that the PC part of the installation was successful, if that's what you are asking. I do not recall the exact text by now.

**Comment by NeoTheThird** [comment]
Interesting... But yes, we can certainly display a warning about this.
