### ISSUE TITLE
Fastboot: Unknown error:  Password:ERROR: usb_read failed with status e00002edERROR: usb_write failed with status e00002d8ERROR: usb_write failed with status e00002d8downloading 'boot.img'...ERROR: usb_write failed with status e00002c0FAILED (command write failed (Invalid argument))finished. total time: 0.000s

### ISSUE THREAD

**Issue by tihom7** [ubports/ubports-installer#61]
Automatically generated error report %0AVersion: 0.1.5-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v7.9.0 %0A%0AError log: http://paste.ubuntu.com/26231226/ %0A

**Comment by NeoTheThird** [comment]
Should be fixed in the upcoming version, thanks for reporting. :)
