### ISSUE TITLE
boot process does not finish

### ISSUE THREAD

**Issue by nwmorton** [ubports/ubports-installer#610]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 (wifi)
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/mGtpHNqgKK/

**Comment by NeoTheThird** [comment]
Could you try again with the [current prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta)? Thanks!
