### ISSUE TITLE
Some recent change introduced a space in AppImage filename

### ISSUE THREAD

**Issue by Ingo-FP-Angel** [ubports/ubports-installer#612]
The filename of the AppImage has changed between a very recent pull request and some older one.

Old: `ubports-installer-0.1.21-beta-x86_64.AppImage` (see [build from Dec 2018](https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubports-installer/detail/PR-517/9/artifacts))
New: `ubports-installer 0.1.21-beta.AppImage` (see [[build from Jan 11th 2019](https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubports-installer/detail/PR-611/1/artifacts))

I don't mind the lack of `-x86_64` but the space right before the version number is rather inconvenient for double-click-to-select.

**Comment by NeoTheThird** [comment]
no longer an issue: https://github.com/ubports/ubports-installer/releases/tag/0.2.5-beta
