### ISSUE TITLE
Can't get installation progress with Windows Executable or Ubuntu Snap package on 18.04

### ISSUE THREAD

**Issue by gelbbauch** [ubports/ubports-installer#614]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Not detected
Package: exe, snap
Operating System: Windows, Kubuntu 18.04.1

Device is Nexus 7 2013 Wifi only

On any installer version, the Nexus 7 tablet is never seen as connected even though debugging is enabled, authorized for the host device, and put in any USB mode - mtp, charging, photo, etc. I had to manually select the version to install each time.

Installer differences are as follows: Windows would inform me to reboot to recovery manually, which I couldn't do; it would just go to black screen.

The snap/deb installers would automatically get me to the recovery page. The snap would say "flashing recovery files" but not go anywhere even though CPU usage was around 20% for 2-3 ubport PIDs. It sat here for over two hours and I gave up.

I removed the snap installer and downloaded/installed the .deb version. This .deb was able to install the recovery and continue with downloading the files and push them to the device.

**Comment by NeoTheThird** [comment]
Should be resolved in #710 and will be included in the next release. Thanks for reporting.
