### ISSUE TITLE
Nexus 7 2017 Wifi only failure to install

### ISSUE THREAD

**Issue by bmw2621** [ubports/ubports-installer#615]
OTA-7 release said Nexus 7 2013 (Wifi only) compatibility was corrected.  UBPorts Installer successfully loads all files.  After installation, system boots to error screen with image of integrated circuit with red X, and says "This phone needs restoring from a PC or service center."

**Comment by buglinjo** [comment]
@bmw2621 
Found a solution. Just follow this steps: https://github.com/ubports/ubuntu-touch/issues/300#issuecomment-456715728

**Comment by bmw2621** [comment]
@buglinjo  Ive tried everything on the thread and it still wont work.  I even tried doing the installer, then flashing the downloaded boot and recovery files.  Something is still wrong.

**Comment by NeoTheThird** [comment]
Hi, could you try again with the [current prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta)? Thanks!

**Comment by ardklg** [comment]
FYI - I'm getting the same error ("This phone needs restoring from a PC or service center") using the 0.2.2-beta (from a Linux Mint 19 machine). I started with the 0.1.21-beta yesterday, and got the chipX image and message. I thought I'd try the updated installer to see if that made  difference, but no joy.

When I do a hard reset on the device, it takes me to that error screen whether I choose "Start" or "Recovery mode".

Running the newest installer, it recognizes the device as a Nexus 7 even while that error screen is being displayed, and the PC installer appears to successfully push the files over to the device (even though the error screen is being displayed on the device while push is taking place). But then after the device reboots to finish flashing, it goes back to the error screen and goes no further. I even let the device sit for 15-20 minutes thinking something may be working in the background, but it goes nowhere.

Product: flo
Variant: flo 16G
HW: rev_e
Bootloader version: FLO-04.08
Carrier info: none 
Serial number: (not relevant)
Signing: yes
Secure boot: enabled
Lock state: unlocked

**Comment by njtwiseman** [comment]
Confirmed and worked around?

I tried a number of times in various ways, the final setup, I believe, was a factory image from 

[https://developers.google.com/android/images#instructions](https://developers.google.com/android/images#instructions)

Then, I booted into that image and let it fully update.  This provided bootloader FLO-04.02

Activated developer mode, enabled USB debugging (I Think?), then started the 0.2.2 installer (Appimage), I did not choose wipe data (It had already been done enough I thought I'd try without this time).  I let it go through till it said success.  I got the Bad IC chip page on the device.

Then, I had noticed that if I used the installer and choose Nexus LTE I would get to installing updates which would eventually fail.  So I flashed the recovery image from the manual install instructions for the Nexus LTE 

```
wget http://cdimage.ubports.com/devices/recovery-deb.img -O recovery.img && echo "432ee1d970b3b18e74fc80e5c0d091d87598505fe371676b80d20b16df2ea089 recovery.img" | sha256sum -c;
fastboot flash recovery recovery.img;
fastboot reboot;
```

This was in a directory which had all the files from the manual install instructions from Nexus 7 Wifi Only flo

**Comment by ploum** [comment]
in the end, is there currently a workaround or should I wait for an update of UBports?

How can I do a "hard reset" of the device?

**Comment by NeoTheThird** [comment]
@polum We're still working out how to reproduce this issue reliably, since it's more complex than it seems. For [some people, it just works suddenly](https://github.com/ubports/ubports-installer/issues/855#issuecomment-525476475) for no apparent reason. So what you can do is try using the installer again or running the manuall install instructions from https://devices.ubuntu-touch.io.

Or maybe @UniversalSuperBox has a more creative idea?

**Comment by ploum** [comment]
I installed the installed from the .dmg on my macbook.

Didn't know it was kind of an heisenbug. If it could help, I have a second Nexus 7 device that I don't use (touchscreen is partially broken) so I can test stuff on two devices (not sure it could be useful).

Thanks for taking the time to answer.

**Comment by ploum** [comment]
Using installer 0.2.5 beta

**Comment by ploum** [comment]
Any info on how to wipe the cache of the installer on Mac ?

**Comment by NeoTheThird** [comment]
The cache is located in `/Users/[username]/Library/Caches/ubports/`

**Comment by ploum** [comment]
Thanks. For the record, I tried to remove the cache and reinstall without success. Also tried the manual instructions without success (and without any error).

**Comment by ploum** [comment]
I managed to get UBports working by installing TWRP and asking TWRP to wipe all data. It didn't work (twrp told it cannot access partition) but, after that,  I reinstalled UB through UBports and it worked.

As, before TWRP, even the official ROM was not booting anymore, I suspect something related to SELinux and encrypted partition. This might be a workaround for other owners : first install TWRP.

**Comment by NeoTheThird** [comment]
Ahhh, i remember this is a problem for other devices as well, #609.

**Comment by patrodyne** [comment]
I have the same issue, using the UBPorts Installer v0.2.7-beta to install 'Ubuntu Touch' on Nexus 7 2013 Wifi (flo) results with the tablet reporting this error message, "This phone needs restoring from a PC or service center" and displays a stop sign.

I repeated the install with and without the 'wipe' option a few times. I tried using both the Debian and Snap methods to install the installer,

**Comment by ploum** [comment]
@patrodyne : try to install TWRP on the phone first. See my previous comment.
