### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...FAILED (command write failed (No such device))finished. total time: 0.000s

### ISSUE THREAD

**Issue by RafitaRC** [ubports/ubports-installer#617]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 (wifi)
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/t2zmBbDqSx/

**Comment by NeoTheThird** [comment]
Looks like a cable issue. Please try again with a different cable.
