### ISSUE TITLE
Command failed: echo "" | sudo -S echo correct[sudo] password for zesty: Lo sentimos, vuelva a intentarlo.[sudo] password for zesty: sudo: 1 intento de contraseña incorrecto

### ISSUE THREAD

**Issue by novatillasku** [ubports/ubports-installer#62]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.04
Host Arch: x64 
Node: v7.9.0

**Comment by NeoTheThird** [comment]
Should be fixed in the upcoming version, thanks for reporting. :)
