### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:419)

### ISSUE THREAD

**Issue by AnonymousWebHacker** [ubports/ubports-installer#620]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.10
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/YvDwkbfQdD/

**Comment by NeoTheThird** [comment]
Sorry about that. You might be able to work around this by simply trying again. This problem is solved in the latest version, but unfortunately that has other problems, which I assume are the reason you are using this old version. We're trying to fix the latest version asap... Sorry about that.
