### ISSUE TITLE
Uncaught Error: Unable to revert mtime: /usr/local/share/fonts (MainRenderer:39)

### ISSUE THREAD

**Issue by mjs6661999** [ubports/ubports-installer#621]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/vRGHC8bjR3/

**Comment by NeoTheThird** [comment]
That's an issue in your operating systems fontconfig. Please open a bug with Linux Mint.
