### ISSUE TITLE
Uncaught Error: user-open error: Object does not implement the interface (MainRenderer:39)

### ISSUE THREAD

**Issue by vebulous** [ubports/ubports-installer#622]
This is a fresh install of 18.04 on an ASUS EeePC (dinosaur). I've been attempting to get Ubuntu Touch to install on my One Plus One, but couldn't get it done in windows. And I couldn't install this tool on 16.04 (my previous install). So, I opted to just do fresh, and here we are.

*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: OnePlus One
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/bdgDxZcx3s/

**Comment by vebulous** [comment]
Update: I flashed a new stock factory everything (cm-13.1.2-ZNH2KAS3P0-bacon-signed-fastboot_64GB) from https://forum.xda-developers.com/oneplus-one/general/guide-return-opo-to-100-stock-t2826541 in case TWRP was causing an issue. And it appears to still just hang on the "Flashing Images..." screen

**Comment by vebulous** [comment]
Question (if anyone is reading): could I just use fastboot and manually flash recovery and the boot image?
I see both .img files are downloaded to /home/user/snap/ubports-installer/179/.cache/ubports/images/bacon/

**Comment by NeoTheThird** [comment]
Sorry about that. You can follow the manual instructions here: https://devices.ubuntu-touch.io/device/bacon
