### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by AlexUlrich99** [ubports/ubports-installer#627]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 (wifi)
Package: unknown
Operating System: Ubuntu Linux  18.10  cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/P6vhfV4jM2/

**Comment by AlexUlrich99** [comment]
I have two "Nexus 7 2013 - Flo" devices here.

Flo "A." was purchased in 2013 with Android 4.3 pre-installed
Flo "B." was purchased a few years later with 6.x.x pre-installed

Flo "A." installed "Ubuntu touch stable v160" without issue
Flo "B." is having issues mounting partitions with both stable and  developer channels...

I hope this is helpful...

**Comment by NeoTheThird** [comment]
The log looks just like the device got disconnected during the installation. You could just try again or use a different usb cable, if this one sits a little loose.

**Comment by AlexUlrich99** [comment]
Thank you so much for the reply. I'll see what i can do to fix the USB port
before i try again.

**Comment by NeoTheThird** [comment]
You can also try our next [prerelease build](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta), if you want.
