### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.355s]booting...FAILED (remote: dtb not found)finished. total time: 0.381s

### ISSUE THREAD

**Issue by sn0m** [ubports/ubports-installer#633]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Z3bMsrhKmG/

**Comment by sn0m** [comment]
trying to install ubuntu touch on nexus 5

**Comment by NeoTheThird** [comment]
Duplicate of #699.
