### ISSUE TITLE
could not find latest version

### ISSUE THREAD

**Issue by yvan-sraka** [ubports/ubports-installer#635]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/h7gFjxdhqZ/

**Comment by NeoTheThird** [comment]
Possibly a network issue. Please try again.
