### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (11828 KB)...OKAY [  0.446s]writing 'recovery'...OKAY [  2.391s]finished. total time: 2.837ssending 'boot' (12302 KB)...OKAY [  0.441s]writing 'boot'...FAILED (remote: partition 'boot' not support flash)finished. total time: 0.457s

### ISSUE THREAD

**Issue by lazare1999** [ubports/ubports-installer#636]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Nexus 5
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/6RmQHqCtjh/

**Comment by NeoTheThird** [comment]
I haven't seen this before with the Nexus 5. Are you sure you selected the right device?

**Comment by lazare1999** [comment]
Hello

It's my fault, i selected wrong one.

Thank's.
