### ISSUE TITLE
UBports bug on Meizu pro 5

### ISSUE THREAD

**Issue by vokaliz** [ubports/ubports-installer#637]
Hello!
I am trying update my Ubuntu phone (Meizu pro 5 factory unlock), but have problem:
1. Installed UBports (last version) on home machine Ubuntu 16.04 - ok
2. Connected device to computer - ok
3. Accept "yes" from UBports and turn on sudo root on Meizu - ok
4. UBports automaticaly detected device - ok
5. Pushed "Install" and UBports download new Ubuntu for my device - ok
6. Then downloading starts, UBports  installing shows me message "Adb push error:  error: device not found". Meizu itself reload to recovery mode (simbol of Ubuntu on the screen) and all process stops. UBports shows me "Pushing files to device" ... and freeze.
UBports needs Adb drivers for Meizu pro 5? Help me, please!

**Comment by NeoTheThird** [comment]
What OS is the device running now?

**Comment by vokaliz** [comment]
Hello! I was on factory firmware Ubuntu 15 vivid, I am updated my meizu to Ubuntu 16.04 OTA-7, waiting OTA-8. But I am updated only with TWRP. I cant updated meizu pro 5 in all steps with ubports-installer.

**Comment by NeoTheThird** [comment]
What version of the installer is this and on what operating system are you running the installer?

**Comment by vokaliz** [comment]
I used ubports-installer from 0.1.21 to 0.1.12 (up to down) at Linux Ubuntu 16.04 pc, only at version 0.1.12 I can downloaded and copyed ota to meizu and went to reboot, but after few seconds wile install line indicate install process installion was stop and shows me message: ask support. After that any installation from ubports-installer rebooting without effect. I am installed TWRP and only with this instrument I can installed ubports ota-7.

**Comment by vokaliz** [comment]
Update my meizu pro 5 to OTA-8 by the TWRP. 
1. Download ubuntu 16.04 stable in ubports-installer (from 10.03.2019 OTA-8)
2. Copy all files to meizu disk + ubuntu touch installer (download from web)
3. Start ubuntu touch installer in TWRP.
* TWRP - look web how to install on meizu pro 5

**Comment by NeoTheThird** [comment]
Should be fixed in #710, will be included in the next release. You can already try the [prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.2.0-beta), if you want.

**Comment by vokaliz** [comment]
Big thanks! I will!
