### ISSUE TITLE
Corrupted recovery image for Nexus 7 2013 (LTE)

### ISSUE THREAD

**Issue by zpy3** [ubports/ubports-installer#639]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 7 2013 (LTE)
Package: unknown
Operating System: Ubuntu Linux undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/YrnZvNHnDM/

**Comment by chrisvanzet** [comment]
If you try to flash the Nexus 7 2013 (LTE) deb with the flo (Wifi only) image, the flashing of the recovery image is working. Looks like the deb recovery image is somehow corrupted.

**Comment by NeoTheThird** [comment]
Thank you for reporting. New image has been released. Could you try again?

**Comment by chrisvanzet** [comment]
> Thank you for reporting. New image has been released. Could you try again?

Hey,

great, now its working flawless :)

**Comment by NeoTheThird** [comment]
Awesome, thanks for reporting :) Sorry about the long wait...
