### ISSUE TITLE
update available or not available?

### ISSUE THREAD

**Issue by dirkvs** [ubports/ubports-installer#644]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/gBxTdxMssw/ 

On launching the installer, I get the "Update available!" screen saying I'm not running the latest stable version. It recommends running "snap refresh ubports-installer --stable", but the command reports there are no updates available.

**Comment by NeoTheThird** [comment]
Fixed. Run `snap refresh` to instantly get the update.
