### ISSUE TITLE
installer is telling me to connect the phone with an USB cable, but the phone is already connected

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubports-installer#65]
using ubports installer 0.1.9 beta appimage on ubuntu 16.04
so.. the installer is telling me to connect the phone with an USB cable, but the phone is already connected
but the phone is already connected and the installer can see the phone just fine, same the OS and i can adb shell into it. see attached screenshot
![zoom](https://user-images.githubusercontent.com/333589/34327033-bfc96784-e8c2-11e7-9d61-aa29c3736acb.png)

so this is probably just a confusing message? maybe should write "connected" instead or something

**Comment by NeoTheThird** [comment]
Please try again using a different usb cable and port.

**Comment by NeoTheThird** [comment]
@olaf-ej that device is not supported.

@pixelr0 Please report a new issue if this continues to happen.
