### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (10046 KB)...OKAY [  0.396s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.399s

### ISSUE THREAD

**Issue by owaishanif786** [ubports/ubports-installer#651]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ Aquaris E5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/JnwKXVmkty/

**Comment by NeoTheThird** [comment]
Sorry about that. Please follow the unlocking instructions [in the docs](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices). Duplicate of #221.
