### ISSUE TITLE
Uncaught Error: Fontconfig warning: "/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf[9136:9179:0214/223301.080220:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process. (MainRenderer:39)

### ISSUE THREAD

**Issue by Elsur** [ubports/ubports-installer#656]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Linux Mint   undefined   undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/JcYJt47Z8K/

**Comment by NeoTheThird** [comment]
Please take up that issue with Linux Mint.
