### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by salvador1956** [ubports/ubports-installer#660]
will their be an upgrade for UBports to recognize Asus Memo pad K017
Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: K017
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/8Fv65fjPG3/

**Comment by salvador1956** [comment]
Ubports would not recognize asus memo pad k017

**Comment by NeoTheThird** [comment]
That device is not supported. See https://devices.ubuntu-touch.io
