### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (9578 KB)...OKAY [  0.461s]writing 'recovery'...FAILED (remote: partition 'recovery' not support flash)finished. total time: 0.471s

### ISSUE THREAD

**Issue by melanynkiddo** [ubports/ubports-installer#666]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: BQ Aquaris E4.5
Package: snap
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/2sY5t37Fqf/

**Comment by NeoTheThird** [comment]
What OS is the device running now?

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
