### ISSUE TITLE
Device not support

### ISSUE THREAD

**Issue by cxh01987** [ubports/ubports-installer#668]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: le_x2
Package: unknown
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/jzW9Rn424t/

**Comment by NeoTheThird** [comment]
What device is that? Please check https://devices.ubuntu-touch.io for supported devices.
