### ISSUE TITLE
Installer cannot determine a meizu pro5 phone and cannot select manually.

### ISSUE THREAD

**Issue by BigET** [ubports/ubports-installer#67]
The problem is that if your .bashrc file has some code that writes to the console than the installer is confused.
After that it says that the device is not supported and would not allow me to select it manually.
Here is the debug output:
`
debug: Using native platform tools!
debug: Running platform tool exec cmd adb kill-server
debug: 
debug: Running platform tool exec cmd adb -P 5038 kill-server
debug: 
debug: Running platform tool exec asar cmd [object Object] -P 5038 start-server
debug: adb shell: echo 1
debug: Running platform tool exec cmd adb -P 5038 shell echo 1
debug: 
debug: adb shell: getprop ro.product.device
debug: Running platform tool exec cmd adb -P 5038 shell getprop ro.product.device
debug: 
debug: getprop: mountNosuchfileordirectory3201m0m3501mkeychain0m36m2710m3201mhttpwwwfuntooorg0m3201m0mFoundexistingsshagent36m76010m3201m0mKnownsshkey36mhomephabletsshid_dsaoss0m3201m0m3501mkeychain0m36m2710m3201mhttpwwwfuntooorg0m3201m0mFoundexistingsshagent36m76010m3201m0mKnownsshkey36mhomephabletsshid_dsaoss0mturbo
plat
{ adb: 'adb',
  fallback: 
   { fastboot: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/fastboot',
     adb: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/adb' } }
debug: Using native platform tools!
debug: Running platform tool exec cmd adb kill-server
Good bye!
debug: 
plat
{ adb: 'adb',
  fallback: 
   { fastboot: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/fastboot',
     adb: '/opt/ubports-installer/resources/app.asar/platform-tools/linux/adb' } }
debug: Running platform tool exec cmd adb -P 5038 kill-server
debug: 
`
the output when I login with my ssh:
`
$ ssh phablet@192.168.2.194
Welcome to Ubuntu 15.04 (GNU/Linux 3.10.100-user-01771-g301b04f aarch64)

 * Documentation:  https://help.ubuntu.com/
Last login: Sat Nov 25 21:18:19 2017 from edi-stick.lan

 * keychain 2.7.1 ~ http://www.funtoo.org
 * Found existing ssh-agent: 7601
 * Known ssh key: /home/phablet/.ssh/id_dsa.oss

phablet@ubuntu-phablet:~$ 
`

**Comment by NeoTheThird** [comment]
Could you try again with the lines that print that commented out?

**Comment by BigET** [comment]
From what I remember, this was 2 months ago, if I empty my .profile on the phone so it will not give any output then it works. If you look at the provided output you see that it ends with "turbo". However in case of not determining the phone, for whatever reason, it should just allow me to force the device.

**Comment by NeoTheThird** [comment]
Might be related to #225. If you're still experiencing this issue with the latest version and the workaround described there, please file a new bug.
