### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by HDHCambridge** [ubports/ubports-installer#670]
Hello, 

I wanted to install Ubuntu Touch on my Fairphone 2.

I went in developpers mode and could activate the USB debogging, but the menu OEM unlock button didn't appear in the menu.

I went on anyway as I found on a website that if you can't find it, means you don't need it.

The result is the following error message. On the screen of my mobile, it is only written Fairphone powered by ubuntu, but nothing happens.

*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux   18.04   bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/6RcTxkB3x2/ 

Did one of you already have this case or do you know what I should do?

**Comment by Ublublu** [comment]
Hello,
I also have this issue with version 0.1.21. 
I succeed to upgrade  with a previous version of UBports installer: the v0.1.12.
see [How to manually upgrade from OTA-3 to OTA-4](https://forums.ubports.com/topic/1599/how-to-manually-upgrade-from-ota-3-to-ota-4/39)
and [Upgrade to OTA 8 (from OTA7, stable) interrupted on FP2](https://forums.ubports.com/topic/2467/upgrade-to-ota-8-from-ota7-stable-interrupted-on-fp2/6)
