### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bootstrap' of undefined (MainRenderer:247)

### ISSUE THREAD

**Issue by kraken5** [ubports/ubports-installer#678]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Nexus 5X%0D%0APackage: dmg%0D%0AOperating System: macOS 10.14.218C54 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/r3TBB6BQz8/ %0D%0A

**Comment by NeoTheThird** [comment]
Sorry, the Nexus 5X is not supported. For a list of supported devices see https://device.ubuntu-touch.io.
