### ISSUE TITLE
Fastboot: Unknown error:  [sudo] hasło użytkownika julia: downloading 'boot.img'...OKAY [  0.565s]booting...FAILED (status read failed (No such device))finished. total time: 8.316s

### ISSUE THREAD

**Issue by bastardo** [ubports/ubports-installer#679]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 HD
Package: unknown
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/TK74PkKyB6/

**Comment by NeoTheThird** [comment]
Fixed in 17269e0933dc85b2c982d1ca58f55ecd1bdfaccd
