### ISSUE TITLE
MAC install: fail to adb push due to wrong file path

### ISSUE THREAD

**Issue by TH-GH** [ubports/ubports-installer#68]
debug: Running platform tool exec cmd adb -P 5038 push /Users/J/Library/Application Support/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz /cache/recovery/
debug:  Error: Command failed: adb -P 5038 push /Users/J/Library/Application Support/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz /cache/recovery/

Fail to push tar.xz due to mistake in file path: correct would have been '/Users/J/Library/Application\ Support/ubports/pool/xxx.tar.xz' (backslash after Application will correctly pass file path for adb, tested manually)

**Comment by TH-GH** [comment]
Workaround: Change "Application Support" in getUbportDir (utils.js) to "ApplicationSupport" or any other path.

**Comment by NeoTheThird** [comment]
Thanks for reporting! Could you send a pull-request with that change?

**Comment by TH-GH** [comment]
Sure, but as i said, it's just a workaround, one should consider passing the folder name correctly to adb instead of creating a new folder.

**Comment by DamianBakerUK** [comment]
As a suggestion, could the working path for downloaded files for pushing etc be located in Documents or Downloads
/Users/<username>/Documents
/Users/<username>/Downloads

Eithier of these paths already exists on macos, and have no spaces in folder names which may cause issues.

**Comment by kaydoubleyoudee** [comment]
Have the same problem using the ubports-installer on my Mac to flash Utouch to my Nexus 5.  Not a coder like you guys all are :)  but I do my best.  Where can I adjust the code to make it pass this error?  In the terminal?  In the source code?  (If so where to look for).  Any suggestions?  Your help is appreciated!
