### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by nar001** [ubports/ubports-installer#680]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: win32 
Host Dist: undefined undefined
Host Arch: ia32 
Node: v7.4.0 

Error log: https://pastebin.com/N8WDWwCW

**Comment by NeoTheThird** [comment]
Sorry about that. You might be able to work around this by simply trying again. This problem is solved in the latest version, but unfortunately that has other problems on Windows. We're trying to fix the Windows issues asap...
