### ISSUE TITLE
Windows 8.1 UBPorts Installer not detecting device

### ISSUE THREAD

**Issue by genifycom** [ubports/ubports-installer#685]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Not detected
Package: exe
Operating System Windows 8.1

Universal ADB driver shows detected device and can successfully reboot bootloader.
This is a new Nexus 7 with new USB cable.
UBPorts Installer sits at Waiting for Device...

Note: Please connect your device with a USB cable (not an)

What other debugging can be done? Is there a log file?

**Comment by genifycom** [comment]
Also tried the installer via osboxes.org in a VirtualBox. Same result. ADB talking to the device, but the installer hangs waiting for device.

What other steps are available to debug this?

**Comment by genifycom** [comment]
Why am I getting 404s here?

sudo add-apt-repository ppa:phablet-team/tools
 
 More info: https://launchpad.net/~phablet-team/+archive/ubuntu/tools
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://repo.linuxliteos.com/linuxlite diamond InRelease
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease                   
Hit:3 http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu bionic InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic InRelease                   
Get:5 http://us.archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:6 http://ppa.launchpad.net/phablet-team/tools/ubuntu bionic InRelease    
Hit:7 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease           
Get:8 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:9 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease    
Ign:10 http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu bionic InRelease  
Err:11 http://ppa.launchpad.net/phablet-team/tools/ubuntu bionic Release     
  404  Not Found [IP: 91.189.95.83 80]
Err:12 http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/phablet-team/tools/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by genifycom** [comment]
Also 404 on these:

Err:11 http://ppa.launchpad.net/phablet-team/tools/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Err:12 http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]

**Comment by genifycom** [comment]
No package:

sudo apt-get install ubuntu-device-flash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ubuntu-device-flash

**Comment by genifycom** [comment]
I am trying with:

Distributor ID:	Ubuntu
Description:	Linux Lite 4.2
Release:	18.04
Codename:	bionic

**Comment by NeoTheThird** [comment]
Why are you installing ubuntu-device-flash?

**Comment by genifycom** [comment]
It stems from the inability of the ubports installer to detect the Nexus 7 - flo device no matter if I use Windows or Linux in a Virtual Box. So I was looking for an alternative.

https://www.techadvisor.co.uk/how-to/linux/how-install-ubuntu-touch-image-3531970/
https://wiki.ubuntu.com/Touch/Install
https://www.addictivetips.com/ubuntu-linux-tips/install-ubuntu-touch-on-your-android-device/
https://itsfoss.com/install-ubuntu-touch-nexus-7-2013/

There are many pages using ubuntu-device-flash so if you are new to this particular area, this looks like a viable solution.

**Comment by NeoTheThird** [comment]
Ubuntu-device-flash is an old canonical unmaintained canonical utility, i'm not sure how well it works nowadays. One thing you might want to try is using the [manual install instructions](https://devices.ubuntu-touch.io/device/flo). They are not 100% tested for windows yet, but it might work.

**Comment by genifycom** [comment]
Thanks for that. Windows would not work, SSL certificate problem. But under Ubuntu in a VirtualBox I was able to download all.

**Comment by NeoTheThird** [comment]
Uhhh, SSL certificate problem? When/where/how? Are we talking manual instructions or the installer?
