### ISSUE TITLE
Fastboot: Unknown error:  < waiting for any device >downloading 'boot.img'...OKAY [  0.395s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.396s

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#686]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/nh8s6VXwv8/

**Comment by NeoTheThird** [comment]
Duplicate of #184. Try again with UBports Installer 0.1.12-beta.
