### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined (MainRenderer:349)

### ISSUE THREAD

**Issue by mesofranico** [ubports/ubports-installer#688]
*Automatically generated error report* 
UBports Installer Version: 0.1.20-beta 
Device: Not detected
Package: snap
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/WvXbfHh4nX/

**Comment by NeoTheThird** [comment]
Can you run `snap refresh` and try again?
