### ISSUE TITLE
Ubport-installer cannot install ubuntu touch on FP2

### ISSUE THREAD

**Issue by epe-1** [ubports/ubports-installer#689]
Good Morning,  

I am trying to install ubuntu touch on my new Fairphone 2.

I have followed different forums and made a lot of tests:
- on ubuntu18.04 with ubports-installer 0.1.21 &  0.1.20   with also command line and trying to put tempo on adb...
- on ubuntu16.04 with ubports-installer 0.1.19 0.1.9
- on windows 10 (shame on me) with ubports-installer 0.1.9 ...
- on ubuntu 16.04 32 bits with ubports-installer 0.1.21 and 0.1.9 with source code compilation
    With 0.1.21 => time out to download image
    With 0.1.9 I went farer :
        - The console showed the text :
            debug: Running platform tool exec cmd adb -P 5038 shell echo 1
            debug:  message=Command failed: adb -P 5038 shell echo 1
            error: device unauthorized.
            This adbd's $ADB_VENDOR_KEYS is not set; try 'adb kill-server' if that seems wrong.
        - The Tel is blocked with the attached image : 
![p_20190303_090641](https://user-images.githubusercontent.com/23014376/53996179-c1169480-4137-11e9-8f77-68073d953401.jpg)

what can I do ? 

Thanks a lot

Regards 

Eric Perottet

**Comment by Ingo-FP-Angel** [comment]
I guess the best way to get installation assistance is via [@Telegram](https://t.me/ubports).

`error: device unauthorized.` looks like you need to boot the previous OS again, enable the developer options and then USB debugging on the phone. Then connect the phone via USB to the PC which should let a dialog appear on the phone where you grant access to the PC. If you try with different PCs/VMs you have to do it with all of those.

After you have done that you should be ready to proceed with the installation beyond the point shown above.

**Comment by NeoTheThird** [comment]
On Ubuntu, you might try running `echo 0x2ae5 >> ~/.android/adb_usb.ini` and then starting the installer again.

**Comment by epe-1** [comment]
thanks a lot 
It worked :  I had already  set up USB debugging. I have done it again and it worked .
Thanks a lot for your support.
Regards 
Eric P

**Comment by epe-1** [comment]
The installation on my FAIRPHONE 2 went OK on ubuntu 16.04 32 bits with ubports-installer 0.1.9 with source code compilation + I set up again  USB debugging.
Thanks
Eric P

**Comment by NeoTheThird** [comment]
Great! Thanks for reporting back
