### ISSUE TITLE
Fastboot: Unknown error:  [sudo] password for joerg: error: cannot load '/home/joerg/snap/ubports-installer/6/.cache/ubports/images/FP2/recovery.img': Permission denied

### ISSUE THREAD

**Issue by jofl** [ubports/ubports-installer#70]
Automatically generated error report 
Version: 0.1.5-beta 
Host OS: linux 
Host Dist: Linux Mint undefined
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/26304781/

**Comment by NeoTheThird** [comment]
Should be fixed in the upcoming version, thanks for reporting. :)
