### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by LarrydeHobit** [ubports/ubports-installer#702]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Fairphone 2
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/qZDRPgBpNV/ 

This is an other issue.. i cant install it..

**Comment by NeoTheThird** [comment]
That looks like an issue with the usb cable. Can you try it again, maybe with a different cable?
