### ISSUE TITLE
Uncaught Error: [10380:10380:0316/151420.509287:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.[10333:10361:0316/151420.559257:ERROR:browser_process_sub_thread.cc(209)] Waited 11 ms for network service (MainRenderer:39)

### ISSUE THREAD

**Issue by ceesiebo** [ubports/ubports-installer#714]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: BQ M10 FHD
Package: unknown
Operating System: Fedora  29  Twenty Nine x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/J8rRWTMZzb/

**Comment by NeoTheThird** [comment]
Is that the rpm package?

**Comment by ceesiebo** [comment]
Yes. I managed to install via u Ubuntu installer. Had to install frieza first.
