### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by tolas9** [ubports/ubports-installer#715]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Q5ZdHwk3hp/

**Comment by NeoTheThird** [comment]
I'm going to need some information ;)

**Comment by NeoTheThird** [comment]
You probably mean that the device is not recognized? Try running `snap connect ubports-installer:adb-support`. That should fix it.
