### ISSUE TITLE
Adb push error: 

### ISSUE THREAD

**Issue by josemfuentes** [ubports/ubports-installer#720]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Nexus 5
Package: unknown
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/tSnq9NrZZN/

**Comment by NeoTheThird** [comment]
Please try with a different usb cable, the installer lost the connection to the device
