### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.699s]booting...FAILED (remote: unknown command)finished. total time: 0.701s

### ISSUE THREAD

**Issue by igorkri** [ubports/ubports-installer#721]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: Meizu MX4
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/zQr4t3CJZs/

**Comment by NeoTheThird** [comment]
What operating system is the device running?

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
