### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytesSending 'recovery' (11390 KB)...OKAY [  0.331s]Writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)Finished. Total time: 0.348s

### ISSUE THREAD

**Issue by pouralijan** [ubports/ubports-installer#723]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: GLX [Iran custom phone]
Package: unknown
Operating System: Ubuntu Linux undefined undefined x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/bWdCYXMjyc/

**Comment by NeoTheThird** [comment]
That device is not supported. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of supported devices.
