### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.360s]booting...FAILED (remote: bootimage: incomplete or not signed)finished. total time: 0.361s

### ISSUE THREAD

**Issue by leoplett** [ubports/ubports-installer#727]
*Automatically generated

Device: FP2
OS: Windows
Version: 0.1.21-beta

**Comment by NeoTheThird** [comment]
Thanks for reporting. This is a known issue in #184. Maybe you could try installing again with the current prerelease? You can download it [here](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta). Please let me know if it works :) Thanks

**Comment by leoplett** [comment]
Hello! No problem! I managed to do it wiht an earlier version of the Linux Ubports-Installer that i ran in a Virtual Box Ubuntu OS.

**Comment by NeoTheThird** [comment]
Ok, great. Hope you'll enjoy Ubuntu Touch :)
