### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11450 KB)...OKAY [  0.377s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.380s

### ISSUE THREAD

**Issue by dlalleme** [ubports/ubports-installer#73]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0

**Comment by NeoTheThird** [comment]
Should be fixed in the upcoming version, thanks for reporting. :)
