### ISSUE TITLE
The Installation stop

### ISSUE THREAD

**Issue by khillsman3** [ubports/ubports-installer#731]
*Automatically generated error report* 
UBports Installer Version: 0.1.21-beta 
Device: OnePlus One (Manual device HUAWEI T1.7)
Package: source
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Yyt9P6sh9c/

**Comment by NeoTheThird** [comment]
So, your device is the Huawei T 1.7, which is [not supported](https://devices.ubuntu-touch.io). Why did you select the Oneplus One?
