### ISSUE TITLE
No detection after enabling Developer mode

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubports-installer#736]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: Not detected (E5)
Channel: Not yet set
Package: AppImage
Operating System: Ubuntu Linux  16.04  xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/QgVwXPdtVj/ 

Steps: 
1) Start AppImage
2) Connect device
3) Open terminal `adb devices` was not running:
```
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
```
4) Enabled developer mode
5) Appimage doesn't detect device but adb does:
```
List of devices attached
UA002890	device
```
6) Unplug and plug device. AppImage doesn't detect device
7) Close and open the app, device detected

**Comment by NeoTheThird** [comment]
Well, if you open another adb daemon and the device connects with that, it can't connect with the installer. There are some things that can lead to the installer not detecting the device immediately, there's no way around that. A couple things you can do: Reconnect the device, enable and disable developer mode, confirm the authorization prompt on the device. But anyways, this is not a problem. The installer does not need to detect, you can always select manually.
