### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by gousee** [ubports/ubports-installer#740]
*Automatically generated error report* %0D%0AUBports Installer Version: 0.1.21-beta %0D%0ADevice: Nexus 5%0D%0APackage: dmg%0D%0AOperating System: macOS 10.13.617G6029 x64 %0D%0ANodeJS version: v8.2.1 %0D%0A%0D%0AError log: http://paste.ubuntu.com/p/GJZTbnttQY/ %0D%0A

**Comment by NeoTheThird** [comment]
Sorry about that, please try again [with the latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.2.2-beta).
