### ISSUE TITLE
Fastboot: Unknown error:  Sending 'boot.img' (11390 KB)                      OKAY [  0.357s]Booting                                            FAILED (remote: 'dtb not found')fastboot: error: C

### ISSUE THREAD

**Issue by qq515114557** [ubports/ubports-installer#741]

**Comment by NeoTheThird** [comment]
Hi there, what device is this and what operating system and version is it running right now? We sometimes see dtb not found when the bootloader version is unsupported (#699), so you might have to install a specific android version first.
