### ISSUE TITLE
Fastboot: Unknown error:  Password:Sending 'recovery' (13708 KB)                      OKAY [  0.600s]Writing 'recovery'                                 FAILED (remote: 'Security deny - Err:0x2017 ')fastboot: error: Command failed

### ISSUE THREAD

**Issue by gousee** [ubports/ubports-installer#742]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.13.617G6029 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/29xWJMdJNF/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
