### ISSUE TITLE
Fastboot: Unknown error:  Password:Sending 'boot.img' (9578 KB)                       ERROR: usb_read failed with status e00002edFAILED (Status read failed (No such file or directory))fastboot: error: Command failed

### ISSUE THREAD

**Issue by ItsYanko** [ubports/ubports-installer#744]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: krillin
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.13.617G66 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/B83r8x7zkj/

**Comment by NeoTheThird** [comment]
Interesting, what OS is the phone running?

**Comment by PerinaElectronic** [comment]
@NeoTheThird 
I am actually updating from Ubuntu 15.04 to 16.04 on my BQ Aquaris E4.5 (2014)
I did a Factory Restore (Wipe) to it but i still get that error.

When i open UBPorts on my iMac it automatically detects the Device Model. Sometimes i get that error and sometimes it just does nothing: no download, any progress shown.

Thanks
Yanko

_(Really sorry for the bad english :/)_

**Comment by NeoTheThird** [comment]
Should be resolved.
