### ISSUE TITLE
MX4: Autodetect failing to show channel selection

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubports-installer#746]
ubports-installer only shows a white screen after the Meizu MX4 has been detected.
![Bildschirmfoto von 2019-04-02 15-09-25](https://user-images.githubusercontent.com/722660/55405273-fd33ee00-5559-11e9-9f83-da0a2c0cfd4b.png)

*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: Not yet set
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/pY6Bfr2Tz4/

**Comment by NeoTheThird** [comment]
Oh what fresh hell is this. What happens if you close the installer and start over?

**Comment by fredldotme** [comment]
Happens reproducibly.
I managed to flash to stable by being quicker than device detection and selecting manual device selection instead.

**Comment by NeoTheThird** [comment]
Very weird. Thanks for reporting, i have yet to find a way to reproduce this...

**Comment by fredldotme** [comment]
Having tried it again, it works now. Channel selection and wipe option show up properly.
Only difference is that I'm already on UBPorts on the phone.
I guess this can be closed now.

**Comment by NeoTheThird** [comment]
Now tracked in #806
