### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by Achavezgit18** [ubports/ubports-installer#748]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: Not detected
Channel: Not yet set
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/kxH2d7WK84/

**Comment by NeoTheThird** [comment]
This is now done automatically starting today, but if you downloaded the installer before, try running `snap connect ubports-installer:adb-support` and restart the installer.
