### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (9578 KB)...OKAY [  0.387s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.390s

### ISSUE THREAD

**Issue by ascmartins** [ubports/ubports-installer#749]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: krillin
Channel: ubports-touch/15.04/stable
Package: snap
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/kHyGZkjbkn/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).

**Comment by ascmartins** [comment]
I realize that now. Thanks. Following those instructions.
