### ISSUE TITLE
Mac fastboot error "Couldn't create a device interface iterator"

### ISSUE THREAD

**Issue by mohses** [ubports/ubports-installer#750]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: FP2
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.418E226 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/s2FBqm4BZj/

**Comment by NeoTheThird** [comment]
Thanks for reporting. I have not seen this before, what operating system is the device running now?

**Comment by mohses** [comment]
Mac OS Mojave Version 10.14.4    Mac Book Air ( Retina, 13-inch,2018 )

 


Thank you for your help

Thomas

 


Gesendet: Dienstag, 09. April 2019 um 14:53 Uhr
Von: "Jan Sprinz" <notifications@github.com>
An: ubports/ubports-installer <ubports-installer@noreply.github.com>
Cc: mohses <strehse@web.de>, Author <author@noreply.github.com>
Betreff: Re: [ubports/ubports-installer] FP2 fastboot error "Couldn't create a device interface iterator" (#750)


Thanks for reporting. I have not seen this before, what operating system is the device running now?

**Comment by haribalajip** [comment]
I am getting this error too.

**Comment by fabiobfava** [comment]
Hey folks, it has worked for me this afternoon, succeded to run Android 9 on my old Moto G3 2015 but then I've made some error trying to restore the original Motorola Stock Software, then now my Mac can't recognize the phone. I assume that is the

**Comment by philburk** [comment]
https://android.stackexchange.com/questions/209725/fastboot-devices-command-doesnt-work-after-macos-high-sierra-10-14-4-upgrade
