### ISSUE TITLE
OEM unlock option missing

### ISSUE THREAD

**Issue by pmiko** [ubports/ubports-installer#752]
Dear all, I have been trying to install Ubuntu on m Fairphone 2 according to the procedure suggested in the ubports-installer. I was able to shift into the developer mode and enable USB debugging, however, no OEM unlock option is available. The installation continues until rebooting to bootloader, however, the reboot to the recovery mode does not proceed, as the phone starts to rebooting and starting Android again. Does anyone have an idea for any solution?
Thanks a lot.

Android ver. 7.1.2

**Comment by musoke** [comment]
I had the same problem with a Nexus 5.  Installed fastboot from the debian repos and ran `fastboot oem unlock`, but couldn't go further.
