### ISSUE TITLE
Phone in a booting loop google logo

### ISSUE THREAD

**Issue by aodanosullivan** [ubports/ubports-installer#753]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 18.10 cosmic x64 
NodeJS version: v8.2.1 
adding as any reference to older bugs suggest it should be fixed

Error log: http://paste.ubuntu.com/p/Hv72qJSWqs/

**Comment by dasscheman** [comment]
I have the same problem with a nexus 4:

*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: mako
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux  18.10  cosmic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/snRYTspjwT/

**Comment by vimpsoft** [comment]
Same here. Nexus 5. Tried different installers on windows 10 and ubuntu.
