### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by denislavstoyanov** [ubports/ubports-installer#754]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: Not detected
Channel: Not yet set
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/3HgJcd3zks/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
