### ISSUE TITLE
Adb push error: Error: Command failed: adb -P 5038 push /home/gl/.cache/ubports/pool/device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz /cache/recovery/failed to copy '/home/gl/.cache/ubports/pool/device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz' to '/cache/recovery//device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz': No space left on device, stdout: , stderr: failed to copy '/home/gl/.cache/ubports/pool/device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz' to '/cache/recovery//device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz': No space left on device

### ISSUE THREAD

**Issue by liangg214** [ubports/ubports-installer#759]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: turbo
Channel: ubports-touch/15.04/stable
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/ZHmcG8STRQ/

**Comment by Tarick** [comment]
I have the same problem

*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: turbo
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/DDgS739pvs/ 

Previously I had TWRP as recovery if that can give any hints.

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
