### ISSUE TITLE
instal it on linux x86

### ISSUE THREAD

**Issue by 6594k** [ubports/ubports-installer#76]
It is possible to install it on linux x86 ?

**Comment by NeoTheThird** [comment]
This installer is only for android/halium-based devices. We do not have a version of Ubuntu Touch for classic x86 devices, but what you can do is [install unity 8 on Ubuntu 16.04](https://github.com/ubports/unity8-desktop-install-tools), the desktop environment used in Ubuntu Touch. Keep in mind that it's just a development preview for the moment, and the openstore does not feature x86 packages. But you will be able to use and install deb packages.
