### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11436 KB)...OKAY [  0.452s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.455s

### ISSUE THREAD

**Issue by jobura** [ubports/ubports-installer#767]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: cooler
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/M8rSdShRbZ/

**Comment by jobura** [comment]
What to do now? M10 is in reboot-mode, go on with ignore? I tried, for more then one hour no reaction .....

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).

**Comment by jobura** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hi Jan, lot of thanks for your Mail. I try that in the next days.Best wishes                                                                                                                                                                         Beste Grüße Jochen Budke                                                                                                                                                                            Von: notifications@github.comGesendet: 24. April 2019 15:50An: ubports-installer@noreply.github.comAntworten: reply@reply.github.comCc: the-ottis@mailbox.org; state_change@noreply.github.comBetreff: Re: [ubports/ubports-installer] Fastboot: Unknown error:  target reported max download size of 134217728 bytessending 'recovery' (11436 KB)...OKAY [  0.452s]writing 'recovery'...FAILED (remote: download for partition 'recovery' is not allowed)finished. total time: 0.455s (#767)  Sorry about that, this device needs to be manually unlocked by installing Canonical Ubuntu Touch.
