### ISSUE TITLE
Command failed: echo "" | sudo -S echo correct[sudo] senha para reinaldo: Desculpe, tente novamente.[sudo] senha para reinaldo: sudo: 1 tentativa de senha incorreta

### ISSUE THREAD

**Issue by rcabanita** [ubports/ubports-installer#77]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/26503083/

**Comment by NeoTheThird** [comment]
Should be fixed in the upcoming version, thanks for reporting. :)
