### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by mohses** [ubports/ubports-installer#771]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: FP2
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.345] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/b7M7K7HFbB/

**Comment by advocatux** [comment]
Hi, are you still having any issue with the installer?
