### ISSUE TITLE
Unable to install  on Meizu Pro 5

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubports-installer#776]
After pushing all devices and reboot recovery to flash, device display error message in recovery.

need to use: sudo ubuntu-device-flash --server=http://system-image.ubports.com touch --device=turbo --channel=ubports-touch/16.04/devel --wipe

**Comment by NeoTheThird** [comment]
i don't understand, what is the issue?

**Comment by rubencarneiro** [comment]
It wont install using the ubports installer.
