### ISSUE TITLE
Adb push error: Error: Command failed: /var/folders/v1/0lmv3s796_ldscccs82d0_lh0000gn/T/.com.ubports.installer.5GfT4s -P 5038 push /Users/duyang/Library/Caches/ubports/pool/device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz /cache/recovery/, stdout: [...]263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz': remote No space left on device/Users/duyang/Library/Caches/ubports/pool/device-60f53a5768e9340729d3a5ef9263bd3a9726792e7d0dbf830e5b124938dd419a.tar.xz: 0 files pushed. 4.3 MB/s (112446048 bytes in 24.665s), stderr: 

### ISSUE THREAD

**Issue by ydu111** [ubports/ubports-installer#777]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: turbo
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.11.615G22010 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/bdt3nBWnPb/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
