### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.429s]booting...FAILED (remote: dtb not found)finished. total time: 0.442s

### ISSUE THREAD

**Issue by josearuano** [ubports/ubports-installer#778]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: vegetahd
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/k2FwxbmqYH/

**Comment by josearuano** [comment]
The mobile phone is an BQ Aquarius M5. It is possible the support for more phones?

Thanks

**Comment by advocatux** [comment]
Hi, that isn't a supported device as you can see on https://devices.ubuntu-touch.io/

You can try to port it though. Please see https://docs.ubports.com/en/latest/porting/introduction.html

(You can close this issue now :wink:)

**Comment by josearuano** [comment]
Thanks
