### ISSUE TITLE
Unable to install on Oneplus one

### ISSUE THREAD

**Issue by sajid-dev** [ubports/ubports-installer#779]
Trying to install using ubports-installer.0.2.2-beta.exe it is detecting the device in fastboot mode and when the device restart it stuck with message waiting for the device to start in recovery mode but the device is already in recovery mode with ubuntu recovery mode.

**Comment by giiba** [comment]
Unplug the the phone and plug it back in. The installer/drivers/abd/? don't always recognize the device when it switches from fastboot to recovery. I find the reconnection aligns some stars and things continue.

I've flashed my 1+1 and need to do this sometimes.

**Comment by advocatux** [comment]
@sajid-dev did that @giiba's tip work? If you still have any issue, please join our official UB Welcome & Install group in Telegram (https://t.me/WelcomePlus).
