### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.457s]booting...FAILED (remote: dtb not found)finished. total time: 0.485s

### ISSUE THREAD

**Issue by javierology** [ubports/ubports-installer#780]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/CYTKy7WjG3/

**Comment by NeoTheThird** [comment]
Sorry about that. Duplicate of #699.
