### ISSUE TITLE
I am not going to stop until UBUNTU TOUCH is running in my Nexus 5

### ISSUE THREAD

**Issue by javierology** [ubports/ubports-installer#781]
Hi,

I tried both, the installer and the manual installation.

I keep getting the same message
- - - - - - - - - - - - - - 
Fastboot: Unknown error:  downloading 'boot.img'...
OKAY [  0.457s]
booting...
FAILED (remote: dtb not found)
finished. total time: 0.485s
- - - - - - - - - - - - - - 

My phone is bricked. The screen only shows this:
"Your device software can't be checked for corruption. Please block the bootloader. Visit this link on another device: g.co/ABH PRESS POWER TO PAUSE THE BOOT"

I already wait about 16 hours, and the message on the phone screen  is the still same.

My phone is a Nexus 5X.

Probably, I am not giving enough information about my hardware and software, but I have not idea, what else I can write in this message, in order for someone to help.

Please, let me know what other information is need it to diagnostic the problem, and I gladly send it.

Any idea, very much appreciated.

Thanks,
Javierology

*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/h8PhQT8kjT/

**Comment by advocatux** [comment]
Hi, as I informed you about the current porting state for Nexus 5x in the Welcome & Install group (in short, it isn't a supported device for now), I think you can close this issue :)
