### ISSUE TITLE
Installer page says troubleshooting has been moved to Docs but that isn't true

### ISSUE THREAD

**Issue by advocatux** [ubports/ubports-installer#785]
As https://github.com/ubports/ubports-installer/#troubleshooting states, supposedly https://github.com/ubports/ubports-installer/commit/f1b6fbd95ae18a3e980d6c8f27cc697c27195d65 moved the troubleshooting section to our Documentation but it isn't there (https://docs.ubports.com/en/latest/userguide/install.html)

**Comment by NeoTheThird** [comment]
Gnarf, that pr wasn't merged. Back in a jiffy.
