### ISSUE TITLE
Native tool called even though fallback tools are needed

### ISSUE THREAD

**Issue by evilvoice** [ubports/ubports-installer#786]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.706] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/rRfdZbm2kj/

**Comment by NeoTheThird** [comment]
The parts responsible for this need soooo much simplification, absolutely impossible to debug!

**Comment by NeoTheThird** [comment]
Duplicate of #762.
