### ISSUE TITLE
Fastboot: Unknown error:  Sending 'recovery' (11828 KB)                      OKAY [  0.590s]Writing 'recovery'                                 OKAY [  0.960s]Finished. Total time: 1.752s'fastboot' is not recognized as an internal or external command,operable program or batch file.

### ISSUE THREAD

**Issue by SadisticCornflakes** [ubports/ubports-installer#789]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.765] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/N4mVJwjz2J/ 

Tried editing the system environment variables but no matter what I do, it still comes back with this error. 

The Nexus 5 is able to reboot to the bootloader but wont get any further than that and this error message.

**Comment by NeoTheThird** [comment]
What happens when you run without custom tools?

**Comment by SadisticCornflakes** [comment]
Without the custom tools, it'll go to the screen saying the device needs to be in bootloader. I'll go to reboot to bootloader and it will just sit there on the bootloader screen on the Nexus and the installer won't change. 

Doing it with custom tools was the only way I could get past that non-responsiveness

**Comment by SadisticCornflakes** [comment]
So I got it working, I was going through the alternate steps for installation and tried downloading the 15 second ADB installer for the manual install process. After I did that I tried installing it again thinking "maybe I'm missing some files somewhere" booted up the installer and it recognized the phone automatically and I was able to get UT installed with no problems. Closing this out.
