### ISSUE TITLE
Uncaught Error: ENOSPC: no space left on device, write (MainRenderer:59)

### ISSUE THREAD

**Issue by roimr** [ubports/ubports-installer#793]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: krillin
Channel: ubports-touch/15.04/stable
Package: deb
Operating System: Ubuntu Linux  16.04  xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/d2KP4xghpf/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
