### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 534773760 bytessending 'recovery' (11390 KB)...OKAY [  0.512s]writing 'recovery'...(bootloader) Invalid partition name recoveryFAILED (remote failure)finished. total time: 0.513s

### ISSUE THREAD

**Issue by jurimava** [ubports/ubports-installer#799]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: bacon
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux     18.04     bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/dj3WPrBqsK/

**Comment by NeoTheThird** [comment]
You selected your device manually. Are you sure you have a **Oneplus One (bacon)**?
