### ISSUE TITLE
The install went through the installation on my Nexus 5 and even said successful, but my phone just boots to a black screen that says "Google" and doesn't go anywhere from there. I can boot into UBports recovery, but i can't seem to get ubuntu touch to boot

### ISSUE THREAD

**Issue by floki2019** [ubports/ubports-installer#802]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.13.417E199 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/6mP6Brjq7X/

**Comment by vimpsoft** [comment]
Same here. Tried different installers on different systems. It just infinitely rebooting itself with Google logo after successful installation.
