### ISSUE TITLE
Fastboot not called at all on macOS

### ISSUE THREAD

**Issue by dammaddammad** [ubports/ubports-installer#803]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: frieza
Channel: Not yet set
Package: dmg
Operating System: macOS 10.11.615G22010 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/sWkQDhpmvt/

**Comment by dammaddammad** [comment]
in bootloader mode nothing happens, on tablet just black screen that says fastboot mode, installer just sits asking for unit to br rebooted to bootloader
![Screen Shot 7](https://user-images.githubusercontent.com/51175169/58750521-792fb100-848b-11e9-97d6-59dcbc931b6c.png)
![Screen Shot 12](https://user-images.githubusercontent.com/51175169/58750524-83ea4600-848b-11e9-83a8-369b76357d40.png)

**Comment by dammaddammad** [comment]
I tried again but the same issue

**Comment by dammaddammad** [comment]
I don't see the point of making an effort with this rubbish as no one else is!

**Comment by NeoTheThird** [comment]
Hey there, sorry about the late reply. Thank you for reporting that issue. The log looks very curious, because no fastboot errors are logged. Maybe fastboot is not called at all? Needs investigation!
