### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, chmod '/tmp/tmp-16029gZS98pn1AMNm/adb' (MainRenderer:248)

### ISSUE THREAD

**Issue by alwayslivid** [ubports/ubports-installer#804]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: Not detected
Channel: Not yet set
Package: dir
Operating System: Arch Linux undefined undefined x64 
NodeJS version: v10.11.0 

Error log: http://paste.ubuntu.com/p/9gMJRJdjJt/

**Comment by NeoTheThird** [comment]
You're running from source, right? You'll have to either install adb and fastboot or build the project once.
