### ISSUE TITLE
Race condition on start of install event

### ISSUE THREAD

**Issue by spemberton** [ubports/ubports-installer#806]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: frieza
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/fNpdDrzV3f/

**Comment by spemberton** [comment]
![ubports-installer](https://user-images.githubusercontent.com/10128303/58631775-e6084700-82e3-11e9-86ea-3ca33385b2f9.png)

**Comment by NeoTheThird** [comment]
Looks like a race condition, please try starting the installer again

**Comment by MaartenFokkinga** [comment]
Re-installing and re-starting does not help. I have the same problem (#845)

**Comment by emale999** [comment]
Have this problem, too.

Tried manual install method which works a little bit more.
Mobile phone enters fastboot mode and its display says that the recovery was installed. But after that nothing more happens. And the UBPorts Installer application says "flashing recovery and system" for hours...
