### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (13708 KB)...OKAY [  0.708s]writing 'recovery'...FAILED (remote: Security deny - Err:0x2017 )finished. total time: 0.772s

### ISSUE THREAD

**Issue by kelvincheung** [ubports/ubports-installer#809]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/v5mVRsh9Fy/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
