### ISSUE TITLE
Uncaught Error: [0207/131828.755515:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process. (MainRenderer:39)

### ISSUE THREAD

**Issue by negations** [ubports/ubports-installer#81]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v7.9.0

**Comment by NeoTheThird** [comment]
Should be fixed in the upcoming version, thanks for reporting. :)
