### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.696s]booting...FAILED (remote: unknown command)finished. total time: 0.709s

### ISSUE THREAD

**Issue by kelvincheung** [ubports/ubports-installer#810]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/PW5fypMkdY/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).

**Comment by kelvincheung** [comment]
> Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).

Yes, I have tried [SP flash tool](https://storage.googleapis.com/otas/2015/Tablets/Freezer%20FHD/Ubuntu/SP_Flash_Tool_exe_Linux_v5.1612.00.100.zip) and followed the steps described in [Install on legacy Android devices](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
Unfortunately, SP flash tool doesn't work for me.
The error message is as follows.
```
Connecting to BROM...
Scanning USB port...
Search usb, timeout set as 3600000 ms
change@/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0

add@/devices/pci0000:00/0000:00:14.0/usb1/1-4

add@/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0

add@/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/tty/ttyACM0

vid is 0e8d

device vid = 0e8d

pid is 0003

device pid = 0003

com portName is: /dev/ttyACM0

Total wait time = -1559536058.000000
USB port is obtained. path name(/dev/ttyACM0), port name(/dev/ttyACM0)
USB port detected: /dev/ttyACM0
BROM connected
Downloading & Connecting to DA...
COM port is open. Trying to sync with the target...
Failed to Connect DA: S_BROM_DOWNLOAD_DA_FAIL
Disconnect!
```
What should I do now?
BTW, my phone is Meizu MX4 running Flyme(v4.2.8.2a).
Thanks very much!
