### ISSUE TITLE
Uncaught Error: IPDL protocol Error: Received an invalid file descriptorIPDL protocol Error: Received an invalid file descriptorIPDL protocol Error: Received an invalid file descriptor[Parent 12292, Gecko_IOThread] WARNING: pipe error (62): Prisijungimas nutrauktas kito serverio: file /build/firefox-MhlWie/firefox-67.0 build2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357 (MainRenderer:39)

### ISSUE THREAD

**Issue by zikaras** [ubports/ubports-installer#812]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 19.04
Host Arch: x64 
Node: v8.2.1 

Error log: http://paste.ubuntu.com/p/Nhb8mBsCQD/

**Comment by NeoTheThird** [comment]
Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).
