### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (10044 KB)...FAILED (command write failed (Bad file descriptor))finished. total time: 0.000s

### ISSUE THREAD

**Issue by rayinalabama** [ubports/ubports-installer#814]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: flo
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/hTK4g9MPTB/

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed now. Please try again.
