### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by mehaks71** [ubports/ubports-installer#817]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17763.529] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/jFRXdJRBrH/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
