### ISSUE TITLE
Fastboot: Unknown error:  sending 'recovery' (13708 KB)...OKAY [  0.635s]writing 'recovery'...FAILED (remote: Security deny - Err:0x2017 )finished. total time: 0.704s

### ISSUE THREAD

**Issue by mehaks71** [ubports/ubports-installer#818]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17763.529] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/rRFTV7yFN4/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
