### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by bricolheure** [ubports/ubports-installer#819]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: krillin
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux   19.04   disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/wQPnfpnjGw/

**Comment by NeoTheThird** [comment]
Looks like the installer can't see your device. Are you sure it's connected properly and in fastboot mode? Try running `sudo fastboot devices` in the terminal and see if a device is detected, if the installer gets stuck in the same place again.
