### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by bricolheure** [ubports/ubports-installer#820]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: krillin
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/gnvHxrPwnh/

**Comment by NeoTheThird** [comment]
Looks like you didn't enter your password...
