### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/Users/climax/Library/Caches/ubports/commandfile/ubuntu_commanddeb7736' (MainRenderer:652)

### ISSUE THREAD

**Issue by chrisvanzet** [ubports/ubports-installer#821]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: deb
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.518F132 x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/mvy7MD5Yc7/

**Comment by bumper314** [comment]
Same issue here, but on macOS 10.9.

Clicking the "Ignore" button moved to the next screen (Downloading) but it never finishes downloading the first file, just keeps animating forever.

Also, since I chose the "Wipe" option, my phone doesn't boot anymore, I just get the Google logo forever.

**Comment by NeoTheThird** [comment]
Hmm, did you maybe start the installer as root (i.e. with sudo) before? You can try removing the folder (`sudo rm -rf /Users/climax/Library/Caches/ubports`), that should give you a clean slate for another run.

Ignoring this issue will not work. Without the commandfile, the ubports recovery has no idea what to do with the files you pushed.

@bumper314 Sorry about the late reply. You should be able to restore your device by flashing an OS with fastboot, or simply using the UBports Installer again.
