### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by DeltonSouza** [ubports/ubports-installer#822]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: Not detected
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/5x5zdNkhjF/

**Comment by NeoTheThird** [comment]
Please put your device in developer mode (as the installer tells you) or select the device manually.
