### ISSUE TITLE
Installer hangs after identifying tablet

### ISSUE THREAD

**Issue by pb731** [ubports/ubports-installer#823]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: frieza
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/mDBjtyP5dT/ 

"Are you ready...." Yes, but no way to proceed.

**Comment by NeoTheThird** [comment]
Duplicate of #806.
