### ISSUE TITLE
Fastboot: Unknown error:  downloading 'boot.img'...OKAY [  0.643s]booting...FAILED (remote: unknown command)finished. total time: 0.658s

### ISSUE THREAD

**Issue by Veledo** [ubports/ubports-installer#825]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: arale
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [�汾 10.0.17134.765] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/gnHDHPThVD/

**Comment by NeoTheThird** [comment]
Sorry about that, this device needs to be [manually unlocked by installing Canonical Ubuntu Touch](https://docs.ubports.com/en/latest/userguide/install.html#install-on-legacy-android-devices).
