### ISSUE TITLE
Auto/Manual detection failure

### ISSUE THREAD

**Issue by ShadyHegazy** [ubports/ubports-installer#827]
Using the 0.2.2 beta version on Win10, I can't proceed with installation on OnePlus One because detection isn't working at all even after rebooting to bootloader.
Fastboot detects it.

**Comment by NeoTheThird** [comment]
Do you have drivers installed? Does fastboot recognize the device outside the installer?

**Comment by SaulNunez** [comment]
Using 0.2.5 I have the same problem on my Nexus 7. 

![imagen](https://user-images.githubusercontent.com/13012976/64069155-41a6e100-cc01-11e9-9cf9-d0352fb29bba.png)
It's detected with fastboot from Android Studio, but no luck with on the Installer.

And this is my fastboot driver.

![imagen](https://user-images.githubusercontent.com/13012976/64069246-f1308300-cc02-11e9-97ae-c37566eaf108.png)

**Comment by NeoTheThird** [comment]
Sorry about that, should be fixed in our [next release](https://github.com/ubports/ubports-installer/releases/tag/0.4.1-beta).
