### ISSUE TITLE
installing ubuntu toch for Android 6.0 One plus one

### ISSUE THREAD

**Issue by Andrey16android** [ubports/ubports-installer#829]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: Not detected
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/B6TxtwnNF8/

**Comment by Andrey16android** [comment]
Ждемс установки Ubuntu Toch на смартфон One plus one

**Comment by NeoTheThird** [comment]
Sorry about that. Duplicate of #700.
