### ISSUE TITLE
Command failed: echo '***' | sudo -S echo correct[sudo] пароль для android16: Попробуйте ещё раз.[sudo] пароль для android16: sudo: 1 попытка ввода неправильного пароля

### ISSUE THREAD

**Issue by Andrey16android** [ubports/ubports-installer#831]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: bacon
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/Nn2fmWjpDS/

**Comment by NeoTheThird** [comment]
Sorry about that. Duplicate of #425.
