### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizesending 'recovery' (13708 KB)...OKAY [  0.736s]writing 'recovery'...FAILED (remote: partition 'recovery' not support flash)finished. total time: 0.791s

### ISSUE THREAD

**Issue by epierre3** [ubports/ubports-installer#84]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v7.9.0

**Comment by NeoTheThird** [comment]
Please try again with the latest version. Please make sure your device is supported and you selected the correct device in the installer.
