### ISSUE TITLE
Format cache from fastboot after bootstrapping

### ISSUE THREAD

**Issue by furstborne1** [ubports/ubports-installer#841]
*Automatically generated error report* 
UBports Installer Version: 0.2.2-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/K3VPjPKpmn/

**Comment by NeoTheThird** [comment]
You selected the device manually. Are you sure you have a **Nexus 5**?
