### ISSUE TITLE
install to unlistet device

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [ubports/ubports-installer#843]
how to install it on Fly Connect 10.1.  May be existing some set to write it via FlashTool?

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
