### ISSUE TITLE
Blank screen on detection of device

### ISSUE THREAD

**Issue by SGCMarketing** [ubports/ubports-installer#844]
![Screenshot 2019-07-14 at 22 48 55](https://user-images.githubusercontent.com/48967837/61189747-97432080-a689-11e9-8bac-0e6fecac0676.png)

**Comment by SGCMarketing** [comment]
The loader just stay stuck in this state. I've tried starting up with the device connected and not - same thing happens.

macOS 10.14.5

**Comment by SGCMarketing** [comment]
Seems to be the same problem ...

https://github.com/ubports/ubports-installer/issues/823

**Comment by NeoTheThird** [comment]
Duplicate of #806.
