### ISSUE TITLE
UBports-installer says "Are you ready ..?" but I cannot confirm

### ISSUE THREAD

**Issue by MaartenFokkinga** [ubports/ubports-installer#845]
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: frieza
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/g4DygxCsmd/

**Comment by MaartenFokkinga** [comment]
UBports-installer (0.2.3-beta on my Ubuntu 16 system) says "Are you ready for Ubuntu Touch on your Bq m10FHD?" and then I cannot confirm: it has an almost empty window and is indefinitely waiting for my answer. (The tablet Bq m10FHD is in developer mode).

**Comment by MaartenFokkinga** [comment]
Seems the same problem as #824

**Comment by MaartenFokkinga** [comment]
The last (= most recent) line in the automatically generated debug file reads:
debug 2019-07-16T12:46:45.092Z getChannelSelects timed out
Maybe, "getChannelSelects" is the cause??

**Comment by NeoTheThird** [comment]
Duplicate of #806.
