### ISSUE TITLE
Spaces in paths aren't escaped properly on windows

### ISSUE THREAD

**Issue by diogocarneiro** [ubports/ubports-installer#847]
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: hammerhead
Channel: ubports-touch/16.04/devel
Package: exe
Operating System: Microsoft Windows [Vers�o 6.1.7601] ia32 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/vg88NKpCcd/

**Comment by NeoTheThird** [comment]
Error thrown is `error: cannot stat 'C:\Users\Diogo': No such file or directoryadb: error: cannot stat 'Carneiro\AppData\Roaming\ubports\pool\ubports-403fdb231a1ae5f201ae7c836c6ca4f38b608cce746b6f72603f10b32aea9c83.tar.xz`

**Comment by NeoTheThird** [comment]
no longer an issue. Pure speculation, but i suspect the nodejs update when we jumped to electron five fixed this for us in the path module.
