### ISSUE TITLE
Adb push error installing to Fairphone 2: 

### ISSUE THREAD

**Issue by leebaylis** [ubports/ubports-installer#85]
see comment -- the initial bug reported here is a duplicate of https://github.com/ubports/ubports-installer/issues/68 but there is another bug relating to LUbuntu

Automatically generated error report %0AVersion: 0.1.9-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v7.9.0 %0A%0A

Error occurs on OSX Sierra, but I also reproduced it on a LUbuntu box. Error also occurs regardless of whether I select Wipe or not, and occurs for 15.04/stable, 15.04/devel, 16.04/devel.

If, after closing the installer, I manually run the adb command it fails at:

adb -P 5038 push "/Users/mpciiljb/Library/Application Support/ubports/pool/ubports-4838b3b40cbd569cac0f5b67ee778a993118696e366587d420830cbe2e2788cc.tar.xz" /cache/recovery/

the command succeeds if I manually add the quote " marks -- although I don't think this is the problem, the LUbuntu box doesn't have a space in the file path but still failed?

Any help appreciated!

**Comment by leebaylis** [comment]
Apologies -- it looks like this *is* a duplicate of https://github.com/ubports/ubports-installer/issues/68 because the workaround described there has enabled my installation to continue. 

In which case, the LUbuntu error must be something else!

The command which failed on LUbuntu was:

adb -P 5037 push '/home/lee/.cache/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/

with an ADB push error. 

There's a pastebin of the LUbuntu push error:

https://paste.ubuntu.com/26543229/

**Comment by NeoTheThird** [comment]
Should be fixed in the latest version that will be published tonight. Thanks for reporting. :)
