### ISSUE TITLE
Fastboot: Unknown error:  target reported max download size of 1073741824 bytessending 'recovery' (11828 KB)...OKAY [  0.595s]writing 'recovery'...FAILED (remote: flash write failure)finished. total time: 0.775s

### ISSUE THREAD

**Issue by BernZxS05** [ubports/ubports-installer#851]
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: snap
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/fm8vbxvzZM/

**Comment by NeoTheThird** [comment]
You selected your device manually. Are you sure you have the **Nexus 5 (hammerhead)**?

**Comment by NeoTheThird** [comment]
That error can sometimes occur when the bootloader is locked. The installer is supposed to unlock it for you, but maybe that did not work. Can you boot your device to bootloader, run `fastboot oem device-info` and send me the output? Thanks!
