### ISSUE TITLE
hangs at "starting adb server" in Arch Linux

### ISSUE THREAD

**Issue by ITwrx** [ubports/ubports-installer#852]
tried 0.2.3-beta in Arch Linux and the installer never gets past the first step of trying to start the adb server. adb works fine in the terminal on this machine. no errors in terminal from the installer. just never proceeds past that step. Installer worked great with different (ubuntu) machine.

thanks

**Comment by NeoTheThird** [comment]
What package was this? AppImage? Snap? Running from Source?

If you could get me a log (`~/.cache/ubports/ubports-installer.log`), that'd be really helpful!

**Comment by NeoTheThird** [comment]
Oh, interesting, i did not know someone published it in AUR. Would you mind taking up this issue with the maintainer there? They either have to add a dependency for fastboot and adb or fix their build script to properly package our fallback tools.

**Comment by NeoTheThird** [comment]
Awesome, thank you!

**Comment by BruceZhang1993** [comment]
@ITwrx 
This package I maintain(bruceutut@AUR) intends to make ubports installer able to run without root.
So before you run this tool, you need to install `android-udev` and reboot first, to make udev rule working.
android-udev package inludes tons of devices and vendors, which will make you able to run adb without root permission.
You can try to stop&disable adb.service and try to run adb devices from terminal, to check if your device is working.

If you still cannot make it work, try AppImage package from here.

**Comment by BruceZhang1993** [comment]
@ITwrx Thanks for the feedback of AUR package. Since pkgbuild script for 0.2.5 beta have changed a lot vs 0.2.3, so I guess this issue may have already been solved.

**Comment by NeoTheThird** [comment]
Thanks to the both of you! Appreciate the support to get the installer to arch users :)
