### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by irfannn2** [ubports/ubports-installer#854]
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: Not detected
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/YxC3YZs5JC/

**Comment by irfannn2** [comment]
I have requested my mobile is redmi note 4 company xiaomi. this ubuntu touch is not available for this device. please this is my request I need this os for my device please do something and tell me what I do

Thankyou you

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
