### ISSUE TITLE
Ubuntu Touch fails to install on Nexus 7 2013 wifi flo

### ISSUE THREAD

**Issue by robert97520** [ubports/ubports-installer#855]
*Automatically generated error report* 
UBports Installer Version: 0.2.3-beta 
Device: flo
Channel: Not yet set
Package: deb
Operating System: Ubuntu Linux   16.04   xenial x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/gHhD27KR4W/ 

Nexus 7 freezes with error message "This device needs restoring from a PC or service center"

**Comment by NeoTheThird** [comment]
Could you try again with the latest version?

**Comment by NeoTheThird** [comment]
Pinging @UniversalSuperBox. Any ideas what's going on here?

**Comment by NeoTheThird** [comment]
duplicate of #615
