### ISSUE TITLE
[hammerhead] Installation fails due to 'supposed' oem lock

### ISSUE THREAD

**Issue by tallero** [ubports/ubports-installer#866]
The ubports installer detects the bootloader as locked, despite it not being it.
If re-locked and then unlocked via installer, the prompt re-appears after a while.
Also I could not find images in download directory.
Where should the 'system' img be?

Apparently it only flashes `boot` and `recovery`.

**Comment by NeoTheThird** [comment]
Can you get me a log?

**Comment by tallero** [comment]
@NeoTheThird Solved, it was not installer's fault, it was caused by this bug:

https://bugs.archlinux.org/task/63370
