### ISSUE TITLE
Network connection drops can error out during system-image step with "could not find latest version"

### ISSUE THREAD

**Issue by Bekkenes** [ubports/ubports-installer#867]
*Automatically generated error report* 
UBports Installer Version: 0.2.6-beta 
Device: flo
Channel: ubports-touch/16.04/edge
Package: deb
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: http://paste.ubuntu.com/p/4H5g5HMmXt/

**Comment by NeoTheThird** [comment]
Weird it should be there: http://system-image.ubports.com/ubports-touch/16.04/edge/flo/

Could you try again? Maybe just a connection issue...

**Comment by Bekkenes** [comment]
Ill try again 😊
Was from Ubuntu Deb.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Bekkenes** [comment]
When launching app btw it says a newer verion is available, then it redirects me to the version before this


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NeoTheThird** [comment]
Yeah, you're using the prerelease version, it's not yet fully tested. The update notice always shows up if you're using anything but the latest stable release. But it should not cause this issue, because we did not touch the part responsible for this in this release.

**Comment by Bekkenes** [comment]
ok.
I just want to inform you that when i tried now, this error did not happen, and edge is installed


________________________________
Fra: Jan Sprinz <notifications@github.com>
Sendt: torsdag 29. august 2019 14.46
Til: ubports/ubports-installer <ubports-installer@noreply.github.com>
Kopi: Bekkenes <thomas.bekkenes@outlook.com>; Author <author@noreply.github.com>
Emne: Re: [ubports/ubports-installer] could not find latest version (#867)


Yeah, you're using the prerelease version, it's not yet fully tested. The update notice always shows up if you're using anything but the latest stable release. But it should not cause this issue, because we did not touch the part responsible for this in this release.

**Comment by NeoTheThird** [comment]
Great, thanks for letting me know. Seems like a network issue, then. Let's keep it open and find a way to properly handle this :)
