### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:423)

### ISSUE THREAD

**Issue by DucktectiveClues** [ubports/ubports-installer#87]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: win32 
Host Dist: undefined undefined
Host Arc

**Comment by NeoTheThird** [comment]
Thanks for reporting. :) This should be fixed in the latest version that will be published tonight.

**Comment by probonopd** [comment]
Still seems to be in the current AppImage:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/5bbe219748bb00b0624c06140bf52024337ada8e/database/ubports-installer/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/commit/5bbe219748bb00b0624c06140bf52024337ada8e
