### ISSUE TITLE
Adb push error: Error: Command failed: adb -P 5038 push "/home/pop-os/.cache/ubports/pool/ubports-6aede75af320a0ee2da5cbe8f967a97bf5b856fab2ba4e4eda44a992a8950089.tar.xz" /cache/recovery/, stdout: [...]da5cbe8f967a97bf5b856fab2ba4e4eda44a992a8950089.tar.xz': remote No space left on device/home/pop-os/.cache/ubports/pool/ubports-6aede75af320a0ee2da5cbe8f967a97bf5b856fab2ba4e4eda44a992a8950089.tar.xz: 0 files pushed. 9.1 MB/s (101711872 bytes in 10.679s), stderr: 

### ISSUE THREAD

**Issue by grandweb4** [ubports/ubports-installer#874]
*Automatically generated error report* 
UBports Installer Version: 0.2.6-beta 
Device: mako
Channel: ubports-touch/16.04/rc
Package: deb
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: /p/K93pXrZXyG/

**Comment by grandweb4** [comment]
I tried:

- Multiple cables
- Live booting Linux
- Resetting the Nexus 4
- Wiping the cache
- Manually installing (almost worked)

It worked up until about push 7 out of 13 the first time on Linux!
I have recovery... Is it something I need to change or is there a bug? Thanks!

**Comment by NeoTheThird** [comment]
Could you try rebooting to bootloader and running `fastboot format cache`?

**Comment by wannaplaywithme69** [comment]
Same issues on D820(E)

**Comment by grandweb4** [comment]
After running that I got a new error (I tried version 0.3.2 beta): 
Error: Unknown: Push failed: Failed push: Failed to push file 0: Push failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/Users/george/Library/Caches/ubports/platform-tools/adb -P 5037 push /Users/george/Library/Caches/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz /cache/recovery/ > /dev/null"}

*Automatically generated error report* 
UBports Installer Version: 0.3.2-beta å
Device: mako
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.518F132 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/N47bRnhkTG/

**Comment by grandweb4** [comment]
For the same version (0.2.7):
Adb push error: Error: Command failed: /var/folders/m_/bychb0f56ls2z4wm7g4x19tc0000gn/T/.com.ubports.installer.UdW1qb -P 5038 push /Users/george/Library/Caches/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz /cache/recovery/, stdout: [...]c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz': remote No space left on device/Users/george/Library/Caches/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz: 0 files pushed. 3.9 MB/s (99995728 bytes in 24.699s), stderr: 

Error: Unknown: Push failed: Failed push: Failed to push file 0: Push failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/Users/george/Library/Caches/ubports/platform-tools/adb -P 5037 push /Users/george/Library/Caches/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz /cache/recovery/ > /dev/null"}
