### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by stdcerr** [ubports/ubports-installer#875]
*Automatically generated error report* 
UBports Installer Version: 0.2.6-beta 
Device: mako
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 
Error log: /p/K5Ppzy6mkT/ 
I've got the phone in bootloader mode now but the installer won't continue (I had to unplug the phone to get it into that mode but re-plugged it since - same USB port)

**Comment by NeoTheThird** [comment]
What OS is the device running?

**Comment by stdcerr** [comment]
Lineage  with TWRP and I have not been able to get Ubuntu touchinstalled on
it. When I get into the bootloader it just sits there and doesn't proceed.
Can you help?
