### ISSUE TITLE
Make for redmi NOte 7

### ISSUE THREAD

**Issue by Yaroslav2017** [ubports/ubports-installer#876]
*Automatically generated error report* 
UBports Installer Version: 0.2.6-beta 
Device: bacon
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17763.678] ia32 
NodeJS version: v8.2.1 

Error log: /p/qFJwrXwZV8/

**Comment by NeoTheThird** [comment]
Sorry, we don't support that device. Please see [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io) for a list of devices or [docs.halium.org](https://docs.halium.org) for porting information, if you want to look into enabling this device yourself.
