### ISSUE TITLE
Fastboot: Unknown error:  target didn't report max-download-sizesending 'recovery' (11390 KB)...FAILED (command write failed (Success))finished. total time: 0.000s

### ISSUE THREAD

**Issue by kennypavan** [ubports/ubports-installer#883]
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: bacon
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/HYXDTbxBXm/

**Comment by natebat** [comment]
I also get this same error with the nexus 5
