### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:437)

### ISSUE THREAD

**Issue by yello121** [ubports/ubports-installer#885]
Automatically generated error report 
Version: 0.1.13-beta 
Host OS: linux 
Host Dist: Linux Mint undefined
Host Arch: x64 
Node: v8.2.1 

Error log: /p/GGNdnNpsWK/

**Comment by NeoTheThird** [comment]
Hey there, please use an up-to-date version of the installer. You can find packages here: https://github.com/ubports/ubports-installer/releases/latest

Or run `snap install ubports-installer` to install the snap package, since that will update automatically.
