### ISSUE TITLE
Device in Recovery but ubports-installer Waiting For Device To Enter Recovery Mode

### ISSUE THREAD

**Issue by nerdcorenet** [ubports/ubports-installer#886]
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: Nexus 5 (hammerhead)
Channel: 16.04/stable
Package: snap
Operating System: Ubuntu Linux  18.04  bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/Qnv44JC8Zn/ 

ubports-installer has successfully replaced my previous Recovery image with its own.
The device then reboots into Ubports Recovery as expected.
However on the PC, ubports-installer GUI says "Waiting for device to enter recovery mode..."
The device is in Recovery mode.
Installation is stalled at this stage.

**Comment by tiagobalmeida** [comment]
Have the same problem on a Nexus 4
