### ISSUE TITLE
Oneplus 1 not recognized on Ubuntu

### ISSUE THREAD

**Issue by aclifton314** [ubports/ubports-installer#889]
**System Info**
- Windows 10 laptop
- Ubuntu 18.04.3 LTS running on a virtual machine on laptop
- UBPorts installer 0.2.7 beta
- Oneplus One phone (A0001)
- Android version 6.0.1

**Windows Attempt**
- I downloaded the ubports installer for Windows (ubports-installer.0.2.7-beta.exe). 
- I plugged my phone into my laptop using a USB cable that was also used to put software on an Amazon tablet through my machine.
- The phone is NOT in developer mode at this point (but will be later on).
- In Windows Explorer, a device named "A0001" shows up, but it is empty when I click on it.
- I put the phone into developer mode and turn on Advanced Reboot, Android Debugging, and the USB Configuration is set to MTP.
- After doing this, the A0001 device now shows the internal storage of the phone and I can view the file system.
- An error shows up that says "Windows Defender Smartscreen prevented the app from starting."
- Right clicking the installer and selecting "Run as administrator" produces the same error.
- I unplug the phone and download and install the Universal ADB Driver from the UBPorts installer notification.
- I plug the phone back in and, interestingly, the phone's filesystem does not show up in Windows Explorer. Setting the USB Configuration to MTP resolves this.
- I use cygwin to open the UBPorts installer successfully.
- I choose "Dismiss" from the installer notice and get "Waiting for Device" on the installer. Unplugging and reconnecting the phone does not resolve this.
     - Note: Unplugging the phone makes the USB Configuration setting switch back to Charging. I took this into account in the above step, to no avail.
- I select the device manually and get to the "Please reboot to bootloader" part of the installer. However, following the instructions doesn't seem to help (I held the buttons for 3 minutes). Also, choosing to reboot into the bootloader by holding the power button down makes the "fastboot mode" screen appear on my phone but does nothing to the "Please reboot to bootloader" page of the installer.
- I unplug the phone from the laptop and try the Ubuntu VM.

**Ubuntu VM Attempt**
- I download the UBPorts AppImage installer and get it setup.
- I install `adb` and `fastboot` and restart the machine.
- Developer mode is enabled with the same options as above and I ensure the USB Configuration option is set to MTP.
- The phone is connected to the laptop.
- The phone does not show up in the Files viewer, nothing appears in `/mnt` or `/media/user_name`, `adb devices` shows nothing, and `lsusb` shows the following:
`Bus 001 Device 002: ID 80ee:0021 VirtualBox USB Tablet`
`Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub`
- Despite this, I go ahead and run the installer.
- The first page of the installer shows the same "Waiting for device" notice as the Windows attempt.
- I choose the advice manually, but still get the same "Please reboot to bootloader"  screen on the installer. 

I'm not sure if I'm doing something wrong but does anyone have any pointers on how to get UBPorts working on this phone? Thanks in advance!

**Comment by NeoTheThird** [comment]
Hey there, wow, you really went through hell. I am sorry you had such a terrible experience. Let's try and fix this.

One thing that would really help me is logs. I can see that you put in a lot of work to meticulously write up what you did and what happened with the installer, but there's way more information in the log.

> An error shows up that says "Windows Defender Smartscreen prevented the app from starting."

That is a [really annoying feature in Windows 10](https://docs.ubports.com/en/latest/userguide/install.html#windows-defender-prevents-installer-from-starting). If you click "More Information", it will present you with an option to run it anyways.

> Also, choosing to reboot into the bootloader by holding the power button down makes the "fastboot mode" screen appear on my phone but does nothing to the "Please reboot to bootloader" page of the installer.

Okay, so at this point your device was in the correct mode (fastboot mode = bootloader), but the installer did not detect it. Could be a driver issue, could be a cable issue, could be a security feature in windows. Impossible to tell without a log.

> Ubuntu VM Attempt

Make sure the VM has access to the USB-Port. [Here's how to do that in virtualbox](https://www.techrepublic.com/article/how-to-enable-usb-in-virtualbox/).

> Developer mode is enabled with the same options as above and I ensure the USB Configuration option is set to MTP.

MTP is media transfer, which allows you to access part of the devices file system on the PC. That has nothing to do with what we need for the installer. Different android versions have different names for it, some call it "USB Debugging", some "ADB" (android debug bridge). That needs to be enabled. MTP does not really matter.

One thing you can try if the installer can't see the device is unplug it and plug it back in again, that sometimes helps. You can also just close the installer and start from the beginning at any time.

One more thing: The current stable release has a problem with oem-unlocking. You can get around that by installing fastboot (run `sudo apt install fastboot` in the terminal on Ubuntu) and then `fastboot oem unlock`. See the manual instructions [on the devices page](https://devices.ubuntu-touch.io) for more information.

Good luck with your further attempts and please let me know if you run into any other issues. If the installer throws an error, please always use the built-in bugreporting feature, so i know what's going on. That gives me all the information i need to help you.

**Comment by aclifton314** [comment]
Ok. I'll give it another go with the information you have provided. Pardon my naivete, but how do I generate the logs and where are they stored?

**Comment by NeoTheThird** [comment]
They are automatically attached to your bug-report if you use the built-in bugreporting feature. If you want to look at the file, you can find it in `~/.cace/ubports/ubports-installer.log` on Linux. On Windows, it'll probably be somewhere in `%APPDATA%`.

**Comment by NeoTheThird** [comment]
Oh, and if you want to see the log as it's being written to, start the installer with `-v` for verbose output.

**Comment by aclifton314** [comment]
Ok. I was able to get the USB drives visible to my VM. Thanks for linking to that. So here is what I have done:

**Ubuntu VM Attempts**
- started up the Ubuntu VM with the phone unplugged.
- start up the ubports installer (AppImage)
- I get the "waiting for device" screen.
- plugged in the phone (it was configured into developer mode with Android debugging)
- the phone shows up on the desktop and in the Files viewer on Ubuntu
- the installer still shows "waiting for device"
- `adb devices` shows nothing although it looks like the server had to start first
- closed the isntaller and unplugged the phone.

- ran `adb start-server`
- start up the ubports installer (AppImage)
- I get the "waiting for device" screen.
- plugged in the phone 
- the phone shows up on the desktop and in the Files viewer on Ubuntu
- the installer still shows "waiting for device"
- `adb devices` shows nothing 

I have attached the logs for the two attempts. 
[ubports-installer_attempt1.log](https://github.com/ubports/ubports-installer/files/3665707/ubports-installer_attempt1.log)
[ubports-installer_attempt2.log](https://github.com/ubports/ubports-installer/files/3665708/ubports-installer_attempt2.log)

- I unplugged the phone and restarted it
- put the phone back in developer mode with Android debugging enabled
- ran `adb devices` and got a hit!
`List of devices attached`
`8a8165fa	device`
- ran `ubports-installer` from the command line
- installer started up and gave the "waiting for device" message
- unplugged phone and plugged back in
- device showed up on desktop but still got the "waiting for device" message

I should note that during all of the attempts the "Select device manually" had no options to choose from (it was blank). 
[ubports-installer.log](https://github.com/ubports/ubports-installer/files/3665723/ubports-installer.log)

**Comment by aclifton314** [comment]
Also, I just tried 5 different USB cables. All of them get the device to show up on the ubuntu desktop, but only two of them give entries in `adb devices`. Presumably, I should be using either of those two cables while debugging this install issue as they will transfer data?

**Comment by aclifton314** [comment]
Ok, new update.

On Windows, I was able to go through the manual instructions and almost get it working. I ended up, unknowingly, using the linux manual instructions in cygwin on Windows 10.

Everything went fine until I got:
`$ adb shell "mount -a"`
`mount: mounting /dev/block/platform/msm_sdcc.1/by-name/boot on /boot failed: No such file or directory`
`mount: mounting /dev/block/platform/msm_sdcc.1/by-name/recovery on /recovery failed: No such file or directory`
`mount: mounting /dev/block/platform/msm_sdcc.1/by-name/modem on /firmware failed: No such file or directory`
`mount: mounting /dev/block/platform/msm_sdcc.1/by-name/persist on /persist failed: No such file or directory`

Although in the instructions it says that this is ok so I pressed on. All the `adb push` commands work, or at least they ended up saying "1 file pushed" each time (along with a data transfer rate and size).

I ran `adb reboot recovery`. The phone responded, produced the "Installing Update" graphic, then it boots to the UBports recovery menu. I'm presented with some options but I didn't know which one to pick. So I chose "Reboot system now".

The system reboots and shows the "OPO powered by Ubuntu supported by ubports" screen and does nothing else. I let the phone sit on that screen for several minutes before giving up.

Any thoughts?

**Comment by aclifton314** [comment]
Any thoughts on this issue?

**Comment by NeoTheThird** [comment]
Would you mind trying again with [the current prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.4.1-beta)?

**Comment by aclifton314** [comment]
I don't mind at all. Would love to try out the new installer!

Is there anything specific I need to do before attempting? The reason I ask is because the phone is semi-flashed now and when I boot it up it shows all the ubuntu touch screens and none of the android ones.

**Comment by NeoTheThird** [comment]
No, nothing special to do. The installer will tell you how to boot into bootloader in the beginning and it should be all smooth sailing from there.

**Comment by aclifton314** [comment]
OK. Here is my update
**WINDOWS ATTEMPT**
- Started with phone powered off.
- I ran into an issue with double clicking the installer to launch it, but opening it in cygwin worked.
- Once prompted, I plugged in device and waited.
- "Powered by ubuntu" and Oneplus one logo appeared. This was from my previous attempt.
- Had to manually pick phone.
- Once I picked the correct phone, I booted to boot loader
   - I actually pressed the lock + volume down button at this step. Because of my previous attempts, I didn't know if the directions on the installer were still accurate. I knew that lock + volume down would boot me to recovery which would give me an option to boot to bootloader, so I chose that option.
- Next screen asked to boot to recovery, so I did that.
- Clicked continue on the installer.
- Ubuntu touch began to download.
- I got success screen on the installer.
   - At this point, there is a section on the installer that says it will begin downloading more files to complete the installation. So I waited.
- Phone showed "Installing updates" with animation.
- Phone restarted and took me to the ubuntu touch Language selection screen.
- Completed installation process on phone. Ubuntu Touch is officially installed and working on this phone!

Fantastic job on this UBPorts team! Thank you to the community for the assistance and please keep up the great work. Can't wait to explore this. 

BTW, if it would be helpful to post the logs, I am happy to do so. I installed this on Windows 10 and am not sure exactly where to find them. Let me know where they are and I can post them.

Thanks again team!

**Comment by NeoTheThird** [comment]
Awesome, good to hear it finally worked out for you! We worked our asses off over the last two months to fix the installer, so i appreciate the praise :)

The log's stored in `%APPDATA%\ubports`, but since it was successful, there won't be much of interest in there.
