### ISSUE TITLE
Uncaught TypeError: log.warning is not a function (MainRenderer:200)

### ISSUE THREAD

**Issue by Luigi01** [ubports/ubports-installer#89]
Automatically generated error report 
Version: 0.1.8-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 17.10
Host Arch: x64 
Node: v7.9.0

Error generated when running ubports-installer in order to update my BQ M10 FHD tablet; tablet is recognized, software is recognized (Carnonical) - I choose to switch to UBports, am asked for my password, tablet is switched to "fastboot" mode, and then a) this error occurs, and b) the programs starts to wait until the device is plugged in. 
UBports started from terminal - terminal output:

************************************************
ubports-installer 
debug: Using native platform tools!
debug: Running platform tool exec cmd adb kill-server
debug: 
debug: Running platform tool exec cmd adb -P 5038 kill-server
debug: 
debug: Running platform tool exec asar cmd [object Object] -P 5038 start-server
debug: adb shell: echo 1
debug: Running platform tool exec cmd adb -P 5038 shell echo 1
debug: 
debug: adb shell: getprop ro.product.device
debug: Running platform tool exec cmd adb -P 5038 shell getprop ro.product.device
debug: 
debug: getprop: frieza
debug: adb shell: cat /etc/system-image/channel.ini
debug: Running platform tool exec cmd adb -P 5038 shell cat /etc/system-image/channel.ini
debug: 
debug: adb shell: echo 1
debug: Running platform tool exec cmd adb -P 5038 shell echo 1
debug: 
debug: reboot to bootloader
debug: Running platform tool exec cmd adb -P 5038 reboot bootloader
debug: 
debug: reboot to bootloader [DONE] err:null
debug: checking password
debug: correct password
debug: fastboot: wait for device
*************************************************
PC: Medion Akoya, Intel(R) Pentium(R) Dual  CPU  T2390  @ 1.86GHz; Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux; OS Ubuntu Mate.
Error repeatable, happens every time program is run.

**Comment by NeoTheThird** [comment]
Thanks for reporting. :) This should be fixed in the latest version that will be published tonight.
