### ISSUE TITLE
Adb push error: Error: Command failed: adb -P 5038 push "/home/tompi/.cache/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz" /cache/recovery/, stdout: [...]b6bdc19830c.tar.xz' to '/cache/recovery/': remote couldn't create file: Permission denied/home/tompi/.cache/ubports/pool/ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz: 0 files pushed. 316.7 MB/s (2686976 bytes in 0.008s), stderr: 

### ISSUE THREAD

**Issue by villefort** [ubports/ubports-installer#891]
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: FP2
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/Zn3mpSHRzz/

**Comment by JassMan23** [comment]
Just been hit by exactly the same ADB Push error message.
The screen on the Nexus flo displays (on a purple fading to orange Ubuntu background):
`Ubuntu Touch (CWM-based) Recovery v6.0.4.6`   
` - reboot system now`   
` - wipe data/factory reset`   
` - wipe cache partition`   
` - backup and restore`   
` - advanced`   
`    `   
`    `   
`    `   
`    `     
`Ubuntu Touch (CWM-based) Recovery v6.0.4.6`   
` e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8`   
` e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8`   
` Can't mount /cache/recovery/ubuntu_command`
` e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8`   
` Can't mount /cache/recovery/command`   
` e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8`   
` Can't mount /cache/recovery/log`   
` Can't open /cache/recovery/log`   
` e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8`
` Can't mount /cache/recovery/last_log`   
` Can't open /cache/recovery/last_log`   
` e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8`
` Can't mount /cache/recovery/last_install`   
` Can't open /cache/recovery/last_install`   
` e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8`
As per the instructions on screen, I typed `snap refresh ubports-installer --stable`   
~$ `snap "ubports-installer" has no updates available`

As suggested on the web, I have tried with and without "wipe" selected.

By default restarting goes  to a Google screen with open padlock and stops. Rebooting with Volume Down, gives the usual `Start/Restart Bootloader/Recovery Mode/Power Off` menu.
