### ISSUE TITLE
Uncaught TypeError: devices.sort is not a function (MainRenderer:419)

### ISSUE THREAD

**Issue by JassMan23** [ubports/ubports-installer#894]
Automatically generated error report 
Version: 0.1.12-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 18.04
Host Arch: x64 
Node: v8.2.1 

Error log: /p/csj9nJND7B/ 

**[edit]**
Realised I had picked the old version of Installer; Removed old version and reran 0.2.7 (beta)
It couldn't detect the device but at least it allowed me to manually select flo
`Attempting to install on Nexus 7 flo ___ currently Android 3.0.1   
Hardware    Nexus 7   
Android 6.0.1   
Security Update Level   5 August 2016   
Kernel  3.4.0-gad29d11   
    android-build@vpea2.mtv.corp.google.com #1   
    Sat Jul 00:00:53 UTC 2016   
Build number    MOB30X`   

It failed to warn that I would need to `fastboot oem unlock` before starting. I left installer running (this may have been a big mistake). I then disconnected the cable so that I could get into fastboot mode (restarting with cable plugged in goes to charging mode and won't restart)
When I plugged the cable back in, the installer changed to downloading Touch 1 of 12
and while it was doing that, the Nexus booted as far as:
`    Ubuntu Touch (CWM-based) Recovery v6.0.4.6   
     - reboot system now   
     - wipe data/factory reset   
     - wipe cache partition   
     - backup and restore   
     - advanced   
    .   
    .   
    .   
    .   
    Ubuntu Touch (CWM-based) Recovery v6.0.4.6   
    e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8   
    e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8   
    Can't mount /cache/recovery/ubuntu_command   
    e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8   
    Can't mount /cache/recovery/command   
    e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8   
    Can't mount /cache/recovery/log   
    Can't open /cache/recovery/log   
    e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8   
    Can't mount /cache/recovery/last_log   
    Can't open /cache/recovery/last_log   
    e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8   
    Can't mount /cache/recovery/last_install   
    Can't open /cache/recovery/last_install   
    e2fsck [/dev/block/msm-sdcc.1/by-name/cache] failed with 8   
`
After half an hour of nothing happening, I am temporarily giving up!

**Comment by NeoTheThird** [comment]
Sorry about that. That is a REALLY old version, did you download that recently? If so, where? We need to update that link, then. Please try again with the [latest version of the installer](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by JassMan23** [comment]
Are you saying there is a newer version than  0.2.7 (beta)?
