### ISSUE TITLE
Fastboot invoked as system-command rather than fallback tool on windows

### ISSUE THREAD

**Issue by Jacentyk90** [ubports/ubports-installer#896]
Please help because I wanted to install Ubuntu Touch on Nexus 5. I am currently using Windows 10. The phone has bootloader unlocked, Android has root privileges.

*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.228] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/h9JMmyyNkY/

**Comment by NeoTheThird** [comment]
Hmm, that is weird. Can you try running the installer from the console with the `--force-fallback` argument?

**Comment by NeoTheThird** [comment]
Duplicate of #762
