### ISSUE TITLE
Fastboot: Unknown error:  < waiting for device >downloading 'boot.img'...FAILED (command write failed (Protocol error))finished. total time: 0.004s

### ISSUE THREAD

**Issue by jethro-swan** [ubports/ubports-installer#90]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Ubuntu Linux 16.04
Host Arch: x64 
Node: v7.9.0

**Comment by NeoTheThird** [comment]
Thanks for reporting. :) This should be fixed in the latest version that will be published tonight. Please try with multiple USB cables if this happens again to make sure the phone does not loose connection. Cheap and old cables tend to do that.
