### ISSUE TITLE
Error: bootstrap: flashing failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/home/lakotaubp/.cache/ubports/platform-tools/fastboot flash LOGO /home/lakotaubp/.cache/ubports/images/bacon/LOGO-bacon.img"}stderr: fastboot: error: cannot load '/home/lakotaubp/.cache/ubports/images/bacon/LOGO-bacon.img': No such file or directory

### ISSUE THREAD

**Issue by lakotaubp** [ubports/ubports-installer#903]
*Automatically generated error report* 
UBports Installer Version: 0.3.1-beta 
Device: bacon
Channel: ubports-touch/16.04/edge
Package: deb
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/cgXJcF38Kr/

**Comment by NeoTheThird** [comment]
Aren't case-sensitive file-systems just a treat? I bet this just works on Windows :D

Thanks for reporting :)
