### ISSUE TITLE
Error: bootstrap: flashing failed: error: {"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\woody\\AppData\\Roaming\\ubports\\platform-tools\\fastboot flash LOGO C:\\Users\\woody\\AppData\\Roaming\\ubports\\images\\bacon\\LOGO-bacon.img"}stderr: fastboot: error: cannot load 'C:\Users\woody\AppData\Roaming\ubports\images\bacon\LOGO-bacon.img': No such file or directory

### ISSUE THREAD

**Issue by lakotaubp** [ubports/ubports-installer#904]
*Automatically generated error report* 
UBports Installer Version: 0.3.1-beta 
Device: bacon
Channel: ubports-touch/16.04/edge
Package: exe
Operating System: Microsoft Windows [Version 10.0.17134.885] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/tYJnMzVsnh/

**Comment by NeoTheThird** [comment]
Huh, guess i was wrong #903, thanks

**Comment by lakotaubp** [comment]
Unfortunately yes
