### ISSUE TITLE
Error: Unknown: error: {"killed":false,"code":1,"signal":null,"cmd":"/home/mike/.cache/ubports/platform-tools/adb -P 5037 shell echo ."}stderr: adb server version (39) doesn't match this client (41)

### ISSUE THREAD

**Issue by mymike00** [ubports/ubports-installer#907]
*Automatically generated error report* 
UBports Installer Version: 0.3.1-beta 
Device: hammerhead
Channel: ubports-touch/16.04/rc
Package: deb
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/PxyQwsxqy9/ 

this log mentions `/tmp/adb.1000.log`, I pasted it here https://paste.ubuntu.com/p/THfQkbSFGm/

**Comment by mymike00** [comment]
I tried a second time but the installer still hanged on the "waiting for device to enter recovery" while the phone was in fastboot. since the phone power button is broken (there is no power button anymore) I'm not able to press the button combo to reboot to recovery. from pc I run `sudo fastboot reboot` and `adb reboot recovery`: the installer started downloading ubuntu touch

iirc a previous version of the installer could reboot automatically to recovery, do I remember correct?

**Comment by mymike00** [comment]
the second try went fine, except for the manual reboot to recovery. don't know if this issue could help you somehow, feel free to close it

**Comment by NeoTheThird** [comment]
Seems to have a problem with another adb server running in the system. It's supposed to kill it, but that seems to have failed. Will have to look into this. Thanks for reporting!

**Comment by mymike00** [comment]
I'm glad this is helpful for you!
