### ISSUE TITLE
user-requested bug-report

### ISSUE THREAD

**Issue by lakotaubp** [ubports/ubports-installer#908]
*Automatically generated error report* 
UBports Installer Version: 0.3.1-beta 
Device: hammerhead
Channel: ubports-touch/16.04/edge
Package: deb
Operating System: Linux Mint undefined undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/vH6JCV4FXH/

**Comment by NeoTheThird** [comment]
What seems to be the problem? Does the installer not recognize the device?

**Comment by lakotaubp** [comment]
Sorry thought bug report was attached.
Device not recognised- did manually
Did not reboot to bootloader-did it manually
Did not enter recovery - did it manually
Just doing it again and ..flip this time it's carrying on. Last two times
it didn't. Oh well. Nothing other than manual rebooting showing in
terminal. Completed Ok

**Comment by NeoTheThird** [comment]
But it always prompted you to reboot manually, right?
