### ISSUE TITLE
Command failed: echo "" | sudo -S echo correct/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'/bin/sh: -c: line 1: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by ezickler** [ubports/ubports-installer#91]
Automatically generated error report 
Version: 0.1.9-beta 
Host OS: linux 
Host Dist: Fedora 27
Host Arch: x64 
Node: v7.9.0 

Error log: http://paste.ubuntu.com/p/vhQ9yTZMhS/

**Comment by NeoTheThird** [comment]
Please try running the installer from source as described in the [README.md](README.md) to make sure it's not a  packaging issue.
