### ISSUE TITLE
Allow restarting just the download rather than the entire install

### ISSUE THREAD

**Issue by timsueberkrueb** [ubports/ubports-installer#916]
Getting this error message in the "Downloading Ubuntu Touch" stage for bacon, xenial stable:
```
info: Starting download of 12 files
info: Download checking file
error: Devices: Download error Checksum mismatch on file ubports-8832267993eb0215232c953d6c5fa7f22ab2fe348b4e68946b098b6bdc19830c.tar.xz
Good bye!
```
Is there a quick workaround? Thanks!

**Comment by timsueberkrueb** [comment]
I don't know why, but the error didn't show up on second attempt. Maybe the validation is skipped if the file has already been downloaded (just a wild guess)? Feel free to reopen if you think this wasn't a temporary glitch.

**Comment by NeoTheThird** [comment]
> Maybe the validation is skipped if the file has already been downloaded (just a wild guess)? Feel free to reopen if you think this wasn't a temporary glitch.

No, that would be very bad behavior! That means we'd flash corrupted or maliciously altered files if any file already exists. What i think happened is that your download got corrupted and on the second try it saw an invalid file and downloaded again successfully. We should maybe add a try again button here that just lets you start the download again. Reopening for that, thanks for reporting :)
