### ISSUE TITLE
Installation stops halfway on macOS

### ISSUE THREAD

**Issue by popesz** [ubports/ubports-installer#92]
Automatically generated error report %0AVersion: 0.1.9-beta %0AHost OS: darwin %0AHost Dist: undefined undefined%0AHost Arch: x64 %0ANode: v7.9.0 %0A%0AError log: http://paste.ubuntu.com/p/M2Pw6yPNGx/ %0A

**Comment by NeoTheThird** [comment]
Should be fixed in the latest version that will be published tonight. Thanks for reporting. :)

**Comment by popesz** [comment]
Thanks for the update. 
Now the recovery image downloads fine and an orange line goes on the Ubports-installer window which stops right here:
<img width="800" alt="screen shot 2018-02-28 at 09 35 43" src="https://user-images.githubusercontent.com/1534467/36778046-eb277966-1c6b-11e8-92c6-12545e2d649c.png">

The terminal is like this:
debug: fastboot: wait for device
info: Download startCheck
error: Not existing /Users/EMV/Library/Caches/ubports/images/vegetahd/recovery-vegetahd.img
info: Starting download of 1 files
info: Downloading file, 1% complete
info: Downloading file, 19% complete
info: Downloading file, 33% complete
info: Downloading file, 47% complete
info: Downloading file, 61% complete
info: Downloading file, 75% complete
info: Downloading file, 91% complete
info: Download checking file
info: checked: recovery-vegetahd.img
info: Download complete
info: done downloading(once listener)
debug: fastboot: flash; [object Object]
info: Booting into recovery image...


The End

**Comment by popesz** [comment]
Looks like it stops at booting into recovery image. If I do it manually:
**info: Booting into recovery image...**
error: Devices: Error: Fastboot: Unknown error:  ERROR: usb_read failed with status e00002ed
ERROR: usb_write failed with status e00002d8
ERROR: usb_write failed with status e00002d8
downloading 'boot.img'...
ERROR: usb_write failed with status e00002c0
FAILED (command write failed (Invalid argument))
finished. total time: 0.000s

**Comment by popesz** [comment]
next step, managed to reboot into recovery.
info: Download complete
debug: adb shell: cat /etc/recovery.fstab
debug:  Error: Command failed: adb -P 5038 shell cat /etc/recovery.fstab
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
debug: adb shell: mount -a
debug: 
debug: adb shell: mkdir -p /cache/recovery
debug: 
info: Start pushing 13 files
debug:  Error: Command failed: adb -P 5038 push '/Users/EMV/Library/Caches/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
error: Devices: Error: Adb push error: 
error: Devices: Adb push error: 
debug: 
info: Adb push, 0% left

error at pushing files

**Comment by NeoTheThird** [comment]
Archiving your log from #104 here: https://paste.ubuntu.com/p/TDxDs9xmZf/

**Comment by NeoTheThird** [comment]
Could you open a terminal and run `ls -R /Users/EMV/Library/Caches/ubports/`, please?

**Comment by popesz** [comment]
commandfile		images			ubports-installer.log
gpg			pool

/Users/EMV/Library/Caches/ubports//commandfile:
ubuntu_commandvegetahd2866

/Users/EMV/Library/Caches/ubports//gpg:
image-master.tar.xz		image-signing.tar.xz
image-master.tar.xz.asc		image-signing.tar.xz.asc

/Users/EMV/Library/Caches/ubports//images:
vegetahd

/Users/EMV/Library/Caches/ubports//images/vegetahd:
recovery-vegetahd.img

/Users/EMV/Library/Caches/ubports//pool:
device-da90b80b4e780bca4ebd1e0d7d5168991e0d14d88c82cfd2906cce9f0d85b9e7.tar.xz
device-da90b80b4e780bca4ebd1e0d7d5168991e0d14d88c82cfd2906cce9f0d85b9e7.tar.xz.asc
keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc
ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz
ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz.asc
version-3.tar.xz
version-3.tar.xz.asc

**Comment by NeoTheThird** [comment]
Ah! got it, silly me!

**Comment by popesz** [comment]
Just in case I send you the full terminal:
debug: adb shell: echo 1
debug: 
info: Download startCheck
debug:  url=https://system-image.ubports.com//pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz, path=/Users/EMV/Library/Caches/ubports/pool, checksum=777b2d05b2a0f26b2a9a302eb7804e7eab9bf536f130ffae2f15455a80bd509b, url=https://system-image.ubports.com//pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz.asc, path=/Users/EMV/Library/Caches/ubports/pool, url=https://system-image.ubports.com//pool/device-da90b80b4e780bca4ebd1e0d7d5168991e0d14d88c82cfd2906cce9f0d85b9e7.tar.xz, path=/Users/EMV/Library/Caches/ubports/pool, checksum=2bb15e0d9b7987c5e15a4e82c6b575467b0df246db8a52b0fd7f9292c10b399d, url=https://system-image.ubports.com//pool/device-da90b80b4e780bca4ebd1e0d7d5168991e0d14d88c82cfd2906cce9f0d85b9e7.tar.xz.asc, path=/Users/EMV/Library/Caches/ubports/pool, url=https://system-image.ubports.com//pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz, path=/Users/EMV/Library/Caches/ubports/pool, checksum=5b6e870acf8944330acb2a9dad6f5270bd06c377603a3115f805290e989ab421, url=https://system-image.ubports.com//pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc, path=/Users/EMV/Library/Caches/ubports/pool, url=https://system-image.ubports.com//ubports-touch/15.04/stable/vegetahd/version-3.tar.xz, path=/Users/EMV/Library/Caches/ubports/pool, checksum=d6432b66c2132c6741734382f8ab4ed8bd0bf407cf55870963d17184e2d9d2be, url=https://system-image.ubports.com//ubports-touch/15.04/stable/vegetahd/version-3.tar.xz.asc, path=/Users/EMV/Library/Caches/ubports/pool, url=https://system-image.ubports.com//gpg/image-signing.tar.xz, path=/Users/EMV/Library/Caches/ubports/gpg, url=https://system-image.ubports.com//gpg/image-signing.tar.xz.asc, path=/Users/EMV/Library/Caches/ubports/gpg, url=https://system-image.ubports.com//gpg/image-master.tar.xz, path=/Users/EMV/Library/Caches/ubports/gpg, url=https://system-image.ubports.com//gpg/image-master.tar.xz.asc, path=/Users/EMV/Library/Caches/ubports/gpg
error: Not existing /Users/EMV/Library/Caches/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz
error: Not existing /Users/EMV/Library/Caches/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz.asc
error: Not existing /Users/EMV/Library/Caches/ubports/pool/device-da90b80b4e780bca4ebd1e0d7d5168991e0d14d88c82cfd2906cce9f0d85b9e7.tar.xz
error: Not existing /Users/EMV/Library/Caches/ubports/pool/device-da90b80b4e780bca4ebd1e0d7d5168991e0d14d88c82cfd2906cce9f0d85b9e7.tar.xz.asc
error: Not existing /Users/EMV/Library/Caches/ubports/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
error: Not existing /Users/EMV/Library/Caches/ubports/pool/keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz.asc
error: Not existing /Users/EMV/Library/Caches/ubports/pool/version-3.tar.xz
error: Not existing /Users/EMV/Library/Caches/ubports/pool/version-3.tar.xz.asc
error: Not existing /Users/EMV/Library/Caches/ubports/gpg/image-signing.tar.xz
error: Not existing /Users/EMV/Library/Caches/ubports/gpg/image-signing.tar.xz.asc
error: Not existing /Users/EMV/Library/Caches/ubports/gpg/image-master.tar.xz
error: Not existing /Users/EMV/Library/Caches/ubports/gpg/image-master.tar.xz.asc
info: Starting download of 12 files
info: Downloading file, 1% complete
info: Downloading file, 1% complete
info: Downloading file, 2% complete
info: Downloading file, 3% complete
info: Downloading file, 4% complete
info: Downloading file, 5% complete
info: Downloading file, 6% complete
info: Downloading file, 7% complete
info: Downloading file, 8% complete
info: Downloading file, 8% complete
info: Downloading file, 9% complete
info: Downloading file, 9% complete
info: Downloading file, 10% complete
info: Downloading file, 10% complete
info: Downloading file, 11% complete
info: Downloading file, 12% complete
info: Downloading file, 12% complete
info: Downloading file, 13% complete
info: Downloading file, 14% complete
info: Downloading file, 15% complete
info: Downloading file, 16% complete
info: Downloading file, 17% complete
info: Downloading file, 18% complete
info: Downloading file, 19% complete
info: Downloading file, 20% complete
info: Downloading file, 21% complete
info: Downloading file, 22% complete
info: Downloading file, 22% complete
info: Downloading file, 23% complete
info: Downloading file, 24% complete
info: Downloading file, 25% complete
info: Downloading file, 26% complete
info: Downloading file, 27% complete
info: Downloading file, 28% complete
info: Downloading file, 29% complete
info: Downloading file, 30% complete
info: Downloading file, 30% complete
info: Downloading file, 31% complete
info: Downloading file, 32% complete
info: Downloading file, 33% complete
info: Downloading file, 34% complete
info: Downloading file, 35% complete
info: Downloading file, 36% complete
info: Downloading file, 37% complete
info: Downloading file, 38% complete
info: Downloading file, 39% complete
info: Downloading file, 40% complete
info: Downloading file, 41% complete
info: Downloading file, 41% complete
info: Downloading file, 42% complete
info: Downloading file, 43% complete
info: Downloading file, 44% complete
info: Downloading file, 44% complete
info: Downloading file, 45% complete
info: Downloading file, 46% complete
info: Downloading file, 47% complete
info: Downloading file, 48% complete
info: Downloading file, 49% complete
info: Downloading file, 50% complete
info: Downloading file, 51% complete
info: Downloading file, 52% complete
info: Downloading file, 53% complete
info: Downloading file, 53% complete
info: Downloading file, 54% complete
info: Downloading file, 55% complete
info: Downloading file, 56% complete
info: Downloading file, 57% complete
info: Downloading file, 58% complete
info: Downloading file, 59% complete
info: Downloading file, 60% complete
info: Downloading file, 61% complete
info: Downloading file, 62% complete
info: Downloading file, 63% complete
info: Downloading file, 64% complete
info: Downloading file, 65% complete
info: Downloading file, 66% complete
info: Downloading file, 67% complete
info: Downloading file, 67% complete
info: Downloading file, 68% complete
info: Downloading file, 69% complete
info: Downloading file, 70% complete
info: Downloading file, 71% complete
info: Downloading file, 72% complete
info: Downloading file, 73% complete
info: Downloading file, 74% complete
info: Downloading file, 75% complete
info: Downloading file, 76% complete
info: Downloading file, 76% complete
info: Downloading file, 77% complete
info: Downloading file, 78% complete
info: Downloading file, 78% complete
info: Downloading file, 79% complete
info: Downloading file, 80% complete
info: Downloading file, 81% complete
info: Downloading file, 82% complete
info: Downloading file, 82% complete
info: Downloading file, 83% complete
info: Downloading file, 84% complete
info: Downloading file, 85% complete
info: Downloading file, 86% complete
info: Downloading file, 86% complete
info: Downloading file, 87% complete
info: Downloading file, 87% complete
info: Downloading file, 88% complete
info: Downloading file, 89% complete
info: Downloading file, 89% complete
info: Downloading file, 90% complete
info: Downloading file, 91% complete
info: Downloading file, 92% complete
info: Downloading file, 93% complete
info: Downloading file, 94% complete
info: Downloading file, 94% complete
info: Downloading file, 95% complete
info: Downloading file, 96% complete
info: Downloading file, 97% complete
info: Downloading file, 97% complete
info: Downloading file, 98% complete
info: Downloading file, 99% complete
info: Downloading file, 100% complete
info: Download checking file
info: checked: ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz
info: Downloading next file, 11 left, 12 total
info: Download checking file
info: Downloading next file, 10 left, 12 total
info: Downloading file, 1% complete
info: Downloading file, 5% complete
info: Downloading file, 9% complete
info: Downloading file, 12% complete
info: Downloading file, 16% complete
info: Downloading file, 20% complete
info: Downloading file, 23% complete
info: Downloading file, 27% complete
info: Downloading file, 30% complete
info: Downloading file, 34% complete
info: Downloading file, 39% complete
info: Downloading file, 43% complete
info: Downloading file, 47% complete
info: Downloading file, 50% complete
info: Downloading file, 54% complete
info: Downloading file, 57% complete
info: Downloading file, 61% complete
info: Downloading file, 64% complete
info: Downloading file, 68% complete
info: Downloading file, 71% complete
info: Downloading file, 76% complete
info: Downloading file, 79% complete
info: Downloading file, 83% complete
info: Downloading file, 87% complete
info: Downloading file, 90% complete
info: Downloading file, 93% complete
info: Downloading file, 96% complete
info: Downloading file, 100% complete
info: Download checking file
info: checked: device-da90b80b4e780bca4ebd1e0d7d5168991e0d14d88c82cfd2906cce9f0d85b9e7.tar.xz
info: Downloading next file, 9 left, 12 total
info: Download checking file
info: Downloading next file, 8 left, 12 total
info: Download checking file
info: checked: keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz
info: Downloading next file, 7 left, 12 total
info: Download checking file
info: Downloading next file, 6 left, 12 total
info: Download checking file
info: checked: version-3.tar.xz
info: Downloading next file, 5 left, 12 total
info: Download checking file
info: Downloading next file, 4 left, 12 total
info: Download checking file
info: Downloading next file, 3 left, 12 total
info: Download checking file
info: Downloading next file, 2 left, 12 total
info: Download checking file
info: Downloading next file, 1 left, 12 total
info: Download checking file
info: Download complete
debug: adb shell: cat /etc/recovery.fstab
debug:  Error: Command failed: adb -P 5038 shell cat /etc/recovery.fstab
error: no devices/emulators found

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
debug: adb shell: mount -a
debug: 
debug: adb shell: mkdir -p /cache/recovery
debug: 
info: Start pushing 13 files
debug:  Error: Command failed: adb -P 5038 push '/Users/EMV/Library/Caches/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
error: Devices: Error: Adb push error: 
error: Devices: Adb push error: 
debug: 
info: Adb push, 0% left

**Comment by NeoTheThird** [comment]
Thanks. For future reference, please use past.ubuntu.com (or something similar) for such long logs. For short snippets like further above, enclose it in three ``` ``` ``` to display it as plain text.

So the problem seems to be that the files are downloaded to a path with a double slash, so adb looks in the wrong location. I'm investigating why that happens right now.

**Comment by popesz** [comment]
do not forget, that to boot into recovery mode I had to do it manually in an other terminal window.
Trying to repeat the process I made, but can not remember how I did. Probably there was a 'try again' option while fastboot was waiting for the device, but not sure.

**Comment by popesz** [comment]
Next level:
info: Download complete
debug: adb shell: cat /etc/recovery.fstab
debug: 
debug: adb shell: umount /cache
debug: 
debug: adb shell: make_ext4fs /dev/block/mmcblk0p5
debug: 
debug: adb shell: mount /cache
debug: 
debug: adb shell: mount -a
debug: 
debug: adb shell: mkdir -p /cache/recovery
debug: 
info: Start pushing 13 files
debug: 
info: Adb push, 2% left
debug: 
info: Adb push, 4% left
debug: 
info: Adb push, 5% left
debug: 
info: Adb push, 6% left
debug:  Error: Command failed: adb -P 5038 push '/Users/EMV/Library/Caches/ubports/pool/ubports-e5cf0885f061c9615931cf863a43f65d8590aa71027315ad71999252ce118868.tar.xz' /cache/recovery/

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
error: Devices: Error: Adb push error: 
error: Devices: Adb push error: 
debug: 
info: Adb push, 0% left

**Comment by NeoTheThird** [comment]
Could you try again with the latest version?

**Comment by popesz** [comment]
/Applications/ubports-installer.app/Contents/MacOS/ubports-installer

Pug interceptor registered successfully

debug: Using native platform tools!

debug:

debug:

debug: adb shell: echo 1

debug:

debug: adb shell: getprop ro.product.device

debug:

debug: getprop: vegetahd

debug: adb shell: cat /etc/system-image/channel.ini

debug:

debug: adb shell: echo 1

debug:

debug: reboot to bootloader

debug:

debug: reboot to bootloader [DONE] err:null

debug: checking password

debug: correct password

debug: fastboot: wait for device

info: Download startCheck

error: Not existing
/Users/EMV/Library/Caches/ubportsimages/vegetahd/recovery-vegetahd.img

info: Starting download of 1 files

info: Downloading file, 1% complete

info: Downloading file, 26% complete

info: Downloading file, 49% complete

info: Downloading file, 72% complete

info: Downloading file, 94% complete

info: Download checking file

info: checked: recovery-vegetahd.img

info: Download complete

info: done downloading(once listener)

debug: fastboot: flash; [object Object]

info: Booting into recovery image...

error: Devices: Error: Fastboot: Unknown error:  ERROR: usb_read failed
with status e00002ed

ERROR: usb_write failed with status e00002d8

ERROR: usb_write failed with status e00002d8

downloading 'boot.img'...

ERROR: usb_write failed with status e00002c0

FAILED (command write failed (Invalid argument))

finished. total time: 0.000s

The installer recognises the device without any problem, the recovery
system has been downloaded, but fastboot still can not boot into recovery
mode.
Probably the same method is needed as on Linux to add the device version
code to the system, to help fastboot in recognition.

**Comment by hugobonav** [comment]
Hello,
I have I think the same issue that @popesz : I'm on a mac (version 10.13.4 (17E199)), the installer recognises the device (BQ Aquaris E5 Ubuntu Edition) without any problem.
This green appears:
<img width="801" alt="capture d ecran 2018-05-21 a 21 42 57" src="https://user-images.githubusercontent.com/6933097/40326568-02c23952-5d40-11e8-9988-85a48bfbd622.png">

But after clicking "Switch to UBports":

- my phone seems (I'm not so good at these things...) to reboot and then "freeze" to a black screen with this inscription: "=> FASTBOOT made..."

- and my mac doesn't do anything after I enter my password...
<img width="803" alt="capture d ecran 2018-05-21 a 21 44 25" src="https://user-images.githubusercontent.com/6933097/40326609-2db28220-5d40-11e8-81f7-1dfdb91056bc.png">
It "freeze" to this screen:
<img width="800" alt="capture d ecran 2018-05-21 a 21 35 54" src="https://user-images.githubusercontent.com/6933097/40326255-fd6cf68c-5d3e-11e8-924e-664db765f616.png">

Any hint ?
PS: I found how to get back my phone working by unplugging it from my computer then rebooting with Power and Volume Up push longly...

thanks in advance,
hugobonav

**Comment by NeoTheThird** [comment]
Please try again with [the latest release](https://github.com/ubports/ubports-installer/releases/latest).

**Comment by hugobonav** [comment]
Thanks for your update. But I broke my Ubuntu phone (glass and half touchpad inactive)... So I won't be able to test it ;-((

**Comment by popesz** [comment]
Jan,

I really apologise, I had the same issue. my BQ is dead since that time.
After 3,5 year of great services, it had to be retired.
Thanks for your efforts, hope for other will work.
Best,
Popesz

**Comment by Vincent14** [comment]
I have the same problem on Ubuntu 18.04 and the latest version of ubports installer
