### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined (MainRenderer:439)

### ISSUE THREAD

**Issue by devil59gh** [ubports/ubports-installer#932]
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: Not detected
Channel: Not yet set
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.418] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/ZgtrzBf9mh/

**Comment by NeoTheThird** [comment]
Our hosting provider had some technical difficulties, should be resolved now. Just try again. Sorry about that. The next release of the installer is going to come with better error handling for this and backup data sources.
