### ISSUE TITLE
ubports-installer.0.3.2-beta missing adb files

### ISSUE THREAD

**Issue by wdehoog** [ubports/ubports-installer#934]
I ran the installer on Windows 10 pro 64bit. My phone is a Oneplus one running TWRP 3.2.3. 

The installed adb.exe and fastboot.exe (C:\Users\<user>\AppData\Roaming\ubports\platform-tools) do not work. I guess some dll files are missing.

It started to work after I copied all files from platform-tools_r29.0.4-windows.zip.  See https://www.xda-developers.com/install-adb-windows-macos-linux/

**Comment by NeoTheThird** [comment]
Ooops, thanks for the hint!

**Comment by wdehoog** [comment]
Just tried the 0.4.0 installer (windows). Skipped fastboot so installed from recovery. So far so good.

**Comment by NeoTheThird** [comment]
Awesome, thanks.
