### ISSUE TITLE
Fastboot dependency in .deb package

### ISSUE THREAD

**Issue by mjsir911** [ubports/ubports-installer#94]
After installing the package for the ubports installer (`ubports-installer_0.1.9-beta_amd64.deb`). I went through the instructions untill the step "detecting phone for usb" (paraphrasing from memory). 

A command running fastboot was failing because fastboot was not installed.

a simple `apt install fastboot` fixed the problem and it continued on after I did that.

Seeing as how fastboot is a dependency, shouldnt it be marked as one in the `.deb` package?

**Comment by netbomo** [comment]
I lost one afternoon on this issue...
Thank you so much mjsir911!
