### ISSUE TITLE
adb push permission denied

### ISSUE THREAD

**Issue by QuiquePG** [ubports/ubports-installer#944]
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: flo
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Linux Mint     undefined     undefined x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/JRtvSt5jSM/

**Comment by QuiquePG** [comment]
I have this report when I tried to install Ubuntu touch on my Nexus 7 2013 (flo)

**Comment by NeoTheThird** [comment]
Ah, sorry, i think i know what's happening. Try removing cache by running `sudo rm -rf ~/.cache/ubports` and then running the installer again without sudo (!).

You might also want to use our [latest prerelease](https://github.com/ubports/ubports-installer/releases/tag/0.4.2-beta), which fixes some issues you might run into on the Nexus 7.

**Comment by QuiquePG** [comment]
I reinstalled recovery.img and system.img then on Android I activate developer mode, and I tried to install Ubuntu Touch again and I works! Thanks for your help.


QUIQUE PAZOS

________________________________
De: Jan Sprinz <notifications@github.com>
Enviado: martes, 29 de octubre de 2019 7:40
Para: ubports/ubports-installer <ubports-installer@noreply.github.com>
Cc: QuiquePG <quiquepazos@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [ubports/ubports-installer] adb push permission denied (#944)


Ah, sorry, i think i know what's happening. Try removing cache by running sudo rm -rf ~/.cache/ubports and then running the installer again without sudo (!).

You might also want to use our latest prerelease<https://github.com/ubports/ubports-installer/releases/tag/0.4.2-beta>, which fixes some issues you might run into on the Nexus 7.

**Comment by NeoTheThird** [comment]
Awesome, good to hear! Thanks for the feedback :)
