### ISSUE TITLE
please describe the problem you are experiencing

### ISSUE THREAD

**Issue by bellka** [ubports/ubports-installer#970]
*Automatically generated error report* 
UBports Installer Version: 0.2.7-beta 
Device: krillin
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.418] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/M8Mf6S257v/

**Comment by NeoTheThird** [comment]
Sorry about that, this problem should be solved in [the upcoming installer release](https://github.com/ubports/ubports-installer/releases/tag/0.4.1-beta).
