### ISSUE TITLE
Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/Applications/ubports-installer.app/Contents/Resources/app.asar.unpacked/platform-tools/mac/adb -P 5037 push /Users/evgrinsven/Library/Caches/ubports/pool/ubports-a1f443971032f2b6a03ed6f83d3340e026d59bfbe1625b259fb77eb05fa2b6a9.tar.xz /cache/recovery/ > /dev/null"}

### ISSUE THREAD

**Issue by pharz** [ubports/ubports-installer#976]
*Automatically generated error report* 
UBports Installer Version: 0.4.1-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: dmg
Operating System: macOS 10.14.618G95 x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/c4JRsycBgK/ 

Before this error popped-up I ran into the issue that /cache was unmounted and the installer would never finish sending files to the device.
Solved it by doing make_ext4fs /dev/block/platform/msm_sdcc.1/by-name/cache and mounting /cache from adb shell. Than the installer actually started sending files on the next iteration.
And before that, and the reason I'm on 0.4.1-beta, /cache seems to be to small to hold the files and I was getting filesystem full messages while pushing files to the device.

**Comment by NeoTheThird** [comment]
Sorry about that, should work now.

**Comment by NeoTheThird** [comment]
But you did the right things as workarounds first, so props for knowing your stuff (or solid research work!) ^^

**Comment by pharz** [comment]
Thanks! Will try again.
