### ISSUE TITLE
Add pictures for different device categories

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#979]
Add graphics for tablets, smartwatches, sd-cards, etc. Consider all the possible button locations for the instruction images. Should look as suru as possible. [Here's some stuff we can steal for that](https://github.com/ubports/ubuntu-themes/tree/b4248c1dec05df0dbf3109a9a49c4bee13d4c9a8/suru-icons/devices/scalable).

**Comment by mymike00** [comment]
Hey Jan, I'm not sure to have understood the issue... Is there something left to do here?

**Comment by NeoTheThird** [comment]
Yes, so far, the files have only been included, but they are not used yet. There's nothing specified in the configs yet about what formfactor a device has, etc. But i'd have to read up on it again for the details.

**Comment by mymike00** [comment]
Ah, got it. Well, if you think I can help here doing something let me know 👍

**Comment by NeoTheThird** [comment]
Sure! If you wanna do some experimenting, i'd start by adding a new `formfactor` property [on the top level of the config file structure](https://github.com/ubports/installer-configs/blob/fce27987ef90cbb9dc4f0f84b6a73dfe72b00870/v1/_device.schema.json#L7). You can then create your own file for testing, feed it to the installer with `-f ./path/to/config.json` and [add the value to the global object](https://github.com/ubports/ubports-installer/blob/fb55b8aee67fef1348e95a3864db9592ef51c59b/src/main.js#L107) so it's accessible throughout the install process. Next, you'd show the correct image in the [select os](https://github.com/ubports/ubports-installer/blob/master/src/pug/views/select-os.pug) and [done](https://github.com/ubports/ubports-installer/blob/master/src/pug/views/done.pug) views based on that value.

In further steps, we'll have to create action images (or a different way to describe actions) for the different formfactors to show in the working screens, but i think we can tackle that later.

**Comment by mymike00** [comment]
Cool!
