### ISSUE TITLE
Installer does not try to detect again if the adb is not authorized yet

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-installer#983]
If the device is in developer mode, but connected to the PC for the first time, there will be a popup on the device to authorize the adb connection. In the mean time, adb will print an error that passes silently as of now. This error should be handled in the [module](https://github.com/ubports/promise-android-tools/), and a modal should be shown in the installer prompting the user to accept the action on the device.

**Comment by JanArneFagertun** [comment]
Hmm - I have seen somebody commented this popup before, but I have never seen it. Neither at the device (Nexus 5), nor at the PC (Debian) screen.
ubports-installer does not recognize my Nexus 5, so I choose it manually. After that I get a popup warning about that this works only on Hammerhead, which it is.
After a while the install process stops with an error message ("yikes....").

I started ubports-installer from the command line, and this is the ouput:

~ (11:33:00) $ ubports-installer
info: Welcome to the UBports Installer version 0.4.17-beta!
info: Downloaded file 1 of 2
info: Downloaded file 2 of 2
error: Error: adb:format: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}
stack trace: Error: {"error":{"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell echo ."},"stdout":"","stderr":"error: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device."}
at /opt/ubports-installer/resources/app.asar/node_modules/promise-android-tools/src/adb.js:66:13
at /opt/ubports-installer/resources/app.asar/src/utils.js:282:7
at ChildProcess.exithandler (child_process.js:319:5)
at ChildProcess.emit (events.js:194:13)
at maybeClose (internal/child_process.js:998:16)
at Socket. (internal/child_process.js:403:11)
at Socket.emit (events.js:194:13)
at Pipe. (net.js:593:12)
info: Good bye!

I have tried to kill the adb server::
root@laptop:/home/janaf/Nedlastinger# adb kill-server
cannot connect to daemon at tcp:5037: Connection refused

Afterwards I started the adb server (adb -start-server) and tried ubports-installer again, but with the same result.
