### ISSUE TITLE
create an Auto-port

### ISSUE THREAD

**Issue by Mannshoch** [ubports/ubports-installer#984]
At moment, I do not have a Supported Device anymore. 
The porting guide looks like it have a strict step-by-step workflow.

Please enhance the ubports-installer with an expert option to autobuild ubport for a connected device.

Use this to may upload data you need to have a better possibility to support more devices.

**Comment by NeoTheThird** [comment]
I'm afraid that's not in the cards. There's a lot of things that can be automated in tools in the porting workflow, but not everything. For the most part it consists of online research, trial and error and reading error logs. Automating everything there is next to impossible and goes far beyond the scope of the Installer.

**Comment by Mannshoch** [comment]
I saw your 36c3 presentation. It seems you have enhanced your ubports Installer in a way that It may help in this case.  Would it be possible to get it that way done that the Installer will do most work and May ask question for the uncertain parts? 

I see the Idea in that way that you try to make at least a backup and present a Terminal for working on the Phone. If a ubports user abort the working on this, ubports should restore the backup. 

May a workflow for using it that way.

1. Ubports get an unsupported device 
2. Advice: "root your device" | "unlock boootloader" | "reboot to download mode" etc.
3. Do Backup
4. Was able to backup your Image, 
5. May boot a small System only for collecting hardware data e.g https://github.com/linuxhw/
6. Open a Terminal for your modification ( ADB, fastboot, connection to mobile phone established)
5. Button cancel -> restore image | Button OK save current state and close the application
