### ISSUE TITLE
Device connection issue - Nexus 5 - Hammerhead

### ISSUE THREAD

**Issue by 3arn0wl** [ubports/ubports-installer#985]
Hi

Thanks for the continuing efforts with the installer. However, the installer isn't picking up that I've plugged the phone in via USB.

- the phone is on Bootloader
- I've tried 4 different USB cables

(Also, when I select the device manually, it doesn't recognize that I've done so the first time, and I have to do it again.)

I've tried the Edge and RC as options.

After that, I restart the bootloader, as instructed, and the installer says that's it's downloading firmware, I reboot to bootloader and press Continue. Then it says it's flashing the firmware, but nothing actually seems to happen.

**Comment by NeoTheThird** [comment]
This is the snap package? Can you try running `snap connect ubports-installer:raw-usb` for me?

**Comment by 3arn0wl** [comment]
Hi Jan - Thanks for coming to my rescue!

I put the phone in bootloader mode, and tried all four cables, and did
snap connect ubports-installer:raw-usb 
after each change of cable. It made no difference - it was still waiting to connect.

I tried Start Ubuntu from the bootloader, which hangs at the Nexus 5 powered by Ubuntu logo, and gives the popup saying "Unable to mount Nexus 5 Unable to open MTP device 'usb:001,034' " Again the snap instruction didn't have any effect.

**Comment by NeoTheThird** [comment]
Could you get me the log file from `~/snap/ubports-installer/current/.cache/ubports/ubports-installer.log`? Also, try rebooting your machine. You never know ;)

If you just want to get this done quickyl, you can always go ahead and use one of the other packages like [AppImage](https://devices.ubuntu-touch.io/installer/appimage), but i do appreciate you taking the time to debug this with me to solve the problem for everyone :)

**Comment by 3arn0wl** [comment]
:) I'm more than happy to try to help!

so - this is the log:

{"level":"info","message":"Welcome to the UBports Installer version 0.4.3-beta!"}
{"level":"debug","message":"killing all running adb servers"}
{"level":"debug","message":"starting adb server on port 5037"}
{"level":"debug","message":"no device detected: stopped waiting"}
{"level":"debug","message":"running step: {\"type\":\"download\",\"condition\":{\"var\":\"bootstrap\",\"value\":true},\"group\":\"firmware\",\"files\":[{\"url\":\"http://cdimage.ubports.com/devices/recovery-hammerhead.img\",\"checksum\":\"91b681a3287808a79e21c2ac17f85537c6c9b23fb009b5e491c2ccf28986856c\"},{\"url\":\"http://cdimage.ubports.com/devices/boot-hammerhead.img\",\"checksum\":\"3f39372bdac0a6a8bd6507683a87da16e74346152525e12d6ea46418a88c62c3\"}]}"}
{"level":"debug","message":"checked: recovery-hammerhead.img"}
{"level":"info","message":"Downloaded file 1 of 2"}
{"level":"debug","message":"checked: boot-hammerhead.img"}
{"level":"info","message":"Downloaded file 2 of 2"}
{"level":"debug","message":"download done"}
{"level":"debug","message":"running step: {\"type\":\"adb:reboot\",\"condition\":{\"var\":\"bootstrap\",\"value\":true},\"to_state\":\"bootloader\",\"fallback_user_action\":\"bootloader\"}"}
{"level":"debug","message":"running step: {\"type\":\"fastboot:flash\",\"condition\":{\"var\":\"bootstrap\",\"value\":true},\"flash\":[{\"partition\":\"boot\",\"file\":\"boot-hammerhead.img\",\"group\":\"firmware\"},{\"partition\":\"recovery\",\"file\":\"recovery-hammerhead.img\",\"group\":\"firmware\"}]}"}
{"level":"debug","message":"[{\"file\":\"/home/mark/snap/ubports-installer/232/.cache/ubports/hammerhead/firmware/boot-hammerhead.img\",\"partition\":\"boot\"},{\"file\":\"/home/mark/snap/ubports-installer/232/.cache/ubports/hammerhead/firmware/recovery-hammerhead.img\",\"partition\":\"recovery\"}]"}

HTH

I'm going to reboot the laptop now, to see if that does anything.

Thank you!!

**Comment by 3arn0wl** [comment]
I'm still floundering, I'm afraid. 

Any further insights would be welcome.

**Comment by NeoTheThird** [comment]
Glad to hear it worked for you in the end, you're very welcome :)

I'll do some investigating on what's going on with the snap. Thanks for your feedback anyways :)
