### ISSUE TITLE
Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: error: {"killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\danie\\AppData\\Local\\Temp\\1SwEg9Y81AuqMw4YMBo5pvVotov\\resources\\app.asar.unpacked\\platform-tools\\win\\adb -P 5037 push \"C:\\Users\\danie\\AppData\\Roaming\\ubports\\pool\\ubports-a1f443971032f2b6a03ed6f83d3340e026d59bfbe1625b259fb77eb05fa2b6a9.tar.xz\" /cache/recovery/ > nul"}

### ISSUE THREAD

**Issue by rthrust** [ubports/ubports-installer#987]
*Automatically generated error report* 
UBports Installer Version: 0.4.3-beta 
Device: hammerhead
Channel: ubports-touch/16.04/stable
Package: exe
Operating System: Microsoft Windows [Version 10.0.18362.418] ia32 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/hZr3DrqhKb/

**Comment by NeoTheThird** [comment]
I need more debug information, could you try again with [this version](https://github.com/ubports/ubports-installer/releases/tag/0.4.6-beta) and report a new bug if it happens again?
