### ISSUE TITLE
Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/opt/ubports-installer/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 push \"/home/vanoise/.cache/ubports/pool/ubports-a1f443971032f2b6a03ed6f83d3340e026d59bfbe1625b259fb77eb05fa2b6a9.tar.xz\" /cache/recovery/ > /dev/null"}

### ISSUE THREAD

**Issue by Billdemoncho** [ubports/ubports-installer#992]
*Automatically generated error report* 
UBports Installer Version: 0.4.3-beta 
Device: turbo
Channel: ubports-touch/16.04/stable
Package: deb
Operating System: Ubuntu Linux 19.04 disco x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/58BfCHZQTz/

**Comment by NeoTheThird** [comment]
Hi, what OS was the device running before?

**Comment by Billdemoncho** [comment]
Ubuntu touch 16.04 OTA 10

**Comment by NeoTheThird** [comment]
I need more debug information, could you try again with [this version](https://github.com/ubports/ubports-installer/releases/tag/0.4.6-beta) and report a new bug if it happens again?
