### ISSUE TITLE
Error: Wait for device: error: {"killed":false,"code":1,"signal":null,"cmd":"/snap/ubports-installer/232/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell cat /etc/system-image/channel.ini"}stderr: /system/bin/sh: cat: /etc/system-image/channel.ini: No such file or directory

### ISSUE THREAD

**Issue by neo-azazello** [ubports/ubports-installer#995]
*Automatically generated error report* 
UBports Installer Version: 0.4.3-beta 
Device: Not detected
Channel: Not yet set
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/x6qz22th3r/

**Comment by NeoTheThird** [comment]
Fixed in https://github.com/ubports/ubports-installer/commit/5ce9c5142a9922fba29c9478101eecba8698c1f5
