### ISSUE TITLE
Error: systemimage: Push failed: Failed push: Failed to push file 0: Push failed: error: {"killed":false,"code":1,"signal":null,"cmd":"/tmp/.mount_ubportk2svwU/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 push \"/home/cm-t/.cache/ubports/pool/ubports-a1f443971032f2b6a03ed6f83d3340e026d59bfbe1625b259fb77eb05fa2b6a9.tar.xz\" /cache/recovery/ > /dev/null"}

### ISSUE THREAD

**Issue by cm-t** [ubports/ubports-installer#996]
*Automatically generated error report* 
UBports Installer Version: 0.4.5-beta 
Device: krillin
Channel: ubports-touch/16.04/stable
Package: AppImage
Operating System: Ubuntu Linux 16.04 xenial x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/yGvqzCfWPJ/

**Comment by NeoTheThird** [comment]
What?? I thought i fixed that!

**Comment by NeoTheThird** [comment]
The `/cache/recovery/log` starts with:

```
__bionic_open_tzdata: couldn't find any tzdata when looking for Europe/Amsterdam!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Starting recovery on Fri Feb 28 23:50:32 2031
```

Your phone is from the future!

![](https://media3.giphy.com/media/WhSlMDqyH3P7G/giphy.webp?cid=790b76118c3b2124dd8796b4b39b1281f874f90e3db35fca&rid=giphy.webp)

**Comment by NeoTheThird** [comment]
Continuing in #1028.
