### ISSUE TITLE
Error: systemimage: Push failed: Failed to mount: error: {"killed":false,"code":5,"signal":null,"cmd":"/snap/ubports-installer/237/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"}stderr: mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argumentmount: mounting /dev/block/bootdevice/by-name/persist on /persist failed: No such file or directorymount: mounting /dev/block/bootdevice/by-name/dsp on /dsp failed: No such file or directorymount: mounting /dev/block/bootdevice/by-name/modem on /firmware failed: No such file or directorymount: mounting /dev/block/bootdevice/by-name/bluetooth on /bt_firmware failed: No such file or directory

### ISSUE THREAD

**Issue by DiogoConstantino** [ubports/ubports-installer#997]
*Automatically generated error report* 
UBports Installer Version: 0.4.5-beta 
Device: oneplus3
Channel: 16.04/arm64/edge
Package: snap
Operating System: Ubuntu Linux 18.04 bionic x64 
NodeJS version: v8.2.1 

Error log: https://paste.ubuntu.com//p/wtzrcDQnJm/

**Comment by NeoTheThird** [comment]
Is there anything you can tell me about this device? Guessing it's running android, what version? Anything weird you've done to it or the previous owner did?

**Comment by NeoTheThird** [comment]
3 or 3t?

**Comment by DiogoConstantino** [comment]
it is was 3.
It was running whatever OnePlus shipped with it updated to the latest version.

I ended up repeating it until it succeeded, but took a few tries, which I suspect means something should fail more graciously.

I can also had this log from the console output:
`diogo@diogo-Aura:~$ ubports-installer 
Gtk-Message: 13:32:13.017: Failed to load module "gail"
Gtk-Message: 13:32:13.017: Failed to load module "atk-bridge"
Gtk-Message: 13:32:13.020: Failed to load module "canberra-gtk-module"
info: Welcome to the UBports Installer version 0.4.5-beta!
Pug interceptor registered successfully
info: device detected: OnePlus3
warn: The device OnePlus3 is not supported!
info: Downloaded file 1 of 1
info: Downloaded file 1 of 1
checked: keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz true
checked: version-4.tar.xz true
checked: device-b4422d1593b76acedd819149ddb24b505a9cc345c6d73cf8094996a926b44ca1.tar.xz true
checked: ubports-f9bc4906ac1b2ecc5f2842eb39e17e1ec02c8ffbe223427e479673ddca42f45e.tar.xz true
error: Error: systemimage: Push failed: Failed to mount: error: {"killed":false,"code":5,"signal":null,"cmd":"/snap/ubports-installer/237/app/resources/app.asar.unpacked/platform-tools/linux/adb -P 5037 shell mount -a"}
stderr: mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument
mount: mounting /dev/block/bootdevice/by-name/persist on /persist failed: No such file or directory
mount: mounting /dev/block/bootdevice/by-name/dsp on /dsp failed: No such file or directory
mount: mounting /dev/block/bootdevice/by-name/modem on /firmware failed: No such file or directory
mount: mounting /dev/block/bootdevice/by-name/bluetooth on /bt_firmware failed: No such file or directory
info: device detected: OnePlus3
info: Downloaded file 1 of 1
checked: keyring-4c4e7ef380ebcfa2c31084efa199138e93bfed8fc58aa3eb06bdf75a78af9b57.tar.xz true
checked: version-4.tar.xz true
checked: device-b4422d1593b76acedd819149ddb24b505a9cc345c6d73cf8094996a926b44ca1.tar.xz true
checked: ubports-f9bc4906ac1b2ecc5f2842eb39e17e1ec02c8ffbe223427e479673ddca42f45e.tar.xz true
`

**Comment by NeoTheThird** [comment]
Oi, it introduced itself as `OnePlus3`, that's fun

**Comment by NeoTheThird** [comment]
> I ended up repeating it until it succeeded, but took a few tries, which I suspect means something should fail more graciously.

Interesting. We can't do all that much about failing gracefully, as there's nothing in the error that indicates that it might work on a second try, but it might be we can just add `adb:format` steps and reboot recovery again. Will pick this up with the porters.

**Comment by Vince1171** [comment]
I can confirm that `mount: mounting /dev/block/bootdevice/by-name/userdata on /data failed: Invalid argument` occurs if OxygenOS 9.x have been installed on the device...
It seems to be due to a change in the fstab.qcom
I'm investigate

**Comment by NeoTheThird** [comment]
Great, thanks vince. On some other devices we run `make_ext4fs` on data to make sure it exists as expected, would that help? Done using the `adb:format` step.

**Comment by NeoTheThird** [comment]
Vince fixed that in the config now.
